### ISSUE TITLE
Please help me. I am not receiving any webhook data response. 

### ISSUE THREAD

**Issue by birbull** [allburov/whatsapp-http-api#100]
Please help me. I am not receiving any webhook data response. 

1. I started the session.
2. I scanned the qr code.
3. I use this command docker run -it -e "WHATSAPP_HOOK_EVENTS=*" -e WHATSAPP_HOOK_URL=https://enn5g90okamcf.x.pipedream.net devlikeapro/whatsapp-http-api

No error any where but I am not receiving webhook response to my webhook url

**Comment by allburov** [comment]
Could you try with WHATSAPP_HOOK_URL=https://httpbin.org/post and see if there's logs for that?

**Comment by allburov** [comment]
At least you should receive webhooks for new incoming messages - could you try to send one?

**Comment by allburov** [comment]
Also could you try to connect your application and the WAHA locally?
Here's an example for that with python echo bot https://github.com/devlikeapro/whatsapp-http-api/tree/core/examples/python

**Comment by birbull** [comment]
I did setup locally and I am not receiving any log in terminal after connecting to Whatsapp api

**Comment by allburov** [comment]
Got it, I'll look at this tomorrow one more time!

**Comment by allburov** [comment]
@birbull51 hi! I just pull the latest core version and tried - it works
1. pull the latest version `docker pull devlikeapro/whatsapp-http-api`
2. Run the docker
```bash
docker run -it -e "WHATSAPP_HOOK_EVENTS=*" -e WHATSAPP_HOOK_URL=https://httpbin.org/post -p 3000:3000 devlikeapro/whatsapp-http-api
```
3. Start a new default session 
4. Scan QR
5. Send a message to phone number
6. See logs in the console
