### ISSUE TITLE
sendLocation doesn't work

### ISSUE THREAD

**Issue by parallels999** [allburov/whatsapp-http-api#102]
I'm trying to send a location, i'm not getting any exception, but location was not sended

https://github.com/devlikeapro/whatsapp-http-api/blob/e1bf8cf735287bad241a89030f1daa2d1318ff2f/src/core/session.webjs.core.ts#L124-L131

**Comment by allburov** [comment]
Yes, it doesn't in the WEBJS engine, waiting for engine to support it

I'm closing the issue as a duplicate - https://github.com/devlikeapro/whatsapp-http-api/issues/49

**Comment by allburov** [comment]
You could try NOWEB engine btw, it does send location! https://waha.devlike.pro/docs/how-to/engines/#noweb
