### ISSUE TITLE
 data.id.id.substring is not a function - I am Just Sending a Text Message via API and Getting this erro

### ISSUE THREAD

**Issue by birbull** [allburov/whatsapp-http-api#103]
I am Just Sending a Text Message via API and Getting this error — 

`{"statusCode":500,"timestamp":"2023-05-22T16:25:26.890Z","exception":{"stack":"TypeError: data.id.id.substring is not a function\n    at Message._patch (/app/node_modules/whatsapp-web.js/src/structures/Message.js:92:75)\n    at new Message (/app/node_modules/whatsapp-web.js/src/structures/Message.js:19:24)\n    at Client.sendMessage (/app/node_modules/whatsapp-web.js/src/Client.js:775:16)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /app/node_modules/@nestjs/core/router/router-execution-context.js:46:28\n    at async /app/node_modules/@nestjs/core/router/router-proxy.js:9:17","message":"data.id.id.substring is not a function","name":"TypeError"},"request":{"path":"/api/sendText?phone=120363128633135747@g.us&text=Test1&session=default","method":"GET","body":{},"query":{"phone":"120363128633135747@g.us","text":"Test1","session":"default"}},"version":{"version":"2023.4.27","tier":"CORE","browser":"/usr/bin/chromium"}}`

**Comment by parallels999** [comment]
Upgrade core version to `2023.5.20` and everything works again
https://github.com/devlikeapro/whatsapp-http-api/commit/7b623d0faa9dd5a4f693b6809ad9fb519380f5aa

**Comment by birbull** [comment]
What is command, I am using arm based processor.

**Comment by parallels999** [comment]
>I am using arm based processor.

What does the processor have to do with it?

**Comment by birbull** [comment]
@allburov Can You help?

**Comment by angeljqv** [comment]
@allburov already gave you the command you need and the steps to follow
https://github.com/devlikeapro/whatsapp-http-api/issues/100#issuecomment-1555889685

**Comment by allburov** [comment]
https://waha.devlike.pro/docs/help/faq/#how-to-update

Sorry, I'll update arm version today and let you know when it's ready!

**Comment by allburov** [comment]
Done, ARM versions have been updated too! 

Don't forget to add `:arm` tag to the docker name
```bash
docker pull docker pull devlikeapro/whatsapp-http-api:arm
docker pull docker pull devlikeapro/whatsapp-http-api-plus:arm
```
