### ISSUE TITLE
[Enhancement] user is online or offline by contact id

### ISSUE THREAD

**Issue by fenilinvica** [allburov/whatsapp-http-api#104]
**It's is possible to get a contact User is online or offline by contact id**

**Comment by arthurbarros** [comment]
Short answer: It's not possible

Long answer: 

None of the engines provide this functionality today, it need to be available there first. 
If this solution fits to your project, assume the last time the user interacted with you is his/her last time seen online/offline status.
You could also assume if you receive the event of "message read" as its online presence.

message.ack should be the event when the user reads your message - https://waha.devlike.pro/docs/how-to/receive-messages/#messageack

But be aware of this is a settings the user can change anytime on WhatsApp Privacy Settings.

**Comment by fenilinvica** [comment]
see this app doing this scrap easily how ? 

**https://play.google.com/store/apps/details?id=com.welog&hl=en&gl=US**

**Comment by allburov** [comment]
Hi! It looks possible (at least in NOWEB engine), we'll look at this closer for other engines too!
- WEBJS doesn't support it yet, waiting -  https://github.com/pedroslopez/whatsapp-web.js/issues/82 
- VENOM has some troubles with that too - https://github.com/orkestral/venom/issues/1733
- Only for NOWEB it seams possible

**Comment by allburov** [comment]
---

**Comment by allburov** [comment]
The endpoints and webhook for presence (online\offline\typing)  will be available in **July 2023** release, both **Core** and **Plus** version.

Here's a short note about it:

-----

You can get presence information (online, offline with last seen, typing status) for a contact if they share their
presence information.

Presence endpoints and webhook is available only in **NOWEB** engine.

Here's few notes about fields:

- `chatId` - either contact id (`213213213@c.us`) or group chat id (`1111111111111@g.us`).
- `lastSeen` - contains Unix timestamps indicating when a participant was last online
- `lastKnownPresence` - contains the last known presence status, which can be
  `offline`, `online`, `typing`, `recording`, or `paused`

## Endpoints

### Get all presence

You can get all presence information available for a session by calling `GET /api/{session}/presence/`.
It returns both groups' and personal chats' presence information.

```json
[
  {
    "id": "2132132130@c.us",
    "presences": [
      {
        "participant": "2132132130@c.us",
        "lastKnownPresence": "offline",
        "lastSeen": 1686719326
      }
    ]
  },
  {
    "id": "11111111111111111111111@g.us",
    "presences": [
      {
        "participant": "11111111111111111111111@g.us",
        "lastKnownPresence": "online",
        "lastSeen": null
      },
      {
        "participant": "2132132130@c.us",
        "lastKnownPresence": "offline",
        "lastSeen": 1686719326
      }
    ]
  }
]
```

### Get chat presence

To get presence information for a single chat - call `GET /api/{session}/presence/{chatId}`.
For a group, you'll get participants' statuses.

```json
{
  "id": "2132132130@c.us",
  "presences": [
    {
      "participant": "2132132130@c.us",
      "lastKnownPresence": "online",
      "lastSeen": null
    }
  ]
}
```

### Subscribe to presence

You can subscribe to presence information by calling `POST /api/{session}/presence/{chatId}/subscribe` request
(no body required).
You can get later presence information for the chat with above `GET` endpoints or by listening to `presence.update`
webhook.

## Webhook

You can subscribe to `presence.update` webhook event to get the most recent presence information.

```json
{
    "event": "presence.update",
    "session": "default",
    "payload": {
        "id": "111111111111111111@g.us",
        "presences": [
            {
                "participant": "11111111111@c.us",
                "lastKnownPresence": "typing",
                "lastSeen": null
            }
        ]
    },
    "engine": "NOWEB"
}
```

**Comment by devlikepro** [comment]
⚠️ ⚠️ ⚠️ ⚠️ ⚠️ 
**WEBJS** - Starting from `2025.8.3` version you must add `config.webjs.tagsEventsOn` to session config to enable `message.ack` event for **WEBJS**

<img width="804" height="191" alt="Image" src="https://github.com/user-attachments/assets/2501038d-d10f-498c-b22d-2a42d1b0dbf3" />

⚠️ ⚠️ ⚠️ ⚠️ ⚠️ 

https://waha.devlike.pro/docs/how-to/sessions/#webjs


-   `tagsEventsOn` — Enable emission of special `tag:*` engine [**🔄 Events**](https://waha.devlike.pro/docs/how-to/events/) - **required** for `presence.update` and `message.ack`.


```json
{
  "name": "default",
  "config": {
    "webjs": {
      "tagsEventsOn": false
    }
  }
}
```

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
