### ISSUE TITLE
mention participant in group

### ISSUE THREAD

**Issue by Tachtas** [allburov/whatsapp-http-api#105]
is there a way to mention participant in a group?

**Comment by allburov** [comment]
Hi! Right now there's no way, but we'll add it!

**Comment by allburov** [comment]
Added, planning to release it in July 2023
.
@Tachtas let me know if you're using WAHA Plus version - we'll release it ASAP in that case.

---

### Mention contact 
If you send a message in a group and want to mention a participant in the message - use mentions field for that in POST /api/sendText request.

Please note that you MUST mention a number in the `text` as well in the format @2132132130 and also mention it in `mentions` in format 2132132130@c.us
```json
{
  "session": "default",
  "chatId": "12132132130@c.us",
  "text": "Hi there! @2132132130",
  "mentions": [
    "2132132130@c.us"
  ]
}
```
