### ISSUE TITLE
Do not receive event on image message [plus version]

### ISSUE THREAD

**Issue by yurganov** [allburov/whatsapp-http-api#107]
[Nest] 20  - 06/08/2023, 7:43:38 AM     LOG [WhatsappSession - default] The message false_66xx9@c.us_3A631AAE48F0F4BA2817 has media, downloading it...
[Nest] 20  - 06/08/2023, 7:43:38 AM VERBOSE [WhatsappSession - default] Writing file from the message [object Object]...
[Nest] 20  - 06/08/2023, 7:44:30 AM     LOG [WhatsappSession - default] The message false_66xx9@c.us_3A6F3AD734796683F816 has media, downloading it...
[Nest] 20  - 06/08/2023, 7:44:30 AM VERBOSE [WhatsappSession - default] Writing file from the message [object Object]...

**Comment by yurganov** [comment]
folder is empty, no event no webhook also

**Comment by allburov** [comment]
Hi!
The issue has been fixed in WAHA Plus 2023.6.9, please update the image and try again!
https://waha.devlike.pro/docs/overview/faq/#how-to-update
