### ISSUE TITLE
Media attachment's available only in WAHA Plus version [plus]

### ISSUE THREAD

**Issue by yurganov** [allburov/whatsapp-http-api#109]
I got error Media attachment's available only in WAHA Plus version

version: '3'
services:
  whatsapp-http-api-plus:
    image: devlikeapro/whatsapp-http-api-plus
    ports:
      - 127.0.0.1:3005:3000/tcp
    environment:
      - WHATSAPP_HOOK_EVENTS=message.any
      - WHATSAPP_HOOK_URL=http://
    restart: unless-stopped

**Comment by allburov** [comment]
OMG, sorry, published the wrong version :(
Now it's been fixed,I've tested it locally.

 Thank you for finding and reporting it so quickly!
