### ISSUE TITLE
Session not auth after restart

### ISSUE THREAD

**Issue by yurganov** [allburov/whatsapp-http-api#110]
I restart docker container and start session manually.

That's first problem - can they start automatically?

Also, when I start it manually, it need to auth again.

Is it possible to keep session after restart?

Thx

**Comment by allburov** [comment]
Hi! Do you use Plus version or Core one? Session storage is supported in Plus one only https://waha.devlike.pro/docs/how-to/plus-version/

If you use Plus and still facing the problem - please pull an image with the latest version, we made a mistake this morning and published wrong version as Plus :(

**Comment by allburov** [comment]
Oh, sorry, didn't look at the nickname :D

**Comment by allburov** [comment]
1. There's few configuration options that could help you for restarting session or starting them automatically https://waha.devlike.pro/docs/how-to/config/
WHATSAPP_RESTART_ALL_SESSIONS=True
WHATSAPP_START_SESSION=session1,session2

Use either of them - I usually prefer WHATSAPP_RESTART_ALL_SESSIONS

**Comment by allburov** [comment]
2. To store the session authentication you must map a permanent folder to the docker
https://waha.devlike.pro/docs/how-to/sessions/#advanced-sessions-imagesversionspluspng
```
docker run --rm -d -v `pwd`/.sessions:/app/.sessions -p 3000:3000/tcp --name whatsapp-http-api devlikeapro/whatsapp-http-api-plus
```

**Comment by allburov** [comment]
Let me know if there's any questions left!

**Comment by yurganov** [comment]
no questions, I just did not read the documentation well.

thanks!
