### ISSUE TITLE
Follow redirects for webhook url

### ISSUE THREAD

**Issue by yurganov** [allburov/whatsapp-http-api#112]
`[Nest] 21  - 06/11/2023, 7:11:34 PM     LOG [Webhook - default] POST request was sent with status code: 301
[Nest] 21  - 06/11/2023, 7:11:34 PM VERBOSE [Webhook - default] Response: "<html>\r\n<head><title>301 Moved Permanently</title></head>\r\n<body>\r\n<center><h1>301 Moved Permanently</h1></center>\r\n<hr><center>nginx/1.18.0 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n"`

**Comment by allburov** [comment]
It's unusual for POST method to follow redirects because of security reasons. 
Use the actual webhook URL for that.
 
Here's some references -
https://github.com/follow-redirects/follow-redirects/issues/121#issuecomment-551739990

**Comment by devlikepro** [comment]
We moved recently to `axios`, let us know if the issue persists there!

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
