### ISSUE TITLE
Endpoint to get chats - GET /api/{session}/chats

### ISSUE THREAD

**Issue by tristan-thar** [allburov/whatsapp-http-api#114]
Hi! Are there any plans to have an endpoint which would list all active chats? Ie. all users and groups that you are actively chatting with.
If so, do you have an ETA for this feature? 

Thanks!

**Comment by allburov** [comment]
>you are actively chatting with.

The best way to get ACTIVE chats - is to listen a webhook and save active conversation it on your side, in database for instance.

Here's few endpoints that could help you to get other chats too
1. https://waha.devlike.pro/docs/how-to/contacts/#get-all-contacts
2. https://waha.devlike.pro/docs/how-to/groups/#get-all-groups

---

There's a way to get all chats tho, actually, so we can create `GET /api/{session}/chats` endpoint for that.
No ETA here

**Comment by tristan-thar** [comment]
Thanks for the quick reply @allburov. 

From my understanding the `/contacts/all `endpoint will list all your contacts though, not only the active ones, right? So that would mean that if your phone has contacts synced with whatsapp, that could be multiple hundreds if not thousands of contacts while you might be only chatting with 5-10 in reality.

Of course you can filter those to just the numbers who are your whatsapp contacts, but that's still way more than the active chats your're having (under the "Chats" tab in WhatsApp). 

The `GET /groups` endpoint is great though, as it's easy to filter for active ones. I'm looking for something similar, just with single contacts. 

Or am i missing something and this is already possible to do? 

Thanks :)

**Comment by liamgwallace** [comment]
@allburov How is [GET /api/{session}/chats] different to [GET /api/{session}/groups] ?

If you could retrieve the last n groups/chats in order that would sure be handy

**Comment by allburov** [comment]
/groups returns only "groups" conversation, where /chats will return all your open conversations, either groups or direct messages .
Under the hood /groups would be the same as `GET /chats?group=True`

**Comment by allburov** [comment]
Hi! There are few new endpoints for chat control https://waha.devlike.pro/docs/how-to/chats/

`GET /api/{session}/chats` what you're looking for!

**Comment by LeninZapata** [comment]
> Hi! There are few new endpoints for chat control https://waha.devlike.pro/docs/how-to/chats/
> 
> `GET /api/{session}/chats` what you're looking for!

@allburov With this I can get only the active chats (not archived) ?
