### ISSUE TITLE
How to send button in whatsapp now

### ISSUE THREAD

**Issue by ahmrifai** [allburov/whatsapp-http-api#118]
Please help me, how the json format to sending button

**Comment by allburov** [comment]
Hi! From what I know, WhatsApp started blocking buttons from usual clients and there's no such way of doing that in none of engines :( 
You can try the example from Swagger and see if it works with `NOWEB` engine and **iOS** WhatsApp app
```
{
  "chatId": "11111111111@c.us",
  "title": "string",
  "footer": "string",
  "buttons": [
    {
      "id": "string",
      "text": "string"
    }
  ],
  "session": "default"
}
```

**Comment by allburov** [comment]
https://dev.to/purpshell/buttons-and-lists-get-deprecated-by-many-libraries-54h

**Comment by allburov** [comment]
You can use Poll instead of buttons (for direct messages work exactly the same way) https://waha.devlike.pro/docs/how-to/polls/

Available only in NOWEB
