### ISSUE TITLE
Webhook associated with the session

### ISSUE THREAD

**Issue by nicolaslopez1000** [allburov/whatsapp-http-api#119]
Is there a way to have dynamic webhook? For example i want one session to post events to one url, and other session to a completely different application.

**Comment by allburov** [comment]
Hi! There's no way of doing it yet, but we're working on that and hopefullly'll add it by the end of August 
Here's more details about features that we're adding to webhooks - https://github.com/devlikeapro/whatsapp-http-api/issues/68

You can subscribe on [Boosty](boosty.to/wa-http-api) (with the Free tier) to get updates and news about the project to see when it's ready!

**Comment by allburov** [comment]
We released that in new version!
