### ISSUE TITLE
diazzaid / whatsapp-api-venom throws info:     [sessionName] Error no open browser....

### ISSUE THREAD

**Issue by alijundi** [allburov/whatsapp-http-api#12]
I get the below:

```
> whatsapp-api-venom@0.0.1 start
> nest start

[Nest] 74040   - 12/11/2021, 1:51:03 PM   [NestFactory] Starting Nest application...



 /\\\      /\\\ /\\\\\\\\\\  /\\\\\     /\\\    /\\\\\\\\    /\\\      \\\\
 \/\\\     /\\\ \/\\\_____/  \/\\\ \\\  \/\\\  /\\\_____/\\\ \/\\\ \\ \\ \\\
   \/\\\   /\\\  \/\\\        \/\\\ /\\\ \/\\\ \/\\\    \/\\\ \/\\\  \\\  \\\
    \/\\\  /\\\   \/\\\\\\\\\\ \/\\\  /\\\ /\\\ \/\\\    \/\\\ \/\\\  \\\  \\\
      \/\\\ \\\    \/\\\_____/  \/\\\ \/\\\ /\\\ \/\\\    \/\\\ \/\\\  \\\  \\\
       \/\\\\\\     \/\\\        \/\\\ \ /\\\ \\\ \/\\\    \/\\\ \/\\\  \\\  \\\
        \/_/\\\      \/\\\\\\\\\\ \/\\\  \/_\\\\\\ \/_/\\\\\\\\\  \/\\\  \\\  \\\
          \/__/       \/________/  \/_/    \/____/    \/_______/   \/_/ \/_/ \/_/



info:     [sessionName] Initializing browser wss...
[Nest] 74040   - 12/11/2021, 1:51:04 PM   [InstanceLoader] ConfigHostModule dependencies initialized +337ms
[Nest] 74040   - 12/11/2021, 1:51:04 PM   [InstanceLoader] ConfigModule dependencies initialized +1ms
[Nest] 74040   - 12/11/2021, 1:51:04 PM   [InstanceLoader] WhatsappConfigService dependencies initialized +2ms
[Nest] 74040   - 12/11/2021, 1:51:04 PM   [InstanceLoader] ServeStaticModule dependencies initialized +0ms
info:     [sessionName] Error no open browser....
noOpenBrowser
[Nest] 74040   - 12/11/2021, 1:51:04 PM   [ExceptionHandler]  +89ms
```

I am not sure what to do? any help please.... thanks in advance

**Comment by diazzaid** [comment]
> I get the below:
> 
> ```
> > whatsapp-api-venom@0.0.1 start
> > nest start
> 
> [Nest] 74040   - 12/11/2021, 1:51:03 PM   [NestFactory] Starting Nest application...
> 
> 
> 
>  /\\\      /\\\ /\\\\\\\\\\  /\\\\\     /\\\    /\\\\\\\\    /\\\      \\\\
>  \/\\\     /\\\ \/\\\_____/  \/\\\ \\\  \/\\\  /\\\_____/\\\ \/\\\ \\ \\ \\\
>    \/\\\   /\\\  \/\\\        \/\\\ /\\\ \/\\\ \/\\\    \/\\\ \/\\\  \\\  \\\
>     \/\\\  /\\\   \/\\\\\\\\\\ \/\\\  /\\\ /\\\ \/\\\    \/\\\ \/\\\  \\\  \\\
>       \/\\\ \\\    \/\\\_____/  \/\\\ \/\\\ /\\\ \/\\\    \/\\\ \/\\\  \\\  \\\
>        \/\\\\\\     \/\\\        \/\\\ \ /\\\ \\\ \/\\\    \/\\\ \/\\\  \\\  \\\
>         \/_/\\\      \/\\\\\\\\\\ \/\\\  \/_\\\\\\ \/_/\\\\\\\\\  \/\\\  \\\  \\\
>           \/__/       \/________/  \/_/    \/____/    \/_______/   \/_/ \/_/ \/_/
> 
> 
> 
> info:     [sessionName] Initializing browser wss...
> [Nest] 74040   - 12/11/2021, 1:51:04 PM   [InstanceLoader] ConfigHostModule dependencies initialized +337ms
> [Nest] 74040   - 12/11/2021, 1:51:04 PM   [InstanceLoader] ConfigModule dependencies initialized +1ms
> [Nest] 74040   - 12/11/2021, 1:51:04 PM   [InstanceLoader] WhatsappConfigService dependencies initialized +2ms
> [Nest] 74040   - 12/11/2021, 1:51:04 PM   [InstanceLoader] ServeStaticModule dependencies initialized +0ms
> info:     [sessionName] Error no open browser....
> noOpenBrowser
> [Nest] 74040   - 12/11/2021, 1:51:04 PM   [ExceptionHandler]  +89ms
> ```
> 
> I am not sure what to do? any help please.... thanks in advance

try git pull
