### ISSUE TITLE
WaHa Pro - Show always online?

### ISSUE THREAD

**Issue by Jolloniego** [allburov/whatsapp-http-api#121]
Is there a way to set a waha bot to always appear online? 

Could not find it in the docs.

**Comment by allburov** [comment]
Hi! Right now it's not possible, but we'll look at this!

**Comment by allburov** [comment]
Hi! There's a new endpoint in the latest WAHA Plus version `2023.7.12`, we'll add it in the next release in WAHA Core.

To set your status as "online", you send a `POST /api/<session>/presence` request with the body:
```json
{
  "presence": "online"
}
```
I haven't tested how often you should send it, usually state works for about 10-25 seconds, after that time you'll probably have to send another request for that.

Keep in mind that being always online will turn off your push notifications from the device https://github.com/devlikeapro/whatsapp-http-api/issues/28

---

# Presence

Possible presence statuses that you can set or get for chats:
- `online`
- `offline`
- `typing`
- `recording`
- `paused` resets the chat presence after you were `typing`


## Endpoints

### Set presence
You can set your global or chat-related presence with `POST /api/{session}/presence` endpoint

Start typing to a chat (you can use `POST /startTyping` instead)
```json
{
  "chatId": "111111111@c.us",
  "presence": "typing"
}
```

Clear "typing" state (you can use `POST /stopTyping` instead)
```json
{
  "chatId": "111111111@c.us",
  "presence": "paused"
}
```

Set global "online", all contacts will see it
```json
{
  "presence": "online"
}
```

💡 In the multi-device version of WhatsApp - if a desktop client is active, WhatsApp doesn't send push notifications
to the device.
If you would like to receive said notifications - you need to mark a session's presence as `offline`.

```json
{
  "presence": "offline"
}
```

**Comment by Jolloniego** [comment]
Thank you @allburov!
