### ISSUE TITLE
[PLUS] - Getting error when getting docker build

### ISSUE THREAD

**Issue by mehmetcoskun** [allburov/whatsapp-http-api#124]
When I try to run Docker as usual, I get an error in the new version. The error message displayed is shown in the attached screenshot [screenshot](https://prnt.sc/AA5fGHUhixzW)

**Comment by allburov** [comment]
Please provide logs as text for the future with screenshot - it'll help people find related issues faster
Looking at this

**Comment by allburov** [comment]
Fixed! Please fetch the latest main branch from the repo https://github.com/devlikeapro/whatsapp-http-api-plus
