### ISSUE TITLE
[PLUS] Download Error when call /sendImage

### ISSUE THREAD

**Issue by frungillo** [allburov/whatsapp-http-api#126]
When I call the sendImage method, passing a BASE64 image above 30k, the recipient of the message is not able to see the image but only the preview thumbnail. When I click on the image to open it WhatsApp says "Unable to download image".
I thought it was a problem in my c# code and tried to post directly from SWAGGER. Same result. What am I doing wrong?

This is the JSON Object passed to SWAGGER

`{"chatId":"39XXXXXXXXXXX@c.us","session":"Test","file":{"mimetype":"image/jpeg","filename":"Immagine_25.jpeg","data":"/9j/4AAQSkZJRgABAQAAAQABAAD/4gHYSUNDX1BST0ZJTEUAAQEAAAHIAAAAAAQwAABtbnRyUkdCIFhZWiAH4AABAAEAAAAAAABhY3NwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAA9tYAAQAAAADTLQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlkZXNjAAAA8AAAACRyWFlaAAABFAAAABRnWFlaAAABKAAAABRiWFlaAAABPAAAABR3dHB0AAABUAAAABRyVFJDAAABZAAAAChnVFJDAAABZAAAAChiVFJDAAABZAAAAChjcHJ0AAABjAAAADxtbHVjAAAAAAAAAAEAAAAMZW5VUwAAAAgAAAAcAHMAUgBHAEJYWVogAAAAAAAAb6IAADj1AAADkFhZWiAAAAAAAABimQAAt4UAABjaWFlaIAAAAAAAACSgAAAPhAAAts9YWVogAAAAAAAA9tYAAQAAAADTLXBhcmEAAAAAAAQAAAACZmYAAPKnAAANWQAAE9AAAApbAAAAAAAAAABtbHVjAAAAAAAAAAEAAAAMZW5VUwAAACAAAAAcAEcAbwBvAGcAbABlACAASQBuAGMALgAgADIAMAAxADb/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD/wAARCABkADgDASIAAhEBAxEB/8QAHQAAAgICAwEAAAAAAAAAAAAAAAgGCQUHAQIEA//EADoQAAIBAwMDAwMBBAcJAAAAAAECAwQFEQAGEgchMQgTQRQiUWEjMnGBCRUXQpGx8CQzcnShosHR4f/EABoBAAEFAQAAAAAAAAAAAAAAAAUAAQMEBgL/xAAoEQABBAECBAcBAQAAAAAAAAABAAIDEQQhMQUSQWEyUXGBseHwE5H/2gAMAwEAAhEDEQA/AN6dckNF1Do5u/FnQL+M5bOtj7YVvpozj+4MgjzqB+pxY6HeW35zgCaoxy/GCMf56kdv3ltXbtLSwX/cNut81THmFKmpSN5ceeCk5bHbOPyNDGlW3jyUvmbl84wPnXgmySBx+fB+NYWv6lbFpPtqd026LOMLJMq5ycDscH/H9NYyHqn0/q5eFLuqgn+728xyiRVbAJBKkgeR/j+upd1FSkUnwD3/ADrwzhuRwT8Hzrmlu9ruaGS3V9PUox8xOG/y8a4mdCPnv5z8aSZeCUsxIY57jx2P8dGioYj9wZOfgaNOkoj66LnHt5du3mQlI4rgObjt9vEsR+f7vx+NIDvb1X7lvr1Nn2vTtSQVUoNRcc8qychmwAe6ogDcVUDIAwCAcacn+k33HSy9PdtUlIi1K3gTVkc4IZFjSAjPY/3veABHb9fGaxrBRbhuVPJHYKCvmMrftmp4ywIIIC9hnBw2e+Djx21FExrrc5XHWAOXcqZVF6r7JUl7jd3mEoZDG9XylpyvENG8eeSgAjyoB747qcfJd9Xmx1tNX0d3mEb5EZWRirLnJUqe2MnOMY/nqM3XYm7KBPcrrLVwEFRh0JIBHb/LWLrttbqt1P78ltq0pmJOeJKsR/0Pz/o6mDWHW1yTJqOVN1066lG82+K82m4vBVwcVqI42Ksj/wAM91PcjOcjI8g6YrY/VS719KsdVU+6V7MJDn51Xf0Ov1ZR7tjtYB4V8bpIpJHFkUurYHyACP4MdOrsChdKZZnXDu2fu/j207hSr6Bb/g3NDWRqWiKcu+Q2QD/DRqLUBkQL4yPgjP8Aho1HaVLt66unkO5fTVt250FNJ9fZKSjjpUgiJaRJFjjMSqvnJ4YABPYAYznSeelvZ1Vfau5WKimip6W0FTVVMWCZmdmCgEYyDxchjkYA/TVl9VtO07y2Fb9kXSSpegpKpamWR5vckljWYzJErEfYFb2xk8vsQr2J5DSdL02tG397Xmthpo6SW6xR01V9LG8Uc88Dyj31k75LiQK2ApDISR3BI3Nc5sfINitDwqNkjue9W9Ox+1GL/wBNLZVW+Gk+nnljAVCvuAqcEYyD28gfGOw8a0D18s+2rTTQ2a7vSW2d+0EUbAylcYHFRkgdsfjsfxpjtq7Eewbiqauq2taLfFDFHFTT0iyS1GCn3rJOzEzKXL8cqpxxyAca0ruinum66/cFwotwS2usprjVwV1LFTxqlTCrRCnLMwL/AGxxygjJVvdXATjlx8UIZICXbfu6NSyOkjoN3/dks/RyyUlJd6u+VEcMnt1DQ0MxbJUAlXYY7DP2jPnz4B7uTtq826ipoHrK+ngWRQymSQLn57Z/lpAL1uy42LeNdNY5oDAr+20eCY3PcnkB8qzMMjHjH511p+pG9oSJVvWD/wAtF3/7f9dtaoRue0FYSZzWyEDYKyeLqHs9ZBTvuGjjkbIALkdxn50ar1s/Wm/0TpHdqSGuiGQ0ij25iM/kfZ2/4RnHc/OjXJgIXP8AQK4S+dY+m3SbbyXzqPvK32OnqFAgSdy89QeaKwhgQNLNxMicuCtxB5HAyQh3Sj1QXnd/qZucO4N2Xaba94qLo+3KO4umad6irSaKJ2ySMRR+2il2VSQiYB1MP6QHcVorOl2xbT9AslwuVwmrqOvwp9qnhiX3EDeRzaenbA7H2hnwNJHt6srrNuKhvUNR7FRQzCWKZUD4dTlW4nIODjsQcgfPjXEmOJMd3mreDkGHKaboXr6K3i4Xm10caC510MPb3ByYBiAMnGT92Mjx+n50n3V2+020qjqFuu2V8M9BO8bRhZo2/ayDAH2nPIkHsfxrb3R7rztbqJtSGx3WpoJb7GvH6FKoCWQqhy0XI8nHEMex5KM8vHIrR6n+oHT+4UFzslorTW3mSp9gQQj9lQKv+9kndsrLK+TGqoTwAZmYMFXQHFiMkoZXqtbmZLIMd0l69PpKhzknqGnmIZ5GLuB27k58fx16lT90DHbsM/8Az/XfXRIEibJB5Ht48fnXc/b3PHIwDrXAUsATa4f9wup7qCMH40a6vJxQqq9yc/w/9aNI0mW4OtG6Jt87tjvQqaqSnjtdBS06TSMwhWOmjDqgPZFMnuPgdsuT5JJ1xLHMkE8pc8FjbDfIOO3/AJ1s+22Ku2LcNl7q6sdMr7Jte5tS1aU9wpKq3xXyhURPKtNUkJy5RuuHjY45q3cHu5Xrh2R6Tpq3o9vvatHt/a+yN+Wm9rUXexW6aGmJigi+hnejpky0kU9U/NDGsjYMUjIq/YgAAAF1ubVc9NJzjUIFwUGBjsNZ7Z/THqH1Orp7V082Nft0VlIiPPDabdLVNArHAaQRqeC57cmwP11YjvXot0k6OdBugHqXsHQii3g1JbbUdz2VLbG9NcKOpschqK2rX2XBaJ0jlDyDiH8kFuQi/pD3/WdIdj7s3j6c+ndz3BQ1u2Lddt7X28QzUtls9TaqeaethppZGaSsqpoqgIsA9tY5mWQFoGIja/JKlpz0segG6eo+K4z3TqfbNrrRxs8EdLQ/1tLKqTvAZHMcscUcbSRSiNvcYy+1IVGELaUSZe5YYx4GAO+rX/T/ANO/TXun0XU++utu35qHYNFfqm+1FBFX3GpWidKioo4QWgJqGAWYFuHFSxLlVUkarS6uWzb1r6h7li2laq+17bqLjNWWKlr45EnW1TN7tCze7lyGppIWViTyDBsnOS4NpioLIWYgAHB7HB8fnRoaTKA58/un5PbRpkyuhv3T7avWfbe4dk7xsVNc0mK2yklaBvqaZo/2kM9Ow4ssqySyEP5KyMjZQ8NJTvToB1S2Be9udMt9dZLP/Z7Z7jUNtq8XBfqLPbKquWJmgr3Qe7SUtQyIjOVMQcyM8cfuStphegXWJNx703XZbrWUrJC1PXiljxFIGlJV1IQEBRxjJwo45I8kLqadaNsR9abNd7ItNNXV11o2jjjoKeCM1KsEaT3DhZCQqM2EcjmZOCuZAQMhmdHui0sAedEg1x3p0r6c7X3dtK07SvUV7vVHW0tq3LatxLVW66UP9aQZQwSQRyxU/ChqfbfkZWMuJVZGBjsSp/XJ6W7Pcdmbd6c7jsNLsmqs96hvEdus81DHaKikjgq4f9lZIysMiy1w/ZxMZJeCr3V8VAb+2pc9gbiqrDXrK0aEimqHGDImO/jtkZwfB8HGCNYmjvVZRSGSjrJoC6SRM8UhVjG6FHQkY+1lZlI8EEg5B0TBDxYQxwLDRVmnRH1kdEPSRtXenT7p/br3vGivF9q91bSraoG1W6qtzUsCNTtNUF6hZY5aSrp1P05E0saH7BKSiIeorq5d/UX1hunUme3LHcb/AA29ailpYWVPqoqKCCRYk5O3AvE3HLFipGe+da+WqSXI5gZBBz4wcaZ304dGt43/AGCb4m2bbPa7xVSm31kPsRV2EJimD1PeRKclGT2vbkPuDnxUDLw5Eox2c6tYWKc2UR3SWK72C+WCoNLd6GSlcdiGw3z+QSO/n9Qe2c6NOD6g7Bs3b80u3zbZKSihomiljYcpGLj7HyQcsOzAkdiAfjRqpBxASNt4/wAV7L4M6F/LE6x3WD6NvVbB9Qlt2xYa2b6WkkuUfKYKzy8KWRwXAAViWiiJPHvwX47acWOrnq6qWuq3WeQV6cllRXSTlzY8lIIIJQZHggn86NGq56KUgWUm/q9slmrdq3Xci2mkpay33enpYPpoVjRVaGFmwoH2AmVvsTigwuFHEYUCB2KAk92Xz/PRo0RxvB7oXleP2X2QlT5J/n+uNOl6CN27lrIb9tKpvM8tptwgqKOmkVXWneQymTgWBKqxQEqDxyWOMsxJo1HnC4D7fKtcIJGW2u/wvn6yJ/csq3OKJYJ6asloSyMxaUGHlzdmJYsPAwQoHhckkmjRqHhwBiKs8ccROKPRf//Z"},"caption":"Buongiorno ,  questo è *auxilia*"}`

**Comment by allburov** [comment]
Hi! Do you use default engine?

I've tested it with the above example - it works fine (it's 3.5 KB in size tho)
After that tested it with 135KB image - it works too, here's an example, could you test this payload please? https://gist.github.com/allburov/ce18d38143e6bc7f273d5fe46532b3e1 

Could you try posting the same image by url to see if it works for your?

You can also check that you encoding is correct here (but I see that it's correct if the example above's been generated with your code) https://base64.guru/converter/encode/file

**Comment by frungillo** [comment]
Tnx for reply. so, in my example I mistakenly passed the BASE64 of the thumbnail image. The original image and the original POST I send to the method  has a size of about 644 kb, by submitting this post, you should also experience the problem.
[https://gist.github.com/frungillo/0daffaa1acb168f85eec33cc2985410b#file-send-json](https://gist.github.com/frungillo/0daffaa1acb168f85eec33cc2985410b#file-send-json)

I don't know what you mean by "default engine", I sure use the downloaded image with the password obtained from boosty.

**Comment by allburov** [comment]
@frungillo yep, it's same for me, thank you, looking at this!

**Comment by allburov** [comment]
Sorry, I've tried `sendText` instead :)  I see the file as attachment in my messages with the payload you provided

**Comment by allburov** [comment]
The first two is my /sendText attempts, the two later are /sendImage
![IMG_20230710_161508](https://github.com/devlikeapro/whatsapp-http-api/assets/4376814/835629d1-4368-41bc-8167-3642c4dba78b)

**Comment by allburov** [comment]
It's weird that it doesn't generate thumbnail tho for the image and shows it as a file

**Comment by frungillo** [comment]
if I use sendFile or sendText, i see the same behavior... the file is attach, and if i click on the attachment the image is correctly downloaded. The problem is on sendImage.

**Comment by allburov** [comment]
I see, for me `sendImage` works exactly as `sendFile`... I'll keep trying to reproduce it!

**Comment by allburov** [comment]
Speaking about engines - there's few engines that you can use https://waha.devlike.pro/docs/how-to/engines/
We'd recommend either default one (that you're using right now) or NOWEB, VENOM has bugs and too slow

**Comment by allburov** [comment]
But it shows the error for me when I'm trying to post by url
```json
{
  "session": "default",
  "chatId": "123@c.us",
  "file": {
    "url": "https://github-production-user-asset-6210df.s3.amazonaws.com/4376814/252297496-53ff9b83-70cd-4429-8926-5e228b0e8b00.jpeg",
    "filename": "filename.jpeg"
  },
  "caption": "string"
}
```
[download](https://github.com/devlikeapro/whatsapp-http-api/assets/4376814/53ff9b83-70cd-4429-8926-5e228b0e8b00)

**Comment by allburov** [comment]
But it works fine with this 2Mb and 700KB image too :(
```json
{
  "session": "default",
  "chatId": "123@c.us",
  "file": {
    "mimetype": "image/jpeg",
    "url": "https://images.unsplash.com/photo-1557479231-e24a676eaa16?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&dl=zane-lee-FcbUKIuoGE0-unsplash.jpg",
    "filename": "filename.jpeg"
  },
  "caption": "string"
}
```
```json
{
  "session": "default",
  "chatId": "123@c.us",
  "file": {
    "mimetype": "image/jpeg",
    "url": "https://images.unsplash.com/photo-1557479231-e24a676eaa16?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&dl=zane-lee-FcbUKIuoGE0-unsplash.jpg&w=1920",
    "filename": "filename.jpeg"
  },
  "caption": "string"
}
```

Does it works with other images for you?

**Comment by frungillo** [comment]
i can try, give me a few minutes.

**Comment by allburov** [comment]
I think I found the issue, publishing a new version

**Comment by frungillo** [comment]
wow! Great!

**Comment by frungillo** [comment]
when can I download from boosty?

**Comment by allburov** [comment]
btw, there's typo in [the provided example](https://gist.github.com/frungillo/0daffaa1acb168f85eec33cc2985410b#file-send-json) I believe - this is why I saw image as file attachment **minetype**. It's important to provide **exact** request that you make in order to help with that (except personal information, of course)


>when can I download from boosty?

Just run the same `login\pull\logout` commands and restart the container (docker stop whatsapp-http-api \ docker run ...)
https://boosty.to/wa-http-api/posts/bbbc52d0-1e37-424e-a7dc-0d1f25426807

Let me know if it helps and we can close the ticket!

**Comment by frungillo** [comment]
ok. I'll try in a few minutes, but if u've tested the thing, i guess the tiket can be close...
