### ISSUE TITLE
[PLUS] Add option to not save files

### ISSUE THREAD

**Issue by dv336699** [allburov/whatsapp-http-api#128]
In this section https://waha.devlike.pro/docs/how-to/config/#files-imagesversionspluspng there are a few variables related to files.

Would there be any chance another option can be added to not save the files at all instead of saving and then deleting them?
We only care about the messages and not the files.

Thanks

**Comment by dv336699** [comment]
Never mind, I guess I can set https://waha.devlike.pro/docs/how-to/config/#downloading-specific-mimetypes to `font/woff` and it will ignore images/video I guess.

Thanks

**Comment by allburov** [comment]
Yes, exactly! We'll add it to the doc, thank you for pointing it out.
