### ISSUE TITLE
/screenshot : Extract QR code image when session is in "SCAN_QR_CODE"

### ISSUE THREAD

**Issue by ehussain** [allburov/whatsapp-http-api#129]
Hello,

Screenshot end point currently returns entire screenshot of whatsapp screen. 
I request you to add a option in end point or a separate end point which can return only QR code image if session is in "SCAN_QR_CODE" status.

Current response : 
![image](https://github.com/devlikeapro/whatsapp-http-api/assets/358413/f7efb923-22a2-4240-ae13-3823bb05bf91)

Expected response (status is "SCAN_QR_CODE"): 
![image](https://github.com/devlikeapro/whatsapp-http-api/assets/358413/2336d746-809a-44ff-8860-9641a8368c52)

Thanks.

**Comment by arthurbarros** [comment]
The endpoint on NOWEB engine returns only the QRCOde, if the limitations on that engine isnt a issue you could use that.

**Comment by ehussain** [comment]
I am looking for that option in Puppeteer version. Because NOWEB has high chances of getting blocked so we are avoiding that option.

**Comment by arthurbarros** [comment]
@ehussain I've been using in multiple numbers NOWEB since it got available to use. never had a singles number blocked because of it.

**Comment by allburov** [comment]
Hi! 
We've added a new endpoint for that - `GET /api/{session}/auth/qr`  - works the same way on both engines, WEBJS and NOWEB, returns only QR image.
https://waha.devlike.pro/docs/how-to/sessions/#get-qr

---

Available in WAHA Plus starting `2023.8.13` version, please update the image and restart docker containers! We'll release the feature in September 2023 in Core.
