### ISSUE TITLE
Receive original file name for any incoming message.

### ISSUE THREAD

**Issue by ehussain** [allburov/whatsapp-http-api#135]
Hello,

Currently when any person sends a document or image to our phone number then there is no way to know the original file name of the file.

Response comes with mediaUrl and other additional parameters like mimetype. however there is no parameter which specifies the original file name sent by the sender.

Please implement this request so we can receive original filename for all of incoming files.

**Comment by allburov** [comment]
Added `filename` field for documents media (file attachments). It's not available for images and videos tho, it's a different media type with no filename. 

The changes will be released on 1-4 December, in `2023.12.1` version

-----

For documents (file attachments) there's also `filename` field with the original file name.
```json
{
  "event": "message",
  "session": "default",
  "payload": {
    "id": "true_11111111111@c.us_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "timestamp": 1667561485,
    "from": "11111111111@c.us",
    "mediaUrl": "http://localhost:3000/api/files/true_11111111111@c.us_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.pdf",
    "filename": "some-file.pdf"
  }
}
```
