### ISSUE TITLE
/api/contacts/all - fetch all contacts sorted by the 'last message received' date

### ISSUE THREAD

**Issue by ehussain** [allburov/whatsapp-http-api#139]
Hello.

We would like to fetch all contacts in phone but it should be sorted in 'last message received' date order.
Please add a parameter to api so that we can get contacts in requested order. 

Current api returns the contacts in alphabetical order. but our need is to sync the messages that apperared when phone was not connected with session. so its important to get contacts in order by last message date.

Thank you.

**Comment by allburov** [comment]
I think it's what /chats will be for https://github.com/devlikeapro/whatsapp-http-api/issues/114

**Comment by ehussain** [comment]
What will be the ETA for this feature? 
When can we expect to have this?

**Comment by devlikepro** [comment]
`GET /chats` is exactly what you asked - it's sorted by last received message
https://waha.devlike.pro/docs/how-to/chats/#get-all-chats

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
