### ISSUE TITLE
/api/messages - get messages in a chat with date time range

### ISSUE THREAD

**Issue by ehussain** [allburov/whatsapp-http-api#140]
Hello,

Currently /api/messages api has parameter named 'limit' that represents count of messages that you need.
However we would like to receive messages only which falls within datetime range. So we only get the latest messages after specific timestamp.

Thank you.

**Comment by allburov** [comment]
The best way to handle it - listen to webhooks and save information in your database and query it

**Comment by ehussain** [comment]
How do we get the messages that was received on phone when session was not connected?
How do we sync those messages with our database?

**Comment by allburov** [comment]
You can get like limit 1000 and search new messages there. If you can get more than 1000 new messages while the session is off - I think you should look at the official API, they give much more stability.

Btw, from what I saw before - if the session is stopped and started after certain time - it'll send all "missed" messages to a webhook (if you use the same session, not a new one by scanning QR)

**Comment by devlikepro** [comment]
Added in `2024.10.9` 

https://waha.devlike.pro/docs/how-to/chats/#get-messages

---

```
GET /api/{session}/chats/{chatId}/messages?limit=10
```

Available parameters:
- `downloadMedia=true` - download media files (images, files) or not
- `chatId=123@c.us` - chatId, phone number 
  - `chatId=all` - get messages from all chats (works on **NOWEB**engine only)
- `limit=100` - limit the number of chats to return
- `offset=0` - skip the number of chats from the start
- `filter.timestamp.lte=1727745026` - filter messages by timestamp less than or equal to `1727745026`
- `filter.timestamp.gte=1727745026` - filter messages by timestamp greater than or equal to `1727745026`
- `filter.fromMe=false` - filter messages from me (by default shows all messages)

Get **10 messages** from 1727745026 timestamp, not from me

```
GET /api/{session}/chats/{chatId}/messages?limit=10&filter.timestamp.gte=1727745026&filter.fromMe=false
```

👉 If you have more messages - you can set `offset` flag 
(increase it always for `limit` amount, even if you get less messages)
```
GET /api/{session}/chats/{chatId}/messages?limit=10&offset=10&filter.timestamp.gte=1727745026&filter.fromMe=false
```


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
