### ISSUE TITLE
WA session not starting - Error: ENOENT: no such file or directory, open '/tmp/waha-sessions/webjs/

### ISSUE THREAD

**Issue by maciejbrylewicz** [allburov/whatsapp-http-api#143]
Hello, I have a docker installation and when I try to initialize the session, I get no response. If I move forward to QR code it just gives me a blank square. Please help

**Comment by maciejbrylewicz** [comment]
The error code:

Error: Bad Request
Response body
Download

{
  "statusCode": 400,
  "message": "Expected double-quoted property name in JSON at position 28",
  "error": "Bad Request"
}

Response headers

 connection: keep-alive  content-length: 112  content-type: application/json; charset=utf-8  date: Fri,14 Jul 2023 16:06:56 GMT  etag: W/"70-odr58HQ7mNffjY2RQhBFdE1QzMY"  keep-alive: timeout=5  x-powered-by: Express

**Comment by maciejbrylewicz** [comment]
I removed the additional comma, but still getting another error:

500
Undocumented
	

Error: Internal Server Error
Response body
Download

{
  "statusCode": 500,
  "timestamp": "2023-07-14T16:09:46.309Z",
  "exception": {
    "stack": "Error: ENOENT: no such file or directory, open '/tmp/waha-sessions/webjs/default-c21f969b5f03d33d43e04f8f136e7682/.waha.session.config.json'",
    "message": "ENOENT: no such file or directory, open '/tmp/waha-sessions/webjs/default-c21f969b5f03d33d43e04f8f136e7682/.waha.session.config.json'",
    "errno": -2,
    "code": "ENOENT",
    "syscall": "open",
    "path": "/tmp/waha-sessions/webjs/default-c21f969b5f03d33d43e04f8f136e7682/.waha.session.config.json",
    "name": "Error"
  },
  "request": {
    "path": "/api/sessions/start",
    "method": "POST",
    "body": {
      "name": "default"
    },
    "query": {}
  },
  "version": {
    "version": "2023.7.12",
    "tier": "CORE",
    "browser": "/usr/bin/chromium"
  }
}

Response headers

 connection: keep-alive  content-length: 700  content-type: application/json; charset=utf-8  date: Fri,14 Jul 2023 16:09:46 GMT  etag: W/"2bc-SKLt4VmlTK+mCjMgvYotsQ4zwfE"  keep-alive: timeout=5  x-powered-by: Express

**Comment by maciejbrylewicz** [comment]
I have donated and the plus version has the same problem.

**Comment by allburov** [comment]
Hi! Could you try to start docker with connected filesystem this way please
```
docker run --rm -d -v `pwd`/.sessions:/app/.sessions -p 3000:3000/tcp --name whatsapp-http-api devlikeapro/whatsapp-http-api-plus
```

**Comment by maciejbrylewicz** [comment]
Hi, Got the QR code but scanning with my mob gives "couldn't link the
device. try again later"

**Comment by maciejbrylewicz** [comment]
Got it. I left the default configuration payload, but it came with a
webhook, which I haven't set up yet. I guess you can close this issue.
Maybe it makes sense to update the command online.

**Comment by allburov** [comment]
Do you use the latest WhatsApp version on the phone?
Can you connect usual WhatsApp Web on your browser? https://web.whatsapp.com

**Comment by allburov** [comment]
I've fixed `Error: ENOENT: no such file or directory, open '/tmp/waha-sessions/webjs/default-c21f969b5f03d33d43e04f8f136e7682/.waha.session.config.json` error  in the latest version.
Let me know if you have any issues with that!
