### ISSUE TITLE
send story status

### ISSUE THREAD

**Issue by sg957** [allburov/whatsapp-http-api#145]
Baileys added support for WhatsApp story posting in the latest version
Documentation of the change is here https://github.com/WhiskeySockets/Baileys/pull/249
The latest version with the change
https://github.com/WhiskeySockets/Baileys/releases/tag/v6.4.0
We would be happy if you could add support for this in your project.

**Comment by allburov** [comment]
Hi! We've added and released new PLUS version with those endpoints, now you can send status - text, image, voice or video!
https://waha.devlike.pro/docs/how-to/send-messages/#send-status-aka-stories
`POST /api/{session}/status/text|image|voice|video`

Please let me know if there's any issues with that
