### ISSUE TITLE
Multiple Issues with Whatsapp-http-api-plus version during creating session

### ISSUE THREAD

**Issue by ksingh7** [allburov/whatsapp-http-api#149]
1.  I tried to create a session (multiple time) but it fails, throwing the below error
`TimeoutError: Timed out after 30000 ms while trying to connect to the browser! Only Chrome at revision r982053 is guaranteed to work.`

![image](https://github.com/devlikeapro/whatsapp-http-api/assets/9701902/f21c0d3f-2923-4ef5-976e-28675cba558d)

2. After this failure i ran `GET /api/sessions` and the status was `failed`
![image](https://github.com/devlikeapro/whatsapp-http-api/assets/9701902/a07cdd64-1c0f-4de2-9f90-10f3becb388f)

3. Next i tried to stop the session by calling `/api/sessions/stop` and provided the session name
![image](https://github.com/devlikeapro/whatsapp-http-api/assets/9701902/940128cc-015f-48f8-8f01-754ecbc21271)
This resulted in error as shown below
![image](https://github.com/devlikeapro/whatsapp-http-api/assets/9701902/29add3c3-5ea8-406c-ac97-b336d7c735e7)

4. Then tried to `GET /api/sessions`
![image](https://github.com/devlikeapro/whatsapp-http-api/assets/9701902/4e00eb52-1967-49b0-ad85-910fce4ec769)

However in logs i am continuously getting QR codes 
![image](https://github.com/devlikeapro/whatsapp-http-api/assets/9701902/55552907-3fd5-4ae9-974c-e28d9c2767a3)

I am using `devlikeapro/whatsapp-http-api-plus` container image to deploy this application on Kubernetes .

**Comment by ksingh7** [comment]
Also intermittently i am getting issues like NO QR in `/api/screenshot` response 

![image](https://github.com/devlikeapro/whatsapp-http-api/assets/9701902/a4742a42-2ccc-4444-8db3-b5bff6368b06)

**Comment by ksingh7** [comment]
@allburov  can you help with the above reported issues , are these known issues with the default engine ? should we try changing the engine or something else to get it working.

I am looking to achieve consistency in establishing a session >> getting QR images >> authenticating session.

**Comment by ksingh7** [comment]
@allburov appreciate any guidance on this

**Comment by allburov** [comment]
Hi! Could you try to `POST /logout`  for that session and start it again?

**Comment by Kristian-Tan** [comment]
I can confirm this bug.

Maybe this bug only happen when list of chats are very long. I confirm this bug happened on a session that have 2000+ open chats and 1000+ unread chats.

Here is some logs:
```
(node:34) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 12 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:34) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 12 SIGINT listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(node:34) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 12 SIGTERM listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(node:34) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 12 SIGHUP listeners added to [process]. Use emitter.setMaxListeners() to increase limit

```

**Comment by devlikepro** [comment]
Hi! Could you try the recent version, `2026.6.4`? We've fixed the chrome version there and added chats limit query for getting long list of chats 

https://waha.devlike.pro/docs/how-to/chats/#get-all-chats

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
If it doesn't help - please comment here and we'll reopen the issue!

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
