### ISSUE TITLE
Even after log out from linked whatsapp from my mobile getting session is WORKING.

### ISSUE THREAD

**Issue by khushboo-scogo** [allburov/whatsapp-http-api#151]
hello @allburov , I have been using waha plus and encountered this issue. Though I have unlinked my whatsApp from the Phone, it shows the session is working. 
![image](https://github.com/devlikeapro/whatsapp-http-api/assets/140512413/26d307ed-45ed-416a-8b96-28dcb90f23df)
So I tried another api. It gave a response as
![image](https://github.com/devlikeapro/whatsapp-http-api/assets/140512413/6e320712-314f-4ccf-b610-6b64c8cbd49d).
After log out from mobile, sessions should stop working right and its status should be STOPPED or anything but not WORKING.
Can you please help me with this?

**Comment by devlikepro** [comment]
What engine do you use, WEBJS default one?

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
If you still have the issue - kindly attach logs after you logout from device.
I see now the session goes to FAILED almost right after logout

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
