### ISSUE TITLE
Get all chats Not working 

### ISSUE THREAD

**Issue by Devanagaraj** [allburov/whatsapp-http-api#152]
https://waha.devlike.pro/docs/how-to/chats/#get-all-chats
giving {'statusCode': 404, 'message': 'Cannot GET /api/otama/messages', 'error': 'Not Found'}

**Comment by allburov** [comment]
Hi! What version  (number) do you use? You can get it with /api/version

Btw, I didn't find the endpoint you mentioned in the doc
There's two of them -
1. GET /api/{session}/chats/{chatId}/messages?limit=100
2. http://localhost:3000/api/messages?chatId=11111111111%40c.us&limit=1000&session=default

Which one do you use?

**Comment by allburov** [comment]
Make sure you use the right endpoint with right parameters!

**Comment by Devanagaraj** [comment]
![image](https://github.com/devlikeapro/whatsapp-http-api/assets/46333885/a1221e83-2c11-45d7-b99a-f6cf28a98e6f)

I am using V 2023.7.1 plus version
http://localhost:3000/api/{session}/chats

not working. It is expected to return all last messages from the chats as per the documentation...

**Comment by allburov** [comment]
Sorry, the endpoints were added recently, could you try to update your container?
https://waha.devlike.pro/docs/overview/changelog/#20238

**Comment by Devanagaraj** [comment]
when did you updated this?

**Comment by allburov** [comment]
The latest version contains all endpoints you mentioned

> when did you updated this?

https://github.com/devlikeapro/whatsapp-http-api/releases/tag/2023.7.16
