### ISSUE TITLE
--use-pairing-code NOWEB

### ISSUE THREAD

**Issue by sg957** [allburov/whatsapp-http-api#154]
Added in Baileys the option to log in with a verification code instead of scanning a QR
It is much easier and convenient and also does not change every few seconds like QR
We'd appreciate it if you could add that too

**Comment by allburov** [comment]
Hi! 
We've added new endpoint for that - `POST /api/{session}/auth/request-code`
```json
{
  "phoneNumber": "12132132130"
}
```

https://waha.devlike.pro/docs/how-to/sessions/#get-pairing-code

Available in WAHA Plus starting `2023.8.13` version, please update the image and restart docker containers! We'll release the feature in September 2023 in Core.
