### ISSUE TITLE
Feature request - /forwardMessages - api end point to forward multiple messages to specific number.

### ISSUE THREAD

**Issue by ehussain** [allburov/whatsapp-http-api#158]
Hello,

We are looking for end point where we can send the message ids and chatId to forward messages.

Sample request.
```
{
    "chatId": "xxxxx@c.us"
    "messageIds": [
        "true_XXXXXXXX@c.us_3EB0E64C08B9F394XX3E0",
        "false_XXXXXXXX@c.us_3AFBDF13XXXXX6B5B05",
    ]
}
```

chatId - is phone number where message should be forwarded
messageIds - is array of message ids which should be forwarded

Response could be anything which indicates success.

**Comment by devlikepro** [comment]
UP - Got one more request about forwarding, will look at this soon

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by hasanbasri1993** [comment]
any update for this  ?

**Comment by devlikepro** [comment]
In **2024.11.1** will be available - `POST /api/forwardMessage`
```json
{
  "chatId": "11111111111@c.us",
  "messageId": "false_11111111111@c.us_AAAAAAAAAAAAAAAAAAAA",
  "session": "default"
}
```

in case of **NOWEB** it'll return the message it sent, but in WEBJS just `sent: true` for now, we'll fix it later in https://github.com/devlikeapro/waha/issues/588 (may be before releasing it, but we'll see)

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
https://waha.devlike.pro/docs/how-to/send-messages/#forward-message
For both WEBJS and NOWEB in 2024.10.5

---

## Forward Message

You can forward a message to another chat (that you chatted before, otherwise it may fail):

```
POST /api/forwardMessage
```

```json
{
  "chatId": "11111111111@c.us",
  "messageId": "false_11111111111@c.us_AAAAAAAAAAAAAAAAAAAA",
  "session": "default"
}
```


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
