### ISSUE TITLE
Feature Request - API to check message status by id

### ISSUE THREAD

**Issue by ehussain** [allburov/whatsapp-http-api#159]
Hello,

We are looking for api which we can use to get message object or a status about the message 'delivered', 'sent', 'seen' etc.
Currently we receive webhook for message.ack, however sometimes message webhooks are not received for some reason and because of that we are unable to get updated status of the message.

Sample request for getting message status
```
{
"chatId" : "XXXXXXX@c.us",
"messageId": "false_XXXXXXX@XXXXX"
}
```

This api would be very much useful in cases where we do not receive webhooks back into our system.

**Comment by devlikepro** [comment]
Added in `2024.10.9`

https://waha.devlike.pro/docs/how-to/chats/#get-message-by-id

----

### Get message by id
Get message by id 
```
GET /api/{session}/chats/{chatId}/messages/{messageId}?downloadMedia=true
```

```json
{
    "id": "false_123123@c.us_AAAAAA",
    "timestamp": 1727745026,
    "from": "123123@c.us",
    "fromMe": false,
    "body": "I'm good!",
    "hasMedia": false,
    "ack": 3,
    "ackName": "READ",
    "replyTo": null,
    "_data": {
        ... // Raw Engine Data
    }
}
```

- `chatId` - in format `123123123@c.us`
- `messageId` - must be in format `{true|false}_213213@c.us_AAAAAAA`)
- `downloadMedia` - download media files (images, files) or not



[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
