### ISSUE TITLE
Session would not be saved if server down or docker stop suddenly

### ISSUE THREAD

**Issue by felixnguyen258** [allburov/whatsapp-http-api#160]
Hi

I face to an issue like the step procedure as below:

1) Create and start new sessions named "session_test_01" and "session_test_02". OK
<img width="317" alt="image" src="https://github.com/devlikeapro/whatsapp-http-api/assets/114893777/eb972995-dd4f-4662-8888-e9d0ce8c9b68">

2) Scan QR Code to link WA account with WAHA app. OK
<img width="354" alt="image" src="https://github.com/devlikeapro/whatsapp-http-api/assets/114893777/d50fb495-d632-47ba-bba3-0eae271be456">

3) Stop docker - re-run docker.
<img width="1092" alt="image" src="https://github.com/devlikeapro/whatsapp-http-api/assets/114893777/2c8c2d40-7d78-4988-8a7a-a156e60df10f">

>> Cannot query previous session.
<img width="740" alt="image" src="https://github.com/devlikeapro/whatsapp-http-api/assets/114893777/6513b265-2bc3-4047-9839-38715d15aa46">

Workaround:
I tried to hard-code the configuration with <_-e "WHATSAPP_START_SESSION=session_test_01, session_test_02"_> in docker run command and it will add 2 sessions but the status is "SCAN_QR_CODE".
<img width="436" alt="image" src="https://github.com/devlikeapro/whatsapp-http-api/assets/114893777/933a6eb7-ba2d-4523-8297-3f19bd917566">

Any advice for auto saving and auto init the previous session name list after instances down?

Thanks & Regards,
Felix

**Comment by allburov** [comment]
Hi! 

> Any advice for auto saving 

Could you share the command you run docker container with?

It should container `-v `pwd`/.sessions:/app/.sessions`.
If it doesn't work - please replace **pwd** with the real path, like this way - `-v /home/allburov/.sessions:/app/.sessions`

docker run --rm -d -v /home/allburov/.sessions:/app/.sessions -p 3000:3000/tcp --name whatsapp-http-api devlikeapro/whatsapp-http-api-plus


> Any advice for ... auto init the previous session name list after instances down

You can set `WHATSAPP_RESTART_ALL_SESSIONS=True` environment variable - on the container start it'll restart all STOPPED session. 
It can't actually track which session was running so it'll restart all sessions - you can see the list by using `GET /api/sessions/all=True`. If you don't want STOPPED session to be restart - you can logout it with `POST /api/sessions/logout`


Let me know if it helps!

**Comment by devlikepro** [comment]
@felixnguyen258 Do you have any questions here or the suggestion helped?

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
