### ISSUE TITLE
Latest Version - Session goes to the FAILED state immediately after scanning QRCODE

### ISSUE THREAD

**Issue by ehussain** [allburov/whatsapp-http-api#162]
Hello,

After updating image with new pro version and restarting the docker containers we are facing this error.

When new session is created it goes into SCAN_QR_CODE state. However once QRCODE is scanned and login completes then session goes into "FAILED" state immediately. 

I deleted the session folders also and repeated image update and docker container restart steps and still facing same error.

{"name":"60601-01","status":"FAILED","config":{"proxy":null,"webhooks":[{"url":'*****',"events":["message","message.any","message.ack"],"hmac":null,"retries":null,"customHeaders":null}]}}

**Comment by allburov** [comment]
ℹ️⚠️
Hi everyone!
If you're facing the same issue with FAILED session - please update to the **2023.8.10** version, it fixes the issue

The error in logs you could see is 
```
 ERROR [WhatsappSession - 60601-01] Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'CallCollection')
    at __puppeteer_evaluation_script__:9:66
```
