### ISSUE TITLE
Whatsapp is not connecting 

### ISSUE THREAD

**Issue by JuliaCristine** [allburov/whatsapp-http-api#166]
I made the integration with WAHA API but I`m getting able to connect WhatsApp, then I also tried to connect Whatsapp using Swagger it shows the following error: 

<img width="1029" alt="image" src="https://github.com/devlikeapro/whatsapp-http-api/assets/17750415/0fc41ef9-450b-433d-878a-e070ef2d9766">

**Comment by Sysoev86** [comment]
I got an error right after scanning the QR code since today:

{
  "statusCode": 422,
  "message": "The session under FAILED status. Please try to restart it.",
  "error": "Unprocessable Entity"
}

**Comment by allburov** [comment]
Hi! Please make sure you're using the latest version, 2023.08.10 - you can get it with /api/version request

**Comment by allburov** [comment]
https://github.com/devlikeapro/whatsapp-http-api/issues/164
https://github.com/devlikeapro/whatsapp-http-api/issues/162

Kindly provide dockef logs if the issue persists after updating to the latest version.
