### ISSUE TITLE
Message not sent although got response from endpoint

### ISSUE THREAD

**Issue by damasusbagus** [allburov/whatsapp-http-api#167]
`{"_data":{"id":{"fromMe":true,"remote":{"server":"c.us","user":"628117007227","_serialized":"628117007227@c.us"},"id":"3EB05863DC8E59CF087B90","_serialized":"true_628117007227@c.us_3EB05863DC8E59CF087B90"},"viewed":false,"body":"[Pesan Otomatis]\r\nTerimakasih telah berlangganan VPN dari vpnmurahjogja.my.id 🙏\r\n\r\nBerikut informasi akun VPN kamu\r\nConnect To : sg08.vpnmurahjogja.my.id\r\nUser : ranahadityoo@gmail.com\r\nPassword : 9912\r\nPaket : sosmed\r\nExpired : sep/12 13:14:50\r\n\r\n📞 WA (Admin) : wa.me/6289670052661","type":"chat","t":1691907295,"from":{"server":"c.us","user":"6289670052661","_serialized":"6289670052661@c.us"},"to":{"server":"c.us","user":"628117007227","_serialized":"628117007227@c.us"},"self":"out","ack":0,"isNewMsg":true,"star":false,"kicNotified":false,"isFromTemplate":false,"pollInvalidated":false,"isSentCagPollCreation":false,"latestEditMsgKey":null,"latestEditSenderTimestampMs":null,"mentionedJidList":[],"groupMentions":[],"isVcardOverMmsDocument":false,"isForwarded":false,"labels":[],"hasReaction":false,"disappearingModeInitiator":"chat","productHeaderImageRejected":false,"lastPlaybackProgress":0,"isDynamicReplyButtonsMsg":false,"isMdHistoryMsg":false,"stickerSentTs":0,"isAvatar":false,"lastUpdateFromServerTs":0,"requiresDirectConnection":null,"invokedBotWid":null},"id":{"fromMe":true,"remote":{"server":"c.us","user":"628117007227","_serialized":"628117007227@c.us"},"id":"3EB05863DC8E59CF087B90","_serialized":"true_628117007227@c.us_3EB05863DC8E59CF087B90"},"ack":0,"hasMedia":false,"body":"[Pesan Otomatis]\r\nTerimakasih telah berlangganan VPN dari vpnmurahjogja.my.id 🙏\r\n\r\nBerikut informasi akun VPN kamu\r\nConnect To : sg08.vpnmurahjogja.my.id\r\nUser : ranahadityoo@gmail.com\r\nPassword : 9912\r\nPaket : sosmed\r\nExpired : sep/12 13:14:50\r\n\r\n📞 WA (Admin) : wa.me/6289670052661","type":"chat","timestamp":1691907295,"from":"6289670052661@c.us","to":"628117007227@c.us","deviceType":"android","isForwarded":false,"forwardingScore":0,"isStatus":false,"isStarred":false,"fromMe":true,"hasQuotedMsg":false,"hasReaction":false,"vCards":[],"mentionedIds":[],"isGif":false}`

i tried send message from API and got response above. but the message not received by receiver
it happened recently, i should re-scan QR again to make it able to send message again :(

**Comment by allburov** [comment]
Hi! Which version do you use? You can check the version by calling GET /api/version
If it's not the latest (2023.08.10) could you try to update docker image (docker pull ...) and **restart** docker containers?

**Comment by damasusbagus** [comment]
`{
  "version": "2023.8.10",
  "tier": "CORE",
  "browser": "/usr/bin/chromium"
}`
its latest already
i did update the docker container with latest, but after update i still experience this issue
ill do re-test again
