### ISSUE TITLE
NOWEB - get all contacts

### ISSUE THREAD

**Issue by sg957** [allburov/whatsapp-http-api#169]
Baileys' noweb engine supports the option of receiving all contacts registered to WhatsApp
Documentation of this can be found here
https://github.com/WhiskeySockets/Baileys/issues/296
I need this option
I would appreciate it if you could add it to your engine

**Comment by allburov** [comment]
The right place to put those - `GET /api/contacts` and `GET /api/contacts/all`

**Comment by devlikepro** [comment]
**Start a brand new session**  - meaning call `POST /api/sessions/logout` before and `POST /api/sessions/start` with payload
```json
{
  "name": "default",
  "config": {
    "noweb": {
      "enabled": {
        "store": true,
        "fullSync": false
      }
    }
  }
}

```

After that you'll have access those endpoints on **NOWEB** engine
-  [GET /api/contacts/all](https://waha.devlike.pro/docs/how-to/contacts/#get-all-contacts)
-  [GET /api/{session}/chats](https://waha.devlike.pro/docs/how-to/chats/#get-all-chats)
-  [GET /api/{session}/chats/{chatId}/messages](https://waha.devlike.pro/docs/how-to/chats/#get-messages-from-chat)

----

https://waha.devlike.pro/docs/overview/changelog/#20246

You asked it, we did it - **contacts, chats, and messages** endpoints are now available in **NOWEB** engine!
Please make sure to [Enable NOWEB Store](https://waha.devlike.pro/docs/engines/noweb/#store) before using these endpoints.
- Build: `2024.6.3`
- Engine: **NOWEB**


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
