### ISSUE TITLE
Gets couldn't link device try again later while scanning QR

### ISSUE THREAD

**Issue by khushboo-scogo** [allburov/whatsapp-http-api#170]
@allburov  If I call the screenshot api and do not scan the qr for the first time. Now, session status is scan_qr_code. If I  hit the screenshot api again and try to scan with this new QR, it shows couldn't link device try again later.
![image](https://github.com/devlikeapro/whatsapp-http-api/assets/140512413/2febac8f-07ae-4a31-97c1-1819e5e7d26d)

Sometimes it does get the QR scanned successfully and sometimes it didn't. This tends to increase inconsistency while using this. Can you help me  with the cause, like why this is happening and also with a guided solution to this issue please.

Thank you in advance

**Comment by allburov** [comment]
Hi! If you're using WEBJS engine (it's default engine) and you see the original screenshot from WhatsApp Web and scan QR from that - I think there's nothing from our side that we could do :( 

You can try to use "Link with phone number instead" - the code doesn't expire so fast as QR does 
https://waha.devlike.pro/docs/how-to/sessions/#get-pairing-code

https://github.com/devlikeapro/whatsapp-http-api/issues/154#issuecomment-1676357464

**Comment by allburov** [comment]
So the flow would be:
1. Start a session
2. `POST /api/{session}/auth/request-code` with your phone number
3. Input the code on your phone with "Link with phone number instead"
4. Profit
