### ISSUE TITLE
[WEBJS] [PLUS] Getting error while starting a new session

### ISSUE THREAD

**Issue by mehmetcoskun** [allburov/whatsapp-http-api#171]
Response of screenshot endpoint
`{
  "statusCode": 422,
  "message": "The session under FAILED status. Please try to restart it.",
  "error": "Unprocessable Entity"
}
`

console log
`[Nest] 34  - 08/14/2023, 3:19:29 PM   ERROR [WhatsappSession - default] Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'CallCollection')
    at __puppeteer_evaluation_script__:9:66`

**Comment by allburov** [comment]
Hi! Please make sure you're using the latest version
https://github.com/devlikeapro/whatsapp-http-api/issues/162#issuecomment-1672542528
