### ISSUE TITLE
Adding a second session fails on a plus version

### ISSUE THREAD

**Issue by maciejbrylewicz** [allburov/whatsapp-http-api#175]
Hello, when I try to create a second session on the exisiting WAHA docker I get:

[
  {
    "name": "default",
    "status": "WORKING"
  },
  {
    "name": "homeaway3",
    "status": "FAILED"
  }
]

My first session is ok, but the second one comes to the stage FAILED whenever I scan QR code. Could you please help me debug it?

Maciej

**Comment by allburov** [comment]
Hi! Which version do you use? 
Is there anything in dockef logs?
You can get loga with the command
docker logs -f whatsapp-http-api

**Comment by allburov** [comment]
You can find version by calling GET /api/version endpoint

**Comment by allburov** [comment]
If it's not 2023.08.16 - please update the image, restart the docker container and try again
