### ISSUE TITLE
sendTextButton is not working

### ISSUE THREAD

**Issue by JuliaCristine** [allburov/whatsapp-http-api#176]
I tried to send buttons but isnt working even if it was sent by swegger 
I'm using free version

<img width="1428" alt="image" src="https://github.com/devlikeapro/whatsapp-http-api/assets/17750415/ad38eb1c-9a01-4190-9f7f-6b908d55b2a9">

<img width="1428" alt="image" src="https://github.com/devlikeapro/whatsapp-http-api/assets/17750415/66b78335-fcbd-4f2a-85c6-734d87863487">

**Comment by allburov** [comment]
Hi! Sorry, it's not going to work, I'll remove API endpoints.
We're working on poll buttons instead https://github.com/devlikeapro/whatsapp-http-api/issues/131 (will be available in NOWEB engine only for now tho)

https://dev.to/purpshell/buttons-and-lists-get-deprecated-by-many-libraries-54h

**Comment by JuliaCristine** [comment]
Ok, thanks

**Comment by allburov** [comment]
You can use Poll instead of buttons (for direct messages work exactly the same way) https://waha.devlike.pro/docs/how-to/polls/

Available only in NOWEB
