### ISSUE TITLE
NOWEB - make poll.vote work after session restarted

### ISSUE THREAD

**Issue by allburov** [allburov/whatsapp-http-api#188]
The part left from - https://github.com/devlikeapro/whatsapp-http-api/issues/131
We wanna reduce number of possible `poll.vote.failed` events

**Comment by devlikepro** [comment]
Solved when you enable NOWEB store 
https://waha.devlike.pro/docs/engines/noweb/#enable--store

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
