### ISSUE TITLE
Failed when starting using compose

### ISSUE THREAD

**Issue by naufalprojects** [allburov/whatsapp-http-api#19]
If I start from compose, it show like this:
But if start from "run -it", it does not have a problem...

![image](https://user-images.githubusercontent.com/52203960/197342436-cb72d0f5-c455-436d-8ff2-baaf9c385ea8.png)

Edit : the problem is cannot access to WA web. Also when I tried to ping to WhatsApp, it does not respond.

**Comment by allburov** [comment]
Thank you! 
I removed the docker-compose yaml because I haven't test it
Feel free to create a PR with right compose configuration!
