### ISSUE TITLE
Get phone number of current session

### ISSUE THREAD

**Issue by 50l3r** [allburov/whatsapp-http-api#191]
Its there a way to obtain the phone number for a specific session already working?

Maybe in `àpi/sessions`

```
[
  {
    "name": "default",
    "status": "WORKING",
    "config": {
      "proxy": null,
      "webhooks": [
        {
          "url": "https://example.org",
          "events": [
            "message"
          ],
          "hmac": null,
          "retries": null,
          "customHeaders": null
        }
      ]
    }
  }
]
```

**Comment by allburov** [comment]
Added new `GET /api/sessions/{session}/me` endpoint and add `me` field to session data for `GET /api/sessions` response.
```json
{
  "id": "11111111111@c.us",
  "pushName": "string"
}
```
Available in **Plus 2023.9.3** (x86, no arm version yet, let me know if one needs it).
We'll release it in the next week for Core version too!

**Comment by allburov** [comment]
The endpoint and `me` field can return `null` if it's stopped or failed or not authenticated yet

**Comment by 50l3r** [comment]
Great! Much thanks :D
