### ISSUE TITLE
New started session should move from STARTING to SCAN_QR_CODE instead of WORKING

### ISSUE THREAD

**Issue by dv336699** [allburov/whatsapp-http-api#196]
Engine: NOWEB

Version:
```
{
  "version": "2023.8.29",
  "tier": "PLUS",
  "browser": "/usr/bin/chromium"
}
```

Steps to reproduce
1. Start container
2. Start a session
Response returns as STARTING (which is correct)
```
{
  "name": "default",
  "status": "STARTING",
  "config": {
    "proxy": null,
    "webhooks": [
      {
        "url": "",
        "events": [
          "message"
        ],
        "hmac": null,
        "retries": null,
        "customHeaders": null
      }
    ]
  }
}
```

3. Calling /api/sessions returns the session with status `WORKING`

I believe that that instead it should move from `STARTING` to `SCAN_QR_CODE` and only after the QR code is scanned move to `WORKING`.

If you wait some time, it will move from WORKING to SCAN_QR_CODE.

**Comment by dv336699** [comment]
@allburov just a bit more information on this.

I have started the container in a VPS with 4 vCPU and 8GB RAM, however, after moving to a dedicated server, the status moving fro STARTING > SCAN_QR_CODE was much quicker.

So not sure if you still want to work on this?
Feel free to close it if you wish.

Thanks

**Comment by allburov** [comment]
@dv336699 Sorry, didn't have time to look at the issue yet :( 
thank you for the feedback!
