### ISSUE TITLE
how to delete in-active session, as my memory storage is getting full and k8's pod getting evicted.

### ISSUE THREAD

**Issue by khushboo-scogo** [allburov/whatsapp-http-api#197]
hey @allburov , I am using the plus version and running my container on k8's pod. After some hours, the memory gets full and the pod gets evicted. I have already increased the memory for the pod. But it gets full eventually. This makes Apis slow and takes time to get a response. As the pod gets evicted, it exits all sessions. How should I manage this? How can I get in-active or unused sessions and delete them and free up the space. Guide me on this please!

Thanks in advance

**Comment by allburov** [comment]
How much memory size we're talking about? How much sessions do you run?
Is there any graphs may be with memory consumption.

**Comment by allburov** [comment]
If you stop sessions with /stop endpoint it releases memory immediately

**Comment by khushboo-scogo** [comment]
hey @allburov , so this is the memory consumption of my pod just after some sessions. 
![image](https://github.com/devlikeapro/whatsapp-http-api/assets/140512413/dd55ba4a-0964-4462-bf9d-822548fc95a1)
This is the total size of .session/webjs folder.
![image](https://github.com/devlikeapro/whatsapp-http-api/assets/140512413/4106304a-bda3-47c3-9255-a314b2712230)
whats the solution for this?? sessions folder itself is taking all the memory. Eventually pod gets slow and evicts after some duration. Please guide me on this??

**Comment by khushboo-scogo** [comment]
Getting one more issue in core version, after qr event, authenticate event is not getting triggered.
![image](https://github.com/devlikeapro/whatsapp-http-api/assets/140512413/f36ff028-8577-4db4-b299-5b4db31adc89)
I have scanned the qr but getting its status is in scan qr state
![image](https://github.com/devlikeapro/whatsapp-http-api/assets/140512413/6cfbfb12-dd38-4697-bfb2-810f50e861e5)

whats the issue???

**Comment by allburov** [comment]
>I have scanned the qr but getting its status is in scan qr state

The issue about SCAN_QR_CODE, working on that https://github.com/devlikeapro/whatsapp-http-api/issues/199

>whats the solution for this??

Could you explain a bit more your case - how does the session folder affect RAM? It must not if you run it right and map `.sessions` to host's folder

> this is the memory consumption of my pod just after some sessions.

How much exactly sessions do you run? 

>sessions folder itself is taking all the memory.

If I get the screenshot right, it's `670000 bytes ~ 0.67mb`, shouldn't be a problem even if you put it in RAM.

**Comment by allburov** [comment]
Remember that WEBJ engine runs chromium instance under the hood for each session. it uses puppeter to work with that (which also [have memory leak](https://github.com/puppeteer/puppeteer/issues/5893)) 
May it's the issue here.

If you want to run more then few sessions - we'd recommend using [NOWEB engine](https://waha.devlike.pro/docs/how-to/engines/#noweb) - it works via websockets and doesn't run chromium under the hood.

**Comment by allburov** [comment]
>whats the issue???

⚠️
New version `2023.9.7` is out (both core and plus).
If you're experiencing any issues with SCAN_QR state or sending messages doesn't work - please update it, restart containers and try try again!

**Comment by devlikepro** [comment]
Hi! Let us know if you're expereicing issue with latest version, it's been improved a lot sine 2023.9

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
