### ISSUE TITLE
unable to read QR code in the newest version

### ISSUE THREAD

**Issue by maciejbrylewicz** [allburov/whatsapp-http-api#199]
[](url)Hello, when I try to start the session I never get to QR_code_scan state, but obly to START state. I don't get the QR code. It looks like:

![waha](https://github.com/devlikeapro/whatsapp-http-api/assets/106823716/ad4e498a-3783-46b7-a505-6216931b3941)

Then in the logs we ahve:

![Screenshot-20230907001200-592x725](https://github.com/devlikeapro/whatsapp-http-api/assets/106823716/0320ee23-57c5-4744-952c-176398899222)

But the session after pairing from the log file dives into STOPPED state:

![waha1](https://github.com/devlikeapro/whatsapp-http-api/assets/106823716/6b2fa336-cedc-451d-a29f-a0487c3e810b)

Please help with that.

**Comment by ibroid** [comment]
yeah i have same issue here

**Comment by allburov** [comment]
@maciejbrylewicz @ibroid 
the version is `2023.9.3`, right? You can check it by requesting `GET /api/version`

**Comment by maciejbrylewicz** [comment]
Yes. That's correct

**Comment by allburov** [comment]
:warning: 
New version `2023.9.7` is out (both core and plus).
If you're experiencing any issues with SCAN_QR state or sending messages doesn't work - please update it, restart containers and try try again!
