### ISSUE TITLE
Show QR and screenshot on Swagger page

### ISSUE THREAD

**Issue by allburov** [allburov/whatsapp-http-api#2]
Show QR and screenshot on Swagger page in order to avoid using console at all

**Comment by joneslisboa** [comment]
Hello Friend ,

it would be very interesting, put an endpoint in the api to return the qr and code and also the use of individual sessions, someone did something similar but it is incomplete ... unfortunately my knowledge of node, docker and etc. do not allow me to help or do the implementation ... if you can, I'll be very grateful. ..

https://github.com/billbarsch/myzap/

Usage
Start new whatsapp session
http: // localhost: 3333 / start? sessionName = session1

Get QRCode (quickly !!)
http: // localhost: 3333 / qrcode? sessionName = session1 & image = true

png
http: // localhost: 3333 / qrcode? sessionName = session1

json (base64)

**Comment by allburov** [comment]
DONE!

**Comment by sg957** [comment]
Is it active?
Why is there no documentation of this in SWAGGER?

**Comment by allburov** [comment]
@sg957 only QR image is available on /screenshot.
I didn't see the comment above about base64 data when mark it as done, probably :(
If you need to have base64 - create an issue about it please, we'll look at this!

Meanwhile you can parse QR image (or a screenshot) and get base64 data from it
