### ISSUE TITLE
Response code 500 when try to send message 

### ISSUE THREAD

**Issue by ibroid** [allburov/whatsapp-http-api#200]
when i try to access api/sendMessage, it return Server Internal Error 500. with following exception

Error: Evaluation failed: TypeError: Cannot read property 'WidFactory' of undefined\n    at __puppeteer_evaluation_script__:2:42\n    at ExecutionContext._evaluateInternal (/waapi/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async ExecutionContext.evaluate (/waapi/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)\n    at async Client.sendMessage (/waapi/node_modules/whatsapp-web.js/src/Client.js:869:28)\n    at async /waapi/node_modules/@nestjs/core/router/router-execution-context.js:46:28\n    at async /waapi/node_modules/@nestjs/core/router/router-proxy.js:9:17

**Comment by oujbih** [comment]
Same here

**Comment by telematicove** [comment]
same here

**Comment by Abh7791** [comment]
same here

**Comment by Abh7791** [comment]
same here

**Comment by telematicove** [comment]
when I'm trying to send a message, I got

{
  "statusCode": 500,
  "timestamp": "2023-09-07T09:29:32.339Z",
  "exception": {
    "stack": "Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'WidFactory')\n    at __puppeteer_evaluation_script__:2:42\n    at ExecutionContext._evaluateInternal (/app/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ExecutionContext.evaluate (/app/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)\n    at async Client.sendMessage (/app/node_modules/whatsapp-web.js/src/Client.js:869:28)\n    at async /app/node_modules/@nestjs/core/router/router-execution-context.js:46:28\n    at async /app/node_modules/@nestjs/core/router/router-proxy.js:9:17",
    "message": "Evaluation failed: TypeError: Cannot read properties of undefined (reading 'WidFactory')\n    at __puppeteer_evaluation_script__:2:42",
    "name": "Error"
  },
  "request": {
    "path": "/api/sendText?phone=58414622xxxx&text=hola&session=default",
    "method": "GET",
    "body": {},
    "query": {
      "phone": "58414622xxxx",
      "text": "hola",
      "session": "default"
    }
  },
  "version": {
    "version": "2023.9.3",
    "tier": "CORE",
    "browser": "/usr/bin/chromium"
  }
}

**Comment by allburov** [comment]
:warning: 
New version `2023.9.7` is out (both core and plus).
If you're experiencing any issues with SCAN_QR state or sending messages doesn't work - please update it, restart containers and try try again!

**Comment by telematicove** [comment]
Excellent. Worked.! Thanks.
