### ISSUE TITLE
SENDING MESSAGE. ERROR 500 - HELP! :(

### ISSUE THREAD

**Issue by telematicove** [allburov/whatsapp-http-api#201]
Hi, I hace an issue. I got an error when I'm trying to send a message, like thiS:

{
  "statusCode": 500,
  "timestamp": "2023-09-07T09:29:32.339Z",
  "exception": {
    "stack": "Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'WidFactory')\n    at __puppeteer_evaluation_script__:2:42\n    at ExecutionContext._evaluateInternal (/app/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ExecutionContext.evaluate (/app/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)\n    at async Client.sendMessage (/app/node_modules/whatsapp-web.js/src/Client.js:869:28)\n    at async /app/node_modules/@nestjs/core/router/router-execution-context.js:46:28\n    at async /app/node_modules/@nestjs/core/router/router-proxy.js:9:17",
    "message": "Evaluation failed: TypeError: Cannot read properties of undefined (reading 'WidFactory')\n    at __puppeteer_evaluation_script__:2:42",
    "name": "Error"
  },
  "request": {
    "path": "/api/sendText?phone=19285445544&text=hola&session=default",
    "method": "GET",
    "body": {},
    "query": {
      "phone": "19285445544",
      "text": "hola",
      "session": "default"
    }
  },
  "version": {
    "version": "2023.9.3",
    "tier": "CORE",
    "browser": "/usr/bin/chromium"
  }
}

**Comment by allburov** [comment]
We have issue, looking at this.
Subscribe to get notification pls https://github.com/devlikeapro/whatsapp-http-api/issues/200

**Comment by allburov** [comment]
:warning: 
New version `2023.9.7` is out (both core and plus).
If you're experiencing any issues with SCAN_QR state or sending messages doesn't work - please update it, restart containers and try try again!
