### ISSUE TITLE
Is there a way to replace the proxy for a session without deleting?

### ISSUE THREAD

**Issue by dv336699** [allburov/whatsapp-http-api#202]
I have set a proxy for a session and I think that the only way replace it is to delete and recreate the session.

**Comment by allburov** [comment]
Not delete, just stop and start again (no QR scan should be required after that)
Yes, it's the only possible way to do it right now, but we'll look at that!

**Comment by allburov** [comment]
Oh, sorry, you were talking about proxy, I thought about webhooks... 
In that case - it's not possible:( We only can configure session webhooks in the runtime 

Only stop/start cycle (still no QR required)

**Comment by dv336699** [comment]
@allburov thanks, is there a way to update a session proxy? 

Can't see to find anything here
https://waha.devlike.pro/docs/how-to/sessions/

**Comment by allburov** [comment]
Stop and start it again with a new proxy
