### ISSUE TITLE
Change webhook configuration per session (without restart)

### ISSUE THREAD

**Issue by dolevhayut** [allburov/whatsapp-http-api#203]
Add option for changing webhook for a session ( after creation

**Comment by allburov** [comment]
What do you mean by "device" here? Is it a session?

Btw if you stop and start session it shouldn't require scanning QR if you're using Plus version

**Comment by dolevhayut** [comment]
Hi thanks for answering my question, i edited my post

**Comment by devlikepro** [comment]
You can update session config now after you've created a session with
```
PUT /api/sessions/{session}
```
https://waha.devlike.pro/docs/how-to/sessions/#update-session

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
