### ISSUE TITLE
Presence not working "The method is not implemented by the engine"

### ISSUE THREAD

**Issue by faruksengul** [allburov/whatsapp-http-api#208]
There seems to be a problem with all entity related APIs. All endpoints are "Method not implemented by engine". mistake

**Comment by allburov** [comment]
Hi!
Yes, it works only on NOWEB engine.

>Get presence endpoints and webhook is available only in **NOWEB** engine.

https://waha.devlike.pro/docs/how-to/presence/#get-all-chats-presence

Default engine (WEBJS) doesn't support it and no progress on it as I can see https://github.com/pedroslopez/whatsapp-web.js/issues/82

We'll add information about
 engines that support endpoints and webhooks soon, sorry for the confusion!
https://github.com/devlikeapro/whatsapp-http-api/issues/207

**Comment by faruksengul** [comment]
I installed it from scratch using the engine as in the link below. But it still comes up empty.
docker run -it -p 3000:3000/tcp -e "WHATSAPP_DEFAULT_ENGINE=NOWEB" devlikeapro/whatsapp-http-api
I cannot access either the relevant chat or all chat latest statuses, the result is empty.
