### ISSUE TITLE
[feature] ability to delete message via api

### ISSUE THREAD

**Issue by ehussain** [allburov/whatsapp-http-api#209]
Hello,

We are looking for API where we can delete the outgoing messages. 

We receive a delete webhook for messages sent by client (any incoming message), however there is no way to delete the message which is sent from us via api.

We can have option to delete by message_id, and signature can look like this.

```
[DELETE] /message
{"id": "false_xxx@xx"} 
```

**Comment by devlikepro** [comment]
Hi! 
You can **edit** and **delete** messages starting **WAHA Plus** `2024.3.11`! :tada: 
Remember to update and restart your containers to use the feature.

-----

### Edit message
You can edit **text** messages or **"caption"** in media messages.

```
PUT /api/{session}/chats/{chatId}/messages/{messageId}
```
👉 Remember to escape `@` in `chatId` and `messageId` with `%40`.

So if you want to edit `true_123@c.us_AAA` message in `123@c.us` chat you need to send request to:
```
PUT /api/{session}/chats/123%40c.us/messages/true_123%40c.us_AAA
```

**Payload:**
```json
{
  "text": "Hello, world!"
}
```

### Delete message
You can delete messages from the chat.

```
DELETE /api/{session}/chats/{chatId}/messages/{messageId}
```

👉 Remember to escape `@` in `chatId` and `messageId` with `%40`.

So if you want to delete `true_123@c.us_AAA` message in `123@c.us` chat you need to send request to:
```
DELETE /api/{session}/chats/123%40c.us/messages/true_123%40c.us_AAA
```


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
