### ISSUE TITLE
new feature - message with button

### ISSUE THREAD

**Issue by JLENF** [allburov/whatsapp-http-api#210]
I use your API and it works great. The only feature it doesn't have is the possibility of sending a message with a button for the person to click and respond to a pre-defined message.

In this project they have this functionality, but I would like to use your API.
https://github.com/salman0ansari/whatsapp-api-nodejs

Congratulations on the project.

**Comment by allburov** [comment]
Have you tested buttons in that project? It probably doesn't work.
this is why https://dev.to/purpshell/buttons-and-lists-get-deprecated-by-many-libraries-54h

You can use polls instead (but it's availalbe in NOWEB engine only) https://waha.devlike.pro/docs/how-to/polls/

**Comment by JLENF** [comment]
"Have you tested buttons in that project? It probably doesn't work."

yes, its working.

That's why I opened this issue, so you can check how he did it.

**Comment by allburov** [comment]
Weird, even the engine that the project above use doesn't support it anymore
https://github.com/WhiskeySockets/Baileys/issues/56

So if it's fine for you to use noweb engine (it's an alias for WhiskeySockets/Baileys) - you can use polls instead, it covers the case!

**Comment by JLENF** [comment]
Hi, this feature i need..

![IMG_5762](https://github.com/devlikeapro/whatsapp-http-api/assets/3689234/348c4d1d-1e84-4df1-9869-5ca5fb815ae0)

**Comment by JLENF** [comment]
<img width="1418" alt="Captura de Tela 2023-09-26 às 14 34 51" src="https://github.com/devlikeapro/whatsapp-http-api/assets/3689234/c0f74c55-43d0-4899-bd01-1dde46825d1d">
<img width="1415" alt="Captura de Tela 2023-09-26 às 14 35 08" src="https://github.com/devlikeapro/whatsapp-http-api/assets/3689234/aa7d1cfe-648c-425e-958f-d88885b0b304">

**Comment by JLENF** [comment]
Now I understand that there is a difference between button and reply message.
Can I use reply message with your project?

**Comment by allburov** [comment]
>Can I use reply message with your project?
I don't think so.

Can't it be done with Polls?  https://waha.devlike.pro/docs/how-to/polls/
So you'll have two options
- Confirm
- Decline

![image](https://github.com/devlikeapro/whatsapp-http-api/assets/4376814/3f2606fe-3bb1-4b59-b177-858c064f576e)

**Comment by PedroGDias** [comment]
Hi - any ETA to fix buttons? Is this a WAHA-specific issue or a Meta issue? Thanks
