### ISSUE TITLE
Stream Errored (conflict)

### ISSUE THREAD

**Issue by Zentelechia** [allburov/whatsapp-http-api#213]
Session generates errors

NOWEB plus version
Docker-compose version
- WHATSAPP_RESTART_ALL_SESSIONS=True

[Nest] 30  - 10/03/2023, 1:17:28 PM   ERROR [WhatsappSession - aygTkMWAr6Gms3yhc] connection closed due to 
{"level":30,"time":1696339048884,"pid":30,"hostname":"7a21101ec301","trace":"Error: WebSocket Error (Opening handshake has timed out)\n    at WebSocketClient.<anonymous> (/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:585:17)\n    at WebSocketClient.emit (node:events:514:28)\n    at WebSocketClient.emit (node:domain:489:12)\n    at WebSocket.<anonymous> (/app/node_modules/@adiwajshing/baileys/lib/Socket/Client/web-socket-client.js:46:100)\n    at WebSocket.emit (node:events:514:28)\n    at WebSocket.emit (node:domain:489:12)\n    at emitErrorAndClose (/app/node_modules/ws/lib/websocket.js:1016:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","msg":"connection errored"}
[Nest] 30  - 10/03/2023, 1:17:28 PM   ERROR [WhatsappSession - aygTkMWAr6Gms3yhc] Error: WebSocket Error (Opening handshake has timed out)
[Nest] 30  - 10/03/2023, 1:17:28 PM   ERROR [WhatsappSession - aygTkMWAr6Gms3yhc] , reconnecting 
[Nest] 30  - 10/03/2023, 1:17:28 PM   ERROR [WhatsappSession - aygTkMWAr6Gms3yhc] true
[Nest] 30  - 10/03/2023, 1:17:30 PM   DEBUG [WhatsappSession - aygTkMWAr6Gms3yhc] Connecting store...
[Nest] 30  - 10/03/2023, 1:17:30 PM   DEBUG [WhatsappSession - aygTkMWAr6Gms3yhc] Binding store to socket...
[Nest] 30  - 10/03/2023, 1:17:30 PM   DEBUG [WhatsappSession - aygTkMWAr6Gms3yhc] Start listening connection.update...
[Nest] 30  - 10/03/2023, 1:17:30 PM     LOG [Webhook - aygTkMWAr6Gms3yhc] Configuring webhooks for http://host.docker.internal:2000/webhooks/whatsapp...
[Nest] 30  - 10/03/2023, 1:17:30 PM     LOG [Webhook - aygTkMWAr6Gms3yhc] Event 'message.any' is enabled for url: http://host.docker.internal:2000/webhooks/whatsapp
[Nest] 30  - 10/03/2023, 1:17:30 PM     LOG [Webhook - aygTkMWAr6Gms3yhc] Webhooks were configured for http://host.docker.internal:2000/webhooks/whatsapp.
{"level":30,"time":1696339051051,"pid":30,"hostname":"7a21101ec301","browser":["Mac OS","Chrome","10.15.7"],"helloMsg":{"clientHello":{"ephemeral":"ISJ/PzalCnOdKvDLmAsbUC0+F1Q8JWr+slxIUBZgrC8="}},"msg":"connected to WA"}
{"level":30,"time":1696339051178,"pid":30,"hostname":"7a21101ec301","node":{"username":"358406214516","passive":true,"userAgent":{"platform":"MACOS","appVersion":{"primary":2,"secondary":2329,"tertiary":9},"mcc":"000","mnc":"000","osVersion":"0.1","manufacturer":"","device":"Desktop","osBuildNumber":"0.1","releaseChannel":"RELEASE","localeLanguageIso6391":"en","localeCountryIso31661Alpha2":"US"},"connectType":"WIFI_UNKNOWN","connectReason":"USER_ACTIVATED","device":67},"msg":"logging in..."}
{"level":50,"time":1696339051424,"pid":30,"hostname":"7a21101ec301","node":{"tag":"stream:error","attrs":{},"content":[{"tag":"conflict","attrs":{"type":"replaced"}}]},"msg":"stream errored out"}
{"level":30,"time":1696339051425,"pid":30,"hostname":"7a21101ec301","trace":"Error: Stream Errored (conflict)\n    at WebSocketClient.<anonymous> (/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:501:13)\n    at WebSocketClient.emit (node:events:514:28)\n    at WebSocketClient.emit (node:domain:489:12)\n    at /app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:236:35\n    at Object.decodeFrame (/app/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:136:17)\n    at WebSocketClient.onMessageRecieved (/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:212:15)\n    at WebSocketClient.emit (node:events:514:28)\n    at WebSocketClient.emit (node:domain:489:12)\n    at WebSocket.<anonymous> (/app/node_modules/@adiwajshing/baileys/lib/Socket/Client/web-socket-client.js:46:100)\n    at WebSocket.emit (node:events:514:28)\n    at WebSocket.emit (node:domain:489:12)\n    at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:1192:20)\n    at Receiver.emit (node:events:514:28)\n    at Receiver.emit (node:domain:489:12)\n    at Receiver.dataMessage (/app/node_modules/ws/lib/receiver.js:543:14)\n    at Receiver.getData (/app/node_modules/ws/lib/receiver.js:476:17)","msg":"connection errored"}
[Nest] 30  - 10/03/2023, 1:17:31 PM   ERROR [WhatsappSession - aygTkMWAr6Gms3yhc] connection closed due to 
[Nest] 30  - 10/03/2023, 1:17:31 PM   ERROR [WhatsappSession - aygTkMWAr6Gms3yhc] Error: Stream Errored (conflict)
[Nest] 30  - 10/03/2023, 1:17:31 PM   ERROR [WhatsappSession - aygTkMWAr6Gms3yhc] , reconnecting 
[Nest] 30  - 10/03/2023, 1:17:31 PM   ERROR [WhatsappSession - aygTkMWAr6Gms3yhc] true
{"level":30,"time":1696339051520,"pid":30,"hostname":"7a21101ec301","msg":"29 pre-keys found on server"}
{"level":30,"time":1696339051638,"pid":30,"hostname":"7a21101ec301","msg":"opened connection to WA"}
{"level":30,"time":1696339051678,"pid":30,"hostname":"7a21101ec301","msg":"handled 0 offline messages/notifications"}

**Comment by allburov** [comment]
Does logout from that session help?

**Comment by devlikepro** [comment]
Hi! Could you try to update to the latest version and see if it helps?
We added few fixes for session startup and session restart

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
