### ISSUE TITLE
Whatsapp Logged Out And webhook Phone number 

### ISSUE THREAD

**Issue by alonenettr** [allburov/whatsapp-http-api#215]
When the WhatsApp session is logged out from the phone, there is no notification and it still appears as "working". This problem should be solved. In addition, since the number of the current session can be seen, if the session qr is scanned, the number should be sent from the webhook.

Engine: Webjs

**Comment by allburov** [comment]
> there is no notification and it still appears as "working".

Duplicate for https://github.com/devlikeapro/whatsapp-http-api/issues/137

>if the session qr is scanned, the number should be sent from the webhook.

We'll add it when we add `session.status` webhook, good point!
