### ISSUE TITLE
[enhancement] /chats endpoint is not implemented on NOWEB

### ISSUE THREAD

**Issue by ehussain** [allburov/whatsapp-http-api#217]
Hello,

We are making following api call on NOWEB instance but we are getting this exception.

```
/api/{session}/chats?session={session}
```

```
{"statusCode":422,"message":"The method is not implemented by the engine.","error":"Unprocessable Entity"}
```

Please implement this endpoint on NOWEB engine so we can fetch the active chats in whatsapp.

**Comment by allburov** [comment]
We'll implement remote storage and add that endpoint after https://github.com/devlikeapro/whatsapp-http-api/issues/41

**Comment by devlikepro** [comment]
**Start a brand new session**  - meaning call `POST /api/sessions/logout` before and `POST /api/sessions/start` with payload
```json
{
  "name": "default",
  "config": {
    "noweb": {
      "enabled": {
        "store": true,
        "fullSync": false
      }
    }
  }
}

```

After that you'll have access those endpoints on **NOWEB** engine
-  [GET /api/contacts/all](https://waha.devlike.pro/docs/how-to/contacts/#get-all-contacts)
-  [GET /api/{session}/chats](https://waha.devlike.pro/docs/how-to/chats/#get-all-chats)
-  [GET /api/{session}/chats/{chatId}/messages](https://waha.devlike.pro/docs/how-to/chats/#get-messages-from-chat)

----

https://waha.devlike.pro/docs/overview/changelog/#20246

You asked it, we did it - **contacts, chats, and messages** endpoints are now available in **NOWEB** engine!
Please make sure to [Enable NOWEB Store](https://waha.devlike.pro/docs/engines/noweb/#store) before using these endpoints.
- Build: `2024.6.3`
- Engine: **NOWEB**


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
