### ISSUE TITLE
[bug] Unlinking device does not stop working session but breaks webhooks

### ISSUE THREAD

**Issue by tristan-thar** [allburov/whatsapp-http-api#223]
Engine: WEBJS
I am using WHAPI-Plus.

I noticed that when I unlink my WhatsApp account using my phone (under WhatsApp->Settings->Devices), the session status in Whapi does not change to STOPPED, it will still show up as WORKING.

Webhooks will no longer work though.

**Comment by allburov** [comment]
Hi! It's been fixed recently, could you try the latest version `2023.10.15`?
https://github.com/devlikeapro/whatsapp-http-api/issues/137#issuecomment-1763054893

**Comment by allburov** [comment]
The status will be `FAILED`, not STOPPED, btw
