### ISSUE TITLE
new problem status 500

### ISSUE THREAD

**Issue by Abh7791** [allburov/whatsapp-http-api#224]
{
  "statusCode": 500,
  "timestamp": "2023-10-17T12:36:07.128Z",
  "exception": {
    "stack": "Error: Protocol error (Target.activateTarget): Session closed. Most likely the page has been closed.\n    at CDPSession.send (/app/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:218:35)\n    at Page._screenshotTask (/app/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1984:28)\n    at /app/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1981:62",
    "message": "Protocol error (Target.activateTarget): Session closed. Most likely the page has been closed.",
    "name": "Error"
  },
  "request": {
    "path": "/api/screenshot?session=XXXXXX",
    "method": "GET",
    "body": {},
    "query": {
      "session": "XXXXXX"
    }
  },
  "version": {
    "version": "2023.10.15",
    "engine": "WEBJS",
    "tier": "PLUS",
    "browser": "/usr/bin/chromium"
  }
}

**Comment by allburov** [comment]
hi! Doesnt'  stop\logout and start again help?
If not - please try to update to latest `2023.10.18` version and see if it helps! :crossed_fingers:

**Comment by Abh7791** [comment]
It start but it gets crash again
