### ISSUE TITLE
Getting error in /sendImage api noweb engine

### ISSUE THREAD

**Issue by khushboo-scogo** [allburov/whatsapp-http-api#227]
hey @allburov, I am using noweb engine now for my application. In that I am getting this error while sending image /sendImage api.
![image](https://github.com/devlikeapro/whatsapp-http-api/assets/140512413/2563fc2e-727d-4a83-b135-c2a0171e3bcf)
can you please help me to figure out where this error is coming from.
Thanks in advance.

**Comment by khushboo-scogo** [comment]
@allburov Also my pod is getting restarted very often 
getting this error 
`{"Error: Stream Errored (conflict)\n    at WebSocketClient.<anonymous> (/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:501:13)\n    at WebSocketClient.emit (node:events:517:28)\n    at /app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:236:35\n    at Object.decodeFrame (/app/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:136:17)\n    at WebSocketClient.onMessageRecieved (/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:212:15)\n    at WebSocketClient.emit (node:events:517:28)\n    at WebSocket.<anonymous> (/app/node_modules/@adiwajshing/baileys/lib/Socket/Client/web-socket-client.js:46:100)\n    at WebSocket.emit (node:events:517:28)\n    at Receiver.receiverOnMessage (/app/node_modules/@adiwajshing/baileys/node_modules/ws/lib/websocket.js:1192:20)\n    at Receiver.emit (node:events:517:28)","msg":"connection errored"}`

how to fix this please help me out

**Comment by allburov** [comment]
@khushboo-scogo hi! Sorry for the delay.
Could you provide the request you send to `/api/sendImage`?
Just tested it with both base64 and url requests - works fine 
https://waha.devlike.pro/docs/how-to/send-messages/#send-image-imagesversionspluspng

**Comment by allburov** [comment]
May the problem in format or in the file itself, or in the recipient format

**Comment by allburov** [comment]
>my pod is getting restarted very often

Is there any errors in docker logs for that, could you send it here too? https://waha.devlike.pro/docs/how-to/deploy/#viewing-the-logs

**Comment by devlikepro** [comment]
Hi! Try now, it should have been fixed a while ago

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
