### ISSUE TITLE
[feature] Implement Security for group info GET option

### ISSUE THREAD

**Issue by ijro** [allburov/whatsapp-http-api#232]
Hello! 

My suggestion is to create the Get method on the Security for group info endpoint, so we can check whether a group is currently enabled for admins only or not.
In many cases in groups where we enable and disable the option daily, it would be interesting to be able to know if it is enabled at any given time.

```
GET /api/{session}/groups/{groupId}/settings/security/info-admin-only
```

**Comment by allburov** [comment]
@ijro hi!
Does `PUT /api/default/groups/{GROUPID}/settings/security/info-admin-only` work for you? I was trying to test it and looks it doesn't work.

**Comment by allburov** [comment]
Added new `GET /api/default/groups/{GROUPID}/settings/security/info-admin-only` to get the current state of the setting.
We'll release it on 02-04 December!
