### ISSUE TITLE
I'm stuck on the QR code

### ISSUE THREAD

**Issue by alexlitwinski** [allburov/whatsapp-http-api#234]
I'm stuck on the QR code. After restarting my server, waha asked for the QR code again and it doesn't go beyond this step. I've tried everything and I can't solve it. I'm using the Plus version:
version: "2023.8.16"
tier: "PLUS"
browser: "/usr/bin/chromium"

Can someone help me?

**Comment by allburov** [comment]
@alexlitwinski hi! 
Could you update the image and try again? We had a few issues about stuck on QR already which have been resolved in the latest version

**Comment by allburov** [comment]
Let us know if it didn't help!
