### ISSUE TITLE
Presence

### ISSUE THREAD

**Issue by diegoheliodasilva** [allburov/whatsapp-http-api#236]
Does the presence method only work with numbers that have my client's bot number in their contacts?

**Comment by allburov** [comment]
Hi! Correct, it's the way when WhatsApp sends that data - https://faq.whatsapp.com/419827870318306

> There are a few reasons why you might not be able to see someone's last seen or online:
> - They might have set their privacy settings to hide this information.
> - You might have set your privacy settings to not share your last seen. If you don't share your last seen, you can't see other contacts' last seen.
> - You might have been blocked.
> - You might not have chatted with them before.
> - **They might not have you saved as a contact.**
>  - You might not have them saved as a contact. 

I don't think the last one is required for presence in NOWEB tho, as long as you subscribed to presence.
