### ISSUE TITLE
QR API is not returning Json Response

### ISSUE THREAD

**Issue by hajanaone** [allburov/whatsapp-http-api#237]
Hi
I am running QR API in my PHP Project. 
Its not giving me image url for QR Code, 
Kindly help me how it will return an Image of QR Code. 

I am Just getting response some thing like this. 

�PNG


IHDR�p�yIDATx�~�CIDAT��A��ʒ�@R��_��e�
T�������ֺ�a��.yXk�K�Z뒇�ֺ�a��.yXk�K�Z뒇�ֺ�a��.yXk�K�Z뒇�ֺ�a��.yXk�K�Z�>R��*�P�*�P9��T��I半ߤ�EŤ2U��2U���Q��Iŉ�IŤ�7U|��Z�<���%k�u��Uܤ�/S9Q�*&��bR�*NT~S�IŤ2U�TL*oT���T��*nR��a��.yXk�K�Z�~��o�L'*SŤrR1���2UL*S���T1���2U|��Fŉ�T1UL*'*''*�I半����Z�<���%k�u��cT~��IŤ2UL*SŤ2U��L��o����TL*oT��L��T1�L*oTL*�K�Z뒇�ֺ�a��.��L�o�L*S�I�I�M�ʉ���IŤr�2UL*Sŉ���*S�����ֺ�a��.yXk�K~�e��7*&��bR�Be��T���7*�P�T��IeR�*�P�*&������bR�*n���<���%k�u��Zk]��e*���bR�*&��bR�*&��bR�*&��bR�*&��bR9Q�*N*&��bR9Q�*���T���Ie�8Q��=���%k�u��Zk]��G�������Ie��T��Ie�8��T��Ie��Tި��bR�*nR�*N*&�7*&��bRy������ֺ�a��.yXk�K~�He��Tn��*NTN*&�/*N*NT����7�ܤr�2U��L�ʉ�TqR1��TL*''*7U����ֺ�a��.yXk�K�.R���De�8Q��*&�7*�Py��D半7TN*&��bR9��M*S�*'��7=���%k�u��Zk]b���IŤ2UL*''*S�*SŤ2UL*Sŉʿ��D半���D�bR9�8Qy��De�8Q��⋇�ֺ�a��.yXk�K~��bR�*&���De��*&�����I����bR�*&�7*&��7*��8Q9��Ie�xCe��*&�����Zk]��Z�<���%��L��IŤ�FŤ�7U���F�*'��Tq�rS�ߤ�E�*oT�K�Z뒇�ֺ�a��.�?�@e�xCe�8Q�*&���I勊7TN*&���I半/TN*&��bR�*�P���
���7Tn��T����Z뒇�ֺ�a��.�?�@半I勊I��
�7*NTN*NTN*NTި�B�bRy�⿤2UL*S�*oT��2U|��Z�<���%k�u����Ie��T�P�*nR�*N*���TN*NT&���De��T&����T��Ie�8�8���bRyC�7=���%k�u��Zk]b���T1��T���TL*''*SŤ2U��L����I�oRy�bR���&���I��D�bR�*&�/*�xXk�K�Z뒇�ֺ���?�2U�M*Sŉ�T��Tq��EŤ2U���T���F�*oT���FŤ2UL*oTL*SŤ2U����Z�<���%k�u��L_�����⍊��⋊���
��T���bR�*&���7*NT�����T1�L*'*SŤ2U|��Z�<���%k�u��L勊I�bR�Tn��*�Py�bR�*�����I勊���M*''_T��L7=���%k�u��Zk]b����bR�*&�����*&���7TN*&��bR�*NTN*�K*'��T��T1�L��T�7=���%k�u��Zk]b���I�*SŤ2UL*_TL*'��T1��Q��Tq�rR�TN*NT��I��
��bR�*�P9��TN*&��⦇�ֺ�a��.yXk�K�>P9��T���TN*&���Ie��Tި��Le��Be��T��I�bRy����bR�*NT����bR�*�xXk�K�Z뒇�ֺ䇿�⦊I半7TN*&�7TN*NTި�T���bR9�8�8��TN*&���I�D�b��T��I�⍊I�7=���%k�u��Zk]b���T1��T��|Q�TN*&���I勊/T��/Tި�T��I半7T���T���Be���a��.yXk�K�Z�>�8��TNT����bR�����*&���De��T�P�*ި8�8��T��I��⋊��bR�*NT����Z뒇�ֺ�a��.�?�@e��TN*NT��/TN*&���D�bR�*NTި8Q�*&�7*�P�*NT���T��I勊I�bR9�8Q9���a��.yXk�K�Z�~YŤr�2UL*oTL�ʤ2UL*S�Tq���T1���LSŤrR1��T1�L'��'���bRy�bR��a��.yXk�K�Z�>��B�D半���Ie�xCe�����7TNTN*&���De��T�P��bR�*NT�P�*����ֺ�a��.yXk�K~�H半Ie�xC半IeR�*��8Q9��T��8�xCe�8Q9Q�*NTn��Be�x��
������Z�<���%k�u��8���De��TN*&��bR�*&���
��bR�*nR�*NTި8Q9�xCeR�M*S�*Sŉ��a��.yXk�K�Z����T��I��
������Ie��Tn�xC勊7TN*nR��*&��bR���
���
��⋇�ֺ�a��.yXk�K�>P�*NT�?��T��I�bR�*&�7*&�YŤ2U���Tܤ�FŤrS�*S�k�u��Zk]��Z��\�2U���TL*SŤ2U���E�*7UL*SŤ2UL*oT|�2UL*7Uܤ2UL*SŤ�F�*'_<���%k�u��Zk]����D�De���*��xCe�8��TNTN*�P�*�P��bR�*NTN*&��bR�B��ozXk�K�Z뒇�ֺ����L_��Tq�rR1��TL*''*_TL*oT|�rR1�L'*S�*'7�L��T��Tq��Zk]��Z�<���%?\�2UL*'��T1�L��T�FŤ2��&���Ie��TnR��bR9��T�P9�8��TN*&�����Ie�xCe���a��.yXk�K�Z�>R�Ie��T��Ie��T����bR�*~SŤ2U��2U��L���ʤ2UL*7U��2UL*S�����Z�<���%k�u���*oT���K*�P9��T�����bRy�bR�*�P�*&�7*&�Iŉ�T1�L7=���%k�u��Zk]��G��T1��Q1�L'*SŤ2U��L'''*SŤ2UL*SŤ�E�M*_����7Tި�TNT����Ie���a��.yXk�K�Z�~��*SŤ2UL��o�L��T�ʉ�T1�L*SŤ2UL*'*'��Tq�2U�Qq�2U��T����a��.yXk�K�Z����Ie��B��De��T������7T��/T��I�
���D�&����&��bRy�bR�*�%k�u��Zk]��Z����oRy�bR�TN*&�7*&���D��De��TNTި8Q9����
�7*��I���T����ֺ�a��.yXk�K�.R�*&������
�/*&���I半Ie�xCe�8Q9�8Q��bR9��TN*&���Ie�8Q�*&��bR�*NT����Z뒇�ֺ�a��.��#��bR9�8QyC�bR�*NT����bR�*�P�*N*NT�P��bR�T��/*&���Ie��TN*&���
��b��Mk�u��Zk]��Z���Q�*''*_T��L'*oTL*S�*��bR�*&���I��De�x�bRyCe�8QyCe�xCe���a��.yXk�K�Z���Tި8Q���De�xCe��Be��Tި�T��7T��8Q�*�P�*&��bR9��TN*NT���7*&�7*�xXk�K�Z뒇�ֺ�L�ߤ2UL*_��T�Qq�2U���Qq�2��T|QqS�IŤ�Fŉ�T1�L'��ozXk�K�Z뒇�ֺ�����T���TL*_TL*oT���TL*'��Tq�2UL*_T���Qq��Fŉ���I�M*Sŉ�T���Zk]��Z�<���%?|��*n��TN*NT&�7*�P9Q�*��I�bR�*NTި�T��7*&��b��TNT����bR9�xC�7=���%k�u��Zk]b��Tn��B�bR�*�P9�xCe��T���T��I半I妊Ie��T��I��De��TN*&��*�xXk�K�Z뒇�ֺ����7*&���D�o��B�bR�*�P�*NT��Ie�8Q�*�P�*&��⿤2UL*_T���Z�<���%k�u���*_T������7*NTn�xC�7U��|Qq��F�*'���bR9���a��.yXk�K�Z�>��M'*SŤ2UL*S�I�M'*SŤrS�*oT��*&���bR9��TN*�Py��7=���%k�u��Zk]��G*S�T1�L�ʉ�T1�L'*Sŉ�T�F�*'*S�oRy���
�7*&���I�De�8��Tި��a��.yXk�K�Z�.��I�D半I�De��T����&����7*�Py�bR�*N*&���7T&���D半/*&��⦇�ֺ�a��.yXk�K~�e*oTܤrRq���YŤr���IŤ2�L��T1��T��L��*S�T1�L_<���%k�u��Zk]�����ߤr�2U�/�xC�����b��Be��*�P�*�ek�u��Zk]��Z���?F�o�8Q9��*N*&����D�⋊IeRy�b��T�����ߤ2UL*SŤrR��Z뒇�ֺ�a��.��U���I�bRy�bR9��TNT����Ie��I半��I��De��T����
�����bRy�����Z�<���%k�u����M*Sŉ�Tq�2�LoT�TL*oT�T1�L�ʤ�7UL*_��Q��Tq��/yXk�K�Z뒇�ֺ��`��.xXk�K�Z뒇�ֺ�a��.yXk�K�Z뒇�ֺ�a��.yXk�K�Z뒇�ֺ�a��.yXk�K�Z뒇�ֺ���3�+��4fIEND�B`�

**Comment by allburov** [comment]
Hi! 
Correct, it's not JSON, it's binary JPEG format. You need to download and render it as is.
If you look at `Content-Type` HTTP header you'll it's not `application/json` but rather `image/jpeg`.

We have an enhancement request  about similar problem - https://github.com/devlikeapro/whatsapp-http-api/issues/177

With that there'll be two flag `base64` and `raw` which you can use to get 
1. `?format=base64` - base64 encoding of the JPEG QR image
2. `?format=raw` - the raw value of the QR, so you can generate your own custom QR code without parsing the existed one.
3. `?format=jpeg` - it's value **by default**, returns the binary image

Thank you for flagging this, we'll prioritize the related task

**Comment by hajanaone** [comment]
Thanks for your reply.
Please provide sample php code to echo qr code.
It is difficult for me.

**Comment by allburov** [comment]
Sorry, I haven't worked with PHP for years... Last project was in 2016, I don't remember anything :) 

You should ask either chatgpt or stackoverflow about that, they'll help faster and better!

**Comment by hajanaone** [comment]
Thank you so much 😊for your reply

**Comment by tecysismx** [comment]
`@hajanaone,` hello bro, catch the body raw and convert it to base64 (in php there is the base64_encode($str) function), once you have converted it print it img src="data:image/png;base64, data, this helped me

**Comment by allburov** [comment]
Hi! In `2023.12.1` release there'll be a way to get QR code in different formats.

https://waha.devlike.pro/docs/how-to/sessions/#get-screenshot

----

#### QR formats
You can get QR in different formats:
1. **binary image** - `GET /api/{session}/auth/qr`
2. **base64 image** - `GET /api/{session}/auth/qr` and set `Accept: application/json` header
3. **raw** - `GET /api/{session}/auth/qr?format=raw`

Here's detailed information about each format:

1. **binary image**, binary image - **default** format, you'll get image in response
```bash
# Get image - binary
GET /api/{session}/auth/qr

# OR
GET /api/{session}/auth/qr?format=image

# OR specify Accept header as well
GET /api/{session}/auth/qr?format=image
Accept: image/png
```

2. **base64 image** - you'll get image in base64 format in response if you set `Accept: application/json` header.
```bash
GET /api/{session}/auth/qr?format=image
Accept: application/json
```

```json
{
  "mimetype": "image/png",
  "data": "base64-encoded-data"
}
```

You can change it in Swagger by clicking on **Media Type** dropdown and selecting **application/json**:

![](https://waha.devlike.pro/images/swagger-media-type.png)

3. **raw** - you'll get raw data in response, you can use it to generate QR code on your side
```bash
GET /api/{session}/auth/qr?format=raw
```

```json
{
  "value": "value-that-you-need-to-use-to-generate-qr-code"
}
```

**Comment by hajanaone** [comment]
Thanks.
It is really appreciated 👍
