### ISSUE TITLE
Feature: WEBJS - star and unstar a message

### ISSUE THREAD

**Issue by normalscene** [allburov/whatsapp-http-api#240]
Hi,

I have been using WAHA plus and so far it works really nice. 

Is it possible to "star" a message because I was not able to find anything related to it in the documentation.

If I have missed to look in a specific place then kindly point me towards it.

**Comment by allburov** [comment]
Hi! It's not available yet, but we'll add it (for WEBJ engine, it's not available in NOWEB yet)
- `isStarred` field to `WAMessage`
- `POST /api/message/star` 
```json
{
  "star": true
}
```

**Comment by normalscene** [comment]
Thank you for such quick response. So when can I start using this feature ?

**Comment by allburov** [comment]
@normalscene I'll provide a version number here when it's ready!

**Comment by normalscene** [comment]
That is great! I will eagerly wait for it. Thank you so much.

**Comment by normalscene** [comment]
Hi. Is there any update ?

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by allburov** [comment]
@normalscene oh, I have two tabs with that issue already in my browser :D Didn't have a change to get to this, but I'll, hopefully soon :crossed_fingers:

**Comment by devlikepro** [comment]
Hi, thank you for your patience and your support to the project! 

Added `PUT /api/star` endpoint in **WAHA Plus** `2024.3.8` version in both [WEBJS and NOWEB engines](https://waha.devlike.pro/docs/how-to/engines/)

-----

### Star and unstar message
Use `PUT /api/star` method to star or unstar a message.

👉 Star API uses **PUT**, not POST request! Please make sure you send right request.

**Star:**
```json
{
  "messageId": "false_71111111111@c.us_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "chatId": "71111111111@c.us",
  "star": true,
  "session": "default"
}
```

**Unstar:**
```json
{
  "messageId": "false_71111111111@c.us_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
  "chatId": "71111111111@c.us",
  "star": false,
  "session": "default"
}
```



[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
