### ISSUE TITLE
[Feature Request] Edit Text Message

### ISSUE THREAD

**Issue by normalscene** [allburov/whatsapp-http-api#241]
**Is your feature request related to a problem? Please describe.** I'm always
frustrated when I am not able to edit a text message.

The problem is simple. Sometimes we don't want to delete the sent message but just edit it,
as now whatsapp allows editing of messages.

**Describe the solution you'd like**

Say I have sent message and it has msgid=1234, i should be able to call api /editMessage(msgid, newtext)
and the already sent message text should change from earlier text to newtext.

**Additional context** Add any other context or screenshots about the feature
request here.

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by normalscene** [comment]
Hi @allburov Hope all is well!

When do u see this feature coming to life ?

**Comment by normalscene** [comment]
Hi. Is there any update ?

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by allburov** [comment]
Hi! Sorry for the delay, was busy with other things... 
The next thing in the queue, hopefully it'll be available soon :crossed_fingers:

**Comment by devlikepro** [comment]
Hi! 
You can **edit** and **delete** messages starting **WAHA Plus** `2024.3.11`! :tada: 
Remember to update and restart your containers to use the feature.

-----

### Edit message
You can edit **text** messages or **"caption"** in media messages.

```
PUT /api/{session}/chats/{chatId}/messages/{messageId}
```
👉 Remember to escape `@` in `chatId` and `messageId` with `%40`.

So if you want to edit `true_123@c.us_AAA` message in `123@c.us` chat you need to send request to:
```
PUT /api/{session}/chats/123%40c.us/messages/true_123%40c.us_AAA
```

**Payload:**
```json
{
  "text": "Hello, world!"
}
```

### Delete message
You can delete messages from the chat.

```
DELETE /api/{session}/chats/{chatId}/messages/{messageId}
```

👉 Remember to escape `@` in `chatId` and `messageId` with `%40`.

So if you want to delete `true_123@c.us_AAA` message in `123@c.us` chat you need to send request to:
```
DELETE /api/{session}/chats/123%40c.us/messages/true_123%40c.us_AAA
```


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by yyhezkel** [comment]
can i edit a message in channel?

**Comment by devlikepro** [comment]
@yyhezkel We haven't tested editing messages on the channel , could you check and tell if it works (and if it doesn't - create a new issue with the error🙏 )

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
