### ISSUE TITLE
My WhatsApp Business number got bannned by whatsapp

### ISSUE THREAD

**Issue by khushboo-scogo** [allburov/whatsapp-http-api#246]
hey @allburov, I want help to unban my WhatsApp business number. I will give a short overview of the last 2–3 weeks. I was sending messages to Whatsapp users through IVR call from 10th Dec. On 15th Dec I ran a script which sent 300 messages with 2 sec of delay and after half an hour more, 300 messages with the same delay. Next day, had sent 300 messages with the same 2 sec of delay. On 20th Dec, my number got banned from WhatsApp.  On the 21st of Dec, I scanned with a new whatsapp business number to continue my service, but in 1 hour, that number also got banned. Have they detected my IP or someone has reported me, don't understand the reason? I want to unban both numbers. Can you please guide me on how to tackle this issue?

**Comment by allburov** [comment]
Hi! 
Here's general tips what you should do to avoid getting banned https://waha.devlike.pro/docs/overview/how-to-avoid-blocking/

It's always dangerous to send messages in bulk - if one has deleted your account from their contact list they can mark your message as SPAM. If few people did it - you get banned from whatsapp.
Also if the content is the same it's easy to detect it's a spam.
Correct, it's easy to track the bot by IP, especially if you're using well know VPS provider IP. Consider using https://waha.devlike.pro/docs/how-to/config/#proxy 

Contact Meta about your numbers and they'll unban it if possible
