### ISSUE TITLE
[Feature Request][NOWEB] - Add sendContactVcard

### ISSUE THREAD

**Issue by mycodemm** [allburov/whatsapp-http-api#256]
GET /api/sendContactVcard	Can we send this through NOWEB? As Whatsapp Web Support To Send Contact.
![WhatsApp Image 2024-01-14 at 8 29 08 PM](https://github.com/devlikeapro/whatsapp-http-api/assets/136724221/e86b05b2-12f3-4d29-955f-76f55063f5b3)

[![patron:ADVANCED](https://img.shields.io/badge/patron-ADVANCED-4cd07d)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by allburov** [comment]
Yep, it's possible, just didn't get such request. Will add it (no ETA yet)

**Comment by devlikepro** [comment]
Hi! Support for `POST /api/sendContactVcard` in **NOWEB** engine has been added in **WAHA Plus** `2024.3.10`!
Please make sure to update your version to use that feature

If anyone is interested in sending contact vcard in **WEBJS** engine (default one) - please create a new issue so we can work on that too :pray: 

-----

### Send contact (vcard)
Use `POST /api/sendContactVcard` to send contact (vcard).

You can use fields this way:
```json
{
  "session": "default",
  "chatId": "79111111@c.us",
  "contacts": [
    {
      "fullName": "John Doe",
      "organization": "Company Name",
      "phoneNumber": "+91 11111 11111",
      "whatsappId": "911111111111"
    }
  ]
}
```

Or provide a vCard file content:
```json
{
  "session": "default",
  "chatId": "79111111@c.us",
  "contacts": [
    {
      "vcard": "BEGIN:VCARD\nVERSION:3.0\nFN:Jane Doe\nORG:Company Name;\nTEL;type=CELL;type=VOICE;waid=911111111111:+91 11111 11111\nEND:VCARD"
    }
  ]
}
```

Or even combine it:
```json
  {
  "chatId": "79111111@c.us",
  "contacts": [
    {
      "vcard": "BEGIN:VCARD\nVERSION:3.0\nFN:Jane Doe\nORG:Company Name;\nTEL;type=CELL;type=VOICE;waid=911111111111:+91 11111 11111\nEND:VCARD"
    },
    {
      "fullName": "John Doe",
      "organization": "Company Name",
      "phoneNumber": "+91 11111 11111",
      "whatsappId": "911111111111"
    }
  ],
  "session": "default"
}
```




[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
