### ISSUE TITLE
[BUG][WEBJS] - I'm not getting anything webhooks

### ISSUE THREAD

**Issue by ForceDev1** [allburov/whatsapp-http-api#257]
In httpbin, the following request is issued:
"{
  "args": {},
  "data": "",
  "files": {},
  "form": {},
  "headers": {
    { "accept": "application/json",
    "Accept-Encoding": "gzip, deflate, br",
    "Accept-Language": "ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7",
    "Content-Length": "0",
    "Host": "httpbin.org",
    "Origin": "https://httpbin.org",
    "Referer": "https://httpbin.org/",
    "Sec-Ch-Ua": "Not_A Brand\";v=\"8\", "Chromium\";v=\"120\", "Google Chrome\";v=\"120\",
    \"Sec-Ch-Ua-Mobile": "?0",
    "Sec-Ch-Ua-Platform": "\"Windows\",
    "Sec-Fetch-Dest": { "empty",
    "Sec-Fetch-Mode": "cors",
    "Sec-Fetch-Site": "same-origin",
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0.0 Safari/537.36",
    "X-Amzn-Trace-Id": "Root=1-65a450df-73d366ac141867fa708b1e8f"
  },
  "json": null,
  "origin": "92.248.168.79",
  { "url": "https://httpbin.org/post"
}"

**Comment by tecysismx** [comment]
check your body have a message, or message.any or session.status in your events node

"webhooks": [
      {
        "url": "url",
        "events": [
          "message",
          "session.status",
          "message.any"
        ],

**Comment by ForceDev1** [comment]
Yes, we have everything. I'm using the plus version

**Comment by allburov** [comment]
Hah, that's weird. Do you get all events like this or may be some? Did you try restart the session? Is there anything in docker logs before that happens, could you send it? https://waha.devlike.pro/docs/how-to/deploy/#viewing-the-logs

**Comment by ForceDev1** [comment]
I can't get any of the events. I have tried restarting sessions, using plus and core versions. I'm going to look at the logs now

**Comment by devlikepro** [comment]
Did it work at all and stopped working or never worked for you?

**Comment by ForceDev1** [comment]
Never worked. Need it for a project, for the function of collecting answers

**Comment by devlikepro** [comment]
Try using https://webhook.site/ to see if it works

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by okki-op01** [comment]
Same here, can not get any webhooks. Use Plus version, find that WEBJS not emit 'message_create' to waha

**Comment by xm-waba** [comment]
Same here. Find that WEBJS not emit `message_create` or any other events. Stopped and start not work for me. Any idea?

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
@xm-waba Hi! 
Are you using the latest `2024.7.8` version? We had some issues before

If yes - could you DM me on discord `devlikepro.` (dot is important) or send a question in the discord group, we'll figure it out!

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by xm-waba** [comment]
> @xm-waba Hi! Are you using the latest `2024.7.8` version? We had some issues before
> 
> If yes - could you DM me on discord `devlikepro.` (dot is important) or send a question in the discord group, we'll figure it out!
> 
> [![patron:PRO](https://camo.githubusercontent.com/53c8c17e54974d30f0938bed9c2aa4e5c7dc7bc776296a6776840124e4086a04/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

@devlikepro cant find you on discord. How can i join the discord group?

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
@xm-waba you can find discord link at the bottom of the page https://portal.devlike.pro/

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
