### ISSUE TITLE
[BUG][WEBJS] - Bans in case of simultaneous mailing from several accounts

### ISSUE THREAD

**Issue by ForceDev1** [allburov/whatsapp-http-api#258]
I use several dozen accounts at a time for mailings. Very strong bans when using 2+ accounts at the same time, with no such bans when using 1 account. Good latency, proxies, randomization.

**Comment by allburov** [comment]
https://waha.devlike.pro/docs/overview/how-to-avoid-blocking/

**Comment by allburov** [comment]
Sorry, we can't help with bans if you send messages first or it's a new account. You need to follow the guide and never send messages first https://waha.devlike.pro/docs/overview/how-to-avoid-blocking/
