### ISSUE TITLE
About WhatsApp Status Check - /api/checkNumberStatus

### ISSUE THREAD

**Issue by sfnemis** [allburov/whatsapp-http-api#26]
Hi Again, 

First of all Thank you for quick response the issues @allburov If i am not misunderstanding /api/checkNumberStatus Check number status it's for the WA Number is Online / Offline status check ? If it's like that, it should return as a true if the wa number is online if not the number status false ? 

![SS-Swagger UI-Google Chrome-19-11 at 17](https://user-images.githubusercontent.com/78266266/202869919-b9475e15-1b96-4941-8436-abba47d5ed94.png)

Thank you, 
SFN

**Comment by allburov** [comment]
@sfnemis hi! No, it's not for online\offline status - it's just an answer "Does the number registered in WhatsApp"?

I added more information to the response like a description text - please pull a new Plus version - `2022.11.20`. 
Few examples of responses:
```json
# Number exists
{
  "status": 200,
  "numberExists": true,
  "id": {
    "server": "c.us",
    "user": "79111111111111",
    "_serialized": "79111111111111@c.us"
  }
}

# Does not exist - 79222222
{
  "status": 404,
  "text": "The number does not exist",
  "numberExists": false,
  "connection": "CONNECTED"
}

# Invalid - like 123
{
  "status": 404,
  "numberExists": false,
  "connection": "CONNECTED"
}
```

-------------

If you're looking for account status like online\offline - probably it's a part of "profile" functionality that we haven't added endpoints for yet. 
Please create an issue about it and we'll look at this!
