### ISSUE TITLE
Appear online[Feature Request]

### ISSUE THREAD

**Issue by evollution** [allburov/whatsapp-http-api#263]
Hello, i have a problem, my account appears online just yeterday but sends messages today, this is very easy to link to robot. how can i appear online?

**Comment by allburov** [comment]
You need to indicate your presense by using https://waha.devlike.pro/docs/how-to/presence/#set-presence (the endpoint work on both WEBJS and NOWEB engines)

Send it before send a response for a message (because 24 hours online account looks like a bot too)
```
POST /api/{session}/presence
{
  "presence": "online"
}
```

**Comment by evollution** [comment]
Thank you, and after i stop typing is better if i set it o offline?
