### ISSUE TITLE
Multiline text messages?

### ISSUE THREAD

**Issue by Vaibhavcste** [allburov/whatsapp-http-api#264]
Hi how do I send multi-line text messages?

**Comment by allburov** [comment]
`\n`
```
{
  "chatId": "111111@c.us",
  "text": "Hi there!\n\nNewLine",
  "session": "default"
}
```

**Comment by mpdafa** [comment]
why i cant
![image](https://github.com/user-attachments/assets/64fdee17-6517-421f-9166-2121c0107ade)

**Comment by devlikepro** [comment]
I see you managed to send? @mpdafa :) 
https://github.com/devlikeapro/waha/issues/600#issuecomment-2425010110

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
