### ISSUE TITLE
No matching manifest for linux/arm64/v8 in the manifest list entries

### ISSUE THREAD

**Issue by barikhan1986** [allburov/whatsapp-http-api#265]
Hi,

I am using Macbook pro m1 Max, i tried to install docker image by the following command:

docker pull devlikeapro/whatsapp-http-api-plus

I got this message:

no matching manifest for linux/arm64/v8 in the manifest list entries

could you help please to fix it?

**Comment by allburov** [comment]
Hi! Try using this one
`devlikeapro/whatsapp-http-api-plus:arm`
https://waha.devlike.pro/docs/how-to/engines/#docker-images
