### ISSUE TITLE
Multiple Sessions / High Consume CPU and RAM

### ISSUE THREAD

**Issue by sfnemis** [allburov/whatsapp-http-api#27]
Hi Again, 

I just realize, if i have started one session and actively using than if i tried to create second or third sessions they are not starting always dropping to error and than i realize one thing more its consuming really high cpu and memory usage as you can see below screenshot attachments. 

![SS-Portainer  local-Google Chrome-20-11 at 15](https://user-images.githubusercontent.com/78266266/202902263-1c0d34c4-bd36-4355-be25-dd35b443cf68.png)

![SS-Swagger UI-Google Chrome-20-11 at 15](https://user-images.githubusercontent.com/78266266/202902295-b86f17eb-539c-4f89-8a28-ea6aaa776458.png)

Also you can check log files which i added here. 

[_WAHA_logs (1).txt](https://github.com/devlikeapro/whatsapp-http-api/files/10049702/_WAHA_logs.1.txt)

Best Regards,
SFN

------- Update; I wouldn't like create for the same issue second part but you can check from here 

When i create first session, there is not problem it's working but when i try to create second session it's not working usually 
![SS-Swagger UI-Google Chrome-20-11 at 16](https://user-images.githubusercontent.com/78266266/202905941-5cc9433c-a78f-45cf-be20-09c54d13ca47.png)

![SS-Swagger UI-Google Chrome-20-11 at 16](https://user-images.githubusercontent.com/78266266/202905950-bacfa5e1-fc4b-4577-afdc-ca2ac663b554.png)

One little question  ❓ If i would like to use for 100 session or more what's your idea for the same docker with multiple session RAM or CPU requirements ? 

Thank you from now, 
SFN

**Comment by allburov** [comment]
I'll look at venom engine and why it doesn't start more than one session!

As for resources - yesterday I've made benchmark for  multiple sessions - https://waha.devlike.pro/docs/help/faq/
- It consumes about **30% CPU and 400MB for the first account** when it LOGGED IN. 
- It consumes a bit more (with webjs engine) when it shows QR code. I think the same happened with venom in your case, but I'll double check it
- For **10 accounts** the resources are **~270% CPU and 1.4GB memory**. Just because of the nature of all web-based engines - they run real Chrome instance to prevent blocking.

**Comment by allburov** [comment]
Dear Santa Claus, I wish all issues look alike @sfnemis's issues - with logs and detail information.

**Comment by Manjit2003** [comment]
Hey @sfnemis, I was also experiencing similar issues with Chromium-based solutions. This resulted in heavy downtimes and multiple failure issues. So I took the task into my own hands and designed my own API in Golang. This one doesn't need chrome or any other browser to function. 
If you want to know more, here is a deployed [demo](https://demo.brightcase.studio/api/docs/index.html). 

As of performance, even running 10+ simultaneous connections on a 2GiB & 2 Core CPU, only 50Mb was used.

![image](https://user-images.githubusercontent.com/51269657/205243417-eea52805-6588-49ca-8251-cbc8b17bacc9.png)

Also as for storing sessions, I am using the Postgres database.

Currently, I don't have any plans to open-source the API. Though I would be happy to host the API on your own server :)

Regards, 
@Manjit2003

**Comment by allburov** [comment]
@Manjit2003 
I removed your comment as off topic. 
If you want to help with CPU and Memory for **THIS** project - please open a PR! It's fine if PR adds go-language code in the project

I've already told @sfnemis about your project before.

**Comment by allburov** [comment]
Hi! Added `NOWEB` engine in the latest release! https://waha.devlike.pro/docs/how-to/engines/#noweb
