### ISSUE TITLE
[BUG][NOWEB] - Every secret code is getting invalid in whatsapp 

### ISSUE THREAD

**Issue by avinashmishratpots** [allburov/whatsapp-http-api#270]
![image](https://github.com/devlikeapro/whatsapp-http-api/assets/112680267/ba4f4b10-d4fa-4261-a02e-c092c3668d97)
Every secret code is getting invalid in whatsapp 

When i tried to get access with the generated code, that code is giving invalid and couldn't identify and establish the connection 

It should send the notification on APP so that directly jump on the code enter screen, same as the web whatsapp.

**Comment by devlikepro** [comment]
Hi! Could you try to use the latest version of WAHA `2024.3.2` (either core or plus) AND the latest android\iOS official WhatsApp client on the phone please?
Just checked it - it works on that configuration for me. 
It doesn't mean tho that it's 100% will work for you, please provide feedback after you tested it!

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
