### ISSUE TITLE
CAN'T DOWNLOAD DOCKER IMAGE BEING PRO

### ISSUE THREAD

**Issue by maciejbrylewicz** [allburov/whatsapp-http-api#273]
![image](https://github.com/devlikeapro/whatsapp-http-api/assets/106823716/95cbd396-ff92-486d-8f59-5ee49f50a95f)

The key is not presented! Please help

**Comment by devlikepro** [comment]
Hi! Thank you for the issue, fixed it, sorry about that.
Could you try again and see if it helps? 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
