### ISSUE TITLE
[Feature Request] Group Security feature - Add the possibility to send messages only from administrators

### ISSUE THREAD

**Issue by simonemori** [allburov/whatsapp-http-api#274]
Hello and thanks for this cool tool!

Is it possible to Add the possibility to send messages only from administrators?

In this way, it is possible to create groups for communications services only, like school things etc...

Now there is the possibility to use `PUT /api/{session}/groups/{groupId}/settings/security/info-admin-only` to set name, picture, etc and it works properly.

Thanks 

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by allburov** [comment]
It looks possible, weird we didn't add it when we added `info-admin-only`

**Comment by devlikepro** [comment]
Hi! It's been added in `2024.3.5` version  - already available in WAHA Plus and we'll release it later in WAHA Core.
[Security - who can send messages](https://waha.devlike.pro/docs/how-to/groups/#security---who-can-send-messages)

----

### Security - who can send messages
Updates the group settings to only allow admins to send messages.

`PUT /api/{session}/groups/{groupId}/settings/security/messages-admin-only`
```json
{
  "adminsOnly": true
}
```
Returns `true` if the setting was properly updated. This can return false if the user does not have the necessary permissions.

Get the group settings to only allow admins to send messages.

`GET /api/{session}/groups/{groupId}/settings/security/messages-admin-only`
```json
{
  "adminsOnly": true
}
```

---

### 👉 Breaking changes
- Add **required body** in `PUT /api/{session}/groups/{groupId}/settings/security/info-admin-only` endpoint.
```json
{
  "adminsOnly": true
}
```


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
