### ISSUE TITLE
[Feature Request] Receive Emoji Reactions to Message

### ISSUE THREAD

**Issue by ehussain** [allburov/whatsapp-http-api#275]
**Is your feature request related to a problem? Please describe.** I'm always
frustrated when [...]

I would like to receive a webhook or an api call when someone in conversation reacts to the message via emoji.

**Describe the solution you'd like**

Receive a webhook for any emoji reaction to any message. 

**Describe alternatives you've considered**

May be API call to extract the emoji reactions. But it not reliable because it involves polling. 

[![patron:ADVANCED](https://img.shields.io/badge/patron-ADVANCED-4cd07d)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Hi!
We've added [message.reaction](https://waha.devlike.pro/docs/how-to/webhooks/#messagereaction)
Please remember to add `message.reaction` in `events` when you start a session
```json
{
  "name": "default",
  "config": {
    "webhooks": [
      {
        "url": "https://httpbin.org/post",
        "events": [
          "message.reaction"
        ]
      }
    ]
  }
}
```
----
Receive events when a message is reacted to by a user (or yourself reacting to a message).
- `payload.reaction.text` - emoji that was used to react to the message. It’ll be an empty string if the reaction was removed.
- `payload.reaction.messageId` - id of the message that was reacted to.

```json
{
    "event": "message.reaction",
    "session": "default",
    "me": {
        "id": "79222222222@c.us",
        "pushName": "WAHA"
    },
    "payload": {
        "id": "false_79111111@c.us_11111111111111111111111111111111",
        "from": "79111111@c.us",
        "fromMe": false,
        "participant": "79111111@c.us",
        "to": "79111111@c.us",
        "timestamp": 1710481111.853,
        "reaction": {
            "text": "🙏",
            "messageId": "true_79111111@c.us_11111111111111111111111111111111"
        }
    },
    "engine": "WEBJS",
    "environment": {
        "version": "2024.3.3",
        "engine": "WEBJS",
        "tier": "PLUS",
        "browser": "/usr/bin/google-chrome-stable"
    }
}
```


👉**NOWEB** engine note - reactions were sent in 'message' and 'message.any' events, not it's available only in 'message.reaction'!

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
