### ISSUE TITLE
[BUG][WEBJS] - Instance moves to 'FAILED' state randomly.

### ISSUE THREAD

**Issue by ehussain** [allburov/whatsapp-http-api#276]
**Describe the bug**

Instance moves randomly into 'FAILED' state.
We have restarted instance multiple times and also did many logouts. It keeps moving to this state randomly.

**Version**

```json
{
  "version": "2024.3.2",
  "engine": "WEBJS",
  "tier": "PLUS",
  "browser": "/usr/bin/chromium"
}
```

**To Reproduce** Steps to reproduce the behavior:

No Reproduction steps. 
However this logs might be helpful in debugging
```

{"log":"\u001b[31m[Nest] 30  - \u001b[39m03/14/2024, 11:39:54 PM \u001b[31m  ERROR\u001b[39m \u001b[38;5;3m[WhatsappSession - 60413] \u001b[39m\u001b[31mError: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'push')\r\n","stream":"stdout","time":"2024-03-14T23:39:54.334903661Z"}
{"log":"    at fillModuleArray (eval at \u003canonymous\u003e (:2:5), \u003canonymous\u003e:6:74)\r\n","stream":"stdout","time":"2024-03-14T23:39:54.334940538Z"}
{"log":"    at moduleRaid (eval at \u003canonymous\u003e (:2:5), \u003canonymous\u003e:15:3)\r\n","stream":"stdout","time":"2024-03-14T23:39:54.334944013Z"}
{"log":"    at __puppeteer_evaluation_script__:4:17\u001b[39m\r\n","stream":"stdout","time":"2024-03-14T23:39:54.334946751Z"}
{"log":"\u001b[2K\u001b[1G\u001b[1myarn run v1.22.19\u001b[22m\r\n","stream":"stdout","time":"2024-03-15T00:24:51.036829744Z"}
{"log":"\u001b[2K\u001b[1G\u001b[2m$ node --unhandled-rejections=none dist/main\u001b[22m\r\n","stream":"stdout","time":"2024-03-15T00:24:51.064656402Z"}
{"log":"WAHA (WhatsApp HTTP API) - Running PLUS version...\r\n","stream":"stdout","time":"2024-03-15T00:24:51.544752585Z"}

{"log":"\u001b[31m[Nest] 30  - \u001b[39m03/15/2024, 12:25:17 AM \u001b[31m  ERROR\u001b[39m \u001b[38;5;3m[WhatsappSession - 60413] \u001b[39m\u001b[31mError: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'push')\r\n","stream":"stdout","time":"2024-03-15T00:25:17.164836399Z"}
{"log":"    at fillModuleArray (eval at \u003canonymous\u003e (:2:5), \u003canonymous\u003e:6:74)\r\n","stream":"stdout","time":"2024-03-15T00:25:17.164868856Z"}
{"log":"    at moduleRaid (eval at \u003canonymous\u003e (:2:5), \u003canonymous\u003e:15:3)\r\n","stream":"stdout","time":"2024-03-15T00:25:17.164872767Z"}
{"log":"    at __puppeteer_evaluation_script__:4:17\u001b[39m\r\n","stream":"stdout","time":"2024-03-15T00:25:17.164875754Z"}
```

**Expected behavior**

It should stay connected for long enough without going to FAILED state.

**Engine** I'm using **WEBJS** engine.

**Requests - Responses**

**Docker Logs**

https://gist.github.com/ehussain/4e1854bad50fa8c9a74ced35a630be0a
https://gist.github.com/ehussain/cefd2cb1ee2d54da8106112103bd6552
https://gist.github.com/ehussain/13573ee07cac3f59b051d42c8c727131
https://gist.github.com/ehussain/1ac2c9631abed56e6c89f6560afbecc6
https://gist.github.com/ehussain/2e87b1077093f0d363829d4171a5d9e4
https://gist.github.com/ehussain/03a8370bbf386081b31142bc390cd302

[![patron:ADVANCED](https://img.shields.io/badge/patron-ADVANCED-4cd07d)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by allburov** [comment]
Hi! Just published `2024.3.4` with the possible fix, could you try and give a feedback?

**Comment by ehussain** [comment]
Issue is still reproducing.

```
{"log":"\u001b[31m[Nest] 30  - \u001b[39m03/17/2024, 11:36:36 PM \u001b[31m  ERROR\u001b[39m \u001b[38;5;3m[WhatsappSession - 60011] \u001b[39m\u001b[31mError: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'default')\r\n","stream":"stdout","time":"2024-03-17T23:36:36.134932503Z"}
{"log":"    at __puppeteer_evaluation_script__:5:95\u001b[39m\r\n","stream":"stdout","time":"2024-03-17T23:36:36.134973966Z"}
{"log":"\u001b[2K\u001b[1G\u001b[1myarn run v1.22.19\u001b[22m\r\n","stream":"stdout","time":"2024-03-17T23:44:24.26275598Z"}
{"log":"\u001b[2K\u001b[1G\u001b[2m$ node --unhandled-rejections=none dist/main\u001b[22m\r\n","stream":"stdout","time":"2024-03-17T23:44:24.30053548Z"}
{"log":"WAHA (WhatsApp HTTP API) - Running PLUS version...\r\n","stream":"stdout","time":"2024-03-17T23:44:24.955704789Z"}

```

[![patron:ADVANCED](https://img.shields.io/badge/patron-ADVANCED-4cd07d)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by ehussain** [comment]
Please reopen this bug.

[![patron:ADVANCED](https://img.shields.io/badge/patron-ADVANCED-4cd07d)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by allburov** [comment]
Could you test it with `2024.3.7`? :pray:

**Comment by Thavia** [comment]
Hello, I'm facing the same issue! Version 2024.4.2. Status failed just after QR CODE is read

**Comment by ehussain** [comment]
Please reopen this issue. Its still happening.

[![patron:ADVANCED](https://img.shields.io/badge/patron-ADVANCED-4cd07d)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by Thavia** [comment]
I've manage to get it working by stopping all sessions and recreating containers;

**Comment by kekekekkek** [comment]
For those who dont know how to fix the problem, just  terminate all docker containers and all WhatsApp sessions, and put the command `docker pull devlikeapro/whatsapp-http-api` again in cmd. Idk, but it worked for me

**Comment by egbertomonteiro** [comment]
Hello, I'm facing the same issue! Version **_2024.5.7_**. Status failed just after QR CODE is read

![image](https://github.com/devlikeapro/whatsapp-http-api/assets/298314/ab72e49a-ec4e-4b19-8441-228a79eec05b)

**Comment by devlikepro** [comment]
@egbertomonteiro try running it locally 
- https://waha.devlike.pro/blog/waha--geonode-proxy-bypassing-errors-on-cloud-or-vps/
- https://waha.devlike.pro/blog/waha--ngrok-running-waha-on-local-network/

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
> Its still happening.

How is it going after we added autorestart in WEBJS? I didn't find changelog, but we did it!

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
