### ISSUE TITLE
Payment failing with Patreon on different cards, any other payment method available?

### ISSUE THREAD

**Issue by abe-elusive-services** [allburov/whatsapp-http-api#277]
Hi, We have tried to pay using 2 different payment methods from 2 different people, so 4 tries in total with totally different personal card details but the payment keeps on failing, I would like to request another payment method, perhaps Ethereum?

**Comment by devlikepro** [comment]
Could you try Boosty? https://boosty.to/wa-http-api

We have automated pipeline with Boosty and Patreon so you'll get your access automatically.
With crypto we don't have integrations yet, but if Boosty doesn't work - send us an email and we'll see what we can do!
admin@devlike.pro

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
> send us an email and we'll see what we can do!

Also please mention me please here if do it :) 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by abe-elusive-services** [comment]
![image](https://github.com/devlikeapro/whatsapp-http-api/assets/162314043/b0ec6a00-9501-4533-92c0-9b4bc1a4f01d)

I just subscribed to your service using Boosty.to, it worked!
