### ISSUE TITLE
WhatsApp Notification 

### ISSUE THREAD

**Issue by sfnemis** [allburov/whatsapp-http-api#28]
Hi,

I am using VENOM core and i just remark when i scan qr, my phone whatsapp notifications becoming silent ? 

Thank you

**Comment by allburov** [comment]
Weird, may be whatsapp send notification only to one device? Like Slack does
Or venom mark the message as seen automatically. I'll check and look at this

**Comment by dv336699** [comment]
@allburov I'm having the same behaviour with NOWEB. It seems that the engine is sending "read messages" when receiving a message.

https://github.com/WhiskeySockets/Baileys#reading-messages

On another library, as soon as they received a message, the library was sending the read command to mark the message as seen which was causing the notifications to not come through on phones with the API.

**Comment by dv336699** [comment]
@allburov sorry to bother you, but is there any chance this can be looked at, please?
thanks

**Comment by allburov** [comment]
In the multi-device version of WhatsApp - if a desktop client is active, WhatsApp doesn't send push notifications to the device. If you would like to receive said notifications - you need to mark a session's presence as "unavailable".
I'm planning to add `POST /api/<session>/presence` endpoint for that and test how it works.

**Comment by allburov** [comment]
Hi! There's a new endpoint in the latest WAHA Plus version `2023.7.12`, we'll add it in the next release in WAHA Core.

To turn on push notifications you need to send `POST /api/<session>/presence` request with the payload
```json
{
  "presence": "offline"
}
```

Keep in mind that push notification is not compatible with "being always online" https://github.com/devlikeapro/whatsapp-http-api/issues/121

---

# Presence

Possible presence statuses that you can set or get for chats:
- `online`
- `offline`
- `typing`
- `recording`
- `paused` resets the chat presence after you were `typing`


## Endpoints

### Set presence
You can set your global or chat-related presence with `POST /api/{session}/presence` endpoint

Start typing to a chat (you can use `POST /startTyping` instead)
```json
{
  "chatId": "111111111@c.us",
  "presence": "typing"
}
```

Clear "typing" state (you can use `POST /stopTyping` instead)
```json
{
  "chatId": "111111111@c.us",
  "presence": "paused"
}
```

Set global "online", all contacts will see it
```json
{
  "presence": "online"
}
```

💡 In the multi-device version of WhatsApp - if a desktop client is active, WhatsApp doesn't send push notifications
to the device.
If you would like to receive said notifications - you need to mark a session's presence as `offline`.

```json
{
  "presence": "offline"
}
```
