### ISSUE TITLE
[Feature Request] Helo How to send message to channel?

### ISSUE THREAD

**Issue by jenilutfifauzi** [allburov/whatsapp-http-api#281]
How to send message to channel?

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by allburov** [comment]
Hi! No way yet, but we're working on that!
https://github.com/devlikeapro/whatsapp-http-api/issues/254
