### ISSUE TITLE
[BUG][WEBJS + NOWEB] - /api/sendVoice doesn't work properly

### ISSUE THREAD

**Issue by allburov** [allburov/whatsapp-http-api#284]
> Error: Evaluation failed: u\n at ExecutionContext._evaluateInterna

**Comment by Khosravangroup** [comment]
Yes Iv got this error too

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by allburov** [comment]
Hi! It looks like there was an issue with file format in example

Tried it with with both **WEBJS** and **NOWEB** engine - works with no issues!
```json
{
  "chatId": "79111@c.us",
  "file": {
    "mimetype": "audio/ogg; codecs=opus",
    "url": "https://opus-codec.org/static/examples/ehren-paper_lights-96.opus"
  },
  "session": "default"
}
```

Another file that I've tried - https://opus-codec.org/static/examples/ehren-paper_lights-96.opus

Make sure you're sending OPUS encoding
