### ISSUE TITLE
[BUG][BOOSTY] - subscription not working

### ISSUE THREAD

**Issue by nataliafurtado** [allburov/whatsapp-http-api#285]
**Describe the bug**
boosty in not acepting supscriptions ! 
**Screenshots**

> If applicable, add screenshots to help explain your problem.

**Additional context**

> Add any other context about the problem here.

![image](https://github.com/devlikeapro/whatsapp-http-api/assets/7144000/b0d5682f-c58a-49b0-968b-15746d20281e)

**Comment by nataliafurtado** [comment]
It get stuck in this page forever!

**Comment by devlikepro** [comment]
@nataliafurtado hi! I see you did manage to subscribe, didn't you? Did you get access to [portal](http://portal.devlike.pro/)?
Sorry, it was some platform or payment related issue.

Let me know if it happens again and we'll find a way to fix that!


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
