### ISSUE TITLE
[BUG][WEBJS] Run with docker compose Bug 

### ISSUE THREAD

**Issue by Khosravangroup** [allburov/whatsapp-http-api#286]
I use Docker Compose and when I run the program, Seasons does not run and is fixed in the starting phase. But when I run the app without Docker Compose, I have no problem.

![2](https://github.com/devlikeapro/whatsapp-http-api/assets/165145449/c3cb926c-5db3-430c-90f4-bc8d68433c59)
![1](https://github.com/devlikeapro/whatsapp-http-api/assets/165145449/c84780c3-0b02-4fab-93b9-0985ef1ce45b)

plses someone help me 

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
It's not a project bug if it runs in docker run command.

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
