### ISSUE TITLE
[BUG][WEBJS] - Status 'FAILED' while starting a session.

### ISSUE THREAD

**Issue by AliAkash404** [allburov/whatsapp-http-api#289]
After yesterday WhatsApp global outage, I am getting problem in starting WEBJS session. After scanning the QR code the session goes under 'FAILED' status.

After scanning the QR code when I try to get the screenshot I got the following response:
{
  "statusCode": 422,
  "message": "The session under FAILED status. Please try to restart it.",
  "error": "Unprocessable Entity"
}

And when I get all the sessions I get this response: (i.e. session with 'FAILED' status)
[
  {
    "name": "default",
    "status": "FAILED",
    "config": {
      "proxy": null,
      "webhooks": [
        {
          "url": "https://httpbin.org/post",
          "events": [
            "message"
          ],
          "hmac": null,
          "retries": null,
          "customHeaders": null
        }
      ]
    },
    "me": null
  }
]

I am getting these issues after yesterdays WhatsApp outage before that every thing was working fine.

-----
:warning: **If you have the same issue - please update the version to `2024.3.7` or later!** :warning: 

[![patron:ADVANCED](https://img.shields.io/badge/patron-ADVANCED-4cd07d)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by allburov** [comment]
Could you contact Meta? May be the problem on their side :rofl: 
just kidding.

What WAHA version do you use? You can check it by `GET /api/version`
Where the account (WhatsApp) is from  (country)?

**Comment by AliAkash404** [comment]
I am using these two versions:

{
  "version": "2023.9.11",
  "tier": "PLUS",
  "browser": "/usr/bin/chromium"
}

{
  "version": "2024.3.2",
  "engine": "WEBJS",
  "tier": "CORE",
  "browser": "/usr/bin/chromium"
}

And in both versions I am getting the same error.
The WhatsApp account is from Pakistan.

**Comment by xMunduSCodEx** [comment]
Same error for me

**Comment by mshehrozsajjad** [comment]
Same error for me with:
{
    "version": "2024.2.4",
    "engine": "WEBJS",
    "tier": "CORE",
    "browser": "/usr/bin/chromium"
}
Error:
{
    "statusCode": 422,
    "message": "The session under FAILED status. Please try to restart it.",
    "error": "Unprocessable Entity"
}

Number from US

**Comment by oizamadpedro** [comment]
me too, version: 2024.3.6

EDIT: i updated the version and now its working

[
    {
        "name": "default",
        "status": "FAILED",
        "config": {
            "webhooks": [
                {
                    "url": "http://172.18.0.3:8000/webhook",
                    "events": [
                        "message"
                    ]
                }
            ]
        },
        "me": null
    }
]

**Comment by AliAkash404** [comment]
After updating to version 2024.4.1 (latest version), issue is solved. Thank you admin.

[![patron:ADVANCED](https://img.shields.io/badge/patron-ADVANCED-4cd07d)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by allburov** [comment]
Yep, sorry, there was important update for WEBJS engine, we notified by Boosty / Patreon
https://boosty.to/wa-http-api/posts/c7e7b494-11c6-4ed4-b642-ac9ced25143b

Please subscribe there to have the latest updates!

**Comment by allburov** [comment]
:warning: If you have the same issue - please update the version to `2024.3.7` or later! :warning:
