### ISSUE TITLE
[BUG][NOWEB] - Issue when using the proxy

### ISSUE THREAD

**Issue by suhasrekhu** [allburov/whatsapp-http-api#290]
**Describe the bug**

I am using the NOWEB engine. Issue is connecting with proxy.  Its getting logged out , after QR scan or Pairing code Authenication.
If I start session without proxy server, its working without any issue. But I require proxy server to be used with NOWEB engine.

**Version**

```json
{
  "version": "2024.4.1",
  "engine": "NOWEB",
  "tier": "PLUS",
  "browser": "/usr/bin/chromium"
}
```

session status is shown below, after the QR logout
```json
{
    "name": "XXXX",
    "status": "FAILED",
    "config": {
      "proxy": {
        "server": "http://XXXXXX",
        "username": "XXXXXX",
        "password": "XXXXXX"
      },
      "webhooks": [
        {
          "url": "https://httpbin.org/post",
          "events": [
            "message",
            "session.status"
          ],
          "hmac": null,
          "retries": null,
          "customHeaders": null
        }
      ],
      "debug": false
    },
    "me": {
      "id": "XXXXXXX@c.us",
      "pushName": "Beth"
    },
    "engine": {
      "engine": "NOWEB"
    }
  },
```

[![patron:ADVANCED](https://img.shields.io/badge/patron-ADVANCED-4cd07d)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
@suhasrekhu after updating to the latest version (2024.4.2 PLUS) it's been fixed, could you confirm? 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
