### ISSUE TITLE
Sync logout or stop session to devices list on phone

### ISSUE THREAD

**Issue by synl0rd** [allburov/whatsapp-http-api#291]
I tried logging out and stopping the session endpoint. It succeeded on the API side, as when I checked the /api/sessions endpoint, the session was no longer there. However, the connected device list on the WhatsApp phone app still showed, and manual logout was necessary. I compared it with the WhatsApp web and desktop versions, where upon logging out, the connected device list on the phone also logged out (synchronized). Does this mean the session stop or logout endpoint is a bug? Because I require this logout synchronization. I am a Waha Plus user.

**Comment by devlikepro** [comment]
Yes, it's a bug. Right now, you have to log out from the device manually. 
https://github.com/devlikeapro/whatsapp-http-api/issues/148

We'll look at this!

> I am a Waha Plus user.

By the way, you can specify your GitHub username at https://portal.devlike.pro/ and you'll get that mark to highlight your support!
:point_down: 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
