### ISSUE TITLE
How do I subscribe to the "ADVANCED" version if I don't see this subscription

### ISSUE THREAD

**Issue by ceo404** [allburov/whatsapp-http-api#293]

**Comment by devlikepro** [comment]
Hi! We've decided to deprecate that tier, now there's only two available - PLUS (product) and PRO (product + source code + support)

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
