### ISSUE TITLE
Whether cryptocurrency can be used for sponsorship

### ISSUE THREAD

**Issue by simsreyninh** [allburov/whatsapp-http-api#294]

**Comment by devlikepro** [comment]
Hi! 
Sure, could you contact us at admin@devlike.pro? 

related issue
https://github.com/devlikeapro/whatsapp-http-api/issues/277

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
