### ISSUE TITLE
Getting error in /Qrcode scan

### ISSUE THREAD

**Issue by linuxserver2016** [allburov/whatsapp-http-api#296]
Hello,

## We are frequently facing Some Technical issues.

- We are pulling the latest Docker container using an active key.
- After downloading, I have to run the docker container after accessing the service via the browser.
- First, I have to start the session. Then Get a QR code for pairing WhatsApp Web or WhatsApp.
- But we are facing a QR Coder error. Also, facing Couldn't Link Devices in WhatsApp and WhatsApp.
- Also Not able to get the Qrcode 

![image](https://github.com/devlikeapro/whatsapp-http-api/assets/17586833/453a09e2-755d-4af6-8098-a28a7058015e)

```
{
  "statusCode": 422,
  "message": "Can get QR code only in SCAN_QR_CODE status. The current status is 'STARTING'",
  "error": "Unprocessable Entity"
}
```

- Need for a complete solution to this issue.

Awaiting for your response,

Thank you

**Comment by allburov** [comment]
Hi! Could you check your version at /api/version to make sure you're using the latest one? 
Is there anything in docker logs after you /start session, may be error or warning?
If there's no - could you try to start a session with `debug: true` flag and see what happens in logs?
https://waha.devlike.pro/docs/how-to/deploy/#viewing-the-logs

**Comment by S1D007** [comment]
i am also not able to login please help
![image](https://github.com/devlikeapro/whatsapp-http-api/assets/94226898/96bfbe11-6d99-4039-bd7e-e1a6fec629ce)
this is happening after login and getting this when i want to get the screenshot.
and in the logs i am getting
![image](https://github.com/devlikeapro/whatsapp-http-api/assets/94226898/4f86af6d-3533-405c-a34b-f2a355660b09)
Please help its urgent!!!

**Comment by S1D007** [comment]
**I tried it for 5-10 times with both paid and free**

**Comment by S1D007** [comment]
@allburov please help?

**Comment by allburov** [comment]
@S1D007 
`2023.12.2` looks too old, try to update, we had important update recently (well, about a month ago)

https://www.patreon.com/posts/waha-plus-webjs-100765474

**Comment by linuxserver2016** [comment]
@allburov 

- Hello, I'm facing the same issue! Latest Version 2024.4.2 & 2024.4.4
- This version also Gets the Same Error.
- How to overcome this issue. We're already paid but do not use it.

![image](https://github.com/devlikeapro/whatsapp-http-api/assets/17586833/632a06d7-4a61-4296-8b70-2625cba83d7c)

![image](https://github.com/devlikeapro/whatsapp-http-api/assets/17586833/b49468ed-5179-4133-afb4-28a16c89f9ef)

**Comment by allburov** [comment]
@linuxserver2016 hi! is it WEBJS (default engine), right? 
Could you check /screenshot - what does it show?

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by linuxserver2016** [comment]
@allburov The Reason for Getting an Unprocessable Entity.Also facing season start issue for below mentioned scenario.


**scenario:1**

- First start the session with the session name for `default`.

![image](https://github.com/devlikeapro/whatsapp-http-api/assets/17586833/351f8726-b9f5-40e8-a42e-d7eabc1c6388)

- We are getting QR code and functionally working properly.

![image](https://github.com/devlikeapro/whatsapp-http-api/assets/17586833/ff545241-b1a6-43f2-acb6-044484c825eb)

**scenario:2**


- Again we start or refresh the same session (default). We are getting an Unprocessable Entity Error.

![image](https://github.com/devlikeapro/whatsapp-http-api/assets/17586833/e537ebef-c205-4e38-b0d7-1a20e8b77730)


**scenario:2**

- Change the Session or different Again functionality working.

![image](https://github.com/devlikeapro/whatsapp-http-api/assets/17586833/ef5dceb7-de61-47c0-a5c9-903d2d3799ca)


- so, once the session starts do not hit the session again.
- but WAHA API Response does not show once the session started to stop status.
- what is the reason for not using one session multiple times?kindly update the status.

- Awaiting for your response

Thankyou.

**Comment by allburov** [comment]
@linuxserver2016 One more thing to try - using chrome based (not chromium) docker image

https://waha.devlike.pro/docs/how-to/engines/#docker-images

This one:
```
devlikeapro/whatsapp-http-api-plus:chrome
```

May be it's some sort of bug in chromium + whatsapp web

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by allburov** [comment]
@linuxserver2016 any news? Have you tried chrome image? 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
@linuxserver2016 did you try the above suggestions and still have the issue?

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
