### ISSUE TITLE
[BUG][WEBJS] - Session doesn't start. Always in FAILED state.

### ISSUE THREAD

**Issue by gr8tushar** [allburov/whatsapp-http-api#297]
**Session doesn't start. It always ends up in FAILED state**

Whenever a new session is requested, the state becomes SCAN_QR_CODE. After receiving the code, when we scan the code, the session doesn't start. It goes to failed state. 
However, the session in the mobile phone gets established.

This is the error in the logs. 

[Nest] 34  - 04/17/2024, 7:44:43 AM   ERROR [WhatsappSession - 8BBE9AAFD225465CB175FEAAC3E3A876] Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'default')
    at __puppeteer_evaluation_script__:5:95

**Version**

```json
 {
  version: '2023.11.1',
  engine: 'WEBJS',
  tier: 'PLUS',
  browser: '/usr/bin/chromium'
}

```

**Comment by allburov** [comment]
Could you try to update to the latest version?
We have an important update for WEBJS a month ago
https://www.patreon.com/posts/waha-plus-webjs-100765474

**Comment by allburov** [comment]
It should show you **2024.4.3**

**Comment by gr8tushar** [comment]
Hi,
I got the latest version, and it is working now. Thanks. 
{
  "version": "2024.4.3",
  "engine": "WEBJS",
  "tier": "PLUS",
  "browser": "/usr/bin/chromium"
}

**Comment by gr8tushar** [comment]
Hi,
I got the latest version, and it is working now. Thanks. 
{
  "version": "2024.4.3",
  "engine": "WEBJS",
  "tier": "PLUS",
  "browser": "/usr/bin/chromium"
}
