### ISSUE TITLE
Add filter by session name to /api/sessions

### ISSUE THREAD

**Issue by allburov** [allburov/whatsapp-http-api#300]
It would be useful to have the ability to filter the result of "/api/session" end point with a single session name.
With this feautures i'm able to know the state of the session.

_Originally posted by @giovannicarella in https://github.com/devlikeapro/whatsapp-http-api/discussions/299_
---
- [x] Add `GET /api/sessions/{name}`
- [x] Mentioned endpoint in documentation
- [x] Add changelog (issue + doc links)
- [x] Split commits - CORE, PLUS
- [x] Bump version
- [x] Release it WAHA PLUS
- [x] Mention it's been fixed

**Comment by devlikepro** [comment]
Hi! Added in `2024.4.4` (WAHA Plus).

Make sure to update the image and restart the container.

----

### Get session
To get information about a specific session - call `GET /api/sessions/{session}`.
```json
{
  "name": "default",
  "status": "WORKING",
  "config": {
    "proxy": null,
    "webhooks": [
      {
        "url": "https://httpbin.org/post",
        "events": [
          "message",
          "session.status"
        ],
        "hmac": null,
        "retries": null,
        "customHeaders": null
      }
    ],
    "debug": false
  },
  "me": {
    "id": "79111111@c.us",
    "pushName": "WAHA"
  },
  "engine": {
    "engine": "NOWEB"
  }
}
```



[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by MadhabaPatra** [comment]
Hi @devlikepro / @allburov 

If the {session} is not available, we should return a 404 error, similar to how it's handled in sessions/{session}/me.

```
data: {
  statusCode: 404,
  message: "We didn't find a session with name '{session}'. Please start it first by using POST /sessions/start request",
  error: 'Not Found'
}
```

This ensures consistency in error handling across endpoints and provides clear guidance to users when a session is not found.

**Comment by devlikepro** [comment]
@MadhabaPatra yep, totally agree!Created a new issue for that, #333

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
