### ISSUE TITLE
[Feature Request] Webhook only for messages received from specific group that only mention me?

### ISSUE THREAD

**Issue by evollution** [allburov/whatsapp-http-api#301]
Hello, how can we setup the webhooks in such a way to send a reques to a specific URL only when i am mentioned but only in specific groups?

**Comment by allburov** [comment]
Hi! You need to listen all `message` event and filter filter messages on your application side.
Because those filter are dynamic and should be handled in more specific way, no way to handle implement "general" filtering

**Comment by allburov** [comment]
https://waha.devlike.pro/docs/how-to/receive-messages/#message
>only in specific groups?

Filter by `to` field

>only when i am mentioned

I'm not sure how `body` looks like, but may be you can either filter it by `body` or by internal `_data` if it contains more information about the who has been mentioned in the message.
