### ISSUE TITLE
[Feature Request]Get Chats with NOWEB

### ISSUE THREAD

**Issue by xMunduSCodEx** [allburov/whatsapp-http-api#303]
Hello any way to fetch chat using NOWEB and Phone Number Linking? as it's really annoying to scan the QR code needs 2 devices. the phone number is good option but i see that doesn't support to fetch the messages any idea?

**Comment by allburov** [comment]
Sorry, could you explain a bit what do you mean? " Phone Number Linking" is it like [by pairing by code](https://waha.devlike.pro/docs/how-to/sessions/#get-pairing-code)? Or emulating the real app, I don't get it :(

**Comment by devlikepro** [comment]
**Start a brand new session**  - meaning call `POST /api/sessions/logout` before and `POST /api/sessions/start` with payload
```json
{
  "name": "default",
  "config": {
    "noweb": {
      "enabled": {
        "store": true,
        "fullSync": false
      }
    }
  }
}

```

After that you'll have access those endpoints on **NOWEB** engine
-  [GET /api/contacts/all](https://waha.devlike.pro/docs/how-to/contacts/#get-all-contacts)
-  [GET /api/{session}/chats](https://waha.devlike.pro/docs/how-to/chats/#get-all-chats)
-  [GET /api/{session}/chats/{chatId}/messages](https://waha.devlike.pro/docs/how-to/chats/#get-messages-from-chat)

----

https://waha.devlike.pro/docs/overview/changelog/#20246

You asked it, we did it - **contacts, chats, and messages** endpoints are now available in **NOWEB** engine!
Please make sure to [Enable NOWEB Store](https://waha.devlike.pro/docs/engines/noweb/#store) before using these endpoints.
- Build: `2024.6.3`
- Engine: **NOWEB**


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
