### ISSUE TITLE
Can't install with docker

### ISSUE THREAD

**Issue by Shinchan7222** [allburov/whatsapp-http-api#306]
I can't run my pc forever please make a way to install this in a hosting server for example shared hosting that allows shell access and stuff🙃

**Comment by allburov** [comment]
Hi! Just order any VPS (VM) with 2CPU and 2 RAM and run it there!
I can suggest digitalocean, pretty stable one

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by allburov** [comment]
>that allows shell access

Ssh access and root is the only thing you need

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by Shinchan7222** [comment]
> > that allows shell access
> 
> Ssh access and root is the only thing you need
> 
> [![patron:PRO](https://camo.githubusercontent.com/53c8c17e54974d30f0938bed9c2aa4e5c7dc7bc776296a6776840124e4086a04/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

Don't have root access
