### ISSUE TITLE
can we add WhatsApp call events in webhook of NOWEB Engine response ? [Feature Request]

### ISSUE THREAD

**Issue by Himanshu1234556** [allburov/whatsapp-http-api#307]
Need Call Events on webhook of NOWEB ENGINE 

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
You can receive events about calls in WhatsApp using webhooks!
https://waha.devlike.pro/docs/how-to/calls/

---

## Features
Here's the list of features that are available by [**🏭 Engines**](https://waha.devlike.pro/docs/how-to/engines/):
|                                                     | WEBJS | NOWEB |
|-----------------------------------------------------|:-----:|:-----:|
| `call.received`                                     |  ✔️   |  ✔️   |
| `call.accepted`                                     |       |  ✔️   |
| `call.rejected`                                     |       |  ✔️   |


```json
{
  "event": "call.received",
  "session": "default",
  "payload": {
    "id": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "from": "22222222222@c.us",
    "timestamp": 1721374000,
    "isVideo": false,
    "isGroup": false
  },
  ...
}
```




[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
