### ISSUE TITLE
how to use/access it on VPS

### ISSUE THREAD

**Issue by kslakhani** [allburov/whatsapp-http-api#309]
Succesfully installed through docker and runs by giving "docker run -it -p 3000:3000/tcp devlikeapro/whatsapp-http-api". or the new updated command.

Problem is how can access it from browser?

I tried it something like "docker run -it -p my.dedicated.ip:33:33/tcp devlikeapro/whatsapp-http-api" the command runs successfully and shows the message ##WhatsApp HTTP API is running on: http://[::1]:3000

But after if I go to http://my-dedicated-ip:33 it says this site cant be reach

**Comment by allburov** [comment]
try 3000 or 80 port

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by allburov** [comment]
```
docker run -it -p my.dedicated.ip:80:3000/tcp devlikeapro/whatsapp-http-api
```

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by kslakhani** [comment]
Error response from daemon: driver failed programming external connectivity on endpoint whatsapp-http-api (794672b162d4b07bfede2f2ea0cf47c9abe753a45089aa2ae6b7ba3850d737e2): Error starting userland proxy: listen tcp4 my.ip:80: bind: address already in use.
ERRO[0000] error waiting for container: context canceled


> ```
> docker run -it -p my.dedicated.ip:80:3000/tcp devlikeapro/whatsapp-http-api
> ```
> 
> [![patron:PRO](https://camo.githubusercontent.com/53c8c17e54974d30f0938bed9c2aa4e5c7dc7bc776296a6776840124e4086a04/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by kslakhani** [comment]
> try 3000 or 80 port
> 
> [![patron:PRO](https://camo.githubusercontent.com/53c8c17e54974d30f0938bed9c2aa4e5c7dc7bc776296a6776840124e4086a04/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

if I give command like "docker run -it --rm -p my.server.ip:255:255/tcp --name whatsapp-http-api devlikeapro/whatsapp-http-api" app runs successfully but then not opening on browser http://my.server.ip:255

**Comment by devlikepro** [comment]
The question is not related to the project, but rather to your specific infrastructure.
If you wish you can get paid consultations - in [WAHA PRO tier](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
