### ISSUE TITLE
we need an endpoint to get messages

### ISSUE THREAD

**Issue by behind24proxies** [allburov/whatsapp-http-api#31]
a GET endpoint for messages (10 messages , or from 10-20 , 20-30 , 30-90 , to optimize the payload).

**Comment by allburov** [comment]
I think it requires adding endpoints to get chats first - like to get list of users and groups. Otherwise there's no way to get "unprocessed" messages (if it's the case here). 
https://github.com/devlikeapro/whatsapp-http-api/issues/34
https://github.com/devlikeapro/whatsapp-http-api/issues/32

After that - it makes sense to add that endpoint too!

**Comment by behind24proxies** [comment]
> I think it requires adding endpoints to get chats first - like to get list of users and groups. Otherwise there's no way to get "unprocessed" messages (if it's the case here). #34 #32
> 
> After that - it makes sense to add that endpoint too!

I don't think so , when we send messages we need a chat id :
[country code without +] + [phone number]@c.us

what if you make an endpoint to get those chats ?

**Comment by allburov** [comment]
Hi there!
Added `GET /messages` endpoint
```bash
curl -X 'GET' \
  'http://localhost:3000/api/messages?chatId=11111111111%40c.us&limit=1000&session=default' \
  -H 'accept: application/json'
```


Right now it's available in PLUS `2022.12.19` , will add it to CORE in January 2023.

**Comment by behind24proxies** [comment]
well, that's some good news 
❤️ 

by the way , regarding the core version
if I pay 19$ I get the updated versions even after I unsubscribe from patreon , right?

**Comment by allburov** [comment]
> I get the updated versions even after I unsubscribe from patreon

Unfortunately not, but the previous downloaded versions will work fine!
