### ISSUE TITLE
[Feature Request] (Web) Get labels and get contacts by label id

### ISSUE THREAD

**Issue by zulfio** [allburov/whatsapp-http-api#318]
Engine: whatsapp-web.js
Additional information: https://docs.wwebjs.dev/Client.html#getLabels

**Is your feature request related to a problem?**
I need this feature to retrieve available labels and get contacts within those labels.

**A clear and concise description of what the problem is.**
We can use this method to get labels. https://docs.wwebjs.dev/Client.html#getLabels
And this method to get contacts by label id. https://docs.wwebjs.dev/Client.html#getChatsByLabelId

**A clear and concise description of what you want to happen.**
NEW ENDPOINT:
Get Labels:
method: GET
URL: /labels

Get Contacts by Label ID:
method: GET
URL: /label/:label_id

**Comment by Boffice** [comment]
+1 Will be perfect if you could add label directly to incoming message JSON.

Knowing the labels from incoming message JSON would help separate personal messages from business ones. It would also allow us to better organize customer messages based on their labels.

Also, it gives ability to create diverse workflows with automations. 


[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by Himanshu1234556** [comment]
I also need it.

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by Himanshu1234556** [comment]
+1

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Related PR https://github.com/devlikeapro/waha-plus/pull/13

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
working on it, will be in `2024.8.1` version!

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by zulfio** [comment]
Yaaay it's here [2024.8.1](https://github.com/devlikeapro/waha/releases/tag/2024.8.1)

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
You can work with [WhatsApp Labels](https://faq.whatsapp.com/3398508707096369/?cms_platform=android) available in **WhatsApp Business** using the API!

## Features

Here's the list of features that are available by [**🏭 Engines**](https://waha.devlike.pro/docs/how-to/engines/):

|                                                                          | WEBJS | NOWEB |
|--------------------------------------------------------------------------|-------|-------|
| **Get list of labels**<br>`GET /api/{session}/labels`                    | ✔️    | ✔️    |
| **Get chats by label id**<br>`GET /api/{session}/labels/{labelId}/chats` | ✔️    | ✔️    |
| **Get labels by chat id**<br>`GET /api/{session}/labels/chats/{chatId}/` | ✔️    | ✔️    |
| **PUT labels to chat**<br>`PUT /api/{session}/labels/chats/{chatId}/`    | ✔️    | ✔️    |
| `labels.upsert`                                                          |       | ✔️    |
| `labels.deleted`                                                         |       | ✔️    |
| `labels.chat.added`                                                      |       | ✔️    |
| `labels.chat.deleted`                                                    |       | ✔️    |

****

_If you see the feature is not available in the above list, please [create a feature request](https://github.com/devlikeapro/waha/issues/new/choose) or **leave "+1" comment** on the existing one._
****


## Endpoints

### Get list of labels

You can get a list of labels for the session using the endpoint:

```bash
GET /api/{session}/labels
```

Response:

```json

[
  {
    "id": "1",
    "name": "New Client",
    "color": 1,
    "colorHex": "#64c4ff"
  },
  ...
]
```

### Get chats by label id

You can get a list of chats by label id using the endpoint:

```bash
GET /api/{session}/labels/{labelId}/chats
```

ℹ️ Response right now depends on
[**🏭 Engine**](https://waha.devlike.pro/docs/how-to/engines/)
you're using,
the same way as
[**💬 Chats**](https://waha.devlike.pro/docs/how-to/chats/#get-all-chats)

### Get labels by chat id

You can get a list of labels by chat id using the endpoint:

```bash
GET /api/{session}/labels/chats/{chatId}/
```

Response:

```json
[
  {
    "id": "1",
    "name": "New Client",
    "color": 1,
    "colorHex": "#64c4ff"
  },
  ...
]
```

### Update labels to chat

```bash
PUT /api/{session}/labels/chats/{chatId}/
```

**Upsert label**:

👉 You need to provide **the full list of labels** you want to set to the chat. All other labels will be removed.

```json
{
  "labels": [
    {
      "id": "1"
    }
  ]
}
```

**Remove labels**:

```json
{
  "labels": []
}

```

## Webhooks

### labels.upsert

```json
{
  "event": "label.upsert",
  "session": "default",
  "payload": {
    "id": "10",
    "name": "Label Name",
    "color": 14,
    "colorHex": "#00a0f2"
  },
  "engine": "NOWEB",
  ...
}

```

### labels.deleted

```json
{
  "event": "label.deleted",
  "session": "default",
  "payload": {
    "id": "10",
    "name": "",
    "color": 14,
    "colorHex": "#00a0f2"
  },
  "engine": "NOWEB",
  ...
}

```

### labels.chat.added

```json
{
  "event": "label.chat.added",
  "session": "default",
  "payload": {
    "labelId": "6",
    "chatId": "11111111111@c.us",
    "label": null <=== right after scanning QR it can be null. 
  },
  "engine": "NOWEB",
  ...
}
```

### labels.chat.deleted

```json
{
  "event": "label.chat.deleted",
  "session": "default",
  "payload": {
    "labelId": "6",
    "chatId": "11111111111@c.us",
    "label": null
  },
  "engine": "NOWEB",
  ...
}
```


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
