### ISSUE TITLE
[Feature Request] [Dashboard] - show environment variables for server

### ISSUE THREAD

**Issue by allburov** [allburov/whatsapp-http-api#319]
No way to know with which environment variables the server (worker) have been started.

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
We'll show it in `2024.9.1`
![image](https://github.com/user-attachments/assets/af846aab-3f95-49d0-a821-fbecb9c02f9e)


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
