### ISSUE TITLE
Get Info User

### ISSUE THREAD

**Issue by SergeKZ** [allburov/whatsapp-http-api#32]
How to get information about a user by number? avatar, online status

**Comment by allburov** [comment]
Right now it's not possible. We'll add the endpoints for that soon!

**Comment by SergeKZ** [comment]
> Right now it's not possible. We'll add the endpoints for that soon!

Big thk!

**Comment by allburov** [comment]
Hi! We've added [contacts endpoints](https://waha.devlike.pro/docs/how-to/contacts/) in WAHA

Right now it supports:
- Get all contacts or a single one
- Get "about" contact (aka status)
- Get contact's profile picture
- Check phone number is registered in WhatsApp (works even if the number is not in your contact list)
- Block and unblock contacts

It's not possible to get online status yet :(

The endpoints are available in WAHA Plus `2023.1` version and we'll add them in Core version in February 2023

**Comment by TANTELY00** [comment]
Est-ce que c’est possible d’ajouter un ou plusieurs contacts WhatsApp à partir de WAHA ?
