### ISSUE TITLE
[BUG][WEBJS] - Unable to send video

### ISSUE THREAD

**Issue by francescodauria** [allburov/whatsapp-http-api#321]
I tried to send video with endpoint /api/sendVideo but it is continuously loading via PostMan. I used the devlikeapro/whatsapp-http-api-plus:chrome image as written in the documentation.

**Version**

```json
{
  "version": "2024.5.3",
  "engine": "WEBJS",
  "tier": "PLUS",
  "browser": "/usr/bin/google-chrome-stable"
}
```

**Docker Logs**

In the Docker logs there are no messages

**Comment by allburov** [comment]
Hi, we're on it!
As a quick workaround - you can send the video as attachment (file) 
https://waha.devlike.pro/docs/how-to/send-messages/#send-file-imagesversionspluspng
IT's not the best solution, but it's something...

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by francescodauria** [comment]
Is there any provision for resolution?

**Comment by devlikepro** [comment]
Fixed in `2024.5.6`!

Try first the example payload from https://waha.devlike.pro/docs/how-to/send-messages/#send-video-imagesversionspluspng

```json
{
  "session": "default",
  "chatId": "11111111111@c.us",
  "caption": "Watch this video!",
  "file": {
    "mimetype": "video/mp4",
    "filename": "video.mp4",
    "url": "https://github.com/devlikeapro/whatsapp-http-api/raw/core/examples/video.mp4"
  }
}
```


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by allburov** [comment]
Added a temporary solution in **WAHA Plus** `2024.5.9`

---
https://waha.devlike.pro/docs/how-to/send-messages/#send-video-imagesversionspluspng

⚠️ **WEBJS** (default) engine notes for sending videos ⚠️
- 💡 If you're experiencing **"forever loading" issue** ([#321](https://github.com/devlikeapro/whatsapp-http-api/issues/321), [#328](https://github.com/devlikeapro/whatsapp-http-api/issues/328)) - set up `WAHA_WEBJS_WEB_VERSION=2.2412.54-videofix` environment variable:

```bash
docker run -it -p 3000:3000/tcp -e WAHA_WEBJS_WEB_VERSION=2.2412.54-videofix devlikeapro/whatsapp-http-api-plus:chrome
```

---

I don't close the issue #328, please use it as the latest new about the sending video issues!



[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by francescodauria** [comment]
I'll try it. 
Thank you.

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
