### ISSUE TITLE
Get contact info for NOWEB 

### ISSUE THREAD

**Issue by Khosravangroup** [allburov/whatsapp-http-api#322]
Hello

please add this features to NOWEB ENGINE 👇🏽
![IMG_6764](https://github.com/devlikeapro/whatsapp-http-api/assets/165145449/861a628b-a60e-48b0-bd4d-fb04bcf563b0)

**Comment by Khosravangroup** [comment]
@allburov please check this issue 

thanks

**Comment by devlikepro** [comment]
**Start a brand new session**  - meaning call `POST /api/sessions/logout` before and `POST /api/sessions/start` with payload
```json
{
  "name": "default",
  "config": {
    "noweb": {
      "enabled": {
        "store": true,
        "fullSync": false
      }
    }
  }
}

```

After that you'll have access those endpoints on **NOWEB** engine
-  [GET /api/contacts/all](https://waha.devlike.pro/docs/how-to/contacts/#get-all-contacts)
-  [GET /api/{session}/chats](https://waha.devlike.pro/docs/how-to/chats/#get-all-chats)
-  [GET /api/{session}/chats/{chatId}/messages](https://waha.devlike.pro/docs/how-to/chats/#get-messages-from-chat)

----

https://waha.devlike.pro/docs/overview/changelog/#20246

You asked it, we did it - **contacts, chats, and messages** endpoints are now available in **NOWEB** engine!
Please make sure to [Enable NOWEB Store](https://waha.devlike.pro/docs/engines/noweb/#store) before using these endpoints.
- Build: `2024.6.3`
- Engine: **NOWEB**


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
For `/about` and `block/unblock` let's create new issues, because it's rare cases in the day to day usage, we'll implement it a bit later

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
