### ISSUE TITLE
[BUG][NOWEB] - Send document with caption doesn't receive the download link

### ISSUE THREAD

**Issue by TuanMinPay** [allburov/whatsapp-http-api#323]
**Describe the bug**

Send document with caption doesn't receive the download link

**Version**

```json
{
  "version": "2024.5.3",
  "engine": "NOWEB",
  "tier": "PLUS",
  "browser": "/usr/bin/chromium"
}
```

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Hi! Fixed in 2024.5.10 version!
https://github.com/devlikeapro/whatsapp-http-api/issues/345

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
