### ISSUE TITLE
Group Message Sent by participants Delete for Everyone 

### ISSUE THREAD

**Issue by Himanshu1234556** [allburov/whatsapp-http-api#324]
I require to delete for everyone the message from group sent by participants.
Existing revoke message api is not working for group.

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
@Himanshu1234556 is it about NOWEB or WEBJS engine? I've tested and it worked with no issue on NOWEB

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Tested it in WEBJS, also working with such long id
```
true_111111111111111111@g.us_AAAAAAAAAAAAAAAAAAA_7111111111111@c.us
```

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Let me know additional context here please, the request you send, the conditions (have you send the message or it's participant and you're group admin)

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
