### ISSUE TITLE
[BUG][NOWEB] -  Session is automatically logout just after login and mostly session are failed to start 

### ISSUE THREAD

**Issue by Himanshu1234556** [allburov/whatsapp-http-api#325]
Please fix this issue ASAP 🙏🙏

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by allburov** [comment]
Hi! Just publised new `2024.5.5` version, could you check this one?
If it doesn't help - please run the session with debug enabled and send here logs :pray: 
https://waha.devlike.pro/docs/how-to/sessions/#enable-debug
```json
{
  "name": "default",
  "config": {
    "debug": true
  }
}
```

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Try to setup proxy for phone numbers (especially for  Indian 🇮🇳 ): 
https://waha.devlike.pro/docs/how-to/proxy/

----

## Overview
If you're experiencing issues scanning QR codes in WhatsApp, especially with **Indian 🇮🇳 phone numbers**,
using a proxy located close to the phone number's location may help resolve the problem.

It affects both **WEBJS** and **NOWEB** engines.

### Symptoms
1. You start a new session in WhatsApp.
2. Scan the QR code.
3. Experience a long loading time.
4. Face login failures or instant logout.
5. Encounter a new QR code or enter a FAILED state immediately.

![image](https://github.com/devlikeapro/whatsapp-http-api/assets/4376814/211f93b2-feb8-472f-914c-501e1b324ca3)

## Configuration
There are two ways to set up proxies:
1. Global Setting (for all sessions per container)
2. Per Session Configuration (you can define a proxy for each session when you start it)

### Global Proxy Configuration
To use a proxy, you can set the following environment variables:

- `WHATSAPP_PROXY_SERVER=localhost:3128`: Set the proxy server in the format `host:port`, without HTTP or HTTPS.
- `WHATSAPP_PROXY_SERVER_USERNAME=username` and `WHATSAPP_PROXY_SERVER_PASSWORD=password`: Configure credentials for the proxy.
- `WHATSAPP_PROXY_SERVER_LIST=host1.example.com:3138,host2.example.com:3138`: Specify a comma-separated list of addresses to use, utilizing a round-robin algorithm for server selection.
- `WHATSAPP_PROXY_SERVER_INDEX_PREFIX=proxy-`: Define a session name prefix to choose the appropriate proxy from the list.


### Session Proxy Configuration
You can configure proxy for a session by setting `config.proxy` fields when you `POST /api/sessions/start`:
- `server` - proxy server address, without `http://` or `https://` prefixes
- `username` and `password` - set this if the proxy requires authentication


**No authentication**
```json
{
  "name": "default",
  "config": {
    "proxy": {
      "server": "localhost:3128"
    }
  }
}
```

**Proxy with authentication**
```json
{
  "name": "default",
  "config": {
    "proxy": {
      "server": "localhost:3128",
      "username": "username",
      "password": "P@ssw0rd"
    }
  }
}
```

The configuration is saved and will be applied if the docker container restarts,
and you set `WHATSAPP_RESTART_ALL_SESSIONS` environment variables.
Read more about it in [Autostart section](#autostart).


## Recommended Proxies

### Proxy6
We recommend using <b><a href="https://proxy6.net/en/?r=628046" target="_blank">Proxy6</a></b>
where you can get a DEDICATED proxy (only you'll use it) for **$1.77 per month**.

Apply the promocode get a **5% discount** on your purchase.
```
9W9oVxx3UX
```

### Geonode
Another option is <b><a href="https://geonode.com/invite/89107" target="_blank">Geonode</a></b>.


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by roo12312** [comment]
> Try to setup proxy for phone numbers (especially for Indian 🇮🇳 ): https://waha.devlike.pro/docs/how-to/proxy/
> 
> ## Overview
> If you're experiencing issues scanning QR codes in WhatsApp, especially with **Indian 🇮🇳 phone numbers**, using a proxy located close to the phone number's location may help resolve the problem.
> 
> It affects both **WEBJS** and **NOWEB** engines.
> 
> ### Symptoms
> 1. You start a new session in WhatsApp.
> 2. Scan the QR code.
> 3. Experience a long loading time.
> 4. Face login failures or instant logout.
> 5. Encounter a new QR code or enter a FAILED state immediately.
> 
> ![image](https://private-user-images.githubusercontent.com/4376814/331778964-211f93b2-feb8-472f-914c-501e1b324ca3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NTAxODksIm5iZiI6MTcxNzk0OTg4OSwicGF0aCI6Ii80Mzc2ODE0LzMzMTc3ODk2NC0yMTFmOTNiMi1mZWI4LTQ3MmYtOTE0Yy01MDFlMWIzMjRjYTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDlUMTYxODA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2IyZDVlY2Y3NDRiMTVkYmEwMDhmZTUyOTYyODhiMDczMjI3NDQzZDcyNjc4NjM4N2E3NjFiNDJjZDI1ZDYzYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GPLIKst7DZIq-kFY5kmiFpA39Vy-ExZX4weXt2zDdUk)
> 
> ## Configuration
> There are two ways to set up proxies:
> 
> 1. Global Setting (for all sessions per container)
> 2. Per Session Configuration (you can define a proxy for each session when you start it)
> 
> ### Global Proxy Configuration
> To use a proxy, you can set the following environment variables:
> 
> * `WHATSAPP_PROXY_SERVER=localhost:3128`: Set the proxy server in the format `host:port`, without HTTP or HTTPS.
> * `WHATSAPP_PROXY_SERVER_USERNAME=username` and `WHATSAPP_PROXY_SERVER_PASSWORD=password`: Configure credentials for the proxy.
> * `WHATSAPP_PROXY_SERVER_LIST=host1.example.com:3138,host2.example.com:3138`: Specify a comma-separated list of addresses to use, utilizing a round-robin algorithm for server selection.
> * `WHATSAPP_PROXY_SERVER_INDEX_PREFIX=proxy-`: Define a session name prefix to choose the appropriate proxy from the list.
> 
> ### Session Proxy Configuration
> You can configure proxy for a session by setting `config.proxy` fields when you `POST /api/sessions/start`:
> 
> * `server` - proxy server address, without `http://` or `https://` prefixes
> * `username` and `password` - set this if the proxy requires authentication
> 
> **No authentication**
> 
> ```json
> {
>   "name": "default",
>   "config": {
>     "proxy": {
>       "server": "localhost:3128"
>     }
>   }
> }
> ```
> 
> **Proxy with authentication**
> 
> ```json
> {
>   "name": "default",
>   "config": {
>     "proxy": {
>       "server": "localhost:3128",
>       "username": "username",
>       "password": "P@ssw0rd"
>     }
>   }
> }
> ```
> 
> The configuration is saved and will be applied if the docker container restarts, and you set `WHATSAPP_RESTART_ALL_SESSIONS` environment variables. Read more about it in [Autostart section](#autostart).
> 
> ## Recommended Proxies
> ### Proxy6
> We recommend using [Proxy6](https://proxy6.net/en/?r=628046) where you can get a DEDICATED proxy (only you'll use it) for **$1.77 per month**.
> 
> Apply the promocode get a **5% discount** on your purchase.
> 
> ```
> 9W9oVxx3UX
> ```
> 
> ### Geonode
> Another option is [Geonode](https://geonode.com/invite/89107).
> 
> [![patron:PRO](https://camo.githubusercontent.com/53c8c17e54974d30f0938bed9c2aa4e5c7dc7bc776296a6776840124e4086a04/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

my vps is in India and still im not able to login

**Comment by devlikepro** [comment]
@rohankm could you try to run it on your local PC/laptop? Some VPS is blocked as well.

If it works, the only way to fix that - setup a your own proxy somewhere in real location (using 4G\5G usually helps as well)

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
