### ISSUE TITLE
send message to groups

### ISSUE THREAD

**Issue by behind24proxies** [allburov/whatsapp-http-api#33]
hi, there is no endpoint to send messages to groups.
and there is no way to get the chat id of groups.

**Comment by allburov** [comment]
Hi!

>hi, there is no endpoint to send messages to groups.
The usual `sendText` works here https://waha.devlike.pro/docs/how-to/send-messages/#send-text-imagesversionscorepng-imagesversionspluspng - set group id in `chatId` field

You need to get chat id of the group first - it's better to do so by joining the group and then [receiving a message](https://waha.devlike.pro/docs/how-to/receive-messages/) - the event that send to the webhook contains chat id that you're searching for

>and there is no way to get the chat id of groups.

It's true, right now there's no way to get list of groups nor list of your contacts. We're working on it tho https://github.com/devlikeapro/whatsapp-http-api/issues/32

**Comment by allburov** [comment]
@behind24proxies Please let us know if it doesn't help!

**Comment by behind24proxies** [comment]
> Hi!
> 
> >hi, there is no endpoint to send messages to groups.
> The usual `sendText` works here https://waha.devlike.pro/docs/how-to/send-messages/#send-text-imagesversionscorepng-imagesversionspluspng - set group id in `chatId` field
> 
> You need to get chat id of the group first - it's better to do so by joining the group and then [receiving a message](https://waha.devlike.pro/docs/how-to/receive-messages/) - the event that send to the webhook contains chat id that you're searching for
> 
> >and there is no way to get the chat id of groups.
> 
> It's true, right now there's no way to get list of groups nor list of your contacts. We're working on it tho https://github.com/devlikeapro/whatsapp-http-api/issues/32

Yes, that works 👍👍
Are you also making a get endpoint to retrieve the last x messages from a convo? (I opened an issue for that a while ago, nobody answered)
