### ISSUE TITLE
[Feature Request] Add profilePicture in /{session}/me API

### ISSUE THREAD

**Issue by MadhabaPatra** [allburov/whatsapp-http-api#334]
Hi @devlikepro,

Right now, we are able to access the id and pushName in the /{session}/me API. 

However, it would be beneficial to also include the profile image of the authenticated user in the API response.

Current
```{
  "id": "11111111111@c.us",
  "pushName": "string"
}
```

Proposed
```{
  "id": "11111111111@c.us",
  "pushName": "string",
  "profilePicture": "string"
}

```

Including the profilePicture in the response would provide a more complete user profile and enhance the functionality of the API.

**Comment by allburov** [comment]
You can get the profile picture by dedicated API after you get /me "id" 
https://waha.devlike.pro/docs/how-to/contacts/#get-contact-profile-picture

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
