### ISSUE TITLE
[Feature Request] - internal event bus improvements (websocket)

### ISSUE THREAD

**Issue by allburov** [allburov/whatsapp-http-api#335]
Prepare internal event bus architecture for those features:
- [ ] Change webhook configuration per session (without restart) #203
- [ ] websocket conneciton
- [ ] socket.io connection

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
t

**Comment by devlikepro** [comment]
Will add first `session.status` event in 2024.6.7

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
```bash
# Listen all sessions and events
websocat ws://localhost:3000/api/ws
# The same as above
websocat ws://localhost:3000/api/ws?session=*&events=*

# Listen certain events
# (!) Only 'session.status' event is supported now
websocat ws://localhost:3000/api/ws?session=*&events=session.status

# Listen certain session
# NOT SUPPORTED YET
# websocat ws://localhost:3000/api/ws?session=default&events=session.status
```


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
