### ISSUE TITLE
[BUG][NOWEB] - Webhook when viewing status not working #329

### ISSUE THREAD

**Issue by MoishyShuvax** [allburov/whatsapp-http-api#340]
No, I'm talking about viewing from another account
The webhook is sent only on the first view, and subsequent views from other accounts are not sent

_Originally posted by @MoishyShuvax in https://github.com/devlikeapro/whatsapp-http-api/issues/329#issuecomment-2122728190_

**Comment by devlikepro** [comment]
Let's work on that in the original issue! 
https://github.com/devlikeapro/whatsapp-http-api/issues/329

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by oteGroupMoishy** [comment]
> Let's work on that in the original issue! #329
> 
> [![patron:PRO](https://camo.githubusercontent.com/53c8c17e54974d30f0938bed9c2aa4e5c7dc7bc776296a6776840124e4086a04/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

I would be happy to receive an answer in the original issue
