### ISSUE TITLE
[Feature Request]  Enable/Disable "Recording Voice Message" Service

### ISSUE THREAD

**Issue by claudioggomees** [allburov/whatsapp-http-api#344]
I am writing to request an improvement to our application to include a service that allows users to activate and deactivate the "Voice Message Recording" feature based on existing services [startTyping and stopStyping]. This functionality is crucial to improving user control and flexibility when sending voice messages.

The main requirements for this improvement are the following:

Implementing this feature will greatly improve the user experience and provide greater flexibility in managing voice communications, as it truly simulates human interaction.

Thank you for considering this request. I look forward to your positive response and will be happy to discuss further details if necessary.

Yours sincerely,

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Hi! Do you mean "recording" status? Try this one
https://waha.devlike.pro/docs/how-to/presence/#set-presence
```
POST /api/{session}/presence
```

```json
{
  "chatId": "111111111@c.us",
  "presence": "recording"
}
```

and PLEASE :pray:  stop using chatgpt, it generates plenty of not important text that you could just translate using the same chatgpt
The rule of thumb would be to formulate the text in your language and just ask it to translate.


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
