### ISSUE TITLE
Run on Mac Silicon processor

### ISSUE THREAD

**Issue by martinmineo** [allburov/whatsapp-http-api#35]
I noticed that when trying to follow the steps on my Macbook pro M1 pro I'm having some issues.

When running 
```
docker run -it --rm -p 127.0.0.1:3000:3000/tcp --name whatsapp-http-api devlikeapro/whatsapp-http-api
``` 
I received a warning 
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```
and when using the API, I got an error. 
```
[Nest] 28  - 12/18/2022, 2:06:38 AM   ERROR [WhatsappSession - default] Error: Failed to launch the browser process!
[1218/020638.479843:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Function not implemented (38)
Assertion failed: p_rcu_reader->depth != 0 (/qemu/include/qemu/rcu.h: rcu_read_unlock: 101)

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
```

After some research, I found that it's because my processor is not compatible with this app.

Then I began again adding some parameters to the commands. 
First, 
```
docker pull --platform linux/amd64 devlikeapro/whatsapp-http-api
```
Then I run 
```
docker run --platform linux/amd64 -it --rm -p 127.0.0.1:3000:3000/tcp --name whatsapp-http-api devlikeapro/whatsapp-http-api
``` 
with any warning or error 💪

But when I tried to POST `api/sessions/start` I got this error (the same error as before)

```
WhatsApp HTTP API is running on: http://[::1]:3000
[Nest] 28  - 12/18/2022, 1:48:28 AM     LOG [SessionManager] 'default' - starting session...
[Nest] 28  - 12/18/2022, 1:48:28 AM     LOG [Webhook - default] Configuring webhooks...
[Nest] 28  - 12/18/2022, 1:48:28 AM     LOG [Webhook - default] Webhooks were configured.
[Nest] 28  - 12/18/2022, 1:48:29 AM   ERROR [WhatsappSession - default] Error: Failed to launch the browser process!
[1218/014829.073020:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Function not implemented (38)
Assertion failed: p_rcu_reader->depth != 0 (/qemu/include/qemu/rcu.h: rcu_read_unlock: 101)
```

I think that the docker image is not ready to work with these kinds of processors. Could you make it work, please?
Thanks!

**Comment by allburov** [comment]
@martinmineo hi! 
I think the bug is related to chromium, but I can not test it and properly debug (don't have Macbook pro M1).
We probably will have to support two version of docker image - like `devlikeapro/whatsapp-http-api:arm`

Please feel free to open pull requests with the issue's fix! 

If anyone else encountered the same issue - please hit thumb up 👍 on the first comment - we'll know how many of people experience the issue.

**Comment by martinmineo** [comment]
@allburov I wish I knew how to fix it!

**Comment by allburov** [comment]
@martinmineo btw, for Mac users the easiest way to work with the project - purchase a VPS with 2CPU and Ubuntu (I tried with 1CPU but it's too slow)
In DigitalOcean it costs about $24 https://www.digitalocean.com/

**Comment by martinmineo** [comment]
Yes, I will do something like that! 
For testing purposes, I used another computer with an Intel processor and it works great! Amazing job!!

**Comment by allburov** [comment]
Hi! 
We've published tags for ARM architecture - `devlikeapro/whatsapp-http-api:arm` and `devlikeapro/whatsapp-http-api-plus:arm`
There's a note [how to install the right docker image](https://waha.devlike.pro/docs/overview/quick-start/#11-download-image-on-arm)

@martinmineo could you try this one on your Mac when you have time please?

**Comment by martinmineo** [comment]
Hi! It seems that there's still something to be fixed
Note: I'm using the PLUS version
```
{
  "statusCode": 500,
  "timestamp": "2023-02-28T11:45:55.359Z",
  "exception": {
    "stack": "Error: Evaluation failed: Error: wid error: invalid wid\n    at new c (https://web.whatsapp.com/app.208e5a49d844a8c35245.js:68:45641)\n    at Object.s [as createWid] (https://web.whatsapp.com/app.208e5a49d844a8c35245.js:68:50862)\n    at __puppeteer_evaluation_script__:2:53\n    at ExecutionContext._evaluateInternal (/app/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ExecutionContext.evaluate (/app/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)\n    at async Client.sendMessage (/app/node_modules/whatsapp-web.js/src/Client.js:686:28)\n    at async /app/node_modules/@nestjs/core/router/router-execution-context.js:46:28\n    at async /app/node_modules/@nestjs/core/router/router-proxy.js:9:17",
    "message": "Evaluation failed: Error: wid error: invalid wid\n    at new c (https://web.whatsapp.com/app.208e5a49d844a8c35245.js:68:45641)\n    at Object.s [as createWid] (https://web.whatsapp.com/app.208e5a49d844a8c35245.js:68:50862)\n    at __puppeteer_evaluation_script__:2:53",
    "name": "Error"
  },
  "request": {
    "path": "/api/sendText",
    "method": "POST",
    "body": {
      "chatId": "XXXXXXXXXXXX.us",
      "text": "Hi there!",
      "session": "my-session"
    },
    "query": {}
  },
  "version": {
    "version": "2023.3.1",
    "tier": "PLUS",
    "browser": "/usr/bin/chromium"
  }
}
```

**Comment by allburov** [comment]
@martinmineo Could you check the chatId that you used there? It looks like it contains + at the start

I've put it in format `123123123@c.us` (where 123123123 is my real number) and it works, but with `+123123123@c.us` it showed the same error, ` invalid wid`

The same happens when you put a random number, like `123@c.us`

**Comment by martinmineo** [comment]
It's not including the "+", this is the body I used (I will change some numbers with "X" to keep privacy)
```
"body": {
      "chatId": "54XXXXXXXXX68.us",
      "text": "Hi there!",
      "session": "54XXXXXXXXXX33"
    },
```

**Comment by martinmineo** [comment]
ooooh I've realized that there's a missing "@c." in the chatId

I will try again

**Comment by martinmineo** [comment]
yes! It's working fine now. Thank you very much for adding this feature :)

**Comment by allburov** [comment]
@martinmineo thank you for testing the feature!

**Comment by alvarocosta01** [comment]
Just a point for anyone coming later: To run via compose, add the parameter `platform: linux/arm64` after the image definition.
