### ISSUE TITLE
[Feature Request] Disable QR printing in logs (by env.variable)

### ISSUE THREAD

**Issue by allburov** [allburov/whatsapp-http-api#351]
[Feature Request] Disable QR printing in logs (by env.variable)
Request from https://github.com/devlikeapro/whatsapp-http-api/issues/347#issuecomment-2132379331

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by egbertomonteiro** [comment]
Waiting a lot!

**Comment by devlikepro** [comment]
Added in `2024.5.13`(both Core and Plus) https://waha.devlike.pro/docs/how-to/config/#sessions

- `WAHA_PRINT_QR=True` - set this variable to `False` to disable printing QR codes to the console. By default, `True`.



[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
