### ISSUE TITLE
[Feature Request] Support to S3 file storage

### ISSUE THREAD

**Issue by pablomorato1** [allburov/whatsapp-http-api#353]
On my application is necessary to store the media sent on a message on S3 right when my Waha client receives the message to because I use SQS to handle the requests and ensure the delivery of all messages on a server downtime.

I'd like to have a plug and play feature that make possible to deliver the media data directly to my S3 bucket, and have the file url for it returned instead of the local_storage file url.

Is there already any way to do it?

**Comment by allburov** [comment]
Not yet, but we'll add it, shouldn't be a problem!


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by arielpts** [comment]
+1

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by HuangDaHui** [comment]
+1

**Comment by mohammadkurdi** [comment]
+1

**Comment by shivkodam** [comment]
+1

**Comment by puntorigen** [comment]
+1

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by meovary150** [comment]
+1

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by melquisedeque-magalhaes** [comment]
+1

**Comment by devlikepro** [comment]
S3 support will be added in `2024.9.1` version :crossed_fingers: 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by marcelomanchester** [comment]
+ 1

**Comment by chardea** [comment]
+1

**Comment by devlikepro** [comment]
https://waha.devlike.pro/docs/how-to/storages/#media---s3

## Media - S3
You can use the S3 storage to store the media files.

Any **S3 Compatible** storage can be used, such as AWS S3, MinIO, DigitalOcean Spaces, etc. For in-house solutions, you can use [**MinIO**](https://min.io/).

### Configuration

- `WAHA_MEDIA_STORAGE=S3` - enable the S3 storage
- `WAHA_S3_REGION=eu-west-1` - the region of the S3 bucket
- `WAHA_S3_BUCKET=waha` - the name of the S3 bucket
- `WAHA_S3_ACCESS_KEY_ID=minioadmin` - the access key of the S3 bucket
- `WAHA_S3_SECRET_ACCESS_KEY=minioadmin` - the secret access key of the S3 bucket
- `WAHA_S3_ENDPOINT=http://127.0.0.1:9000` - the endpoint of the S3 bucket (not required for AWS S3)
- `WAHA_S3_FORCE_PATH_STYLE=True` - force path style for the S3 bucket (not required for AWS S3)
- `WAHA_S3_PROXY_FILES` - proxy media files through WAHA (`False` by default)
  - `WAHA_S3_PROXY_FILES=False` - generate pre-signed URLs for media files and send them to the client in `media.url`
  - `WAHA_S3_PROXY_FILES=True` - WAHA will proxy media files through itself in `media.url`

After you enabled S3 here's example for **message** webhook payload:
```json
{
  "event": "message",
  "session": "default",
  "engine": "WEBJS",
  "payload": {
    "id": "true_11111111111@c.us_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "hasMedia": true,
    "media": {
        "url": "http://localhost:3000/api/files/true_11111111111@c.us_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.jpg",
        "mimetype": "image/jpeg",
        "filename": null,
        "s3": {
            "Bucket": "bucket-name",
            "Key": "/default/true_11111111111@c.us_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.jpg"
        },
        "error": null // if there was an error during file download
    }
    ...
  }
}
```
in addition to `media.*` field it will have `media.s3.*` field with the S3 bucket information.

### S3 Metadata
Each file saved in S3 has additional metadata:
- `X-Amz-Meta-Waha-Session=default` - the session name
- `X-Amz-Meta-Waha-Message-Id=true_111...` - the message ID
- `X-Amz-Meta-Waha-Media-File-Name=media.jpg` - the media file name (if available)



[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
In `2024.9.1` https://waha.devlike.pro/docs/overview/changelog/#20249

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by HuangDaHui** [comment]
> https://waha.devlike.pro/docs/how-to/storages/#media---s3
> 
> ## Media - S3
> You can use the S3 storage to store the media files.
> 
> Any **S3 Compatible** storage can be used, such as AWS S3, MinIO, DigitalOcean Spaces, etc. For in-house solutions, you can use [**MinIO**](https://min.io/).
> 
> ### Configuration
> * `WAHA_MEDIA_STORAGE=S3` - enable the S3 storage
> * `WAHA_S3_REGION=eu-west-1` - the region of the S3 bucket
> * `WAHA_S3_BUCKET=waha` - the name of the S3 bucket
> * `WAHA_S3_ACCESS_KEY_ID=minioadmin` - the access key of the S3 bucket
> * `WAHA_S3_SECRET_ACCESS_KEY=minioadmin` - the secret access key of the S3 bucket
> * `WAHA_S3_ENDPOINT=http://127.0.0.1:9000` - the endpoint of the S3 bucket (not required for AWS S3)
> * `WAHA_S3_FORCE_PATH_STYLE=True` - force path style for the S3 bucket (not required for AWS S3)
> * `WAHA_S3_PROXY_FILES` - proxy media files through WAHA (`False` by default)
>   
>   * `WAHA_S3_PROXY_FILES=False` - generate pre-signed URLs for media files and send them to the client in `media.url`
>   * `WAHA_S3_PROXY_FILES=True` - WAHA will proxy media files through itself in `media.url`
> 
> After you enabled S3 here's example for **message** webhook payload:
> 
> ```json
> {
>   "event": "message",
>   "session": "default",
>   "engine": "WEBJS",
>   "payload": {
>     "id": "true_11111111111@c.us_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
>     "hasMedia": true,
>     "media": {
>         "url": "http://localhost:3000/api/files/true_11111111111@c.us_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.jpg",
>         "mimetype": "image/jpeg",
>         "filename": null,
>         "s3": {
>             "Bucket": "bucket-name",
>             "Key": "/default/true_11111111111@c.us_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.jpg"
>         },
>         "error": null // if there was an error during file download
>     }
>     ...
>   }
> }
> ```
> 
> in addition to `media.*` field it will have `media.s3.*` field with the S3 bucket information.
> 
> ### S3 Metadata
> Each file saved in S3 has additional metadata:
> 
> * `X-Amz-Meta-Waha-Session=default` - the session name
> * `X-Amz-Meta-Waha-Message-Id=true_111...` - the message ID
> * `X-Amz-Meta-Waha-Media-File-Name=media.jpg` - the media file name (if available)
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

Can I use Azure Blobs?

**Comment by devlikepro** [comment]
> Can I use Azure Blobs?

If there's S3 compatible interface - yes!
but I don't think so https://learn.microsoft.com/en-us/answers/questions/1183760/s3-api-support-over-azure-blob-storage

However, **you can use an S3-to-Azure gateway**
https://portal.azure.com/#create/flexify.azure-s3-apice

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by HuangDaHui** [comment]
> > 我可以使用 Azure Blob 吗？
> 
> 如果有 S3 兼容接口 - 是的！ 但我不这么认为https://learn.microsoft.com/en-us/answers/questions/1183760/s3-api-support-over-azure-blob-storage
> 
> 但是，**您可以使用 S3 到 Azure 网关** https://portal.azure.com/#create/flexify.azure-s3-apice
> 
> [![赞助人：PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

ok let me look into it thank you very much

**Comment by HuangDaHui** [comment]
hello, i have a question
If I use S3 to store media attachments, will the attachment be re-downloaded when I request this interface?
downloadMedia=true
`/api/messages?chatId=11111111111%40c.us&downloadMedia=true&limit=1&session=default`

**Comment by devlikepro** [comment]
> will the attachment be re-downloaded

Hi! With all media storages it'll first check if the file is already in the storage and after that download or just return `url` from the existing file, so you can safely request it over and over, it will not re-download files multiple time if you're asking about that!

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by HuangDaHui** [comment]
> > will the attachment be re-downloaded
> 
> Hi! With all media storages it'll first check if the file is already in the storage and after that download or just return `url` from the existing file, so you can safely request it over and over, it will not re-download files multiple time if you're asking about that!
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

Okay, but I encountered a problem recently. When I requested this interface, I got 20 messages and still couldn't get the result after more than 20 minutes.

/api/messages?chatId=11111111111%40c.us&downloadMedia=true&limit=20&session=default
Error: response status is 524

**Comment by HuangDaHui** [comment]
> > > will the attachment be re-downloaded
> > 
> > 
> > Hi! With all media storages it'll first check if the file is already in the storage and after that download or just return `url` from the existing file, so you can safely request it over and over, it will not re-download files multiple time if you're asking about that!
> > [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
> 
> Okay, but I encountered a problem recently. When I requested this interface, I got 20 messages and still couldn't get the result after more than 20 minutes.
> 
> /api/messages?chatId=11111111111%40c.us&downloadMedia=true&limit=20&session=default Error: response status is 524

I don’t know why, but it keeps getting 524, so I want to try S3 to see if it can solve this situation.

**Comment by devlikepro** [comment]
@HuangDaHui hi! 
Could you send us your discord please so we can find out the problem with 20 messages? It should work like in a minute, even if all 20 messages would have simple image waha@devlike.pro

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by HuangDaHui** [comment]
> @HuangDaHui hi! Could you send us your discord please so we can find out the problem with 20 messages? It should work like in a minute, even if all 20 messages would have simple image [waha@devlike.pro](mailto:waha@devlike.pro)
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

Hi, I sent you an email but I don't know how to contact you using Discord.
