### ISSUE TITLE
[BUG][NOWEB] - stopped uploading status (story)

### ISSUE THREAD

**Issue by oteGroupMoishy** [allburov/whatsapp-http-api#363]
**statuses not sent**

**Version**

```json
{
  "version": "2024.6.2",
  "engine": "NOWEB",
  "tier": "PLUS",
  "browser": "/usr/bin/chromium"
}
```

**Expected behavior**

When using endpoints `/api/{session}/status/{type}` (happened in types: text and image, the rest were not tried)
Status not sent
Although the response is success - 201

**Engine** I'm using **NOWEB** engine.

**Comment by oteGroupMoishy** [comment]
Update
For now, deleting the session and reconnecting solved the problem
I will update later if the problems return

**Comment by devlikepro** [comment]
> Have You Tried Turning It Off And On Again

That would be our first question anyway :D That's great it helped!

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
