### ISSUE TITLE
[Feature Request] white label - check the links in examples

### ISSUE THREAD

**Issue by sg957** [allburov/whatsapp-http-api#373]
Wit hin the examples in Swagger there are links to your project So the white label is ineffective...

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Will add in 2024.6.7 so you can overwrite it + removed the link to `waha.devlike.pro`
- `WHATSAPP_SWAGGER_VIDEO_EXAMPLE_URL` - link to the video example `https://github.com/devlikeapro/waha/raw/core/examples/video.mp4`
- `WHATSAPP_SWAGGER_OPUS_EXAMPLE_URL` - link to the opus example `https://github.com/devlikeapro/waha/raw/core/examples/dev.likeapro.opus`
- `WHATSAPP_SWAGGER_JPG_EXAMPLE_URL` - link to the jpg example `https://github.com/devlikeapro/waha/raw/core/examples/dev.likeapro.jpg`


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
