### ISSUE TITLE
 [BUG][WEBJS] -  Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'default')

### ISSUE THREAD

**Issue by AlbertMrMaruk** [allburov/whatsapp-http-api#375]
**Describe the bug**

There is a new error when scanning qr code
[Nest] 30  - 06/17/2024, 1:00:01 PM   ERROR [WhatsappSession - default] Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'default')
    at pptr://__puppeteer_evaluation_script__:5:95

And then session change status to FAILED

**Version**

```json
{
  "version": "2024.4.4",
  "engine": "WEBJS",
  "tier": "PLUS",
  "browser": "/usr/bin/chromium"
}
```

**Expected behavior**

Do not change status to Failed

I'm using **WEBJS** engine.

**Docker Logs**

 [_whatsapp-http-api-4_logs (2).txt](https://github.com/user-attachments/files/15871338/_whatsapp-http-api-4_logs.2.txt)

**Comment by devlikepro** [comment]
Hi! Could you try to use the latest `2024.6.something` version? 
If update doesn't help - could you please run the session with `debug: true` flag enabled?

https://waha.devlike.pro/docs/how-to/sessions/#enable-debug
```json
{
  "name": "default",
  "config": {
    "debug": true
  }
}
```

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by AlbertMrMaruk** [comment]
Hello! There is debug log 
[Nest] 30  - 06/18/2024, 6:48:06 PM   DEBUG [WhatsappSession - default] WEBJS event: {"event":"loading_screen","data":[100,"Loading your chats"]}
[Nest] 30  - 06/18/2024, 6:48:10 PM   ERROR [WhatsappSession - default] Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'default')
    at pptr://__puppeteer_evaluation_script__:5:95

**Comment by AlbertMrMaruk** [comment]
There was some change in last version whatsapp-web-js? Maybe i can do something with this version

**Comment by devlikepro** [comment]
Try to 
1. /logout
2. /start a new session again
3. recreate a container

If it doesn't help - try to update it to the latest version. let us know if it doesn't help!

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
