### ISSUE TITLE
[BUG][WEBJS] - container not start

### ISSUE THREAD

**Issue by devandcom** [allburov/whatsapp-http-api#377]
Now I can't start the container, running until some hours ago.

docker run -it -p 4000:3000/tcp devlikeapro/waha-plus
yarn run v1.22.19
$ node dist/main
NODE - Catching unhandled exceptions enabled
WAHA (WhatsApp HTTP API) - Running PLUS version...
Segmentation fault (core dumped)
error Command failed with exit code 139.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Version**
latest

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Hi! Looking at this, releseard 2024.6.5 exactly few hours ago.
👉 meanwhile, you can keep running old version - use `devlikeapro/waha-plus:latest-2024.6.4` image
https://waha.devlike.pro/docs/how-to/engines/#docker-images

What OS do you use on the host?

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Is it the full command, right? Just wanna test it in the whole context

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devandcom** [comment]
I solved it by completely deleting the container and recreating it.
I don't know exactly what happened, but the machine had been running for a week with the penultimate version.
For the moment it's working.

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
thank you for the feedback!

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
