### ISSUE TITLE
improvement - phone number check 

### ISSUE THREAD

**Issue by behind24proxies** [allburov/whatsapp-http-api#38]
with the venom engine when you verify the existence of phone numbers it never returns a false , it simply times out.
in other words if the phone number is not on whatsapp it does not return a response.

**Comment by allburov** [comment]
Hi! We've added [contacts endpoints](https://waha.devlike.pro/docs/how-to/contacts/) in WAHA

Right now it supports:
- Get all contacts or a single one
- Get "about" contact (aka status)
- Get contact's profile picture
- **Check phone number is registered in WhatsApp** (works even if the number is not in your contact list)
- Block and unblock contacts

It supports default engine, so no needs to use venom for phone number check. Please have a look, it may help you!

The endpoints are available in WAHA Plus `2023.1` version and we'll add them in Core version in February 2023
