### ISSUE TITLE
[BUG][NOWEB] - Getting Status 403 while adding a participant to a group 

### ISSUE THREAD

**Issue by kevinnadar22** [allburov/whatsapp-http-api#389]
**Version**

```json
{
  "version": "2023.11.1",
  "engine": "NOWEB",
  "tier": "PLUS",
  "browser": "/usr/bin/google-chrome-stable"
}
```

**Expected behavior**

Getting Status 403 while adding a participant to a group using group id and participant id

**Engine** I'm using **NOWEB** engine.

**Requests - Responses**

![IMG_7156](https://github.com/devlikeapro/waha/assets/76389377/29f34264-84f9-44c0-8798-25e26522a7b8)

**Comment by devlikepro** [comment]
> 403 while adding a participant to a group using group id and participant id

Do you have permissions in that group?

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by kevinnadar22** [comment]
Yes I created the group using the API itself

**Comment by devlikepro** [comment]
@kevinnadar22 
The participant you're trying to add doesn't allow you to add you to the group.

Tested it this way:
1. Created a group via API (with 1st participant)
2. Add 2nd participant (not private settings set)
3. OK
4. For 2nd participant set privacy mode as "My Contacts Except…" in Group Privacy
5. See 403 error, just as you pointed above

Nothing we can do here, it's WA who doesn't allow it 
https://faq.whatsapp.com/3307102709559968/?locale=en_US&cms_platform=web&cms_id=3307102709559968&draft=true

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
try adding the same participant on phone - you'll get an error as well and WA suggests you to send an invite

For such errors consider sending them Intive link with some short message
https://waha.devlike.pro/docs/how-to/groups/#invite-code

We should work on the original "Invite" message with the button tho :thinking: 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by kevinnadar22** [comment]
Okay thanks
