### ISSUE TITLE
How to authenticate?

### ISSUE THREAD

**Issue by martinmineo** [allburov/whatsapp-http-api#39]
In the documentation you say “We don't recommend expose the API in the internet without authentication!”

I imagine that somebody has already done it. 

Do you provide a way to do it or I should add the piece of code to do it? If so, please give me some guidance on how to do it.

**Comment by allburov** [comment]
@martinmineo hi!
There's [security page](https://waha.devlike.pro/docs/how-to/security/) in the documentation about it. 
It's available "built-in" in [WAHA Plus version](https://waha.devlike.pro/docs/how-to/plus-version/) which is available via donations

Let us know if there's any questions left!

**Comment by allburov** [comment]
Another way is to put the API behind a firewall and not to expose it on the internet
