### ISSUE TITLE
[FIXED][BUG][WEBJS] - WEB whatsapp-http-api-plus CAN NOT LOAD QRCODE after update latest version 

### ISSUE THREAD

**Issue by jerryrat** [allburov/whatsapp-http-api#396]
![image](https://github.com/devlikeapro/waha/assets/19183369/e537c03f-f7ad-4f5e-938f-23b8a905d45f)

---------------update -------------

whatsapp-http-api-plus  name changed to  waha

<img width="423" alt="6fc7258f4ae2a6b6c079ad6182ea82e" src="https://github.com/devlikeapro/waha/assets/19183369/03bbd34b-6df1-4f03-a467-58c632d235a8">

**Comment by Thiagomleite** [comment]
I have this same problem using the plus version.

**Comment by willpexeroo** [comment]
same problem here, please fix this

**Comment by brunoskiner** [comment]
same here too

**Comment by Bolaroleta** [comment]
same problem here after the update..

**Comment by ilhamakbar12** [comment]
anyone that have temporary solution?

**Comment by KapteinBabbalas** [comment]
https://github.com/devlikeapro/waha/issues/395

The same issue I think with a solution that I could not get to work
