### ISSUE TITLE
[BUG][WEBJS] - Scan QR issues (Whatsapp is out of date. Updating now ....)

### ISSUE THREAD

**Issue by joseamonteironeto** [allburov/whatsapp-http-api#399]
Hi! I can't generate a QR CODE because instance stays STARTING forever, tried on different devices, and it repeats the same behaviour... Am i'm doing something wrong? Or is this a bug? I'm using the lastest version!

**Comment by Thiagomleite** [comment]
I have this same problem using the plus version.

**Comment by willpexeroo** [comment]
Yea, same problem here. Im waiting they fix it

**Comment by jerryrat** [comment]
same， tried different version, seems communication with WhatsApp issues, old version also can not load QR code when start new session.

**Comment by synl0rd** [comment]
me too, please fix this.

**Comment by egbertomonteiro** [comment]
Same issue. Latest version available, all sessions "Starting" forever:
![image](https://github.com/devlikeapro/waha/assets/298314/4f523205-3524-4dbd-b9a1-7ce657f99973)


log:
[Nest] 31  - 06/29/2024, 12:38:54 PM   ERROR [WhatsappSession - 7e980f4c-1c02-4833-a073-29afabe7cde3] ProtocolError: Waiting for selector `[data-icon='search']` failed: Protocol error (Runtime.callFunctionOn): Target closed.
[Nest] 31  - 06/29/2024, 12:38:54 PM     LOG [WhatsappSession - 7e980f4c-1c02-4833-a073-29afabe7cde3] Setting up client start in 2 seconds...
[Nest] 31  - 06/29/2024, 12:45:25 PM   ERROR [WhatsappSession - e065d5be-81b7-4c84-8eb6-2d44ba7c34b5] ProtocolError: Waiting for selector `[data-icon='search']` failed: Protocol error (Runtime.callFunctionOn): Target closed.
[Nest] 31  - 06/29/2024, 12:45:25 PM     LOG [WhatsappSession - e065d5be-81b7-4c84-8eb6-2d44ba7c34b5] Setting up client start in 2 seconds...
[Nest] 31  - 06/29/2024, 1:30:28 PM   ERROR [WhatsappSession - b5164473-cb9f-4302-8f81-c8e1e253076c] ProtocolError: Waiting for selector `[data-icon='search']` failed: Protocol error (Runtime.callFunctionOn): Target closed.
[Nest] 31  - 06/29/2024, 1:30:28 PM     LOG [WhatsappSession - b5164473-cb9f-4302-8f81-c8e1e253076c] Setting up client start in 2 seconds...
[Nest] 31  - 06/29/2024, 2:08:34 PM     LOG [SessionManager] Stopping b5164473-cb9f-4302-8f81-c8e1e253076c session...
[Nest] 31  - 06/29/2024, 2:08:34 PM     LOG [SessionManager] "b5164473-cb9f-4302-8f81-c8e1e253076c" has been stopped.
[Nest] 31  - 06/29/2024, 2:08:34 PM   ERROR [WhatsappSession - b5164473-cb9f-4302-8f81-c8e1e253076c] ProtocolError: Waiting for selector `[data-icon='search']` failed: Protocol error (Runtime.callFunctionOn): Target closed.

**Comment by daviddr17** [comment]
same here, sometimes it starts but after scanning qr code nothing happens and whatsapp says after a minute that connection was not successful 

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by mohamed-elghafiani** [comment]
I have the same problem here, it keeps showing the message "Whatsapp is out of date. Updating now ...."
No QR code is shown!
I think the problem is from Whatsapp web!

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by jerryrat** [comment]
<img width="423" alt="6fc7258f4ae2a6b6c079ad6182ea82e" src="https://github.com/devlikeapro/waha/assets/19183369/7b34d594-cbca-46b6-ab0d-9977bdbae527">
docker name changed, after change name it works

**Comment by ilhamakbar12** [comment]
> <img alt="6fc7258f4ae2a6b6c079ad6182ea82e" width="423" src="https://private-user-images.githubusercontent.com/19183369/344515895-7b34d594-cbca-46b6-ab0d-9977bdbae527.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MDI5MDcsIm5iZiI6MTcxOTgwMjYwNywicGF0aCI6Ii8xOTE4MzM2OS8zNDQ1MTU4OTUtN2IzNGQ1OTQtY2JjYS00NmI2LWFiMGQtOTk3N2JkYmFlNTI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDAyNTY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4NzZkM2MwZTZhZTFlNTUzZjU0NTk2MmE1NjAwYmZhMzU2MDU5NjcwMGZhNmE5ZmNlZjczMjcwN2FjOThlOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EKAwxEIb41RPMvDNk-oiU4eoIrmBw_1ctlpbDOq-nMw"> docker name changed, after change name it works

it work for me also, thankyou

**Comment by faezyatama** [comment]
I have the same problem here, it keeps showing the message "Whatsapp is out of date. Updating now ...."
No QR code is shown! Whats wrong...

**Comment by MVidal80** [comment]
same here, using devlikeapro/waha-plus

**Comment by obtulowiczl** [comment]
I also have pro image from May and "Whatsapp is out of date. Updating now ...." problem. I could renew my subscription, but problem is still not solved.

**Comment by mohamed-elghafiani** [comment]
For those who are still experiencing this issue, try pulling the image again and rerunning it. This resolved the problem for me!

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by MVidal80** [comment]
> For those who are still experiencing this issue, try pulling the image again and rerunning it. This resolved the problem for me!
> 
> [![patron:PLUS](https://camo.githubusercontent.com/0655ed188ee8fba6c8313142d2ec7b915d0090b9117796602e468b736824b01f/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d504c55532d613065366261)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

please share the commands

**Comment by mohamed-elghafiani** [comment]
> > For those who are still experiencing this issue, try pulling the image again and rerunning it. This resolved the problem for me!
> > [![patron:PLUS](https://camo.githubusercontent.com/0655ed188ee8fba6c8313142d2ec7b915d0090b9117796602e468b736824b01f/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d504c55532d613065366261)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
> 
> please share the commands

I am using waha-plus
if you're like me:
You can download the image using:
docker login -u devlikeapro -p {KEY}
docker pull devlikeapro/waha-plus
docker logout

and then run it using:
docker run -it -p 3000:3000/tcp devlikeapro/waha-plus

If you're using normal version it's the same think just instead of waha-plus change it to waha. Also you won't need to login!

You can check the doc for more info:
https://waha.devlike.pro/docs/overview/quick-start/

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by MVidal80** [comment]
thanks for sharing.
i had a script that was still calling the old docker name,
I confirm that now I get the qr code

**Comment by devlikepro** [comment]
:warning: Please make sure you're using the new docker image name `devlikeapro/waha` and `devlikeapro/waha-plus` in both `docker pull` command AND `docker run` commands. 
Stop and remove the previous container if you have any (you can check it by `docker ps`)
Check `GET /api/version` response after that it must return `2024.6.8` or later (NOT 2024.6.1 or 2024.6.2 - it 100% means you're running old image, `devlikeapro/whatsapp-http-api`)

If after update you still have issues - kindle create SEPARATE issue and provide `GET /api/version` response with details.

https://waha.devlike.pro/blog/docker-image-has-been-renamed-to-devlikeapro/waha/ 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
