### ISSUE TITLE
[BUG][WEBJS] - sendVoice Not Working

### ISSUE THREAD

**Issue by meein** [allburov/whatsapp-http-api#400]
**Describe the bug**

> The sendVoice endpoint doesn't work, it hangs and eventually times out with a 503 error

**Version**

```json
{
  "version": "2024.6.8",
  "engine": "WEBJS",
  "tier": "PLUS",
  "browser": "/usr/bin/chromium"
}
```

**Requests - Responses**

> ![image](https://github.com/devlikeapro/waha/assets/123134151/96d54ef7-6792-416d-bcd1-5fd919bbd2c7)

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by meein** [comment]
sendVoice is working for me in 2024.7.2

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by borsatti2** [comment]
> sendVoice is working for me in 2024.7.2
> 
> [![patron:PLUS](https://camo.githubusercontent.com/0655ed188ee8fba6c8313142d2ec7b915d0090b9117796602e468b736824b01f/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d504c55532d613065366261)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

Not working here.. 2024.7.2

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
@borsatti2 could you try to use `devlikeapro/waha-plus:chrome` version and send the example to `POST /api/sendVoice`? 

```json
{
  "chatId": "11111111111@c.us",
  "file": {
    "mimetype": "audio/ogg; codecs=opus",
    "url": "https://github.com/devlikeapro/waha/raw/core/examples/dev.likeapro.opus"
  },
  "session": "default"
}
```

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
