### ISSUE TITLE
[BUG][WEBJS] - Unable to Send Audio - Timeout Error

### ISSUE THREAD

**Issue by ehussain** [allburov/whatsapp-http-api#408]
**Describe the bug**

Unable to send audio message using audio type option. 
It results in timeout error.

**Version**
{
  "version": "2024.6.8",
  "engine": "WEBJS",
  "tier": "PLUS",
  "browser": "/usr/bin/chromium"
}

**To Reproduce** Steps to reproduce the behavior:

Send following request.

```
{"chatId":"XXXXXXX@c.us","session":"XXXXX","type_of_file":"audio","type":"media","file":{"mimetype":"audio\/oga","filename":"2024-07-02-14-15-46903381.oga","url":"https:\/\/xxxxxxx.s3.eu-west-3.amazonaws.com\/2024-07-02-14-15-46903381.oga"},"caption":""}
```

**Expected behavior**

It should send audio message.

**Engine** I'm using **WEBJS** engine.

**Requests - Responses**

Send following request.

```
{"chatId":"XXXXXXX@c.us","session":"XXXXX","type_of_file":"audio","type":"media","file":{"mimetype":"audio\/oga","filename":"2024-07-02-14-15-46903381.oga","url":"https:\/\/xxxxxxx.s3.eu-west-3.amazonaws.com\/2024-07-02-14-15-46903381.oga"},"caption":""}
```

Response 
```
cURL error 28: Operation timed out after 20001 milliseconds with 0 bytes received
```

**Docker Logs**
```
[0702/141547.709005:INFO:CONSOLE(133)] "Event handler of 'x-storagemutated-1' event must be added on the initial evaluation of worker script.", source: https://static.whatsapp.net/rsrc.php/v3/y_/r/pC0cxBwVVkV.js?_nc_x=Ij3Wp8lg5Kz (133)

```

[![patron:ADVANCED](https://img.shields.io/badge/patron-ADVANCED-4cd07d)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Related to video too https://github.com/devlikeapro/waha/issues/400

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Hi! Could you try to use `devlikeapro/waha-plus:chrome` `2024.7.2` version and send the example below?
```json
{
  "chatId": "11111111111@c.us",
  "file": {
    "mimetype": "audio/ogg; codecs=opus",
    "url": "https://github.com/devlikeapro/waha/raw/core/examples/dev.likeapro.opus"
  },
  "session": "default"
}
```
if that works, but your voice doesn't - kindly share it with me (you can DM payload to me)

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Hi! I believe it's been fixed in latest version (after https://boosty.to/wa-http-api/posts/a6c01a2d-704e-4066-978a-890e84de9da1)
Let me know if it's happening!

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
