### ISSUE TITLE
[NOWEB] - mark connection as offline by flag

### ISSUE THREAD

**Issue by devlikepro** [allburov/whatsapp-http-api#412]
The request from Discord
https://discord.com/channels/1228605717372604466/1228639621391585354/1256952165516185690

----

I'm using NOWEB... and I want my users to receive notifications on their devices... so I call /api/{session}/presence with { "presence": "offline" } as soon as I receive the WORKING status.
It works fine sometimes... but sometimes when the session receives a message, it goes back online.

Would it be safe to set presence to offline after each message the session receives? Or am I doing something wrong?
Each server I have hosts around >300 NOWEB sessions... and they might receive a lot of messages... so it's going to be way too many presence offline requests... no? Is there a chance of getting a number blocked by too many presence offline requests? 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
We recently added "reconnect session after 30 minutes" behaviour, and at the start it does send "online" status always. We'll fix that, but likely you'll need to add a new flag `markOnline: false`  when running a session.

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by giovannicarella** [comment]
+1

**Comment by elasti-co** [comment]
+1

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Added in `2024.9.6`

----

## NOWEB Configuration
- `markOnline: true` - send `online` **presence** when session starts (default `true`).
  - Required if you want to get notifications in your phone
  - Read more about [**✅ Presence**](https://waha.devlike.pro/docs/how-to/presence/)


```json
{
  "name": "default",
  "config": {
    "noweb": {
      "markOnline": false,
      "store": {
        ...
      }
    }
  }
}
```


## FAQ
👉 **I don't get notifications on my phone when WAHA session is connected**
- You need to send `offline` after all presence you send (WhatsApp doesn't send notifications to the device if a web client is active).
- For [**🏭 NOWEB Engine**](https://waha.devlike.pro/docs/engines/noweb/#configuration) also mark sure to send `markOnline: false` 
when you create a new session.

## Dashboard
![image](https://github.com/user-attachments/assets/e71083de-f4e5-492a-a13d-968aa7ae124e)



[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
