### ISSUE TITLE
[BUG][WEBJS] - Cannot Create group

### ISSUE THREAD

**Issue by AknalRe** [allburov/whatsapp-http-api#416]
**Cannot Create Grup**

> POST
[/api/{session}/groups](https://waha.aknalre.my.id/#/groups/GroupsController_createGroup)
Create a new group.
> <html>
<body>

Code | Details
-- | --
201 | Response bodyDownloadCreateGroupError: An unknown error occupied while creating a group

</body>
</html>

**[2024.7.1](https://waha.devlike.pro/docs/overview/changelog/)**

```json
{
  version: '2024.7.1',
  engine: 'WEBJS',
  tier: 'PLUS',
  browser: '/usr/bin/chromium'
}
```

**![image](https://github.com/devlikeapro/waha/assets/94711128/2e563862-830d-44b1-8af2-92e8c66174cd)**

**Comment by devlikepro** [comment]
fixed in `2024.7.2`

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
