### ISSUE TITLE
Account Blocked 

### ISSUE THREAD

**Issue by KapteinBabbalas** [allburov/whatsapp-http-api#417]
My account got block today after many, many years of using an automation tool like WAHA Api or simmilar.

Anybody else got these problems?
I think Meta is catching on to whats going on in terms of people breaking the terms of use.
Be carefull out there.

I dont think it's WAHA API because I have been using it for a few months without problems.
Too bad, It has been a good run the last 5+ years of hacking WhatsApp Web. 

RIP
![image](https://github.com/devlikeapro/waha/assets/2060705/f921edf9-2cc3-455c-97fb-232c771517e1)

**Comment by devlikepro** [comment]
Hi! 
What engine did you use, WEBJS?
Did you follow the guide https://waha.devlike.pro/docs/overview/how-to-avoid-blocking/?

If you follow the guide and don't make your recipients angry - yes, you can work for 5 and more years with no problem.
Consider using residential proxies as well, to make your WhatsApp Web work from the same region as your phone in if you were using VPS
https://waha.devlike.pro/blog/waha--geonode-proxy-bypassing-errors-on-cloud-or-vps/

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Request unblock, usually it helps btw if it's not permanent ban

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by mmojadad** [comment]
Hi
The exact same blocking happened for me toady, Just after install and enable WAHA plus and activate my number and send just 1 test simple text message in 24 hours.
Too bad
