### ISSUE TITLE
API is not responding because https/http mixed content.

### ISSUE THREAD

**Issue by guimogra** [allburov/whatsapp-http-api#42]
Hi, first of all, you did a great job here. 

I cant get info from the API because my server runs over https and the API is http. Is there any documentation about ssl in api or swagger running in docker?

**Comment by allburov** [comment]
Hi! Thank for your kind words!

I think the easiest way is to place the API behind some reverse proxy like nginx that will handle ssl termination for you and than work with the API just as plain HTTP 
Please follow the guide like this https://leangaurav.medium.com/simplest-https-setup-nginx-reverse-proxy-letsencrypt-ssl-certificate-aws-cloud-docker-4b74569b3c61 - section **Step-4.1: Proxy requests(optinal)** is not optional for you :) 

For testing you can use ngrok https://ngrok.com/

**Comment by giljlle** [comment]
A simpler way is to use an https to http redirector webhook, such as https://webhookrelay.com/

**Comment by devlikepro** [comment]
👉 Here's [**Step by step guide on how to set up HTTPS for WAHA**](https://waha.devlike.pro/blog/setting-up-https-for-waha/)

----
[🔒 Security](https://waha.devlike.pro/docs/how-to/security/#https)

## HTTPS
After you set up the security options - you should set up HTTPS to protect the data in transit and prevent [Man-in-the-middle attacks](https://en.wikipedia.org/wiki/Man-in-the-middle_attack).

That's fine to run it on the local network without HTTPS, but for the production environment, it's a must-have.

### Environment variables
WAHA supports HTTPS out of the box.

You can set up the following environment variables to enable HTTPS:
- `WAHA_HTTPS_ENABLED=true`: Set this variable to `true` to enable HTTPS. By default, it's `false`.
- `WAHA_HTTPS_PATH_KEY=/path/to/key.pem`: The path to the key file for HTTPS. By default `./.secrets/privkey.pem`
- `WAHA_HTTPS_PATH_CERT=/path/to/cert.pem`: The path to the certificate file for HTTPS. By default `./.secrets/cert.pem`
- `WAHA_HTTPS_PATH_CA=/path/to/ca.pem`: The path to the CA file for HTTPS. By default `./.secrets/chain.pem`

### How to set up HTTPS
Here's available options how you can set up HTTPS:
1. **Self-signed certificate** - generate a self-signed certificate and use it for HTTPS.
2. **Let's Encrypt** - use [Certbot](https://certbot.eff.org/) to get a free certificate from Let's Encrypt.
3. **Using reverse proxy** - use Nginx or Apache as a reverse proxy and set up HTTPS there.



[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
