### ISSUE TITLE
[BUG][WEBJS] - no webhook when the message is sent by myself

### ISSUE THREAD

**Issue by gonbad** [allburov/whatsapp-http-api#426]
when i receive a message, i get a webhook successfully. but when the message is sent by myself, there is no webhook.

**Comment by devlikepro** [comment]
Hi! Could you try to enable and listen to `message.any` webhook event?
> Fired on all message creations, including your own.

https://waha.devlike.pro/docs/how-to/receive-messages/#messageany

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by gonbad** [comment]
it worked. thank you!
