### ISSUE TITLE
[BUG][WEBJS] - Still stuck at session initializing

### ISSUE THREAD

**Issue by pablomorato1** [allburov/whatsapp-http-api#428]
I'm still having issues with session stuck at "STARTING" even after updating the docker image to the new name.

> A clear and concise description of what the bug is. Feel free to remove
> sections that you don't feel to make the text shorter!

**Version**

```json
{
  "version": "2024.7.4",
  "engine": "WEBJS",
  "tier": "PLUS",
  "browser": "/usr/bin/chromium"
}
```

The issue related to being stuck at whatsapp version getting updated got fixed, but the session still doesn't move on because now the QRcode is never generated.

<img width="817" alt="image" src="https://github.com/devlikeapro/waha/assets/37642246/66ff1ac7-9c6d-494c-9bbb-f3afd0e98afa">

**Comment by devlikepro** [comment]
@pablomorato1 hi! 
just to check that everything is good, could you try to run a completely new container using different folder? like `.sessions2`
```
docker run -v /home/waha/.sessions2:/app/.sessions -p 3000:3000/tcp devlikeapro/waha-plus
```
if that doesn't help - what country you're in? Where's your VPS is hosted?
another solution would be to try using chrome if you're using default image
```
docker run -v /home/waha/.sessions2:/app/.sessions -p 3000:3000/tcp devlikeapro/waha-plus:chrome
```

waiting for your feedback! 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
any updates?

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
