### ISSUE TITLE
How I get the list of groups_id to send message ?

### ISSUE THREAD

**Issue by MasamioNakada** [allburov/whatsapp-http-api#43]

**Comment by allburov** [comment]
Hi! 
We'll add endpoints to get groups in https://github.com/devlikeapro/whatsapp-http-api/issues/34

Meanwhile you may receive [incoming messages via webhook](https://waha.devlike.pro/docs/how-to/receive-messages/) and then use `from` field from the payload [to send message](https://waha.devlike.pro/docs/how-to/send-messages/#send-text-imagesversionscorepng-imagesversionspluspng)  - the `form` in Group messages is exactly group id that you're looking for!

**Comment by MasamioNakada** [comment]
Thanks, I wil try!!
