### ISSUE TITLE
[Feature Request] Implement Logout Feature Without Deleting Session

### ISSUE THREAD

**Issue by sofyan-ahmad** [allburov/whatsapp-http-api#435]
**Is your feature request related to a problem? Please describe.**

I'm often frustrated when I need to change the WhatsApp number associated with a session. Currently, logging out also deletes the session, causing me to set everything up again, which is time-consuming and inconvenient.

**Describe the solution you'd like**

I would like the app to include a logout feature that does not delete the session. This would allow me to log out to change the WhatsApp number without losing my session data, as all sessions are connected to my frontend app (by session id). The session should be preserved so I can quickly log back in and resume my activities without any disruption.

**Describe alternatives you've considered**

One alternative could be an option to switch WhatsApp numbers without logging out. However, this might involve additional steps and permissions, making the simpler logout option more user-friendly and straightforward.

**Additional context**

Implementing a logout feature that retains the session will significantly enhance the user experience, especially for users who frequently need to switch accounts or numbers. This feature will save time and reduce the frustration associated with setting up everything from scratch.

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Yes, will do, good idea to avoid implementing it on the application side

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by HuangDaHui** [comment]
+1

**Comment by devlikepro** [comment]
will be in `2024.9.1` :crossed_fingers: 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Sessions can be controlled properly now using new API in `2024.9.1`!
https://waha.devlike.pro/docs/how-to/sessions/
![image](https://github.com/user-attachments/assets/b235cb3b-7e8f-41e1-9eb7-cfb73b396f88)


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
