### ISSUE TITLE
session info

### ISSUE THREAD

**Issue by darkkLUCIFER** [allburov/whatsapp-http-api#436]
is there any api to return more data about the session that is connected
like avatar and all data about user session?

**Comment by devlikepro** [comment]
Hi! 
Yes, you can get "me" information about the session - https://waha.devlike.pro/docs/how-to/sessions/#get-me
```
{
  "id": "11111111111@c.us",
  "pushName": "string"
}
```
Using `id` from the above response you can fetch the picture using https://waha.devlike.pro/docs/how-to/contacts/#get-contact-profile-picture

```
GET /api/contacts/profile-picture?contactId=11231231231&session=default
```
it'll return the avatar

```
{
  "profilePictureURL": "https://example.com/profile.jpg"
}
```


>  all data about user session

What data exactly, could you specify? there's many data you can get about the session (aka WhatsApp Account, Phone Number) https://waha.devlike.pro/docs/how-to/



[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
