### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by raj4ever** [allburov/whatsapp-http-api#44]
boosty and petrion show me renew every month

**Comment by allburov** [comment]
@raj4ever yep, it works this way.
If you want to get Plus version and donate once - use these steps:
1. Subscribe
2. Get secret key from the latest post 
3. Download the PLUS docker image
4. **Unsubscribe**

The downloaded image will **always work**, even after month-two-three, no license expiration here.
But you won't receive the image's updates if you unsubscribe from boosty or patreon (actully you'll until the end of your subscription which long one month)

I hope it helped!

**Comment by raj4ever** [comment]
PLUS version can sed button with a link?

**Comment by allburov** [comment]
@raj4ever it can not yet :( 
https://github.com/devlikeapro/whatsapp-http-api/issues/29
