### ISSUE TITLE
[BUG][WEBJS] -get chats error

### ISSUE THREAD

**Issue by HuangDaHui** [allburov/whatsapp-http-api#446]
/api/session_9p7hs/chats?limit=10&offset=0
{
  "statusCode": 500,
  "timestamp": "2024-07-18T10:15:03.417Z",
  "exception": {
    "stack": "Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'getChats')\n    at pptr://__puppeteer_evaluation_script__:2:38\n    at ExecutionContext._ExecutionContext_evaluate (/app/node_modules/whatsapp-web.js/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:229:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ExecutionContext.evaluate (/app/node_modules/whatsapp-web.js/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)\n    at async WebjsClient.getChats2 (/app/dist/core/engines/webjs/WebjsClient.js:19:23)\n    at async WebjsClient.getChats (/app/dist/core/engines/webjs/WebjsClient.js:16:16)",
    "message": "Evaluation failed: TypeError: Cannot read properties of undefined (reading 'getChats')\n    at pptr://__puppeteer_evaluation_script__:2:38",
    "name": "Error"
  },
  "request": {
    "path": "/api/session_9p7hs/chats?limit=10&offset=0",
    "method": "GET",
    "body": {},
    "query": {
      "limit": "10",
      "offset": "0"
    }
  },
  "version": {
    "version": "2024.7.4",
    "engine": "WEBJS",
    "tier": "PLUS",
    "browser": "/usr/bin/chromium"
  }
}

**Comment by HuangDaHui** [comment]
I'm using the PLUS version, but I can't log in to the email, I only have the docker key

**Comment by devlikepro** [comment]
hi! What is the status of the session? Could you stop it and start it again? If it doesn't help - `/logout` and scan QR one more time

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Could be related to https://github.com/devlikeapro/waha/issues/444

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by HuangDaHui** [comment]
After pulling the 2024.7.6 version, deleting sessions and creating sessions will be fine
