### ISSUE TITLE
Sending Multiple Photos, Video, and Comment via API

### ISSUE THREAD

**Issue by 07artem132** [allburov/whatsapp-http-api#448]
Hi, i am trying to send multiple photos, a video, and a comment through the API in the same way it is done via the web version. However, I am unsure how to achieve this.

Could you provide guidance or an example on how to send multiple photos, a video, and a comment together through the API? If additional information is needed, please let me know.

**Comment by 07artem132** [comment]
Wrong, I figured it out.

**Comment by devlikepro** [comment]
I believe the soltuion is to send multiple "single image" messages one after another and the rest does the client (WA app) and combine it so it looks like "multiple images".
Is that what you tried, right? Just for the people who have the similar question

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by 07artem132** [comment]
> I believe the soltuion is to send multiple "single image" messages one after another and the rest does the client (WA app) and combine it so it looks like "multiple images".
> 
> Is that what you tried, right? Just for the people who have the similar question
> 
> [![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

Yes, thanks you.

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
