### ISSUE TITLE
is there a way to add/change the webhook url after the user authentication ? 

### ISSUE THREAD

**Issue by behind24proxies** [allburov/whatsapp-http-api#45]
from what I know , in the core version , it is not possible .
in the plus version though , you can save the session , and restart the docker container with the new websocket url, is that right ?

another question , let's say that I have the plus version , and I host 5 phone numbers on it , is there a way to assign different web sockets to each ? (I don't want to make a proxy server that filters and forwards the messages to individual web sockets )

**Comment by allburov** [comment]
Hi!
>you can save the session , and restart the docker container with the new websocket url, is that right ?

Yes, it's right. Only whatsapp sessions are saved, no other parameters. After restart you have to "start" as session again anyway and you can do it with different webhook url and events.

As for setting different webhook url to sessions ir change it after authentication - great idea, we'll add the functional so you'll be able 
1.  set webhook url and events at the start of session (redefine default from docker)
2. change them at anytime after

**Comment by behind24proxies** [comment]
okay , great , thanks 🦖 :)

**Comment by allburov** [comment]
Let's leave the issue opened, so you can see when it's ready and we can see what we haven't done yet :)

**Comment by allburov** [comment]
Hi! Now you can configure per session webhooks and it's possible to send different events to endpoints. Please read more about it https://waha.devlike.pro/docs/how-to/webhooks/

It's not possible to change the configuration tho without restarting the session, so you'll have to stop and start the session again in that case :( 
Please create an issue if it's the case that you'd love to have, we decided to postpone that implementation a bit.

----
Here's an example: 
**POST /api/sessions/start**
```json
{
  "name": "default",
  "config": {
    "webhooks": [
      {
        "url": "https://httpbin.org/post",
        "events": [
          "message"
        ],
        "hmac": {
          "key": "your-secret-key"
        },
        "retries": {
          "delaySeconds": 2,
          "attempts": 15
        },
        "customHeaders": [
          {
            "name": "X-My-Custom-Header",
            "value": "Value"
          }
        ]
      }
    ]
  }
}
```
