### ISSUE TITLE
[BUG][WAHA-PLUS] - When WHATSAPP_API_KEY is defined, The 'health' endpoint gets unauthorized

### ISSUE THREAD

**Issue by puntorigen** [allburov/whatsapp-http-api#451]
**Describe the bug**

When using the plus version and setting the WHATSAPP_API_KEY environment value, the /health endpoint returns unauthorized, like: 
```json
{"statusCode":401,"message":"Unauthorized"}
```

Most health checks (like AWS) don't support sending header values for checking the health endpoints, so this endpoint should always be responsive, not depending on the API_KEY.

**Version 2024.7.6**

```json
{
  "version": "2024.7.6",
  "engine": "WEBJS",
  "tier": "PLUS",
  "browser": "/usr/bin/chromium"
}
```

**To Reproduce** Steps to reproduce the behavior:

1. Launch docker with the env 'WHATSAPP_API_KEY' set to any value
2. Open the endpoint /health
3. See error

**Expected behavior**

> A clear and concise description of what you expected to happen.

**Engine** I'm using **WEBJS** engine.

The /health endpoint should always respond, without being important if WHATSAPP_API_KEY is set or not.

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
:thinking: 
We'll add `WAHA_HEALTH_REQUIRE_AUTH` flag which will be `True` by default, so you can disable it if required
Does it work for you?

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
`WHATSAPP_API_KEY_EXCLUDE_PATH=health,ping` - this way you will disable auth on certain endpoint in `2024.8.X`. We'll let you know when it's available!

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
btw, added new `GET /ping` endpoint that really does nothing but return "pong" as well (because /health actually perform some actions, like reaches our the filesystem and the mongodb)

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
### Exclude endpoints

https://waha.devlike.pro/docs/how-to/security/#exclude-endpoints

---

If you need to exclude some endpoints (like `GET /health` or `GET /ping`) from the API Key requirement - you can 
set `WHATSAPP_API_KEY_EXCLUDE_PATH` environment variable with a comma-separated list of endpoints (no `/` at the beginning).

```bash
docker run -it \
 -e WHATSAPP_API_KEY_EXCLUDE_PATH="health,ping" \
 -e WHATSAPP_API_KEY=yoursecretkey \
 devlikeapro/waha-plus
```



[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
