### ISSUE TITLE
[BUG][WEBJS] - TypeError: Cannot read properties of undefined (reading 'getChat')

### ISSUE THREAD

**Issue by KKshitiz** [allburov/whatsapp-http-api#452]
**Describe the bug**

> 500 status error while sending message using the `/sendText`, `/sendImage` etc endpoint

**Version**

```json
{
        "version": "2024.7.6",
        "engine": "WEBJS",
        "tier": "PLUS",
        "browser": "/usr/bin/chromium"
}
```

**Engine** I'm using **WEBJS** engine.

**Requests - Responses**

This is the response I'm getting:
```
{
    "statusCode": 500,
    "timestamp": "2024-07-21T09:53:58.542Z",
    "exception": {
        "stack": "Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'getChat')\n    at pptr://__puppeteer_evaluation_script__:2:46\n    at ExecutionContext._ExecutionContext_evaluate (/app/node_modules/whatsapp-web.js/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:229:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ExecutionContext.evaluate (/app/node_modules/whatsapp-web.js/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)\n    at async WebjsClient.sendMessage (/app/node_modules/whatsapp-web.js/src/Client.js:963:25)",
        "message": "Evaluation failed: TypeError: Cannot read properties of undefined (reading 'getChat')\n    at pptr://__puppeteer_evaluation_script__:2:46",
        "name": "Error"
    },
    "request": {
        "path": "/api/sendText",
        "method": "POST",
        "body": {
            "chatId": "91XXXXXXXXXX",
            "text": "Hi, this is a test message",
            "session": "session"
        },
        "query": {}
    },
    "version": {
        "version": "2024.7.6",
        "engine": "WEBJS",
        "tier": "PLUS",
        "browser": "/usr/bin/chromium"
    }
}
```

**Additional context**

> I have around 40 sessions working on different servers but it happens only with this particular session
> I also tried closing, logging out and then rescanning the QR but still the same

[![patron:ADVANCED](https://img.shields.io/badge/patron-ADVANCED-4cd07d)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
@KKshitiz when you're starting the session (exactly this one) - do you have any error logs in the container? 
Looks like WA enrolled a new version to small portion of the users (so it affects only 1/40 sessions), additional info would be really helpful here! :pray: 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
or may be you can scan qr if I send one to your DM? So we can investigate the issue with the session locally

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by HuangDaHui** [comment]
This issue will be resolved after logging out or deleting the session and starting again, and I am not sure what the reason is

**Comment by devlikepro** [comment]
> fter logging out or deleting the session and starting again,

@KKshitiz could you confirm that it helps you too?

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by KKshitiz** [comment]
Yep, in my case the session didn't have enough RAM on the server due to which the headless browser was crashing. Increasing the RAM fixed it. Thanks.

[![patron:ADVANCED](https://img.shields.io/badge/patron-ADVANCED-4cd07d)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
