### ISSUE TITLE
[Feature Request] Update via Dashboard

### ISSUE THREAD

**Issue by daviddr17** [allburov/whatsapp-http-api#454]
Would be a huge time saver to update to a new version via dashboard with keeping all data and without login and update via ssh.

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Yep, that's something we're working on to simplify instillation process!
Subscribe to the issue to get update when it's ready 
https://github.com/devlikeapro/waha/issues/419

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
