### ISSUE TITLE
[Feature Request]Group SendMessage MentionedId

### ISSUE THREAD

**Issue by HuangDaHui** [allburov/whatsapp-http-api#456]
Hi，At present, I see that there is no MentionedIds parameter, which will prevent the implementation of @ group members
I hope to add it to the PLUS version, which should be easy for you, right?

**Comment by devlikepro** [comment]
Hi!
try this one
https://waha.devlike.pro/docs/how-to/send-messages/#mention-contact

```
{
  "session": "default",
  "chatId": "12132132130@c.us",
  "text": "Hi there! @2132132130",
  "mentions": [
    "2132132130@c.us"
  ]
}
```

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
