### ISSUE TITLE
[Feature Request] Repeat all messages from X to Y (or to the latest one) - history sync

### ISSUE THREAD

**Issue by devlikepro** [allburov/whatsapp-http-api#458]
We need to have an endpoint using which we can ask system to "reconcile" all "missed" messages during that period and send it via webhook. 
It'll contain both new and old messages, so it should be a new `message.reconcile` event and we'll send it in the batch in case of huge history

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by HuangDaHui** [comment]
message.reconcile It’s a very good event
Looking forward to using it soon

**Comment by Khosravangroup** [comment]
Yessss we need thisss

Please do it faster 🙏🏻🙏🏻

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Added in `2024.10.9` 

https://waha.devlike.pro/docs/how-to/chats/#get-messages

---

```
GET /api/{session}/chats/{chatId}/messages?limit=10
```

Available parameters:
- `downloadMedia=true` - download media files (images, files) or not
- `chatId=123@c.us` - chatId, phone number 
  - `chatId=all` - get messages from all chats (works on **NOWEB**engine only)
- `limit=100` - limit the number of chats to return
- `offset=0` - skip the number of chats from the start
- `filter.timestamp.lte=1727745026` - filter messages by timestamp less than or equal to `1727745026`
- `filter.timestamp.gte=1727745026` - filter messages by timestamp greater than or equal to `1727745026`
- `filter.fromMe=false` - filter messages from me (by default shows all messages)

Get **10 messages** from 1727745026 timestamp, not from me

```
GET /api/{session}/chats/{chatId}/messages?limit=10&filter.timestamp.gte=1727745026&filter.fromMe=false
```

👉 If you have more messages - you can set `offset` flag 
(increase it always for `limit` amount, even if you get less messages)
```
GET /api/{session}/chats/{chatId}/messages?limit=10&offset=10&filter.timestamp.gte=1727745026&filter.fromMe=false
```


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by gergesh** [comment]
It would be amazing to have a way to fetch directly from WhatsApp's servers, not relying on WAHA's database.
In our usecase, we keep emptying out the WAHA database to save on storage, but then might need it later in the future.
Whatsmeow exposes it with [BuildHistorySyncRequest](https://github.com/tulir/whatsmeow/blob/02c50743e601c797b7b8bf27eba2de1154966cd6/send.go#L544) and baileys with [fetchMessageHistory](https://github.com/WhiskeySockets/Baileys/blob/c037f68c2d6215f4470ed4a5af1ec6c3b8d19fda/src/Socket/messages-recv.ts#L851)

**Comment by devlikepro** [comment]
@gergesh could you create a separate feature request, looks promising 👍 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by gergesh** [comment]
@devlikepro I've created a separate issue #1544
