### ISSUE TITLE
[BUG][WEBJS] - API Requests Time Out after 24 hours for a specific Session.

### ISSUE THREAD

**Issue by RepulsiveStyler** [allburov/whatsapp-http-api#460]
I have 2 sessions running on a single server, the sessions are named 
1. default 
2. session1

After a few hours mostly what I noticed in a timeframe of 24 hours, all API calls to session1 time out and fail but API calls to default session work just fine. 

Workaround - I am able to fix this by stopping and then starting the session back. 

**Version**
[2024.7.7]

**To Reproduce** Steps to reproduce the behavior:
I am not sure but to start first session through swagger named default then another session named session1. 

**Engine** I'm using **WEBJS** engine.

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Hi! 
Consider restarting the sessions every 24 hours (like setting up a cron to restart the container during your timezone midnight).
It'll help with stability a lot.

We'll check what we can do and why the timeout is here - if you can provide the logs it'd be helpful! 
```bash
docker ps # get the container name
docker logs --since 24h {containername}
```
https://waha.devlike.pro/docs/how-to/install/#maintenance

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
https://waha.devlike.pro/docs/how-to/observability/#restart-stop-server
You can use
```
POST /api/server/stop
```
now to restart the server remotely 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
