### ISSUE TITLE
How to send document or PDF file using WhatsApp API?

### ISSUE THREAD

**Issue by smihheemmaanntt** [allburov/whatsapp-http-api#464]
How to Send Document or pdf files?
Here is Showing in ur API doucments only Image:
{
  "chatId": "11111111111@c.us",
  "file": {
    "mimetype": "image/jpeg",
    "filename": "filename.jpg",
    "url": "https://github.com/devlikeapro/waha/raw/core/examples/dev.likeapro.jpg"
  },
  "caption": "string",
  "session": "default"
}

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Hi! Try sending to `POST /api/sendFile` this payload:

```json
{
  "chatId": "123123123@c.us",
  "file": {
    "filename": "example.pdf",
    "url": "https://github.com/devlikeapro/waha/raw/core/examples/example.pdf"
  },
  "caption": "string",
  "session": "default"
}
```

Tested on both WEBJS and NOWEB, it works.
Let me know if it doesn't work for you!

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
