### ISSUE TITLE
Assistance Required for Running WAHA Plus using Static IP on Docker

### ISSUE THREAD

**Issue by smihheemmaanntt** [allburov/whatsapp-http-api#467]
Dear Devlike.pro Team,

I hope this message finds you well.

I am currently working on setting up WAHA Plus and would like to run it using a static IP on Docker. Could you please provide me with the necessary steps or guidance to achieve this setup?

Any assistance or documentation you can provide would be greatly appreciated.

Thank you for your support.

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Hi! 
You need to assign the static IP to any interface (using your Cloud Provider interface) and run the docker container using the one of the method (we recommend using docker-compose)
https://waha.devlike.pro/docs/how-to/install/#docker-compose

Basically docker has nothing to do with static ip, in the suggested configuration it'll listen to all IPs assigned on the host network interfaces.

Let me know if that method doesn't work!

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by smihheemmaanntt** [comment]
its working

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
