### ISSUE TITLE
Assistance Required: Unauthorized Access Error for API [BUG][WEBJS] - 

### ISSUE THREAD

**Issue by smihheemmaanntt** [allburov/whatsapp-http-api#469]
Dear Devlike Team,

I hope this message finds you well.

I am facing an issue with my dashboard, which is accessible via a static IP and works correctly when using another network and Docker Desktop after assigning a static IP. I can send messages without any problems. However, when I attempt to access the API directly via the URL using another network:

http://103.199.214.72:3001/api/sessions/start

I receive the following error message:

json
Copy code
{"statusCode":401,"message":"Unauthorized"}
I am attaching a screenshot of the error for your reference.

Could you please assist me in resolving this issue?

Thank you for your support.

![image](https://github.com/user-attachments/assets/a76671c5-e370-4958-b99b-98f10590ad87)

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by smihheemmaanntt** [comment]
Waiting for your Response

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Hi! Try adding `X-Api-Key` in HTTP header for your request

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
https://waha.devlike.pro/docs/how-to/security/#add-x-api-key-header

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
python example
```python
import requests

headers = {
  'Content-type': 'application/json',
  'X-Api-Key': 'yoursecretkey',
}
requests.get("http://localhost:3000/api/sessions", headers=headers)

```

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
@smihheemmaanntt btw, kindly change your api key from the basic one - you need to change `WHATSAPP_API_KEY` environment variable

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by smihheemmaanntt** [comment]
' Method to start session with the specified waNumber
    Public Sub StartSession(waNumber As String)
        ' Constructing the JSON body
        Dim requestBody As Object = New With {
            .name = waNumber,
            .config = New With {
                .proxy = CType(Nothing, Object),
                .noweb = New With {
                    .store = New With {
                        .enabled = True,
                        .fullSync = False
                    }
                },
                .webhooks = New Object() {
                    New With {
                        .url = "https://webhook.site/11111111-1111-1111-1111-11111111",
                        .events = New String() {"message", "session.status"},
                        .hmac = CType(Nothing, Object),
                        .retries = CType(Nothing, Object),
                        .customHeaders = CType(Nothing, Object)
                    }
                },
                .debug = False
            }
        }

        ' Convert the JSON body to a string
        Dim json As String = JsonConvert.SerializeObject(requestBody)

        ' Sending the POST request
        Dim url As String = BaseUrl & "/api/sessions/start"
        Dim request As HttpWebRequest = CType(WebRequest.Create(url), HttpWebRequest)
        request.Method = "POST"
        request.ContentType = "application/json"
        request.Headers.Add("X-Api-Key", "dckr_pat_6RvH-QAE3fqBkoCbc_sZajml2iA")
        request.ContentLength = Encoding.UTF8.GetByteCount(json)

        Try
            Using streamWriter As New StreamWriter(request.GetRequestStream())
                streamWriter.Write(json)
                streamWriter.Flush()
                streamWriter.Close()
            End Using

            Dim httpResponse As HttpWebResponse = CType(request.GetResponse(), HttpWebResponse)

            Using streamReader As New StreamReader(httpResponse.GetResponseStream())
                Dim result As String = streamReader.ReadToEnd()
                ' Parse the response JSON
                Dim responseBody = JsonConvert.DeserializeObject(Of Dictionary(Of String, Object))(result)
                ' Handle the response status
                Dim status As String = responseBody("status").ToString()
                Select Case status
                    Case "STARTING"
                        Form1.lblMSg.ForeColor = Color.Green
                        Form1.lblMSg.Text = "Session started."
                        Form1.btnGenToken.Text = "Stop"
                        Form1.txtWANumber.Enabled = False
                    Case "FAILED"
                        Form1.lblMSg.Text = "Status: FAILED"
                    Case "WORKING"
                        Form1.lblMSg.Text = "Status: WORKING"
                    Case "SCAN_QR_CODE"
                        Form1.lblMSg.Text = "Status: SCAN_QR_CODE"
                    Case "STOPPED"
                        Form1.lblMSg.Text = "Status: STOPPED"
                    Case Else
                        Form1.lblMSg.Text = "Unknown Status"
                End Select
            End Using

        Catch ex As WebException
            ' Handle WebException
            Dim errorResponse As String = String.Empty
            If ex.Response IsNot Nothing Then
                Using errorStream = ex.Response.GetResponseStream()
                    If errorStream IsNot Nothing Then
                        Using reader As New StreamReader(errorStream)
                            errorResponse = reader.ReadToEnd()
                        End Using
                    End If
                End Using

                Dim errorDetails As Dictionary(Of String, Object) = JsonConvert.DeserializeObject(Of Dictionary(Of String, Object))(errorResponse)
                If errorDetails.ContainsKey("message") AndAlso errorDetails("message").ToString().Contains("already started") Then
                    Form1.lblMSg.ForeColor = Color.Green
                    Form1.lblMSg.Text = "Session started."
                    Form1.btnGenToken.Text = "Stop"
                    Form1.txtWANumber.Enabled = False
                Else
                    MessageBox.Show("WebException: " & ex.Message & vbCrLf & "Response: " & errorResponse)
                End If
            Else
                MessageBox.Show("WebException: " & ex.Message)
            End If
        Catch ex As Exception
            ' Handle other exceptions
            MessageBox.Show("Exception: " & ex.Message)
        End Try
    End Sub
    **I am Using this, But Getting Same Error**

**Comment by devlikepro** [comment]
You need to set it to YOUR API KEY, not docker key :)
```
X-Api-Key: 321
``` 
Sorry for not being clear here

This one, you can (and should) change it to random one (not docker key)
https://github.com/devlikeapro/waha/blob/core/docker-compose.yaml#L68

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
```
request.Headers.Add("X-Api-Key", "321")
```

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by smihheemmaanntt** [comment]
Perfectly works thank you so much

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by smihheemmaanntt** [comment]
Public Sub LoadImageFromUrl(imagePath As String, pictureBox As PictureBox)
        Dim imageUrl As String = BaseUrl & "/api/" & AccessToken & "/" & imagePath & "?format=image"
        Try
            ' Load the image from the URL
            Dim webClient As New WebClient()
            webClient.Headers.Add("X-Api-Key", "321")
            Dim imageBytes As Byte() = webClient.DownloadData(imageUrl)

            ' Convert the byte array to an image
            Using memoryStream As New MemoryStream(imageBytes)
                Dim image As Image = Image.FromStream(memoryStream)
                pictureBox.Image = image
                pictureBox.SizeMode = PictureBoxSizeMode.Zoom
            End Using
        Catch ex As Exception
            MessageBox.Show("Error: " & ex.Message)
        End Try
    End Sub
**I am Unable to Genrate QR Code whats the Mistake in above vb.net code, will you please tell me?**

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
sorry, not familiar with vb.net. Try using swagger to test if the endpoint works correctly 
https://waha.devlike.pro/docs/how-to/swagger/

If it does - you need to change something in the code

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by smihheemmaanntt** [comment]
I wana Send Poll but error Says :
{
  "statusCode": 422,
  "message": "The method is not implemented by the engine.",
  "error": "Unprocessable Entity"
}

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Are you using WEBJS engine? Because polls are available only in NOWEB right now
https://waha.devlike.pro/docs/engines/noweb/
![image](https://github.com/user-attachments/assets/3474fd94-a184-4d9e-857c-36ae9ec483c8)


Comment +1 in https://github.com/devlikeapro/waha/issues/189 to get a notification when it's ready in WEBJS!

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
