### ISSUE TITLE
[BUG][WEBJS] - Server down

### ISSUE THREAD

**Issue by daviddr17** [allburov/whatsapp-http-api#471]
I am running waha-plus on google cloud instance and after updating to v 7.6 and even 7.7 the server stops running after a while. Sometimes a few hours, sometimes one day.

I am not an expert in this area, so i just made it work, but now helpless why its working for a few hours and then the server stops running.

Thanks in advance anybody.

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by daviddr17** [comment]
switched to contebo, now its working

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Hi! Thank you for sharing the feeback, it could be some issue from WA side when they detect cloud IP and force stop the session.
If it happens again - the detailed logs will help here :pray: 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
