### ISSUE TITLE
[BUG][WEBJS] -  Please help the problem with sessions 

### ISSUE THREAD

**Issue by D-erhan** [allburov/whatsapp-http-api#474]
Hello, I ran into such a problem that, when updating the docker, the sessions we're saved by the authorization for them flew
off what to do ?

docker ru -v `pwd`/.sessions:/ep/.sessions -p 3006:3000/tcp -e WAHA_DASHBOARD_USERNAME=waha
launched in this format
![изображение_2024-08-05_121526690](https://github.com/user-attachments/assets/fdf07a41-d977-498d-a02b-05a96c5c6376)

it turns out that it was necessary to launch them)

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Probably you already have found it, but try adding `WHATSAPP_RESTART_ALL_SESSIONS=True`
https://waha.devlike.pro/docs/how-to/config/#sessions

Here's the default configuration we recommend running the project with in production: https://github.com/devlikeapro/waha/blob/core/docker-compose.yaml#L53-L190

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
