### ISSUE TITLE
[BUG][NOWEB] - GET /api/contacts/all returns contacts only from connected phase, but doesn't update it after

### ISSUE THREAD

**Issue by devlikepro** [allburov/whatsapp-http-api#475]
[BUG][NOWEB] - GET /api/contacts/all returns contacts only from connected phase, but doesn't update it after

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by sg957** [comment]
+1

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Tested on both WA Business and regular one - works fine (adding and editing)
The contact has to have WA and you need to open the app on mobile so it gets synced.

Let me know if there's additional context!

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Yes, looks like there's a required action for now - **you need to open the WA App on mobile phone** to get contacts synced

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
