### ISSUE TITLE
[BUG][WEBJS] - unable to recieve any qr code for scanning after stopping default session once

### ISSUE THREAD

**Issue by shubhsardana29** [allburov/whatsapp-http-api#476]
**Describe the bug**

After stopping the default session, no QR code is generated for scanning upon trying to restart or initiate a new session.

**Version**

```json
{
  "version": "2024.7.7",
  "engine": "WEBJS",
  "tier": "PLUS",
  "browser": "/usr/bin/google-chrome-stable"
}
```

**Screenshots**

<img width="1424" alt="Screenshot 2024-08-05 at 5 46 37 PM" src="https://github.com/user-attachments/assets/e43a7373-9010-479b-bf35-8ac0ad6b4435">

**Additional context**

> Add any other context about the problem here.

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Hi! What service are you using or it's local laptop?
Could you try to completely remove the session and start again?
Probably WA start blocking some services, could you try to run it on different cloud?


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Could you also share some logs from docker container, from the moment right after you scan QR and after few minutes, so we can check the issue :pray: 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by shubhsardana29** [comment]
it worked when i completely removed the session and start again

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Looks likely there was some damaged chrome files that it didn't handle well, I'm glad restart helped!

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
