### ISSUE TITLE
[BUG][NOWEB] - /api/reply - Send Message Error

### ISSUE THREAD

**Issue by HuangDaHui** [allburov/whatsapp-http-api#477]
{"statusCode":500,"timestamp":"2024-08-06T04:18:26.881Z","exception":{"stack":"TypeError: Cannot read properties of undefined (reading 'match')\n    at extractUrlFromText (/app/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:39:66)\n    at generateLinkPreviewIfRequired (/app/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:42:48)\n    at generateWAMessageContent (/app/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:249:71)\n    at generateWAMessage (/app/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:526:102)\n    at Object.sendMessage (/app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:628:69)\n    at WhatsappSessionNoWebPlus.reply (/app/dist/core/engines/noweb/session.noweb.core.js:406:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","message":"Cannot read properties of undefined (reading 'match')","name":"TypeError"},"request":{"path":"/api/reply","method":"POST","body":{"session":"session_d3lfcm","reply_to":"false_85254942545@c.us_3EB0ED72B669F44C5EE95A","chatId":"xxxxx@c.us","caption":"xxxxxx","longitude":0,"latitude":0,"file":{"url":"xxxxx","fileName":"xxxxxx ","mimetype":"image/png"}},"query":{}},"version":{"version":"2024.7.7","engine":"NOWEB","tier":"PLUS","browser":"/usr/bin/chromium"}}
This error occasionally occurs when sending messages

**Comment by devlikepro** [comment]
Hi! Could you share the `caption` field here or in  waha@devlike.pro :pray: 
and may be the example of the mesage you're replying to

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by HuangDaHui** [comment]
> Hi! Could you share the `caption` field here or in [waha@devlike.pro](mailto:waha@devlike.pro) 🙏 and may be the example of the mesage you're replying to
> 
> [![patron:PRO](https://camo.githubusercontent.com/53c8c17e54974d30f0938bed9c2aa4e5c7dc7bc776296a6776840124e4086a04/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

```json
{
  "request": {
    "path": "/api/reply",
    "method": "POST",
    "body": {
      "session": "session_d3lfcm",
      "reply_to": "false_xxx@c.us_3EB0ED72B669F44C5EE95A",
      "chatId": "xxxx@c.us",
      "caption": "基本計劃就足夠\n- 可接駁1個WhatsApp號碼\n- 已包括2個user login（可增加至total 5個，$300/每月/每位）\n\n月費$560，三個月會係$1680 ",
      "longitude": 0,
      "latitude": 0,
      "file": {
        "url": "https://xxxx.png",
        "fileName": "基本計劃就足夠\n- 可接駁1個WhatsApp號碼\n- 已包括2個user login（可增加至total 5個，$300/每月/每位）\n\n月費$560，三個月會係$1680 ",
        "mimetype": "image/png"
      }
    },
    "query": {}
  },
  "version": {
    "version": "2024.7.7",
    "engine": "NOWEB",
    "tier": "PLUS",
    "browser": "/usr/bin/chromium"
  }
}
```
Hi！This is request json
Can you see if it's helpful

**Comment by devlikepro** [comment]
Are you trying to reply with media message? It's not possible yet  https://github.com/devlikeapro/waha/issues/503

Try adding a `text` field instead
```json
{
  "session": "session_d3lfcm",
  "reply_to": "false_xxx@c.us_3EB0ED72B669F44C5EE95A",
  "chatId": "xxxx@c.us",
  "text": "基本計劃就足夠\n- 可接駁1個WhatsApp號碼\n- 已包括2個user login（可增加至total 5個，$300/每月/每位）\n\n月費$560，三個月會係$1680 ",
}
```

Comment with +1 to get update when "reply a media" is ready! https://github.com/devlikeapro/waha/issues/503



[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
