### ISSUE TITLE
[BUG][WEBJS] - If my account is blocked, will the webhook return any information to remind me?

### ISSUE THREAD

**Issue by TimousFly** [allburov/whatsapp-http-api#478]
If my account is blocked, will the webhook return any information to remind me?

**Comment by devlikepro** [comment]
You'll get `session.status` with `FAILED` status

https://waha.devlike.pro/docs/how-to/sessions/#sessionstatus



[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
