### ISSUE TITLE
[BUG][WEBJS] -  When sending a file, the file name will be url encoded.

### ISSUE THREAD

**Issue by HuangDaHui** [allburov/whatsapp-http-api#481]
![0c4a2c103cadb49148130dc221644b0](https://github.com/user-attachments/assets/4dfed37a-a78e-43db-81cd-c1635bf4158c)
{
  "chatId": "xxxx@c.us",
  "file": {
    "url": "https://xxx/rdstorage/Dumbchat/TC001/20240808/Chat/测试-2(2).xls",
    "fileName": "测试-2.xls",
    "mimetype": "application/vnd.ms-excel"
  },
  "caption": "测试-2.xls",
  "session": "408320"
}

**Comment by devlikepro** [comment]
could you try lowercase for `fileName` field?
>     "filename": "filename.jpg",

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
https://waha.devlike.pro/swagger/#/chatting/ChattingController_sendFile

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
it gets it from `url` if there's no `filename` field, and you're using `fileName` which is not that one, keys are case sensitive

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by HuangDaHui** [comment]
> it gets it from `url` if there's no `filename` field, and you're using `fileName` which is not that one, keys are case sensitive
> 
> [![patron:PRO](https://camo.githubusercontent.com/53c8c17e54974d30f0938bed9c2aa4e5c7dc7bc776296a6776840124e4086a04/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)


I get it, thank
