### ISSUE TITLE
[Feature Request] Add - GET /api/{session}/chats/{chatId}/messages/{messageId}

### ISSUE THREAD

**Issue by HuangDaHui** [allburov/whatsapp-http-api#484]
/api/{session}/chats/{chatId}/messages/{messageId}?downloadMedia=true

If an attachment fails to download, I can obtain the attachment separately without using /api/{session}/chats/{chatId}/messages
This will reduce the load on the server

**Comment by devlikepro** [comment]
makes sense, we'll check that! 
Do you use NOWEB, right?

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by HuangDaHui** [comment]
> makes sense, we'll check that! Do you use NOWEB, right?
> 
> [![patron:PRO](https://camo.githubusercontent.com/53c8c17e54974d30f0938bed9c2aa4e5c7dc7bc776296a6776840124e4086a04/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

NOWEB is used more, WEBJS is also used, because I think WEBJS can reduce the risk of being blocked
But this function is applicable to both NOWEB and WEBJS. If I have this function, I may not actively download attachments anymore. I will only download them when I need to view them.

**Comment by HuangDaHui** [comment]
> makes sense, we'll check that! Do you use NOWEB, right?
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

Hi, if I buy the PRO version, will this feature be updated soon? I really need this feature, if possible I will buy the PRO version

**Comment by devlikepro** [comment]
Hi! We're planning to work on /messages improvements (including this one) in October.


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by HuangDaHui** [comment]
> Hi! We're planning to work on /messages improvements (including this one) in October.
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

OK, looking forward to your updates, thank you

**Comment by devlikepro** [comment]
related https://github.com/devlikeapro/waha/issues/159

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Added in `2024.10.9`

https://waha.devlike.pro/docs/how-to/chats/#get-message-by-id

----

### Get message by id
Get message by id 
```
GET /api/{session}/chats/{chatId}/messages/{messageId}?downloadMedia=true
```

```json
{
    "id": "false_123123@c.us_AAAAAA",
    "timestamp": 1727745026,
    "from": "123123@c.us",
    "fromMe": false,
    "body": "I'm good!",
    "hasMedia": false,
    "ack": 3,
    "ackName": "READ",
    "replyTo": null,
    "_data": {
        ... // Raw Engine Data
    }
}
```

- `chatId` - in format `123123123@c.us`
- `messageId` - must be in format `{true|false}_213213@c.us_AAAAAAA`)
- `downloadMedia` - download media files (images, files) or not


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
>  buy the PRO version

Feel free to do that now :laughing: :+1: 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
