### ISSUE TITLE
[BUG][NOWEB] - Different behaviour in NOWEB and WEBJS

### ISSUE THREAD

**Issue by ldubrois** [allburov/whatsapp-http-api#485]
**Describe the bug**

I was using WEBJS as engine.

To mark the message as seen I was always providing the Participant value even in the 1 to 1 conversation. It was working well.

I moved to NOWEB engine, and now the mark does nothing. I found that I have to set null to Participant in this case to make the mark seen to work.

**Version**

```json

  "version": "2024.7.7",
  "engine": "NOWEB",
  "tier": "PLUS",
  "browser": "/usr/bin/chromium"
}
```

**To Reproduce** Steps to reproduce the behavior:

Try to mark a message as seen in a chat and providing the Participant using the From value of the payload.

**Expected behavior**

The API should beahve the same, no matter the engine (NOWEB or WEBJS) 

**Engine** I'm using **NOWEB** engine.

**Comment by devlikepro** [comment]
Hi! Could you add example for the payload please for both engines?

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by ldubrois** [comment]
Hi

At the time, I did not found documentation on the sendSeen, so I based my code on the swagger sample.

 It was exactly the one describe in the swagger. 

In WEBJS I was posting :

```
{
  "chatId": "11111111111@c.us",
  "messageId": "false_11111111111@c.us_AAAAAAAAAAAAAAAAAAAA",
  "participant": "11111111111@c.us",
  "session": "default"
}
```

When i switched to NOWEB, I noticed that the message were no longer mark as seen. Looking at the log, Isaw the POST, and the API was returning a success HTTP Code.

By looking at some closed issues on the repo, I found a comment indicating that participant should be filled only when the conversation is in a group, so I tried in swagger :

```
{
  "chatId": "11111111111@c.us",
  "messageId": "false_11111111111@c.us_AAAAAAAAAAAAAAAAAAAA",
  "session": "default"
}
```

It make my message as seen. 

In my code, it would require some time debug to confirm, but I think my payload is more like this (and it is working also).

```
{
  "chatId": "11111111111@c.us",
  "messageId": "false_11111111111@c.us_AAAAAAAAAAAAAAAAAAAA",
  "participant": null,
  "session": "default"
}
```

**Comment by devlikepro** [comment]
got it, thank you for the detailed explanation!
We'll adjust the swagger and add the doc, weird we don't have it yet.

This is the payload you need to use for chats (not groups) for both WEBJS and NOWEB (no `participant` field or `null`)
```json
{
  "chatId": "11111111111@c.us",
  "messageId": "false_11111111111@c.us_AAAAAAAAAAAAAAAAAAAA",
  "session": "default"
}
```

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
