### ISSUE TITLE
[BUG][WEBJS] - /api/{session}/chats?limit=100&offset=0

### ISSUE THREAD

**Issue by TimousFly** [allburov/whatsapp-http-api#486]
response  
{
  "statusCode": 500,
  "timestamp": "2024-08-09T08:32:10.144Z",
  "exception": {
    "stack": "Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'getChats')\n    at pptr://__puppeteer_evaluation_script__:2:38\n    at ExecutionContext._ExecutionContext_evaluate (/app/node_modules/whatsapp-web.js/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:229:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ExecutionContext.evaluate (/app/node_modules/whatsapp-web.js/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)\n    at async WebjsClient.getChats2 (/app/dist/core/engines/webjs/WebjsClient.js:19:23)\n    at async WebjsClient.getChats (/app/dist/core/engines/webjs/WebjsClient.js:16:16)",
    "message": "Evaluation failed: TypeError: Cannot read properties of undefined (reading 'getChats')\n    at pptr://__puppeteer_evaluation_script__:2:38",
    "name": "Error"
  },
  "request": {
    "path": "/api/1821820790430871552/chats?limit=100&offset=0",
    "method": "GET",
    "body": {},
    "query": {
      "limit": "100",
      "offset": "0"
    }
  },
  "version": {
    "version": "2024.8.2",
    "engine": "WEBJS",
    "tier": "PLUS",
    "browser": "/usr/bin/google-chrome-stable"
  }
}

**Comment by devlikepro** [comment]
Could you try to stop and start the session again? Looks like it's in STOPPED or FAILED status
We need to add validation for that to have a better response :thinking: 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by TimousFly** [comment]
I'm sure my session is working here

<img width="1280" alt="error" src="https://github.com/user-attachments/assets/68da5846-c18a-4435-9882-d73da90f7619">

I am true that my account is already working. My account has a lot of chats data, and I am not sure if this is the reason for it

**Comment by TimousFly** [comment]
> Could you try to stop and start the session again? Looks like it's in STOPPED or FAILED status We need to add validation for that to have a better response 🤔
> 
> [![patron:PRO](https://camo.githubusercontent.com/53c8c17e54974d30f0938bed9c2aa4e5c7dc7bc776296a6776840124e4086a04/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

I have no problem using another account, but if this account does not have a limit on the number of records, it will still be blocked. So I tried using limit and it was like reporting an error

**Comment by devlikepro** [comment]
Does it work right after restart or never?
May be you could check docker logs if there's any errors when you start THIS account (with many chats) in a dedicated container :pray: It could be the issue, but we need to have more info


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
@TimousFly hi! Could you try 2024.8.4 :pray: :crossed_fingers: 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
