### ISSUE TITLE
[Feature Request] - Do not restart STOPPED sessions when WHATSAPP_RESTART_ALL_SESSIONS=True (keep track of session status)

### ISSUE THREAD

**Issue by HuangDaHui** [allburov/whatsapp-http-api#491]
After stopping sessions, it will automatically change to SCAN_QR_CODE after a period of time. Can it remain stopped?

**Comment by devlikepro** [comment]
@HuangDaHui hi! Could it because of the container restart AND `WHATSAPP_RESTART_ALL_SESSIONS=True` flag enabled?
https://waha.devlike.pro/docs/how-to/config/#sessions
Because it does restarts all sessions, including `STOPPED` one. 

If it happens even without container restart - this is a bug, please let us know if it's the case!

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
>  it does restarts all sessions, including STOPPED one.

We could track session status and run only working or failed one tho :thinking: 

Before making it possible we need to handle workers approach as well, so if one shares a single store across multiple workers we restart the session only on the previous worker

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by HuangDaHui** [comment]
> WHATSAPP_RESTART_ALL_SESSIONS=True


Yes, I set this variable to true, WHATSAPP_RESTART_ALL_SESSIONS=True
I now think false would be better, thanks for your answer

**Comment by devlikepro** [comment]
> I now think false would be better

But it WILL NOT start sessions at all after the container restart. WAHA doesn't start even `WORKING` one by default, all sessions will be `STOPPED`
So when it happens during the night you need to either make it manually or write a script.

Let's keep the issue open, I think we could handle it on the project side, keeping the status and not restarting STOPPED one looks like the best solution 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by HuangDaHui** [comment]
Yes, I agree, looking forward to your updates

**Comment by devlikepro** [comment]
**2024.10.5** If you remove now `WHATSAPP_RESTART_ALL_SESSIONS=True` - WAHA remembers the session status and restore it on restart (meaning it will not re-run `STOPPED` sessions)

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by BavariaAnde** [comment]
Hi @devlikepro 
I'm still experiencing an issue with WAHA: when I restart the Docker host and the container comes back up, the "default" session remains in the "stopped" state and does not start automatically. For reference, I have set the following environment variables in my .env file:

WAHA_RESTART_ALL_SESSIONS=True

WHATSAPP_RESTART_ALL_SESSIONS=True

WAHA_AUTO_START_DELAY_SECONDS=0

Is there something else I need to configure to ensure the session restarts automatically after a container restart? Any guidance would be appreciated. Thank you!

**Comment by devlikepro** [comment]
@BavariaAnde `WHATSAPP_RESTART_ALL_SESSIONS` doesn't work in waha core, you need to start it manually and provide session config as well

You can find details in https://github.com/devlikeapro/waha/issues/741#issuecomment-2600774278

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
