### ISSUE TITLE
[Feature Request] When a new version is updated, how can I save my account without having to scan the code again

### ISSUE THREAD

**Issue by CapLuo** [allburov/whatsapp-http-api#492]
Every time I update the version, I need to scan the QR code of my 20 accounts to log in to the new docker again. Is there any solution that can be similar to hot update?

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Hi!
Could you share the the command how you start the server?

Here's recommended parameters
https://waha.devlike.pro/docs/how-to/install/
```bash
docker run -d \
    --restart=always \
    --name waha \
    -p 3000:3000/tcp \
    -v ./.sessions:/app/.sessions \
    -v ./.media:/app/.media \
    --env WHATSAPP_API_KEY=321 \
    --env WAHA_DASHBOARD_USERNAME=waha \
    --env WAHA_DASHBOARD_PASSWORD=waha \
    --env WAHA_LOG_FORMAT=PRETTY \
    --env WAHA_LOG_LEVEL=info \
    --env WHATSAPP_DEFAULT_ENGINE=WEBJS \
    --env WHATSAPP_RESTART_ALL_SESSIONS=True \
    --env WAHA_PRINT_QR=False \
    --env WHATSAPP_FILES_LIFETIME=0 \
    --env WHATSAPP_FILES_FOLDER=/app/.media \
    devlikeapro/waha-plus:latest
```

`WHATSAPP_RESTART_ALL_SESSIONS` and ` -v ./.sessions:/app/.sessions` are crucial to avoid rescanning QR

Also feel free to ask in discord, did you get the link in https://portal.devlike.pro?


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by CapLuo** [comment]
ok thanks

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
