### ISSUE TITLE
[BUG] - security environment variables ignored

### ISSUE THREAD

**Issue by maxbellec** [allburov/whatsapp-http-api#493]
**Describe the bug**

I simply pulled the latest image and fired docker-compose, with the default file, and put these env variables. Dashboard is fully open API is not password-protected.

```
     environment:
      #
      # Common
      #
      # If you know the right URL, you can use it here.
      # Use any port in WHATSAPP_API_PORT and domain in WHATSAPP_API_HOSTNAME
      # https://waha.devlike.pro/docs/how-to/config/#common
      #- WHATSAPP_API_PORT=3000
      #- WHATSAPP_API_HOSTNAME=localhost

      #
      # Security
      #
      # https://waha.devlike.pro/docs/how-to/security/
      #
      - WHATSAPP_API_KEY=xxxxxxxxxxxxxxxxxxxxxxx
      - WAHA_DASHBOARD_USERNAME=xxxxxx
      - WAHA_DASHBOARD_PASSWORD=xxxxxx
```

**Version**

```json
{"version":"2024.8.2","engine":"WEBJS","tier":"CORE","browser":"/usr/bin/chromium"}
```

**To Reproduce** Steps to reproduce the behavior:

1. Get default docker-compose.yml file
2. Add security env variables
3. `docker compose up -d`
4. go to :3000/, dashboard is available, swagger is available, no API KEY works

**Expected behavior**

- dashboard is password protected
- api is password (token) protected

**Engine** I'm using **WEBJS** engine.

**Docker Logs**

[See logs](https://pastebin.com/zmTUqiLR)

**Comment by maxbellec** [comment]
I have checked that the env variables are correctly set:

```
$ docker exec -it waha-waha-1 /bin/sh
# echo $WHATSAPP_API_KEY
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

**Comment by maxbellec** [comment]
same issue with simply

```
docker run -it --rm -p 3000:3000/tcp --name waha -e WHATSAPP_API_KEY=XXX  devlikeapro/waha
```

I have also tried a few older versions, with the same issue. I must be doing something stupid, but I can't understand what.

**Comment by maxbellec** [comment]
OK security options are for plus only, got it

**Comment by devlikepro** [comment]
Yes, that's correct - [**🔒 Security**](https://waha.devlike.pro/docs/how-to/security/) options are available in [WAHA Plus](https://waha.devlike.pro/docs/how-to/plus-version/#plus) version only.

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
