### ISSUE TITLE
[Feature Request] - Mark chat as unread

### ISSUE THREAD

**Issue by davidgabbay** [allburov/whatsapp-http-api#498]
im missing the "mark as unread"
its very helpful when the bot answers customer  automatically - a greetings massage, than automatically the chat "unread massage" sign dissapears. 

However still a human should read the customers message
By marking the chat as "unread" the worker understands it was still not processed by human.

**Comment by devlikepro** [comment]
Hi! Good suggestion, we will add it!

Right now we're using Labels for that right now for WA Business accounts for the same purpose

https://waha.devlike.pro/docs/how-to/labels/

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by davidgabbay** [comment]
The labels is a good feature, as far i understand its for different purpose.
The unread sign is being outomatically removered when you read the message, furthermore the common whatsapp web does not let you change Labels.

**Comment by ManuelW77** [comment]
Oh yes, i need this too. I let translate speech to text automatically and wenn waha sends the text message, the chat is also marked as read. So i need that feature to mark the Chat unread again.

**Comment by devlikepro** [comment]
Added in `2024.10.9`

https://waha.devlike.pro/docs/how-to/chats/#unread-chat

----

### Unread chat
Mark chat as unread

```bash
POST /api/{session}/chats/{chatId}/unread
```




[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by Alimadcorp** [comment]
ooh this is cool , i was looking for it, thanks :)
