### ISSUE TITLE
Send messages to a group

### ISSUE THREAD

**Issue by martinmineo** [allburov/whatsapp-http-api#50]
Is it possible to send a message to a group? 
I couldn't find it and I would find it very useful

I would use it by providing the group name and the message to send

**Comment by allburov** [comment]
Hi! 
We'll add endpoints to get groups in https://github.com/devlikeapro/whatsapp-http-api/issues/34

Meanwhile you may receive [incoming messages via webhook](https://waha.devlike.pro/docs/how-to/receive-messages/) and then use `from` field from the payload [to send message](https://waha.devlike.pro/docs/how-to/send-messages/#send-text-imagesversionscorepng-imagesversionspluspng)  - use  Group id from the messages from webhook to send messages to groups!
