### ISSUE TITLE
PRO Plan

### ISSUE THREAD

**Issue by yesbhautik** [allburov/whatsapp-http-api#502]
In your website it's showing we don’t have to pay per month for PRO plan, and when i am going to pay then it showing like pay per month.

**Comment by devlikepro** [comment]
I hope the FAQ will answer your question!
[I want to purchase WAHA Plus (WAHA Pro), is it one time purchase?](https://waha.devlike.pro/docs/overview/faq/#i-want-to-purchase-waha-plus-waha-pro-is-it-one-time-purchase)

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
You can pay for a month and then unsubscribe and only subscribe back if you need to install the project on a new server or get an update - that's fine!

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
All your installed servers will continue to work, no license expiration in the code! Only natural WA backward incompatible changes :( 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Another way to save money would be to support the project for a year using crypto https://waha.devlike.pro/pricing/#crypto

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
