### ISSUE TITLE
[Feature Request] Reply a media - NOWEB, WEBJS

### ISSUE THREAD

**Issue by ShayanShahzad** [allburov/whatsapp-http-api#503]
Hi kindly make a method so we can send an media as a reply message as well

**Comment by devlikepro** [comment]
yep, good idea, will do!

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
You can use `reply_to` with almost any message types now!
https://waha.devlike.pro/docs/how-to/send-messages/#reply_to

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
