### ISSUE TITLE
[BUG][NOWEB] - It seems that the sticker cannot be downloaded

### ISSUE THREAD

**Issue by HuangDaHui** [allburov/whatsapp-http-api#504]
/api/{sessions}/chats/{chatId}/messages?downloadMedia=true&limit=3
Other attachments will have media objects
 {
    "id": "false_1xxxx@g.us_3EB03806238F0A1DB1181E",
    "timestamp": 1722495124,
    "from": "xxxx@g.us",
    "fromMe": false,
    "hasMedia": false,
    "ack": null,
    "ackName": "UNKNOWN",
    "_data": {
      "key": {
        "remoteJid": "xxxx@g.us",
        "fromMe": false,
        "id": "3EB03806238F0A1DB1181E"
      },
      "message": {
        "stickerMessage": {
          "url": "https://web.whatsapp.net",
          "fileSha256": {
            "type": "Buffer",
            "data": "iJtV6ASPi8ZWXgZTX/BCRRt0MxdfmzMhEnI1yK9fi40="
          },
          "fileEncSha256": {
            "type": "Buffer",
            "data": "r8eN7ZiIQJsrCEbhLEsfS7U1ddnYqyvFaTE3Ftl1rzk="
          },
          "mediaKey": {
            "type": "Buffer",
            "data": "msb0YszHd/HUYtdsjeKq/6WHxfR+mVhePDgYzGhfiu4="
          },
          "mimetype": "image/webp",
          "height": 64,
          "width": 64,
          "directPath": "/v/t62.15575-24/26138918_460452883479079_1296719339533067718_n.enc?ccb=11-4&oh=01_Q5AaICAOTmAKv1jVhgNq80cBNU1mKBS3Ud1tSjJTyfjz1lCN&oe=66D25C82&_nc_sid=5e03e0",
          "fileLength": 102028,
          "mediaKeyTimestamp": 1722330370,
          "firstFrameLength": 11152,
          "isAnimated": true,
          "stickerSentTs": 1722495124000,
          "isAvatar": false,
          "isAiSticker": false,
          "isLottie": false
        }
      },
      "messageTimestamp": 1722495124,
      "participant": "xxx@s.whatsapp.net",
      "mediaData": {
        "localPath": "Media/WhatsApp Stickers/STK-20240801-WA0015.webp"
      },
      "reportingTokenInfo": {
        "reportingTag": {
          "type": "Buffer",
          "data": "AaG1pfDVzwEi2Z5+TOU2YA=="
        }
      }
    }
  }

**Comment by devlikepro** [comment]
Hi! 
Looks like it happens when the participant uses web.whatsapp.com and send stickers from these sections
![image](https://github.com/user-attachments/assets/b01c8503-acc6-44fe-908f-98927d974fec)





[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Hi! Fixed in `2024.8.4` :crossed_fingers: 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
