### ISSUE TITLE
Memory utilization is going up continusly

### ISSUE THREAD

**Issue by martinmineo** [allburov/whatsapp-http-api#51]
I was checking the memory graphs in AWS where I have deployed WAHA and I found that it's consuming more memory day after day

Are you aware of that? Is there something I can do to free up some memory?

![Screenshot 2023-02-01 at 17 04 52](https://user-images.githubusercontent.com/11985773/216151541-6ed0ea0f-a4ab-4d5a-ac38-521842f8c1ac.png)

The peak down you see on 1/28 is because the session was closed.

**Comment by allburov** [comment]
Hi! We'll look at this a bit latter. 
We have plans to add less memory consuming engine.

Meanwhile, could you run `top` comand inside the container and then do it after 2 days? Just to look where memory goes
```
docker exec -it whatsapp-http-api /bin/bash
top
```

**Comment by allburov** [comment]
Never mind, it's chromium's issue 99% https://github.com/puppeteer/puppeteer/issues/5893
We'll add non-chrome based engine soon ~hopefully~.

**Comment by allburov** [comment]
Added `NOWEB` (no chrome required) engine in the latest release!
 https://waha.devlike.pro/docs/how-to/engines/
