### ISSUE TITLE
[BUG][WEBJS] -  Docker container was shut down

### ISSUE THREAD

**Issue by D-erhan** [allburov/whatsapp-http-api#515]
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
error Command failed with exit code 134.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Good afternoon, I encountered a problem where a Docker container was shut down with this error. How can I allocate more memory

**Comment by devlikepro** [comment]
Hi! Could you help us identify the problem pls?
1. What WAHA version do you use? You can get it in http://localhost:3000/api/version
2. What VPS and OS are you using?
3. Are you using official docker images, like `devlikeapro/waha[-plus]`  one?
4. how many memory do you have free in the server?
5. After what time does it happen, like right after docker starts or after N minutes?
6. How many session do you run?


looks like some nodejs problem

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
We have this workaround for some memory issues
https://github.com/devlikeapro/waha/blob/core/Dockerfile#L41-L43

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by D-erhan** [comment]
1.WAHA 8.1 
2.DEBAIN
3.WAHAPLUS
4.123gb
5.a month after launch
6.24 session

**Comment by devlikepro** [comment]
> 5.a month after launch

Do you mean the container had 1 month uptime? 

Do you use WEBJS engine, right?

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by D-erhan** [comment]
Yes

**Comment by devlikepro** [comment]
Try adding 
```bash
docker run -v NODE_OPTIONS="--max-old-space-size=32768" ...
```
to your docker run or docker-compose file, so it overrides the container default 16GB one. 


It's good to restart the container time to time, especially if your clients in the same timezone, puppeteer has too much memory leaks, could be this one.

We also have added `POST /api/server/stop` endpoint in `2024.9.1` (will release it soon) which you can call and docker will restart the container (if you run it with `--restart=always`) so consider calling this one like every week or so.

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Let's see if it happens again with 32Gb and restart, just leave a comment here, no needs to open a new issue in that case! :crossed_fingers: 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
