### ISSUE TITLE
Waha Plus - session crashed, unable to restart

### ISSUE THREAD

**Issue by behind24proxies** [allburov/whatsapp-http-api#52]
hi , I have 5 numbers running on waha plus
one number has high traffic (5 messages per minute inbound and outbound).
the session crashed a few minutes ago (I could not take a screenshot , [infinite spinning loop on swagger ui]).
![image](https://user-images.githubusercontent.com/96356684/217276980-a32bb173-4712-4cdf-b53c-4af5308843ed.png)

so I decided to stop it and re-start it (with the same name) , and this is what it returns when I request a screenshot
![image](https://user-images.githubusercontent.com/96356684/217276571-4936505b-37fd-4d3e-8ecf-961db7b53d88.png)
so , the whatsapp spinner keeps spinning in an infinite loop , so it does not return any QR code (it's been like this for the past 20-30 mins) 

note 1 : 
the session is still "starting" 
![image](https://user-images.githubusercontent.com/96356684/217277449-0cf4cae2-add7-42ce-b637-f1964ff4f000.png)

note 2: 
I created a new session with a different name , and everything works perfectly fine , so the problem here is that if the session crashes, I cannot restart it with the same name 

note 3 : 
I have the plus version , so ,I can store sessions.
this is the command that I ran to create the docker container

`docker run -it -v `pwd`/.sessions:/app/.sessions  -e WHATSAPP_HOOK_EVENTS=message -e WHATSAPP_HOOK_URL=http://XXX.XXX.XXX:XXXXX/api/post/ -it --rm -p XXXXX:3000/tcp  --name docker_tmp_plus_kill devlikeapro/whatsapp-http-api-plus`

**Comment by behind24proxies** [comment]
Question : how can I delete (completely delete) a session that is stored in the .sessions folder ? 
[if I stop the session and re-start it with the same name it comes up again with these loops]

**Comment by allburov** [comment]
Hi!
If docker and session restart doesn't work (as I understood from the issue, it doesn't for you) - the only way is to remove the folder - usually it's `.session/webjs-{SESSION_NAME}` folder

It might happen sometime, when WhatsApp changes their credentials format - it either logout the session after few minutes with an error like "There's a error in database, please scan QR code".

**Comment by martinmineo** [comment]
I'm facing a similar issue but I can't make it work again.
I'm running the plus version on AWS. I deleted the cluster and re-deploy it again and every time the same issue shows up.
Steps to reproduce:
Start the session
Take the screenshot
The screenshot works
I scan the QR code
It fails with the following error 
```
ERRO[0193] error waiting for container: invalid character 'c' looking for beginning of value
```
Take the screenshot again
I see the same issue that @behind24proxies is facing, a spinner where the QR code should be

**Comment by behind24proxies** [comment]
> I'm facing a similar issue but I can't make it work again.
> I'm running the plus version on AWS. I deleted the cluster and re-deploy it again and every time the same issue shows up.
> Steps to reproduce:
> Start the session
> Take the screenshot
> The screenshot works
> I scan the QR code
> It fails with the following error 
> ```
> ERRO[0193] error waiting for container: invalid character 'c' looking for beginning of value
> ```
> Take the screenshot again
> I see the same issue that @behind24proxies is facing, a spinner where the QR code should be

@martinmineo where does that error come? In the console, or on the swagger GUI?

**Comment by martinmineo** [comment]
@behind24proxies I see the error in the console. The only thing I see in swagger is that the session state is failed

**Comment by behind24proxies** [comment]
> @behind24proxies I see the error in the console. The only thing I see in swagger is that the session state is failed
> 

It might have to do with the docker environment

**Comment by allburov** [comment]
If session's stuck - now you can logout from it with **POST /api/sessions/logout** request and restart a container
https://waha.devlike.pro/docs/how-to/sessions/#logout
