### ISSUE TITLE
[Feature Request] Fallback Webhook option

### ISSUE THREAD

**Issue by yeheskel2016** [allburov/whatsapp-http-api#522]
I couldnt find anyone asking for this and it's something that I think for some users can add a lot! is having an option to set a fallback webhook,
Right now we have the possibility to add an additional Webhook and WAHA will send to both the same events set, 
but the request here is to maybe have a possibility to mark the secondary webhook as "Fallback Webhook" so only after x fail attempts (as set on the "Main" webhook) are finished and not reply from the server, so it would send this events to that fallback webhook..

Basically the usage here is that if for example the server is currently down, is that I would have a backup server that would listen for any webhook posts and will just reply with 'Maintence message/Server is down....' or something like that (everyone with their own solutions of course...) but for having it happening there is the need for this Fallback Webhook feature ;D 

Hope this is clear enough, Thanks alot of reading ;-)

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Hi! 

it's exactly what reverse proxies (as nginx) are for!
So it should work like `WAHA => Proxy (Ngixn/Traefik) => Your Backends` schema and proxy would understand when your upstream are down.

I'll just copy-paste chatgpt here, if you don't mind :)

We won't include it in the product, unfortunately, it's pure infrastructure solution

----

Certainly! Below is a detailed example of an Nginx reverse proxy configuration with two upstreams. The configuration is set up to use one upstream server primarily and only fall back to the second server if the first one fails to respond after a certain number of retries and timeouts.

### Nginx Configuration

1. **Install Nginx (if not already installed):**

   ```sh
   sudo apt update
   sudo apt install nginx
   ```

2. **Edit your Nginx configuration file (`/etc/nginx/nginx.conf` or the relevant site configuration in `/etc/nginx/sites-available/`):**

   ```nginx
   http {
       # Define the upstream servers
       upstream backend_primary {
           server primary_backend_server:80;
           check interval=1000 rise=1 fall=3 timeout=2000 type=http;
           check_http_send "HEAD / HTTP/1.0\r\n\r\n";
           check_http_expect_alive http_2xx http_3xx;
       }

       upstream backend_secondary {
           server secondary_backend_server:80;
           check interval=1000 rise=1 fall=3 timeout=2000 type=http;
           check_http_send "HEAD / HTTP/1.0\r\n\r\n";
           check_http_expect_alive http_2xx http_3xx;
       }

       # Enable the additional module for health or you can use the nginx default one
       # fastcgi_cache_path /var/cache/nginx levels=1:2 keys_zone=BACKEND_PRIMARY:10m inactive=60m;
       # fastcgi_cache_path /var/cache/nginx levels=1:2 keys_zone=BACKEND_SECONDARY:10m inactive=60m;

       server {
           listen 80;
           server_name yourdomain.com;

           location / {
               proxy_pass http://backend_primary;
               proxy_next_upstream error timeout http_404 http_500 http_502 http_503 http_504;
               proxy_next_upstream_tries 3;    # Retry three times before falling back
               proxy_next_upstream_timeout 10s;    # Time for each try

               proxy_http_version 1.1;
               proxy_set_header Upgrade $http_upgrade;
               proxy_set_header Connection 'upgrade';
               proxy_set_header Host $host;
               proxy_cache_bypass $http_upgrade;

               # Specify proxy headers for the backend servers
               proxy_set_header X-Real-IP $remote_addr;
               proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
               proxy_set_header X-Forwarded-Proto $scheme;
           }

           # Fallback to the secondary backend if the primary is unavailable
           location @fallback {
               proxy_pass http://backend_secondary;
               proxy_http_version 1.1;
               proxy_set_header Upgrade $http_upgrade;
               proxy_set_header Connection 'upgrade';
               proxy_set_header Host $host;
               proxy_cache_bypass $http_upgrade;

               proxy_set_header X-Real-IP $remote_addr;
               proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
               proxy_set_header X-Forwarded-Proto $scheme;
           }
       }
   }
   ```

3. **Reload or Restart Nginx to apply the changes:**

   ```sh
   sudo systemctl reload nginx
   ```

### Explanation

- **Upstream configuration:**
  - `upstream backend_primary` and `upstream backend_secondary` define the primary and secondary backend servers.
  - Health checks are implemented using the `check` directive and various health check settings like `interval`, `rise`, `fall`, `timeout`, and the type of check (`type=http`).

- **Fallback Mechanism:**
  - The `proxy_next_upstream` directive specifies the conditions under which the request should be passed to the next server.
  - The `proxy_next_upstream_tries` directive limits the number of attempts to connect to the upstream servers.
  - The `proxy_next_upstream_timeout` directive sets the timeout for each attempt.

- **Server Configuration:**
  - Listens on port 80, and proxy passes to `backend_primary`.
  - If the primary server fails, the request is redirected to the `@fallback` location block, which proxies requests to `backend_secondary`.

This configuration ensures that the primary backend server is used predominantly, and the fallback server is only used if the primary backend fails to respond within the specified retries and timeout settings.

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by yeheskel2016** [comment]
Yes, I also thought about having similar approach (I more thought about having global webhook set to a server that will forward the events to the relevant avaliable webhook) but yeah it's all about workarounds ;D I still think it can be cool to have this kind of feature, I'm coming here after using Twilio services for whatsapp and there they had really simple feature of fallback webhook where if the main webhook was not responding it would just go there, but understood that there are probably better things that cant be set with workarounds so better to focus on them, thanks anyways ;-)

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
