### ISSUE TITLE
[BUG][WEBJS] - WEBJS will appear in a state of suspended animation

### ISSUE THREAD

**Issue by HuangDaHui** [allburov/whatsapp-http-api#523]
![image](https://github.com/user-attachments/assets/942d0b42-0c56-42fc-809e-6fb674f0959f)
In the WORKING state, the session cannot display the WhatsApp name and cannot send and receive messages normally. It needs to be stopped and started to return to normal.
It seems to only appear in some sessions with a lot of dialogue.
I haven’t gotten the relevant logs yet, so I’ll add them after they appear next time.

**Comment by devlikepro** [comment]
Hi! Yes, it happens time to time, we're checking a way to see how to add some "health check" to restart a session automatically..
Yes, logs would help here a lot :pray: 

What about screenshot btw, what does it show in this state?

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by HuangDaHui** [comment]
> Hi! Yes, it happens time to time, we're checking a way to see how to add some "health check" to restart a session automatically.. Yes, logs would help here a lot 🙏
> 
> What about screenshot btw, what does it show in this state?
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

The frequency of occurrence is about once a day
In this state, the screenshot is usually blank. I think if I can check whether it is normal through this interface, this problem can be solved.
/api/sessions/{session}/me
I'm thinking about how to implement automatic restart through existing interfaces

**Comment by devlikepro** [comment]
>is about once a day

Do you restart the container like every day at midnight? May be it'll help to solve all issues. Chrome + puppeter is pretty hard to maintain in long run thing... 
You can automate it by calling
https://waha.devlike.pro/docs/how-to/observability/#restart-stop-server
```
POST /api/server/stop
```
the docker will restart it automaticly (if you provide `--restart=always` flag in docker run)

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by HuangDaHui** [comment]
> > is about once a day
> 
> Do you restart the container like every day at midnight? May be it'll help to solve all issues. Chrome + puppeter is pretty hard to maintain in long run thing... You can automate it by calling https://waha.devlike.pro/docs/how-to/observability/#restart-stop-server
> 
> ```
> POST /api/server/stop
> ```
> 
> the docker will restart it automaticly (if you provide `--restart=always` flag in docker run)
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

There is currently no restart every day. I will use this interface to try restarting every day to see if it can solve the problem.

**Comment by HuangDaHui** [comment]
> > is about once a day
> 
> Do you restart the container like every day at midnight? May be it'll help to solve all issues. Chrome + puppeter is pretty hard to maintain in long run thing... You can automate it by calling https://waha.devlike.pro/docs/how-to/observability/#restart-stop-server
> 
> ```
> POST /api/server/stop
> ```
> 
> the docker will restart it automaticly (if you provide `--restart=always` flag in docker run)
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

I understand that the server restarts every morning, but the problem still cannot be solved. I will open the stop and start functions to customers and let them operate on their own to solve the problem.

**Comment by HuangDaHui** [comment]
> > > is about once a day
> > 
> > 
> > Do you restart the container like every day at midnight? May be it'll help to solve all issues. Chrome + puppeter is pretty hard to maintain in long run thing... You can automate it by calling https://waha.devlike.pro/docs/how-to/observability/#restart-stop-server
> > ```
> > POST /api/server/stop
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > the docker will restart it automaticly (if you provide `--restart=always` flag in docker run)
> > [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
> 
> I understand that the server restarts every morning, but the problem still cannot be solved. I will open the stop and start functions to customers and let them operate on their own to solve the problem.

But it is still easy for the status to change to STARTING/FAILED after restarting, so I can only solve it by deleting and re-creating it.
This should also be a problem

**Comment by devlikepro** [comment]
I see, that's problem.
Do you have any logs in the container after you started it and see FAILED sessions? That would help!
Could you also tell a bit more about your setup - do you use file storage or mongodb one, do you use `chrome` or regular docker image? 
Where do you run WAHA (vps or your server) and how do you run the docker container?

> I can only solve it by deleting and re-creating it.

In `2024.9` we've added the way to logout from the session, so you can logout without removing it (you'll need to rescan QR code tho, yes)

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by HuangDaHui** [comment]
> I see, that's problem. Do you have any logs in the container after you started it and see FAILED sessions? That would help! Could you also tell a bit more about your setup - do you use file storage or mongodb one, do you use `chrome` or regular docker image? Where do you run WAHA (vps or your server) and how do you run the docker container?
> 
> > I can only solve it by deleting and re-creating it.
> 
> In `2024.9` we've added the way to logout from the session, so you can logout without removing it (you'll need to rescan QR code tho, yes)
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

I always forget to collect logs
I use mongodb storage
I don't quite understand. Does chrome need to install another docker image?
I'm running WAHA on my own liunx server
docker run -it -p 3000:3000/tcp --restart=always -e "WHATSAPP_DEFAULT_ENGINE=WEBJS" -e WHATSAPP_SESSIONS_MONGO_URL=mongodb://192.168.18.170:27017/ -e WHATSAPP_FILES_LIFETIME=0  -e WHATSAPP_RESTART_ALL_SESSIONS=True devlikeapro/waha-plus
Would providing these be helpful?

**Comment by devlikepro** [comment]
>Does chrome need to install another docker image?

Yes, https://waha.devlike.pro/docs/how-to/engines/#docker-images
```
devlikeapro/waha-plus:chrome	
```

> I use mongodb storage

Could it be because of the fact you're using more then one worker? https://github.com/devlikeapro/waha/issues/525
Or in this case mongodb is used for a single worker? 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by HuangDaHui** [comment]
> > Does chrome need to install another docker image?
> 
> Yes, https://waha.devlike.pro/docs/how-to/engines/#docker-images
> 
> ```
> devlikeapro/waha-plus:chrome	
> ```
> 
> > I use mongodb storage
> 
> Could it be because of the fact you're using more then one worker? #525 Or in this case mongodb is used for a single worker?
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
`devlikeapro/waha-plus:chrome`
I'll try this image
Currently, a MongoDB corresponds to a WEBJS docker container and a NOWEB docker container. The sessions in them are different. I wonder if this will affect it?

**Comment by devlikepro** [comment]
> Currently, a MongoDB corresponds to a WEBJS docker container and a NOWEB docker container. The sessions in them are different. I wonder if this will affect it?

In this setup that's fine :thinking: 
It could affect if you'd use 2 WEBJS with the same mongodb 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by HuangDaHui** [comment]
> > Currently, a MongoDB corresponds to a WEBJS docker container and a NOWEB docker container. The sessions in them are different. I wonder if this will affect it?
> 
> In this setup that's fine 🤔 It could affect if you'd use 2 WEBJS with the same mongodb
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

Yes, I tried it, the webhook will push repeatedly
