### ISSUE TITLE
[BUG][WEBJS] - contacts api not working 

### ISSUE THREAD

**Issue by jvkassi** [allburov/whatsapp-http-api#526]
**Describe the bug**

I can't get my contacts http://localhost:3000/api/contacts?session=default

```json
{
  "statusCode": 500,
  "timestamp": "2024-09-05T00:19:07.305Z",
  "exception": {
    "stack": "TypeError: Cannot read properties of undefined (reading 'includes')\n    at ensureSuffix (/app/dist/core/abc/session.abc.js:20:15)\n    at WhatsappSessionWebJSPlus.ensureSuffix (/app/dist/core/abc/session.abc.js:306:16)\n    at WhatsappSessionWebJSPlus.getContact (/app/dist/core/engines/webjs/session.webjs.core.js:347:34)\n    at ContactsController.get (/app/dist/api/contacts.controller.js:29:25)\n    at /app/node_modules/@nestjs/core/router/router-execution-context.js:38:29",
    "message": "Cannot read properties of undefined (reading 'includes')",
    "name": "TypeError"
  },
  "request": {
    "path": "/api/contacts?session=default",
    "method": "GET",
    "body": {

    },
    "query": {
      "session": "default"
    }
  },
  "version": {
    "version": "2024.9.3",
    "engine": "WEBJS",
    "tier": "PLUS",
    "browser": "/usr/bin/chromium"
  }
}
```

**Version**

```json
{
  "version": "2024.9.3",
  "engine": "WEBJS",
  "tier": "PLUS",
  "browser": "/usr/bin/chromium"
}
```

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Hi! 
Could you try  http://localhost:3000/api/contacts/all?session=default

https://waha.devlike.pro/docs/how-to/contacts/#get-all-contacts

Yeah, /api/contacts is more intuitive but it works for a single contact only :( 
http://localhost/api/contacts?contactId=11231231231&session=default

We need to review API endpoints in the future to make it more REST compatible...

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
