### ISSUE TITLE
WaHa Plus - disable webhook retires

### ISSUE THREAD

**Issue by behind24proxies** [allburov/whatsapp-http-api#53]
hi
Q1 - is there a way to disable webhook retires on the plus version ? (web.js)
Q2 - how much time does the waha server wait before attempting again ? is it possible to increase/decrease this time ?

**Comment by allburov** [comment]
Hi! 
1. Right now it's not possible, but it's must have feature - they must be configurable - retries count and retry delay. We'll add it a bit later
2. 15 attempts with 2 seconds delay between them on network or http errors

**Comment by behind24proxies** [comment]
> Hi! 
> 1. Right now it's not possible, but it's must have feature - they must be configurable - retries count and retry delay. We'll add it a bit later
> 2. 15 attempts with 2 seconds delay between them on network or http errors
> 

Okey
I will try to cache the reply_id, and ignore all the following messages with the same id.
Anyhow, in my case, the waha webhook retries even if the server returns a valid response.
Sometimes the server takes 1-2 minutes to process a request, in the meantime waha overloads the server with duplicate requests, this is what's happening, right?

**Comment by allburov** [comment]
Hi! Now it possible to configure or disable retries - please read more about that https://waha.devlike.pro/docs/how-to/webhooks/

**POST /api/sessions/start**
```json
{
  "name": "default",
  "config": {
    "webhooks": [
      {
        "url": "https://httpbin.org/post",
        "events": [
          "message"
        ],
        "hmac": {
          "key": "your-secret-key"
        },
        "retries": {
          "delaySeconds": 2,
          "attempts": 15
        },
        "customHeaders": [
          {
            "name": "X-My-Custom-Header",
            "value": "Value"
          }
        ]
      }
    ]
  }
}
```
