### ISSUE TITLE
[Question] How to Install On windows Server 2022 and How to Correct Timezone in Screenshot messages?

### ISSUE THREAD

**Issue by smihheemmaanntt** [allburov/whatsapp-http-api#530]
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\Users\Administrator> cd d:\waha
PS D:\waha> docker-compose up -d
[+] Running 0/1
 - waha Pulling                                                                                                    2.9s
no matching manifest for windows/amd64 10.0.20348 in the manifest list entries
PS D:\waha>
I am Installing Waha on Windows Server 2022,, so can use After lock Server too Running Services.
**And Also Want to Know Why I am Not Getting Screenshot Messages Timezone Correctly?**

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Hi! 
> How to Install On windows Server 2022 

For docker you need to use **linux** container, not windows one. We don't have plans to add window container, it's nightmare to support :( You need to follow something like https://techcommunity.microsoft.com/t5/itops-talk-blog/using-wsl-2-on-windows-server-2022-to-run-linux-containers/ba-p/3624745 

If you want to run it in Windows (native) you need to manually follow Dockerfile and replicate the full environment like https://github.com/devlikeapro/waha/blob/core/Dockerfile

> Screenshot Messages Timezone Correctly

Could you explain it a bit or show the screenshot? We use the server timezone everywhere, may be some issues with server => docker timezone replication

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by smihheemmaanntt** [comment]
![image](https://github.com/user-attachments/assets/4784d622-eef4-4658-9b06-1526c224d3c3)

Here is the Screenshot of Server and Local timezone, how to Correct it? if it is a bug please solve or guide me to correct timezone on screenshots

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
@smihheemmaanntt I see, for that you need to configure `TZ` environment variable when you run docker container
```bash
docker run ... -eTZ="Africa/Lusaka" ...
```

or put it in docker-compose.yaml file if you're using this one
```yaml
    environment:
     - TZ=Africa/Lusaka
```

and restart the container after that 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
You can find your timezone name in the list https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
> You need to follow something like https://techcommunity.microsoft.com/t5/itops-talk-blog/using-wsl-2-on-windows-server-2022-to-run-linux-containers/ba-p/3624745

Btw, wsl2 is not the best backend, try using Hyper-V docker backend instead

https://docs.docker.com/desktop/install/windows-install/

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
