### ISSUE TITLE
[BUG][NOWEB] - possible memory leak

### ISSUE THREAD

**Issue by abelgenial** [allburov/whatsapp-http-api#533]
Hi WAHA, Congratulations on the changes to the dashboard.
I would like to report instability in version 2024.9.4
I recreated the container and after 4 hours of production it is already at 18 gigabytes. Before, it took more than a week for the container to reach this size and I had the impression that when the container got big the API itself restarted it without any human action. I work with many sessions, on average between 400 and 500, my server has 48 gigabytes of memory. Below are prints and logs from a moment when the requests started to cause problems today (from 11:20 to 11:34) Brasilia time.

**Version**  2024.9.4

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by abelgenial** [comment]
logs
[loghoje.txt](https://github.com/user-attachments/files/16909891/loghoje.txt)
![WhatsApp Image 2024-09-06 at 12 15 32](https://github.com/user-attachments/assets/79638e9c-e31d-4b0e-a482-bdb5dde83e29)
![WhatsApp Image 2024-09-06 at 12 16 04](https://github.com/user-attachments/assets/cb8d98da-f480-4e8b-871f-1c7558d3ddbf)
![WhatsApp Image 2024-09-06 at 12 16 54](https://github.com/user-attachments/assets/061ce090-2102-4f3e-9e3c-40b802ba0125)


[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by abelgenial** [comment]
Yesterday I deleted all the scan qr code sessions and today the clients started reading new qrcode. I left active only 150 sessions that were working since version 8

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
@abelgenial hi!
what the pervious version you were using, do you rememeber? We'd love to dig into memory issues so we know where to search, it'd help :pray: 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by abelgenial** [comment]
Hi !!
I don't remember, it was probably version 2024.8, I ended up updating it by accident when I ran a batch file

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by abelgenial** [comment]
I have an average of 500 sessions, and I don't know what might happen if I recreate the containers. In a previous post I saw some guidance on splitting into more than one container. Can you explain better how I can do this on the same computer? I have a 48 GB computer and Windows 10 Pro.

If you need any logs or anything else on my machine, let me know, I'm at your disposal.

thank you

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by abelgenial** [comment]
I believe I discovered a procedure that was working in version 2024.8 and is no longer working. When the container has a lot of data, the previous version restarted it before it started to show slowness in requests. In the JPG you can see that it is at its limit and started to show problems, so I went to docker, stopped it and then started it and it restarted with little data and started working normally again.
![container no limite](https://github.com/user-attachments/assets/fbde6e11-8342-4563-88f2-f7d9a7e38dc2)


[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Hi! Yeah, there's memory leak, we need to find it, working on this as first priority!

> In a previous post I saw some guidance on splitting into more than one container. Can you explain better how I can do this on the same computer?

This one likely: https://waha.devlike.pro/blog/waha-scaling-how-to-handle-500-sessions/

So basically you need to run multiple containers on different ports attaching different `.sessions` folders and route the requests in your application code to the right instance

Something like run these command multiple times
```bash
docker run -d \
    --restart=always \
    --name waha-1 \
    -p 3001:3001/tcp \
    -v ./.sessions1:/app/.sessions \
    -v ./.media:/app/.media \
    --env WHATSAPP_API_KEY=321 \
   --env WHATSAPP_API_PORT=3001 \
    --env WAHA_DASHBOARD_USERNAME=waha \
    --env WAHA_DASHBOARD_PASSWORD=waha \
    --env WAHA_LOG_FORMAT=JSON \
    --env WAHA_LOG_LEVEL=info \
    --env WHATSAPP_DEFAULT_ENGINE=NOWEB \
    --env WHATSAPP_RESTART_ALL_SESSIONS=True \
    --env WAHA_PRINT_QR=False \
    --env WHATSAPP_FILES_LIFETIME=0 \
    --env WHATSAPP_FILES_FOLDER=/app/.media \
    devlikeapro/waha-plus:latest
```
or by configuring multiple services in docker-compose https://github.com/devlikeapro/waha/blob/core/docker-compose.yaml

https://waha.devlike.pro/docs/how-to/install/


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
>the previous version restarted it before it started to show slowness in requests

For now as a quick fix you can restart container during your night using http request
https://waha.devlike.pro/docs/how-to/observability/#restart-stop-server
```
POST /api/server/stop
```
you can do it in crontab or any other scheduled logic you have, like n8n https://waha-n8n-templates.devlike.pro/restart-server-at-midnight/ (https://waha.devlike.pro/docs/integrations/n8n/)

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
If you still have the problem - let's test it with `2024.9.5` and see how it goes :crossed_fingers: 
Leave a comment here if it doesn't help and we'll reopen the issue

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by abelgenial** [comment]
I tested the http restart-stop-server option and it worked fine. I'm going to implement this to run automatically at night. Is there a certain number of times this can be done to keep the container running smoothly? What is the recommended frequency in your opinion? Could you adjust the request so that it returns true or success when it is executed successfully? Because it returns "null"

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Once a day is totally fine! If it requires more frequent restarts - we must fix it internally :( 
How the new version is going, did you have a change to update and check this? It could work with no restart, ideally 

> Because it returns "null"

Sure, we'll send `{stopping: true}`. 
The main problem - it'll always be `true` because you can not answer on the response when the server is rebooting :rofl: 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by abelgenial** [comment]
I use version 2024.9.4 , should update ? 
thanks, I set the 23:00 restart via Http 

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
> I use version 2024.9.4 , should update ?

The 2024.9.5 should be a bit more stable in terms of memory, but if the 9.4 works good with the restarts you can use it, no worries!

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by abelgenial** [comment]
![erro api](https://github.com/user-attachments/assets/b659074a-c793-4f91-b9d8-1d9ed95f03ef)

Yesterday I updated the version, it was on version 2024.9.4 and today the sessions were like this this afternoon, in the morning everything was ok. I think there is a problem with this version. I use the noweb option, Help please

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by abelgenial** [comment]
![dockerhoje](https://github.com/user-attachments/assets/47298aa2-167b-4fde-9f46-6746009402e7)


[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by abelgenial** [comment]
![stopandstart](https://github.com/user-attachments/assets/415c17bb-74d1-4420-846e-503edfccb81c)

After stopping and starting docker and pressing f5 on the dashboard, all sessions returned to normal. If you need anything, please let me know.

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by abelgenial** [comment]
It is important to inform that some message sending requests are giving timeout

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by abelgenial** [comment]
around 00:00 in Sao Paulo, I deleted the containers because I was going to update to version 2024.9.4 which was more stable, and when using the command

docker login -u devlikeapro -p .......... 

gave the error below:
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get "https://registry-1.docker.io/v2/": unauthorized: incorrect username or password

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

At 00:25 hrs (Sao Paulo), the login worked and I tried to return to the version according to the manual without success.

docker-compose.yml:
image: devlikeapro/waha-plus:noweb:latest-2024.9.4
error !!!

**Comment by devlikepro** [comment]
@abelgenial try this one 
```
devlikeapro/waha-plus:noweb-2024.9.4
```

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Here's helper docker image builder https://portal.devlike.pro/docker-image

![image](https://github.com/user-attachments/assets/280bf259-e653-4124-9673-811c3f2358d5)


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
