### ISSUE TITLE
[Feature Request] - websockets support

### ISSUE THREAD

**Issue by devlikepro** [allburov/whatsapp-http-api#535]
Add Full websockets supports, right now only `session.status` is available
https://waha.devlike.pro/docs/how-to/webhooks/#websockets

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Added in `2024.11.5`, now websockets can send all events
https://waha.devlike.pro/docs/how-to/webhooks/#websockets


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by totalard** [comment]
![Image](https://github.com/user-attachments/assets/b30bf0cb-ea4b-41ef-b253-c3f03b0fc43b)

still no success, it only fire session.status

my url is ws://localhost:3000/ws

in webhook it fireall, even qr code data, but in websocket, it only fire session.status only

{"id":"evt_01jmq909gkqstwc0nz5nhj3cd4","event":"session.status","session":"WASS-00000024","metadata":{},"payload":{"name":"WASS-00000024","status":"SCAN_QR_CODE"},"environment":{"version":"2025.2.5","engine":"GOWS","tier":"PLUS","browser":"/usr/bin/chromium"}}


ws://localhost:3000/ws?session=*&events=session.status&events=message&events=engine.event
the above is working, 

events=* not working

**Comment by devlikepro** [comment]
Hi! 
The [**Event Monitor** on Dashboard ](https://waha.devlike.pro/docs/how-to/dashboard/#event-monitor)uses websockets. 

Could you check you're getting all events to it?
http://localhost:8000/dashboard/event-monitor

Make sure to scan QR code, otherwise the only event you'll get - `session.status`

👉  One thing to notice, `events=*` does not fire `engine.event`! 

If you want to listen both all events and raw `engine.event`, you need to set query as:
```
/ws?session=*&events=*&events=engine.event
```


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
