### ISSUE TITLE
[BUG][NOWEB] - NOWEB not synchronizing anymore

### ISSUE THREAD

**Issue by aitoroses** [allburov/whatsapp-http-api#537]
Since updating to version 2024.9.4 (core) a few days ago, I haven't been able to sync groups or contacts. I've tried removing and recreating the session with the store and fullSync set to true, but the logs don't show any synchronization happening. As a result, when I call the chats and messages APIs, I get empty arrays.

**Comment by devlikepro** [comment]
Hi! Here's the steps you need to do if you're using core:
1. Run a new `devlikeapro/waha` docker container
2. Go to http://127.0.0.1:3000/dashboard/
3. Remove default session
4. Add `default` session back with enabled store
5. Wait 1-2 minutes so waha syncs all the data from the phone
6. Get /chats or /chats/{id}/messages?limit=10 endpoints

![image](https://github.com/user-attachments/assets/cfcf5b77-65b4-4745-b1f5-04d9eab94166)
Just tested it, works normal

If it doesn't help - could you run a session with **debug enabled** and get all logs from docker output (right from the start) and send it to waha@devlike.pro (as an attachment) :pray: 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
