### ISSUE TITLE
[BUG][WEBJS] -  Cannot read properties of null (reading 'getScreenshot') on my debian VPS

### ISSUE THREAD

**Issue by mo-tech55** [allburov/whatsapp-http-api#538]
After running this command on my debian  vps:

`docker run -it --rm -p 3000:3000/tcp --name waha devlikeapro/waha`

I cant generate the qr code. 
![image](https://github.com/user-attachments/assets/2efeeb4b-71a3-42b8-be18-153c587b2704)

{
  "statusCode": 500,
  "timestamp": "2024-09-10T20:40:46.192Z",
  "exception": {
    "stack": "TypeError: Cannot read properties of null (reading 'getScreenshot')\n    at ScreenshotController.screenshot (/app/dist/api/screenshot.controller.js:29:38)\n    at /app/node_modules/@nestjs/core/router/router-execution-context.js:38:29",
    "message": "Cannot read properties of null (reading 'getScreenshot')",
    "name": "TypeError"
  },
  "request": {
    "path": "/api/screenshot?session=default",
    "method": "GET",
    "body": {},
    "query": {
      "session": "default"
    }
  },
  "version": {
    "version": "2024.9.4",
    "engine": "WEBJS",
    "tier": "CORE",
    "browser": "/usr/bin/chromium"
  }
}

**Version**

```json
 {
    "version": "2024.9.4",
    "engine": "WEBJS",
    "tier": "CORE",
    "browser": "/usr/bin/chromium"
  }
```

**Comment by devlikepro** [comment]
Hi! you need to start the `default` session before 
![image](https://github.com/user-attachments/assets/9a8c773d-dade-40c9-9882-585a26db9b15)

We'll work on the error message, totally agree it doesn't make sense :laughing: 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by alexagfra190personal** [comment]
<img width="1750" height="717" alt="Image" src="https://github.com/user-attachments/assets/1689bb24-1f3a-4a67-89c1-3d779e0033ea" />

Is the bug back? Or what's going on? Could you please help me?
