### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by TimousFly** [allburov/whatsapp-http-api#539]
I'm always
frustrated when Operations such as session restart or service update ,Local service will lost message.
Now, I can only actively obtain it through /api/{session}/chats/{chatId}/messages, and I also need to compare the information locally, which is too complicated.
I hope to communicate through webhook to push the incremental data generated during the waha outage

**Comment by devlikepro** [comment]
Hi! 
> I also need to compare the information locally, which is too complicated.

Yeah, agree on that point :( 

We'll work on history sync webhooks for that purpose soon :crossed_fingers: 
 #458

Would it solve your problem?

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by TimousFly** [comment]
Ok please post it asap
