### ISSUE TITLE
Whatsapp sesion FAILED (instantly after scanning qr code)

### ISSUE THREAD

**Issue by behind24proxies** [allburov/whatsapp-http-api#54]
version : latest@plus
when I scan the whatsapp qr code , this is what I get

```
{
  "statusCode": 422,
  "message": "The session under FAILED status. Please try to restart it.",
  "error": "Unprocessable Entity"
}
```

this is happening with all new sessions , I tried restarting , but it does not work (I tried restarting , starting new sessions about 7-8 times )

**Comment by behind24proxies** [comment]
update :
I tried switching to the venom engine.It is not working , I still cannot send messages ( I opened an issue on this a few weeks ago :()

**Comment by behind24proxies** [comment]
update:
I get this error when I start a whatsapp web session with the web.js engine
```
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'queryExists')
    at __puppeteer_evaluation_script__:26:69
```

I remember that this happened a few weeks ago as well, but then you patched it 

https://github.com/pedroslopez/whatsapp-web.js/issues/1313

**Comment by behind24proxies** [comment]
I tried running it on another server , with a different IP 
and I get this error
```
Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'LegacyPhoneFeatures')
    at __puppeteer_evaluation_script__:13:76
```

**Comment by philmor90** [comment]
Same here!

**Comment by allburov** [comment]
Hi! I've updated the webhs engine, could you try to pull the new version and try again?

**Comment by behind24proxies** [comment]
Hi @allburov 
I pulled the plus version again , and now I am getting this error

```
 Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'queryExists')
    at __puppeteer_evaluation_script__:25:69
```

on swagger it gives me this error


```
{
  "statusCode": 422,
  "message": "The session under FAILED status. Please try to restart it.",
  "error": "Unprocessable Entity"
}
```

this happens right after I scan the qr code

maybe you updated only the core version ?

**Comment by behind24proxies** [comment]
UPDATE 
@allburov 
I pulled the core (I have the plus version , but I decided to pull the core version , to check if everything was working fine there) version from another VPS , and , well , same problem .


```
[Nest] 20  - 02/11/2023, 11:54:09 AM   ERROR [WhatsappSession - default] Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'queryExists')
    at __puppeteer_evaluation_script__:25:69
```


also , can you fix the Venom engine when you have time ? the webhooks work fine there ,but I cannot send messages

**Comment by doutorinfamous** [comment]
Having the exactly same problem...

LOGS:
[Nest] 20  - 02/11/2023, 1:14:02 PM     LOG [Webhook - clara] Configuring webhooks...
[Nest] 20  - 02/11/2023, 1:14:02 PM     LOG [Webhook - clara] Webhooks were configured.
[Nest] 20  - 02/11/2023, 1:14:20 PM   ERROR [WhatsappSession - clara] Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'queryExists')
    at __puppeteer_evaluation_script__:25:69

GET SCREENSHOT:
{
  "statusCode": 422,
  "message": "The session under FAILED status. Please try to restart it.",
  "error": "Unprocessable Entity"
}

DROP ALL MY SESSIONS TO FAILED STATUS
[
  {
    "name": "ricardo",
    "status": "FAILED"
  },
  {
    "name": "clara",
    "status": "FAILED"
  }
]


I'm using the lastest PLUS docker. Did a update to test it, same error.

**Comment by allburov** [comment]
@behind24proxies could you pull new core version again please and see if it works for you? If it does - I'll fix plus too

**Comment by doutorinfamous** [comment]
> @behind24proxies could you pull new core version again please and see if it works for you? If it does - I'll fix plus too

I tested now with the core version, it worked.

**Comment by allburov** [comment]
Fixed in Plus version too!

**Comment by doutorinfamous** [comment]
I'm going to test it in the plus

**Comment by doutorinfamous** [comment]
I can confirm now! Working perfect in CORE and in PLUS!

Thanks a lot @allburov !
