### ISSUE TITLE
[BUG][WEBJS] - After restarting the service, it keeps STARTING

### ISSUE THREAD

**Issue by TimousFly** [allburov/whatsapp-http-api#540]
When I restart services in batches, a large number of sessions in the STARTING state are generated. I have to restart them one by one manually to make the sessions normal one by one. I want to know what may cause me to have sessions in the STARTING state.
<img width="396" alt="71b646d3981e9f5e80c52e9a3eee023a" src="https://github.com/user-attachments/assets/c7d46173-54f2-4c1d-bf43-f63cbbd64353">
<img width="482" alt="1726020951566_975A78FD-4072-48c8-97C1-71BE31889DD7" src="https://github.com/user-attachments/assets/7b87d6af-8ab4-4893-9c43-b3e953a83ded">

,"session":"1833493435099693056","sessionRunTimestamp":1726021687360}
    err: {
      "type": "ProtocolError",
      "message": "Protocol error (Runtime.callFunctionOn): Target closed.",
      "stack":
          ProtocolError: Protocol error (Runtime.callFunctionOn): Target closed.
              at /app/node_modules/whatsapp-web.js/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:329:24
              at new Promise (<anonymous>)
              at CDPSessionImpl.send (/app/node_modules/whatsapp-web.js/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:325:16)
              at ExecutionContext._ExecutionContext_evaluate (/app/node_modules/whatsapp-web.js/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:211:46)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async JSHandle.evaluateHandle (/app/node_modules/whatsapp-web.js/node_modules/puppeteer-core/lib/cjs/puppeteer/common/JSHandle.js:97:16)
              at async WaitTask.rerun (/app/node_modules/whatsapp-web.js/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:114:28)
      "name": "ProtocolError",
      "originalMessage": ""
    }

**Comment by devlikepro** [comment]
Hi! I see you're using WEBJS engine with multple workers setup - do they use the same `.sessions` folder or the same MongoDB connection by any chance?


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
~100 sessions in a container, that's impressive! and a bit dangerous... 
We'd kindly recommend splitting it into 50 WEBJS sessions if possible https://waha.devlike.pro/blog/waha-scaling-how-to-handle-500-sessions/

We'll check the restarting question anyway, likely because all 100 sessions start at the same time - chrome can not properly start it :( 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Btw, are you using chrome or default chromium instance?

```
devlikeapro/waha-plus:latest
OR
devlikeapro/waha-plus:chrome
```

https://waha.devlike.pro/docs/how-to/engines/#docker-images

Just so we know how to test it properly

and I guess you have `WHATSAPP_RESTART_ALL_SESSIONS=True` flag enable, right?

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by TimousFly** [comment]
> Hi! I see you're using WEBJS engine with multple workers setup - do they use the same `.sessions` folder or the same MongoDB connection by any chance?
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
All my waha services share a mongod

**Comment by TimousFly** [comment]
> 顺便说一句，您使用的是 chrome 还是默认的 chromium 实例？
> 
> ```
> devlikeapro/waha-plus:latest
> OR
> devlikeapro/waha-plus:chrome
> ```
> 
> https://waha.devlike.pro/docs/how-to/engines/#docker-images
> 
> 只是为了让我们知道如何正确测试
> 
> 我猜你启用了标志，对吧？`WHATSAPP_RESTART_ALL_SESSIONS=True`
> 
> [![赞助人：PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)



> 一个容器中的 ~100 个会话，这真是令人印象深刻！而且有点危险......如果可能的话，我们恳请将其拆分为 50 个 WEBJS 会话https://waha.devlike.pro/blog/waha-scaling-how-to-handle-500-sessions/
> 
> 无论如何，我们都会检查重新启动问题，可能是因为所有 100 个会话同时启动 - chrome 无法正确启动它:(
> 
> [![赞助人：PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)



> 一个容器中的 ~100 个会话，这真是令人印象深刻！而且有点危险......如果可能的话，我们恳请将其拆分为 50 个 WEBJS 会话https://waha.devlike.pro/blog/waha-scaling-how-to-handle-500-sessions/
> 
> 无论如何，我们都会检查重新启动问题，可能是因为所有 100 个会话同时启动 - chrome 无法正确启动它:(
> 
> [![赞助人：PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

I use multiple containers here, and the STOPED shown in the screenshot is incorrect (maybe because the same Mongodb is used), in fact, each container starts only about 20

**Comment by TimousFly** [comment]
> Btw, are you using chrome or default chromium instance?
> 
> ```
> devlikeapro/waha-plus:latest
> OR
> devlikeapro/waha-plus:chrome
> ```
> 
> https://waha.devlike.pro/docs/how-to/engines/#docker-images
> 
> Just so we know how to test it properly
> 
> and I guess you have `WHATSAPP_RESTART_ALL_SESSIONS=True` flag enable, right?
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

I have a chance to get this error when I restart manually in batches. For example, if I start 5 in a row, there will always be a few that keep STARTING

**Comment by TimousFly** [comment]
> Btw, are you using chrome or default chromium instance?
> 
> ```
> devlikeapro/waha-plus:latest
> OR
> devlikeapro/waha-plus:chrome
> ```
> 
> https://waha.devlike.pro/docs/how-to/engines/#docker-images
> 
> Just so we know how to test it properly
> 
> and I guess you have `WHATSAPP_RESTART_ALL_SESSIONS=True` flag enable, right?
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

my image devlikeapro/waha-plus   chrome  
my config WHATSAPP_RESTART_ALL_SESSIONS=False

The batch restart logic is controlled by me. After the waha upgrade, I will only restart the previously started sessions, and I start them through the /api/sessions/{session}/start interface.

**Comment by devlikepro** [comment]
I see, thank you for the explanation, we'll test it properly! 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
If you still have the problem - let's test it with `2024.9.5` and see how it goes :crossed_fingers: 
We have added few additional optimization flag for chrome process

Leave a comment here if it doesn't help and we'll reopen the issue!

JFYI, we'll work on multi workers approach soon so you don't have to manually (or using API) start the sessions :crossed_fingers: 
https://github.com/devlikeapro/waha/issues/525

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
