### ISSUE TITLE
[Feature Request][NOWEB] - Pairing Code authorization

### ISSUE THREAD

**Issue by ForceDev1** [allburov/whatsapp-http-api#543]
Please add the use of pairing code in NOWEB engine

**Comment by devlikepro** [comment]
Added while ago https://waha.devlike.pro/docs/how-to/sessions/#get-pairing-code

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
