### ISSUE TITLE
[Feature Request] Button Message 

### ISSUE THREAD

**Issue by Himanshu1234556** [allburov/whatsapp-http-api#544]
Now button is working in Baileys.
And provider already integrated please do it as soon as possible 

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
In `2024.10.5` in **NOWEB** engine only 
https://waha.devlike.pro/docs/how-to/send-messages/#send-buttons

----
![image](https://github.com/user-attachments/assets/043b0557-24d9-4195-a153-447d8471366c)

## Send Buttons

![](send-buttons.jpg)

You can send **interactive message** (aka **buttons**) using

```
POST /api/sendButtons
```

```json
{
  "chatId": "11111111111@c.us",
  "header": "How are you?",
  "headerImage": {
    "mimetype": "image/jpeg",
    "filename": "filename.jpg",
    "url": "https://github.com/devlikeapro/waha/raw/core/examples/waha.jpg"
  },
  "body": "Tell us how are you please 🙏",
  "footer": "If you have any questions, please send it in the chat",
  "buttons": [
    {
      "type": "reply",
      "text": "I am good!"
    },
    {
      "type": "call",
      "text": "Call us",
      "phoneNumber": "+1234567890"
    },
    {
      "type": "copy",
      "text": "Copy code",
      "copyCode": "4321"
    },
    {
      "type": "url",
      "text": "How did you do that?",
      "url": "https://waha.devlike.pro"
    }
  ],
  "session": "default"
}
```

⚠️ **Buttons** is not super stable feature, consider
adding fallback logic in case the buttons are not working right now.

👉 `headerImage` is available only in
[**➕ WAHA Plus**]({{< relref "/docs/how-to/waha-plus" >}})

### Buttons
Here's available buttons you can use in `buttons`:

**Quick Reply**

```json
{
  // Optional id
  // "id": "123",
  "type": "reply",
  "text": "I am good!"
}
```

**URL**

```json
{
  "type": "url",
  "text": "How did you do that?",
  "url": "https://waha.devlike.pro"
}
```

**Call**

```json
{
  "type": "call",
  "text": "Call us",
  "phoneNumber": "+1234567890"
}
```

**Copy**

```json
{
  "type": "copy",
  "text": "Copy code",
  "copyCode": "4321"
}
```



[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by web-codder** [comment]
you recived a message but your version of whatsapp doesn't;t support it getting this error by sending this

**Comment by ceosarzone** [comment]
It will work on web only if one type is selected.

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
@web-codder do you use the latest WhatsApp version? Could you share some details, OS or smthg

@ceosarzone awesome note, will test it!

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by ceosarzone** [comment]
It is not working, the api response is ok but the msg is not being displayed on mobile nor on web.

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by DionathaFraga** [comment]
Não está funcionando nessa versão ? Até já comprar a mensalidade só por causa dos botões mas vi essa mensagem do ceosarzone. Aguardou um retorno de como está essa parte aí se ok eu vou adquirir.

**Comment by ceosarzone** [comment]
@devlikepro Waiting for your response

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Hi! Buttons are fragile creatures, no guarantee it'll always work :( Looks like Meta got patched our solution recently...
Consider having a fallback logic to regular text in case of such errors.
We'll see what we can do with buttons :crossed_fingers: 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by DionathaFraga** [comment]
Sei que tem um programa Nowhats sender eles tem os botões na baileys está funcionando normal
