### ISSUE TITLE
[BUG][WEBJS] - Missing Error  GET /api/sessions/{session}

### ISSUE THREAD

**Issue by AliSot2000** [allburov/whatsapp-http-api#546]
The endpoint returns a `200` status code with an `application/octet-stream` as response type. 

I would expect that a 404 Error be returned instead.

**Comment by devlikepro** [comment]
Fixed in `2024.9.6`, not it returns http status code 404 and message
```json
{
  "statusCode": 404,
  "message": "Session not found",
  "error": "Not Found"
}
```

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
