### ISSUE TITLE
[BUG][WEBJS] - When the forwarded message type is video, the webhook notification will not be pushed.

### ISSUE THREAD

**Issue by HuangDaHui** [allburov/whatsapp-http-api#547]
WEBJS - When the forwarded message type is video, the webhook notification will not be pushed.

**Comment by devlikepro** [comment]
Hi! Tried these steps for 3 accounts - 3rd account connected to WAHA
1. 1 => 2 video (https://github.com/devlikeapro/waha/raw/core/examples/video.mp4)
2. 2 forwarded the image to 3rd account (WAHA)
3. Got the webhooks with `media.url` from 3rd account (WAHA)

What docker image do you use btw? 
If regular (`devlikeapro/waha-plus`) one - try `devlikeapro/waha-plus:chrome`
https://waha.devlike.pro/docs/how-to/engines/#examples

Let me know if it helps or don't and I'll reopen the issue if it doesn't!


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by HuangDaHui** [comment]
devlikeapro/waha-plus:chrome
Problem solved using this image
Thank you
