### ISSUE TITLE
[BUG][NOWEB] - Add preview for Video in Status messages

### ISSUE THREAD

**Issue by sg957** [allburov/whatsapp-http-api#548]
When sending a story status of a video, the messages sent in the engine are not displayed on the client until the download of the entire video is finished, unlike the normal sending of a status through the application, which has a preview and the file is downloaded while it is playing,

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Hi! Could you try with the example video? Just tested it on the latest version - works good, it has the preview

`POST /api/{SESSION}/status/video`

```json
{
  "contacts": [
    "123123@c.us"
  ],
  "file": {
    "mimetype": "video/mp4",
    "filename": "video.mp4",
    "url": "https://github.com/devlikeapro/waha/raw/core/examples/video.mp4"
  },
  "caption": "string"
}
```

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Hi! waiting for the feedback for few days and will close the issue if don't get it

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
