### ISSUE TITLE
[BUG][WEBJS] - failed when get session 

### ISSUE THREAD

**Issue by renaldpputra** [allburov/whatsapp-http-api#549]
i got this error when get session

version: 2024.6.8
OAS 3.1

[Nest] 30  - 09/18/2024, 6:12:34 AM     LOG [SessionManager] 'default' - starting session...
[Nest] 30  - 09/18/2024, 6:12:34 AM     LOG [Webhook - default] Configuring webhooks for https://webhook.site/11111111-1111-1111-1111-11111111...
[Nest] 30  - 09/18/2024, 6:12:34 AM     LOG [Webhook - default] Event 'session.status' is enabled for url: https://webhook.site/11111111-1111-1111-1111-11111111
[Nest] 30  - 09/18/2024, 6:12:34 AM     LOG [Webhook - default] Webhooks were configured for https://webhook.site/11111111-1111-1111-1111-11111111.
[Nest] 30  - 09/18/2024, 6:12:34 AM     LOG [Webhook - default] Sending POST to https://webhook.site/11111111-1111-1111-1111-11111111...
[Nest] 30  - 09/18/2024, 6:12:34 AM     LOG [Webhook - default] Event 'message' is enabled for url: https://webhook.site/11111111-1111-1111-1111-11111111
[Nest] 30  - 09/18/2024, 6:12:35 AM     LOG [Webhook - default] POST request was sent with status code: 429
[Nest] 30  - 09/18/2024, 6:23:17 AM    WARN [SessionManager] Error while getting engine info
[Nest] 30  - 09/18/2024, 6:23:17 AM    WARN [SessionManager] Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'VERSION')
    at pptr://__puppeteer_evaluation_script__:2:33

**Comment by devlikepro** [comment]
hi! Try to update waha, it's too old, there was important fixes 
https://waha.devlike.pro/docs/overview/changelog/#20249
```bash
docker pull devlikeapro/waha
```

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
https://waha.devlike.pro/docs/how-to/install/

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by renaldpputra** [comment]
IT WORKS ! Thanks
