### ISSUE TITLE
[BUG][WEBJS] - It says message sent succesfully , when check via api looks as sent

### ISSUE THREAD

**Issue by evollution** [allburov/whatsapp-http-api#552]
[BUG][WEBJS] - It says message sent succesfully , when check via api looks as sent but when checking the phone there is no such message sent, session is working.

This is not ok because we have no idea when waha stops from sending messages

**Comment by devlikepro** [comment]
Hi! Found one more state when the session can be disconnected, but browser still working... :( 
We'll handle it in `2024.10.1`, just wanna make sure it helps in this case :crossed_fingers: 

After the fix it'll restart the session, BUT one `sendText` request (or few, depends on timing) will pass anyway and return OK, but won't send message actually :( 

Not sure why it doesn't resend it when the browser gets back online, probably we don't create some internal entities in storage, we'll dig into it later! https://github.com/devlikeapro/waha/issues/559


Probably the best way to really make sure the message send - is to listen `message.any` events right now and mark those that you send as "sent" or repeat after few minutes
https://waha.devlike.pro/docs/how-to/webhooks/#messageany

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by MadhabaPatra** [comment]
Hi @devlikepro ,

The message seems to have been sent, but when I checked WhatsApp(Phone), there is no message. However, in the screenshot (WAHA dashboard), it shows the timer icon. Please check the screenshot.

<img width="53" alt="Image" src="https://github.com/user-attachments/assets/a785f916-0419-4145-a151-c8940993bce3" />

What could be the issue?
VERSION -  2024.12.6 (WEBJS)

**Comment by devlikepro** [comment]
@MadhabaPatra try repairing (logout/scan qr) for the session

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
