### ISSUE TITLE
[Feature Request] Event for "waiting" / "cipher" text messages

### ISSUE THREAD

**Issue by arielpts** [allburov/whatsapp-http-api#554]
Sometimes, when receiving a message, whatsapp displays "Waiting for this message...", and waits for the message to be cleared before sending any webhook.
Example:
<img width="798" alt="Screenshot 2024-09-19 at 17 22 55" src="https://github.com/user-attachments/assets/8b7044f7-e07c-493a-a147-8ced0fdf7619">

> A clear and concise description of what the problem is. Ex.

In our use case (using a multi-agent interface), it's important to display the same information to the agent (Waiting for this message).

> A clear and concise description of what you want to happen.

A solution would be to forward the `Events.MESSAGE_CIPHERTEXT` that wa.js supports here: https://github.com/devlikeapro/whatsapp-web.js/blob/main/src/Client.js#L716

Something like:
![image (2)](https://github.com/user-attachments/assets/35ef5065-24f1-4559-839b-bbf2eb9e5496)

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Hi! Yeah, make sense, thank you for the report and possible solution! 
it'll be a bit hard to replicate that behaviour tho :thinking: but we'll figure it out!

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by arielpts** [comment]
Thanks!

Apparently this problem is related to E2E encryption, versions or network.

Perhaps doing the opposite of the "solution" that the Whatsapp says may work:
https://faq.whatsapp.com/3398056720476987?cms_id=3398056720476987&draft=false

To reproduce, I would try to get a number that exchanges a lot of messages with new numbers.

In our setup for some reason (WA Business,  exchanging ~4K messages per day and it's concentrated in some hours) it is happening ~10 day, so if you want us to QA we can easily reproduce.

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
got it, thank you for the details, yeah, probably we could emulate it by sending encrypted message with wrong key :thinking: We'll check that! :+1: 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
https://waha.devlike.pro/docs/how-to/webhooks/#messagewaiting
`message.waiting` in 2024.10.1

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
