### ISSUE TITLE
Feature Request] Heroku compatible deploymend - listen PORT, add WAHA_BASE_URL for media

### ISSUE THREAD

**Issue by italoj** [allburov/whatsapp-http-api#555]
I'm attempting to deploy the Waha Plus image to Heroku, but I keep encountering the following error:

![CleanShot 2024-09-21 at 19 21 16@2x](https://github.com/user-attachments/assets/fdc170e9-05f9-4cc3-8f78-641ed3cca883)

I'd appreciate any insights or suggestions on how to resolve this issue.

Thanks in advance!

**Comment by devlikepro** [comment]
Hi! 
Looks like you need to map `PORT` environment variable to `WHATSAPP_API_PORT` https://waha.devlike.pro/docs/how-to/config/#common so WAHA starts listening on the right port



[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Probably we could add it in the project as well, looks simple.


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by italoj** [comment]
Thanks for your attention.

Heroku dynamically assigns the PORT environment variable at runtime, so each time the app restarts, a random value is assigned. This makes it impossible to manually set WHATSAPP_API_PORT with a fixed value (since it's not static), and I can't use something like WHATSAPP_API_PORT=$PORT.

**Comment by devlikepro** [comment]
> I can't use something like WHATSAPP_API_PORT=$PORT.

Heroku doesn't allow it? that's a shame

We'll handle it in WAHA 2024.10.1 release, no worries! :+1: 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by italoj** [comment]
I really appreciate that. Thank you team 💪

**Comment by devlikepro** [comment]
https://waha.devlike.pro/docs/how-to/config/#common
`PORT` and `WAHA_BASE_URL` is available so you can set it in heroku :rocket: 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
