### ISSUE TITLE
[BUG][WEBJS] - Unauthorised Access to Server pc Where Docker and Waha Installed and Suspicious Activity Inquiry

### ISSUE THREAD

**Issue by smihheemmaanntt** [allburov/whatsapp-http-api#556]
I have been using your WhatsApp unofficial API service purchased from WAHA. However, on 22-09-24, at around 3:51 AM Indian Standard Time, my server was accessed without authorization, and a software named "Unminer" was installed on the system. Additionally, various websites were surfed on my server during this time.

Given these unusual activities, I wanted to inquire whether your repository or any associated files might have caused this. Could you kindly confirm if this access or software installation has any connection to the API service provided by WAHA?

I have attached two screenshots detailing the suspicious activity for your reference. Please review them and advise on the matter at your earliest convenience.

Thank you for your assistance.

Best regards,
HEMANT
![WhatsApp Image 2024-09-22 at 12 34 19_abbc3629](https://github.com/user-attachments/assets/1b0831aa-6d21-42b3-90a3-f908af4f2b60)
![WhatsApp Image 2024-09-22 at 12 34 54_1c7b6d8b](https://github.com/user-attachments/assets/0adaa4a5-a9d5-4fc0-880b-6de8b6d2672c)

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Hi! 
The project is fully open source:
1. WAHA Core https://github.com/devlikeapro/waha
2. WAHA Plus https://github.com/devlikeapro/waha-plus (available for PRO subscribers)

Unlikely we'd do something like this with so many eyes on us :) 

As for securyty - we recently updated docker image used in Dockefile so it should be more safe.
However, the project still uses several old libraries, but unlikely they could cause such issues if you run it inside docker container.
Docker container is like a sandbox, no one can get out of it, only this sandbox can be damaged if got hacked, not ouside of the system.
We'll update the libs by the end of the month anyway :crossed_fingers: 

Windows sucks anyway, consider using Linux as host OS.

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Weird that your server didn't get encrypted, change all your passwords and update OS immediately, otherwise you can endup with mallox or similar ransomware

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
