### ISSUE TITLE
I want to ask question about NoWeb

### ISSUE THREAD

**Issue by UmairHashmi90** [allburov/whatsapp-http-api#558]
Basically i have run WAHA on my system with Command

docker run -it --rm -p 3000:3000/tcp --name waha devlikeapro/waha

here it ren on WEBJS but i want to run it on NOWEB when i run using command 
docker run -it -e "WHATSAPP_DEFAULT_ENGINE=NOWEB" devlikeapro/waha

then how to create session or send message

**Comment by devlikepro** [comment]
You need to combine all arguments in the command:
```bash
docker run -it --rm -p 3000:3000/tcp --name waha -e "WHATSAPP_DEFAULT_ENGINE=NOWEB" devlikeapro/waha
```

Here's full commands and docker compose "almost" ready for production:
https://waha.devlike.pro/docs/how-to/install/

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
