### ISSUE TITLE
[BUG][NOWEB] - NOWEB error message sent

### ISSUE THREAD

**Issue by HuangDaHui** [allburov/whatsapp-http-api#561]
request：
{
  "text": "JVBET . VIP",
  "session": "588917",
  "reply_to": null,
  "chatId": "628314359****@c.us",
  "caption": null,
  "url": null,
  "title": null,
  "longitude": 0.0,
  "latitude": 0.0,
  "file": null,
  "contacts": null,
  "mentions": null
}
response:
{"statusCode":500,"timestamp":"2024-09-25T08:10:20.903Z","exception":{"stack":"Error: Connection Closed\n    at sendRawMessage (/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:59:19)\n    at sendNode (/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:78:16)\n    at query (/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:142:15)\n    at getUSyncDevices (/app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:168:30)\n    at /app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:401:57\n    at Object.transaction (/app/node_modules/@adiwajshing/baileys/lib/Utils/auth-utils.js:136:32)\n    at relayMessage (/app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:307:30)\n    at Object.sendMessage (/app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:677:23)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","message":"Connection Closed","data":null,"isBoom":true,"isServer":false,"output":{},"name":"Error"},"request":{"path":"/api/sendtext","method":"POST","body":{"text":"JVBET . VIP","session":"588917","chatId":"628314359****@c.us","longitude":0,"latitude":0},"query":{}},"version":{"version":"2024.9.2","engine":"NOWEB","tier":"PLUS","browser":"/usr/bin/chromium"}}

**Comment by HuangDaHui** [comment]
"version":"2024.9.2"
Not sure if it is affected by the version?

**Comment by HuangDaHui** [comment]
Or will it be affected by the number?
The messages sent and received are all related numbers 6282312******

**Comment by devlikepro** [comment]
Hi! Does the retry help? 
If yes - that's fine, it could happen time to time - due to WA restart or our session restart (every 30 minutes).
If you have detailed logs around this request (like 1 minute before, 1 minute after) would rely help here :pray: 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
