### ISSUE TITLE
[BUG][WEBJS] - Inconsistent READ Acknowledgment Delivery in WEBJS Engine

### ISSUE THREAD

**Issue by Sabyrzhanuly** [allburov/whatsapp-http-api#565]
Hi!

> I'm not entirely sure if this is a bug, but the issue definitely exists.

In 95% of cases, after sending a message, I only receive a webhook up to ackName DEVICE. I noticed the issue when the recipient replied, but I never received a READ acknowledgment. Although some users may disable read receipts, I sent 38 messages, and only two triggered READ, the rest stopped at DEVICE. I'm not sure if this happens because the recipient opens the message much later.

```
{
  "version": "2024.10.1",
  "engine": "WEBJS",
  "tier": "PLUS",
  "browser": "/usr/bin/chromium"
}
```

To Reproduce

1. Send a message using the WEBJS engine.
2. Check for webhook events.
3. Only receive DEVICE acknowledgments, few READ events.

Expected behavior

I expected to receive READ acknowledgments when the recipient reads the message.

[response_1727636166650.json](https://github.com/user-attachments/files/17180824/response_1727636166650.json)

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by Sabyrzhanuly** [comment]
@devlikepro 

I'm eagerly waiting for your response.

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Hi! looking at this
Did it work in previous version or you just started with ack research?

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by Sabyrzhanuly** [comment]
> Hi! looking at this Did it work in previous version or you just started with ack research?
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

I just started using it.

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
@Sabyrzhanuly have they added your account to their contact list? I see it's notifications about orders, right?

Because if not - I believe WhatsApp doesn't send ack "read" in that case. 
Even more, after they added your number, it WILL NOT send ack read for previous messages.

It behaviour you can see in the official apps as well, the first "message" to the contacts with "two gray arrows"
![image](https://github.com/user-attachments/assets/836411bb-3f01-420a-8888-d379f3f3033b)


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by Sabyrzhanuly** [comment]
> @Sabyrzhanuly have they added your account to their contact list? I see it's notifications about orders, right?
> 
> Because if not - I believe WhatsApp doesn't send ack "read" in that case. Even more, after they added your number, it WILL NOT send ack read for previous messages.
> 
> It behaviour you can see in the official apps as well, the first "message" to the contacts with "two gray arrows" ![image](https://private-user-images.githubusercontent.com/155617407/372053842-836411bb-3f01-420a-8888-d379f3f3033b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2OTM2MjksIm5iZiI6MTcyNzY5MzMyOSwicGF0aCI6Ii8xNTU2MTc0MDcvMzcyMDUzODQyLTgzNjQxMWJiLTNmMDEtNDIwYS04ODg4LWQzNzlmM2YzMDMzYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkzMFQxMDQ4NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOTk2NTE1ZGYxNGUzNjQ1MzA5YWMyZjk3YzBhMWYyY2QwNWYyNGRmMjhhZTA0MDdlZGRkNjc2ZWI0NTBmYTc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kzYOKRNstdvt6jJqCemnLh14U5zEThK3kYt1gIkK51Y)
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

Yes, these are order notifications, and my number is not always in the recipient's contacts. So, does this mean I cannot receive the "read" status in such cases, correct?

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
>does this mean I cannot receive the "read" status in such cases, correct?

Yes, exactly! You need to ask them to add your phone number (it'll also increase your score on WA side if many people have your account in contacts) and you'll get "read" status on the future messages

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
