### ISSUE TITLE
[Feature Request] Add profile picture object be included in the GET /api/{session}/chats endpoint response

### ISSUE THREAD

**Issue by tiarsagitar** [allburov/whatsapp-http-api#566]
**Is your feature request related to a problem? Please describe.** I'm always
frustrated when facing timeouts when trying to fetch profile pictures separately using the GET /api/contacts/profile-picture?contactId= endpoint in a loop.

** A clear and concise description of what the problem is.
I would like to add a profile picture url object in the GET /api/{session}/chats endpoint response. For example:

```
[{
    "id": "1232132@g.us",
    "readOnly": false,
    "ephemeralExpiration": 0,
    "ephemeralSettingTimestamp": 0,
    "conversationTimestamp": 1726799908,
    "name": "Contoh",
    "profilePictureUrl": "....",
    ...
}]
```

**Comment by devlikepro** [comment]
I believe it's for NOWEB engine, right?

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by tiarsagitar** [comment]
> I believe it's for NOWEB engine, right?
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

Yes, that’s correct. I use the NOWEB engine.

**Comment by huangzhong0406** [comment]
+1

**Comment by devlikepro** [comment]
Added in `2024.12.6` :rocket: 

https://waha.devlike.pro/docs/how-to/chats/#get-chats-overview

----

### Get chats overview
Get chats "overview" - the API that almost all  [**Chat UI**](https://waha.devlike.pro/docs/how-to/dashboard/#chat-ui) client needs!
```
GET /api/{session}/chats/overview?limit=20&offset=0
```

**Response** contains the main info you need to show in the chat list:
1. `id` - chat id
2. `name` - chat name (if any)
3. `picture` - chat picture (if any)
4. `lastMessage` - last message in the chat (if any). 
5. `_chat` - the structure depends on engine you're using

⚠️ `lastMessage` doesn't have media attachments, you need to [get message by id]({{< relref "#get-message-by-id" >}}) to get media attachments.

```json
[
  {
    "id": "12312l123@c.us",
    "name": "John Doe",
    "picture": "https://example.com/picture.jpg",
    "lastMessage": {
      "id": "true_11111111111@c.us_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "timestamp": 1667561485,
      "from": "11111111111@c.us",
      "fromMe": true,
      "to": "11111111111@c.us",
      "body": "Hi there!",
      ...
    },
    "_chat": {
      ...
    }
  }
]

```

**Pagination**:
- `limit=100` - limit the number of chats to return
- `offset=0` - skip the number of chats from the start

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
