### ISSUE TITLE
[BUG][NOWEB] - missing webhook event 

### ISSUE THREAD

**Issue by mrbitencourt** [allburov/whatsapp-http-api#567]
**Describe the bug**

Everytime that we receive this type of messages ("sent by advertisement") on phone we did not receive waha webhook.
Below you can see the message into phone but we did not received the incoming message into webhook.

**Version**

{
  "version": "2024.8.5",
  "engine": "NOWEB",
  "tier": "PLUS",
  "browser": "/usr/bin/chromium"
}

**Screenshots**

![297239](https://github.com/user-attachments/assets/02f20866-dd15-4971-b1d5-10d9aac07bc4)

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
let's try 2024.10.4 version!

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
