### ISSUE TITLE
Send message Status issue either its send or not

### ISSUE THREAD

**Issue by UmairHashmi90** [allburov/whatsapp-http-api#569]
I have an issue when i send a message or file  to any number is response status Pending even if the receiver number is not register on whatsapp
json rsponse
`{
    "key": {
        "remoteJid": "1111111@s.whatsapp.net",
        "fromMe": true,
        "id": "3EB027FBB9CD0225E9D27F"
    },
    "message": {
        "extendedTextMessage": {
            "text": "Hi there!"
        }
    },
    "messageTimestamp": "1727857121",
    "status": "PENDING"
}`

**Comment by devlikepro** [comment]
Hi! You can check the `chatId` before by requesting https://waha.devlike.pro/docs/how-to/contacts/#check-phone-number-exists
```
GET /api/contacts/check-exists?phone=1111111&session=default
```
and see the result in 
```
{
  "numberExists": true,
  "chatId": "1111111@c.us"
}
```

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
