### ISSUE TITLE
[Feature Request]I would like to ask how can I increase the speed of my API, for example, if I want to stress test and make a large number of calls, can adding sessions increase the speed? Or is the API access speed of a waha server limited and cannot be increased by adding sessions and ws accounts?

### ISSUE THREAD

**Issue by leviowenpunk** [allburov/whatsapp-http-api#570]
Any good suggestions?

**Comment by devlikepro** [comment]
Hi! What is your use case? 
> make a large number of calls

It depends on the calls you're making, not all of them are equal

API is fast itself, most of the work on WA side.
You may running sessions in different containers if you have any problem https://waha.devlike.pro/blog/waha-scaling-how-to-handle-500-sessions/

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
