### ISSUE TITLE
[Feature Request] Last message and Contact on Get all chats

### ISSUE THREAD

**Issue by gamoridev** [allburov/whatsapp-http-api#573]
On Engine **NOWEB**.
I would like to know if we can add the **"Last Message"** from every chat on **get all chats** Request.
Also, if the contact info can be added too.

It would be awesome if we have the _profilePicture_ included on the **Contact** Object, but I know that this could underperform the query.
But at least the _name_ of the contact would be great.

```json
  {
    "id": "xxxxxx@s.whatsapp.net",
    "readOnly": false,
    "ephemeralExpiration": 0,
    "ephemeralSettingTimestamp": 0,
    ...
    "lidJid": "xxxxxxx@lid",
    "lastMessageRecvTimestamp": 1728314011
    "lastMessage": "<BODY OF LAST MESSAGE ON CHAT>"
    "contact": {
      "id": "xxxxx",
      "name": "Jhon Doe",
      "profilePicture": "https://xxxx.png" (nice to have)
    }
  },
```

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Related https://github.com/devlikeapro/waha/issues/566

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Added in `2024.12.6` :rocket: 

https://waha.devlike.pro/docs/how-to/chats/#get-chats-overview

----

### Get chats overview
Get chats "overview" - the API that almost all  [**Chat UI**](https://waha.devlike.pro/docs/how-to/dashboard/#chat-ui) client needs!
```
GET /api/{session}/chats/overview?limit=20&offset=0
```

**Response** contains the main info you need to show in the chat list:
1. `id` - chat id
2. `name` - chat name (if any)
3. `picture` - chat picture (if any)
4. `lastMessage` - last message in the chat (if any). 
5. `_chat` - the structure depends on engine you're using

⚠️ `lastMessage` doesn't have media attachments, you need to [get message by id]({{< relref "#get-message-by-id" >}}) to get media attachments.

```json
[
  {
    "id": "12312l123@c.us",
    "name": "John Doe",
    "picture": "https://example.com/picture.jpg",
    "lastMessage": {
      "id": "true_11111111111@c.us_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "timestamp": 1667561485,
      "from": "11111111111@c.us",
      "fromMe": true,
      "to": "11111111111@c.us",
      "body": "Hi there!",
      ...
    },
    "_chat": {
      ...
    }
  }
]

```

**Pagination**:
- `limit=100` - limit the number of chats to return
- `offset=0` - skip the number of chats from the start



[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
