### ISSUE TITLE
[Feature Request] Proposal: Separate Dashboard with One-Click Update Button for Seamless Release Management

### ISSUE THREAD

**Issue by Sabyrzhanuly** [allburov/whatsapp-http-api#574]
Hi,

I have a suggestion.

Is it possible to run the dashboard separately in its own container and include an "Update to the next release" button inside the dashboard? In the settings, there would be a field to input a Docker Hub API key, and the update process would be triggered by pressing the button. This would be very convenient as it eliminates the need to access the server for urgent updates.

Thank you!

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Yeah, that would be great, but people use too different environments... 

Probably we could provide a UI where you can put few things and it'd do the update for you tho via ssh :thinking: 
like what we'll need basically:
1. ssh server\username\password (or key)
2. docker key from portal.devlike.pro
3. Folder where your docker-compose.yaml lives

It'll work only with docker-compose installations, however 
https://waha.devlike.pro/docs/how-to/install/

Let's see what we can do, but not this year 100%, we need to work on engines and new features

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by Sabyrzhanuly** [comment]
> Yeah, that would be great, but people use too different environments...
> 
> Probably we could provide a UI where you can put few things and it'd do the update for you tho via ssh 🤔 like what we'll need basically:
> 
> 1. ssh server\username\password (or key)
> 2. docker key from portal.devlike.pro
> 3. Folder where your docker-compose.yaml lives
> 
> It'll work only with docker-compose installations, however https://waha.devlike.pro/docs/how-to/install/
> 
> Let's see what we can do, but not this year 100%, we need to work on engines and new features
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

That's exactly what I meant. It would be really great, and I'm looking forward to it!

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
will work on that https://github.com/devlikeapro/waha/issues/419

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
