### ISSUE TITLE
[BUG] - looks like webhook ignores "retries" and send request endlessly 

### ISSUE THREAD

**Issue by devlikepro** [allburov/whatsapp-http-api#580]
[BUG] - looks like webhook ignores "retries" and send request endlessly 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
```json
{
    "name": "default",
    "config": {
        "webhooks": [
            {
                "url": "https://httpbin.org/status/504",
                "events": [
                    "message",
                    "session.status",
                    "message.ack"
                ],
                "retries": {
                    "delaySeconds": 1,
                    "attempts": 3
                }
            }
        ]
    }
}
```

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
https://discord.com/channels/1228605717372604466/1293465810240802897/1293534838304804876

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by hamayreh** [comment]
What is the expected ETA on this?

**Comment by devlikepro** [comment]
looks good, it does retry only attempts times and then stops retries 🤔 
It could be because of this bug https://github.com/devlikeapro/waha/issues/579 - it basiclly creates two session at once - normal (one you see in Dashboard/API) and shadow one which can negatively influence each other... 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
### Retries
You can configure retry policy for webhooks by settings `config.retries` structure when `POST /api/sessions/`:

```json
{
  "name": "default",
  "config": {
    "webhooks": [
      {
        "url": "https://webhook.site/11111111-1111-1111-1111-11111111",
        "events": [
          "message"
        ],
        "retries": {
          "delaySeconds": 2,
          "attempts": 15,
          "policy": "constant"
        }
      }
    ]
  }
}

```

Possible `policy`:
- `constant` - retry with the same delay between attempts (2, 2, 2, 2)
- `linear` - retry with linear backoff (2, 4, 6, 8)
- `exponential` - retry with exponential backoff with 20% jitter (2, 4.1, 8.4, 16.3).


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
