### ISSUE TITLE
[Feature Request][NOWEB] - Send Instant Video Messages

### ISSUE THREAD

**Issue by johndoely** [allburov/whatsapp-http-api#585]
When interacting inside a group it is import to be able to send instant (round) videos like this one below:

<img width="180" alt="Captura de Tela 2024-10-09 às 21 00 43" src="https://github.com/user-attachments/assets/d9314f2c-9172-4fc2-85df-e10195c80217">

Maybe you could create a new endpoint **/api/sendInstantVideo** or just add a parameter to /api//sendVideo like isInstant to set true or false, so it would look like this:

```
{
    "session": "default",
    "chatId": "11111111111@c.us",
    "file": {
        "mimetype": "video/mp4",
        "filename": "video.mp4",
        "url": "https://mysite.com/myvideo.mp4"
    },
    "caption": "",
    "isInstant":true
}
```

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
yeah, something we missed :( 
added in `2024.11` release, but the request will be
```json
{
    "session": "default",
    "chatId": "11111111111@c.us",
    "file": {
        "mimetype": "video/mp4",
        "filename": "video.mp4",
        "url": "https://mysite.com/myvideo.mp4"
    },
    "caption": "",
    "isNote":true
}
```
WA calls it this way, I believe:
https://faq.whatsapp.com/993629751672762/?cms_platform=android

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
