### ISSUE TITLE
[BUG][NOWEWB] - NOWEB will remain in the STARTING state after automatic restart. It requires manual ReStart to change to WORKING.

### ISSUE THREAD

**Issue by HuangDaHui** [allburov/whatsapp-http-api#586]
![1728549469965](https://github.com/user-attachments/assets/8ac85011-9497-4243-b621-8e1abad66980)
NOWEB will remain in the STARTING state after automatic restart. It requires manual ReStart to change to WORKING.

**Comment by HuangDaHui** [comment]
This is an accidental phenomenon. Normally, it will automatically change to WORKING after a few seconds of STARTING.

**Comment by HuangDaHui** [comment]
Also, I would like to ask if it is possible to turn off the automatic restart of noweb?

**Comment by HuangDaHui** [comment]
version 2024.10.1

**Comment by HuangDaHui** [comment]
![d70d1f8b892aadcb6396ad5c458ca157](https://github.com/user-attachments/assets/b238c1d2-2af3-41e9-96f5-4525677802f3)
Suddenly a large batch changed to the failed state, and returned to normal after restarting.

**Comment by HuangDaHui** [comment]
![image](https://github.com/user-attachments/assets/fb1075f2-b698-4341-bb2a-f96a175a34cf)
Suddenly a large batch changed to the failed state, and returned to normal after restarting.

**Comment by devlikepro** [comment]
> I would like to ask if it is possible to turn off the automatic restart of noweb?

You need to remove `WHATSAPP_RESTART_ALL_SESSIONS` from the environemnt variables





[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
> Normally, it will automatically change to WORKING after a few seconds of STARTING

yeah, noticed this behaviour after container restart too, checking it!

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Quick question - do you use file or mongodb? 

We should start CRM system or something to avoid such question over an over :D 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by HuangDaHui** [comment]
> Quick question - do you use file or mongodb?
> 
> We should start CRM system or something to avoid such question over an over :D
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
use mongodb

**Comment by HuangDaHui** [comment]
> > I would like to ask if it is possible to turn off the automatic restart of noweb?
> 
> You need to remove `WHATSAPP_RESTART_ALL_SESSIONS` from the environemnt variables
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
OK, thanks

**Comment by devlikepro** [comment]
Let's try `2024.10.5` and see if it helps :crossed_fingers: 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by HuangDaHui** [comment]
> > I would like to ask if it is possible to turn off the automatic restart of noweb?
> 
> You need to remove `WHATSAPP_RESTART_ALL_SESSIONS` from the environemnt variables
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
Hi，I deleted the WHATSAPP_RESTART_ALL_SESSIONS environment variable, will this have any impact on NOWEB? I think your design like this must be useful

**Comment by HuangDaHui** [comment]
> Let's try `2024.10.5` and see if it helps 🤞
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

![image](https://github.com/user-attachments/assets/f168e341-4dc3-4a51-8ddd-f0dad28063d1)
Doesn't seem to help, these sessions stay on starring

**Comment by devlikepro** [comment]
@HuangDaHui could you try to add `WAHA_AUTO_START_DELAY_SECONDS=1` environment variable? 
The issue likely because all sessions starts at once (almost), but with 1 seconds delay it can help slowly run them one by one to avoid such issues.

If there's something in logs right after the start, it'd help us as well :pray: 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by HuangDaHui** [comment]
> I deleted the WHATSAPP_RESTART_ALL_SESSIONS environment variable, will this have any impact on NOWEB? I think your design like this must be useful
ok let me try
I deleted the WHATSAPP_RESTART_ALL_SESSIONS environment variable, will this have any impact on NOWEB? I think your design like this must be useful

**Comment by HuangDaHui** [comment]
> ok let me try
> I deleted the WHATSAPP_RESTART_ALL_SESSIONS environment variable, will this have any impact on NOWEB? I think your design like this must be useful

ok let me try
I deleted the WHATSAPP_RESTART_ALL_SESSIONS environment variable, will this have any impact on NOWEB? I think your design like this must be useful

**Comment by HuangDaHui** [comment]
> @HuangDaHui could you try to add `WAHA_AUTO_START_DELAY_SECONDS=1` environment variable? The issue likely because all sessions starts at once (almost), but with 1 seconds delay it can help slowly run them one by one to avoid such issues.
> 
> If there's something in logs right after the start, it'd help us as well 🙏
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

ok let me try
I deleted the WHATSAPP_RESTART_ALL_SESSIONS environment variable, will this have any impact on NOWEB? I think your design like this must be useful

**Comment by HuangDaHui** [comment]
> > I would like to ask if it is possible to turn off the automatic restart of noweb?
> 
> You need to remove `WHATSAPP_RESTART_ALL_SESSIONS` from the environemnt variables
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

![image](https://github.com/user-attachments/assets/1aa8ff84-651b-493e-9184-fde5a9aa4318)
Deleting it seems to have no effect. It still turns into starting in large batches and cannot be started. I don’t know why?

**Comment by HuangDaHui** [comment]
Could it be related to MongoDB? I have another container with relatively few sessions, and this never seems to happen.

**Comment by HuangDaHui** [comment]
> > > I would like to ask if it is possible to turn off the automatic restart of noweb?
> > 
> > 
> > You need to remove `WHATSAPP_RESTART_ALL_SESSIONS` from the environemnt variables
> > [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
> 
> ![image](https://private-user-images.githubusercontent.com/16524141/378697502-1aa8ff84-651b-493e-9184-fde5a9aa4318.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NzYzMjQsIm5iZiI6MTcyOTU3NjAyNCwicGF0aCI6Ii8xNjUyNDE0MS8zNzg2OTc1MDItMWFhOGZmODQtNjUxYi00OTNlLTkxODQtZmRlNWE5YWE0MzE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDA1NDcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlZTdmNzQ2ZjkzMTg3MmRjZTIxNjZhMTIzNzI5NjUxYTJiZmQwYzE5YmQ4M2Y4YTBiY2Q2OTVlMzliOGQ2MTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KHnLwyTmvkUr_dvmQnEZALW62WiOykY1R7IxL7uUOug) Deleting it seems to have no effect. It still turns into starting in large batches and cannot be started. I don’t know why?

Soon after this happens, the container will exit on its own and I need to re-docker start id

**Comment by devlikepro** [comment]
@HuangDaHui Do you use a **single MongoDB** with **multiple WAHA workers** by any change? Lioke multiple docker container but with the same MONGO_URL string? If yes - you need to setup `WAHA_WORKER_ID=waha{ID}` for each container (unique one)

Could you try to add `WAHA_WORKER_RESTART_SESSIONS=False` - in this case after restart all sessions will be stopped

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by HuangDaHui** [comment]
> @HuangDaHui Do you use a **single MongoDB** with **multiple WAHA workers** by any change? Lioke multiple docker container but with the same MONGO_URL string? If yes - you need to setup `WAHA_WORKER_ID=waha{ID}` for each container (unique one)
> 
> Could you try to add `WAHA_WORKER_RESTART_SESSIONS=False` - in this case after restart all sessions will be stopped
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

Yes, 2 containers use the same MongoDB, 1 NOWEB and 1 WEBJS
Is this the reason that causes the problem?

**Comment by HuangDaHui** [comment]
> @HuangDaHui Do you use a **single MongoDB** with **multiple WAHA workers** by any change? Lioke multiple docker container but with the same MONGO_URL string? If yes - you need to setup `WAHA_WORKER_ID=waha{ID}` for each container (unique one)
> 
> Could you try to add `WAHA_WORKER_RESTART_SESSIONS=False` - in this case after restart all sessions will be stopped
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

docker run -it -p 15101:3000/tcp --restart=always -e "WAHA_WORKER_ID=waha15101"  -e "WHATSAPP_DEFAULT_ENGINE=NOWEB" -e WHATSAPP_SESSIONS_MONGO_URL=mongodb://192.168.18.170:27018/ -e WHATSAPP_FILES_LIFETIME=0   -e WHATSAPP_RESTART_ALL_SESSIONS=True -e WAHA_AUTO_START_DELAY_SECONDS=1 devlikeapro/waha-plus
Is this okay?

**Comment by HuangDaHui** [comment]
No matter how I configure it, it always becomes starting and I don't know how to fix it
![image](https://github.com/user-attachments/assets/06b8d729-76cd-4ea3-a5b7-edfb97485d53)

**Comment by devlikepro** [comment]
`WAHA_WORKER_RESTART_SESSIONS=False` this one too
After that after each restart you need to start them manually. But let's see if it helps at all

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
> Yes, 2 containers use the same MongoDB, 1 NOWEB and 1 WEBJS

That should be fine

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by HuangDaHui** [comment]
> `WAHA_WORKER_RESTART_SESSIONS=False`这个也是 每次重启后你都需要手动启动它们。但让我们看看它是否有帮助
> 
> [![赞助人：PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

ok let me try
Is there anything else that could cause this problem to occur? It happens very frequently recently, which makes me very distressed

**Comment by devlikepro** [comment]
>Is there anything else that could cause this problem to occur?

Logs would help to understand what is happening :pray: 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by HuangDaHui** [comment]
> > Is there anything else that could cause this problem to occur?
> 
> Logs would help to understand what is happening 🙏
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

I don't know how to get useful logs. Can you tell me what command to execute to get them?

**Comment by HuangDaHui** [comment]
throw er; // Unhandled 'error' event
      ^

Error: Opening handshake has timed out
    at ClientRequest.<anonymous> (/app/node_modules/@adiwajshing/baileys/node_modules/ws/lib/websocket.js:872:7)
    at ClientRequest.emit (node:events:520:28)
    at TLSSocket.emitRequestTimeout (node:_http_client:851:9)
    at Object.onceWrapper (node:events:634:28)
    at TLSSocket.emit (node:events:520:28)
    at Socket._onTimeout (node:net:590:8)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
Emitted 'error' event on WebSocketClient instance at:
    at WebSocket.<anonymous> (/app/node_modules/@adiwajshing/baileys/lib/Socket/Client/web-socket-client.js:46:100)
    at WebSocket.emit (node:events:520:28)
    at emitErrorAndClose (/app/node_modules/@adiwajshing/baileys/node_modules/ws/lib/websocket.js:1035:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)

Is this useful?

**Comment by devlikepro** [comment]
You don't use any proxies for the sessions, right? Seen this before with bad proxies 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by HuangDaHui** [comment]
> You don't use any proxies for the sessions, right? Seen this before with bad proxies
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

No proxy used

**Comment by HuangDaHui** [comment]
Will it have any impact if I run 2 MongoDB containers in docker? They use different ports

**Comment by HuangDaHui** [comment]
The same is NOWEB, mongodb://192.168.18.170:27017. When using this MongoDB, everything is normal, but when using this MongoDB, it often gets stuck. mongodb://192.168.18.170:27018/

**Comment by devlikepro** [comment]
>  I run 2 MongoDB containers in docker

Fine if it's NOWEB and WEBJS (different engines)

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
ok, we'll try to find why the session not got restarted after the handshake timeout, that's weird. 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by HuangDaHui** [comment]
> > I run 2 MongoDB containers in docker
> 
> Fine if it's NOWEB and WEBJS (different engines)
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

`--WEBJS
docker run -it -p 15000:3000/tcp --restart=always -e "WHATSAPP_DEFAULT_ENGINE=WEBJS" -e WHATSAPP_SESSIONS_MONGO_URL=mongodb://192.168.18.170:27017/ -e WHATSAPP_FILES_LIFETIME=0  -e WHATSAPP_RESTART_ALL_SESSIONS=True  devlikeapro/waha-plus:chrome

docker run -it -p 15001:3000/tcp --restart=always -e "WHATSAPP_DEFAULT_ENGINE=WEBJS" -e WHATSAPP_SESSIONS_MONGO_URL=mongodb://192.168.18.170:27018/ -e WHATSAPP_FILES_LIFETIME=0  -e WHATSAPP_RESTART_ALL_SESSIONS=True  devlikeapro/waha-plus:chrome

--NOWEB
docker run -it -p 15100:3000/tcp --restart=always -e "WHATSAPP_DEFAULT_ENGINE=NOWEB" -e WHATSAPP_SESSIONS_MONGO_URL=mongodb://192.168.18.170:27017/ -e WHATSAPP_FILES_LIFETIME=0  -e WHATSAPP_RESTART_ALL_SESSIONS=True  devlikeapro/waha-plus

docker run -it -p 15101:3000/tcp --restart=always  -e "WHATSAPP_DEFAULT_ENGINE=NOWEB" -e WHATSAPP_SESSIONS_MONGO_URL=mongodb://192.168.18.170:27018/ -e WHATSAPP_FILES_LIFETIME=0   -e WHATSAPP_RESTART_ALL_SESSIONS=True -e WAHA_AUTO_START_DELAY_SECONDS=1  devlikeapro/waha-plus`

This is the command I currently use to run WAHA. I don’t know if there is anything that needs to be adjusted. Everything is normal with NOWEB at port 15100:3000, and everything is normal with WEBJS.
NOWEB with only port 15101:3000 often gets stuck and the container exits.

**Comment by HuangDaHui** [comment]
In addition, I would like to ask if it is possible not to restart if the sessions are in the scan qr code state? Because I think it doesn't make sense, restarting just takes up resources

**Comment by devlikepro** [comment]
> sessions are in the scan qr code state

If you stop it - it'll remember the state and won't restart it after  container restart (with `WHATSAPP_RESTART_ALL_SESSIONS=False` and `WAHA_WORKER_RESTART_SESSIONS=True`)

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by HuangDaHui** [comment]
> > sessions are in the scan qr code state
> 
> If you stop it - it'll remember the state and won't restart it after container restart (with `WHATSAPP_RESTART_ALL_SESSIONS=False` and `WAHA_WORKER_RESTART_SESSIONS=True`)
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

ok let me try

**Comment by HuangDaHui** [comment]
> @HuangDaHui Do you use a **single MongoDB** with **multiple WAHA workers** by any change? Lioke multiple docker container but with the same MONGO_URL string? If yes - you need to setup `WAHA_WORKER_ID=waha{ID}` for each container (unique one)
> 
> Could you try to add `WAHA_WORKER_RESTART_SESSIONS=False` - in this case after restart all sessions will be stopped
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
Hello, WAHA_WORKER_ID=waha{ID} After setting the ID, multiple NOWEBs can use the same MongoDB, right?

**Comment by HuangDaHui** [comment]
> @HuangDaHui Do you use a **single MongoDB** with **multiple WAHA workers** by any change? Lioke multiple docker container but with the same MONGO_URL string? If yes - you need to setup `WAHA_WORKER_ID=waha{ID}` for each container (unique one)
> 
> Could you try to add `WAHA_WORKER_RESTART_SESSIONS=False` - in this case after restart all sessions will be stopped
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

Hello, WAHA_WORKER_ID=waha{ID} After setting the ID, multiple NOWEBs can use the same MongoDB, right?

**Comment by devlikepro** [comment]
> After setting the ID, multiple NOWEBs can use the same MongoDB, right?

Yes and make sure to set `WHATSAPP_RESTART_ALL_SESSIONS=False` as well. 
Do not run the same session on two workers, no protection for it right now. On two NOWEB workers you'll see "STOPPED" sessions from the different worker

Here's example for docker-compose 
https://github.com/devlikeapro/waha/blob/core/docker-compose/docker-compose.workers.yaml

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by HuangDaHui** [comment]
> > After setting the ID, multiple NOWEBs can use the same MongoDB, right?
> 
> Yes and make sure to set `WHATSAPP_RESTART_ALL_SESSIONS=False` as well. Do not run the same session on two workers, no protection for it right now. On two NOWEB workers you'll see "STOPPED" sessions from the different worker
> 
> Here's example for docker-compose https://github.com/devlikeapro/waha/blob/core/docker-compose/docker-compose.workers.yaml
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

OK, thank you
