### ISSUE TITLE
If I purchase the paid version of the code, does it include the ability to create a chat bot that includes a button to display the restaurant menu, a button to create an order, and a button for electronic payment?

### ISSUE THREAD

**Issue by Eng-ali28** [allburov/whatsapp-http-api#589]
**Is your feature request related to a problem? Please describe.** I'm always
frustrated when [...]

> A clear and concise description of what the problem is. Ex.

**Describe the solution you'd like**

> A clear and concise description of what you want to happen.

**Describe alternatives you've considered**

> A clear and concise description of any alternative solutions or features
> you've considered.

**Additional context** Add any other context or screenshots about the feature
request here.

**Comment by devlikepro** [comment]
Hi!
Nope, I believe it's all for official API, isn't it?

Here's what API can do:
https://waha.devlike.pro/docs/how-to/engines/#messages

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
