### ISSUE TITLE
[BUG][WEBJS] - Whend Sending button Messages then Error

### ISSUE THREAD

**Issue by smihheemmaanntt** [allburov/whatsapp-http-api#593]
{
  "statusCode": 422,
  "message": "The method is not implemented by the engine.",
  "error": "Unprocessable Entity"
}
Please Provide me Full API Method of sendButtons
And Also Desktop Docker COnainer Uses Maximum Memory tell me Why ?

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
You need to use NOWEB engine for buttons. try adding `WHATSAPP_DEFAULT_ENGINE=NOWEB` to .env file (or in docker run command)
https://waha.devlike.pro/docs/how-to/engines/#noweb


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
> Docker COnainer Uses Maximum Memory tell me Why ?

How many memory exactly? How many session do you run?

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by francescodauria** [comment]
And for WEBJS? When will it be implemented?

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
no ETA yet

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
