### ISSUE TITLE
[Feature Request] [NOWEB] Ignore contacts not to be synced

### ISSUE THREAD

**Issue by gamoridev** [allburov/whatsapp-http-api#594]
Hello!
It's possible to ignore certain contacts, maybe on **session creation**, not to be _synced_?

The idea is to given list of contacts, exclude them from the Full Sync process and don't storage any info from these contacts.

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Hi! Could you explain your pain points? 
like storage is nothing for saving contacts (even if you have 100K, that's fine), so not sure what we'll solve with that approach :thinking: 
For /contacts/ we're adding `limit&offset` parameters, so you filter this properly as well https://github.com/devlikeapro/waha/issues/371

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
> don't storage any info from these contacts

Do you mean like ignore incoming messages and etc? 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by gamoridev** [comment]
> > don't storage any info from these contacts
> 
> Do you mean like ignore incoming messages and etc?

Yes! I don't want to store anything from contacts on this "ignore" list.



> Hi! Could you explain your pain points? like storage is nothing for saving contacts (even if you have 100K, that's fine), so not sure what we'll solve with that approach 🤔 For /contacts/ we're adding `limit&offset` parameters, so you filter this properly as well #371

I'll probably have many users with huge amount of messages and contacts, .ie:
![image](https://github.com/user-attachments/assets/b1c0abd4-0cd6-4bd3-9be8-07f2c4d31b50)

**But not every** "chat|contact" needs to be _synced_. So I was thinking in minimize the cost of storage (currently in MongoDB Atlas).

Right know I'll probably delete data _manually_ and _sanitize_ the database, but it would be nice if I could do something directly on Waha.

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
oh, do you want to be in free tier there? 
Unlikely we'll implement the request at all, but may be we'll add cleanup API in the future, hit +1 there if you need it!
https://github.com/devlikeapro/waha/issues/592

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by gamoridev** [comment]
> oh, do you want to be in free tier there? Unlikely we'll implement the request at all, but may be we'll add cleanup API in the future, hit +1 there if you need it! #592
> 

I've never mentioned free tier.
But ok, I'll follow updates from #592 then.


[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
