### ISSUE TITLE
[Feature Request] Make the ".sessions" folder configurable (URGENT!!!!)

### ISSUE THREAD

**Issue by Muscola78** [allburov/whatsapp-http-api#597]
**Is your feature request related to a problem? Please describe.** 
I'm always frustrated when I would like to use **WAHA HTTP API** image on **Azure**.

I would like to create an Azure app service with the WAHA API image but I can't due to the impossibility (in Azure) of using special characters in the mounting path of the external storage volume (**/app/.sessions**).
In this case the "dot" char in ".sessions" does not permit the volume mount.

**Describe the solution you'd like**

It would be useful for many to be able to make **PARAMETRIC** the name of the folder in which the sessions are saved (currently .sessions is static) using the WAHA environment variables that can be injected from outside as already happens for many configurations.
It could also be useful for users to decide different folders for each need, in case of multiple instances of the WAHA engine

**Additional context** Add any other context or screenshots about the feature
request here.

Storage configuration
![image](https://github.com/user-attachments/assets/a1f50a23-752b-4acb-8752-69c7e39d9093)

Error saving
![image](https://github.com/user-attachments/assets/a572889c-1f60-4415-a32e-4623db841e50)

For me this feature is very URGENT!!!
Thanks a lot!

**Comment by devlikepro** [comment]
In `2024.10.8` added `WAHA_LOCAL_STORE_BASE_DIR` env variables which you can override with `/app/sessions` (no dots in the path) and map the folder to the `/app/sessions` from Azure


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by CsarChvz** [comment]
@Muscola78 Do you have any terraform file with this configuration?
