### ISSUE TITLE
Evaluation failed: TypeError: Cannot read property 'attributes' of undefined

### ISSUE THREAD

**Issue by dubeychandan996** [allburov/whatsapp-http-api#6]
Getting error while installing through docker on fresh server.

**Comment by lascimmia** [comment]
Same issue trying to launch on Windows docker.

**Comment by lascimmia** [comment]
> Same issue trying to launch on Windows docker.

To be more specific:

I launch the docker via `docker run -it -v %cd%/tokens:/app/tokens -p 127.0.0.1:3000:3000/tcp allburov/whatsapp-http-api `, and it starts fine, docs on Swaggers is up and running, and some commands (like getWAVersion) just works fine.
When I try to send a message trough:

`curl -d "{\"chatId\": \"${PHONE}@c.us\", \"text\": \"Hello from WhatsApp HTTP API Free\" }" -H "Content-Type: application/json" -X POST http://localhost:3000/api/sendText`

it does nothing, but logsl like:

`WhatsApp HTTP API is running on: http://[::1]:3000
(node:27) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'get' of undefined
    at Object.window.WAPI.window.WAPI.sendMessage (/app/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:35932)
    at __puppeteer_evaluation_script__:3:53
    at ExecutionContext._evaluateInternal (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:27) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:27) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'get' of undefined
    at Object.window.WAPI.window.WAPI.sendMessage (/app/node_modules/venom-bot/dist/lib/wapi/wapi.js:1:35932)
    at __puppeteer_evaluation_script__:3:53
    at ExecutionContext._evaluateInternal (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:27) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)`

Take note that on launching Venom it warns with:

 `┌─────────────────────────────────────────────────────┐
│                                                     │
│   There is a new version of Venom 2.2.3 ➜  3.0.21   │
│   Update your package by running:                   │
│                                                     │
│   > npm update venom-bot                            │
│                                                     │
└─────────────────────────────────────────────────────┘`

In any case, thanks a lot for your work!

**Comment by lascimmia** [comment]
Trying it on a VM, have issues on QR code.

![QR Code](https://user-images.githubusercontent.com/71778736/126318101-59f38d0b-ba89-44db-87df-ab9ac63f1493.png)

**Comment by allburov** [comment]
Could you try to use a version without docker? 
The fork uses the latest venom https://github.com/diazzaid/whatsapp-api-venom
