### ISSUE TITLE
[BUG][WEBJS] Hi how do we use line break on text? looks ilke it wont work using '\n' or even '<br>' :(

### ISSUE THREAD

**Issue by mpdafa** [allburov/whatsapp-http-api#600]
Hi how do we use line break on text? looks ilke it wont work using '\n' or even '<br>' :(

**Comment by mpdafa** [comment]
![image](https://github.com/user-attachments/assets/a5c37429-7d16-45c9-933b-465ffc86b9e0)

**Comment by mpdafa** [comment]
using windows, wrong way to curl, nvm

**Comment by devlikepro** [comment]
@mpdafa could you share your result?

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by masitings** [comment]
Any idea how to achieve this ? Im using curl, but it seems doesn't work using \n or <br>

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
To send a "new line" (`\n`) properly in the `text` field for each environment, you need to escape it correctly or use appropriate quoting for the shell. Here's how you can handle it for `sh` (Linux), `.cmd` (Windows), and PowerShell:

---

### **1. `sh` (Linux)**

In Linux shells like `bash`, you can escape the `\n` or use proper string quoting:

```bash
curl -X 'POST' \
  'https://waha.devlike.pro/api/sendText' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "chatId": "11111111111@c.us",
  "text": "Hi there!\nHow are you?",
  "session": "default"
}'
```

If the `\n` is not interpreted as a literal new line, ensure that your shell passes it as a raw string. You can also use double quotes and escape the JSON content:

```bash
curl -X 'POST' \
  'https://waha.devlike.pro/api/sendText' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d "{\"chatId\": \"11111111111@c.us\", \"text\": \"Hi there!\\nHow are you?\", \"session\": \"default\"}"
```

---

### **2. `.cmd` (Windows Command Prompt)**

In Windows `.cmd`, JSON strings must use escaped double quotes (`\"`) and escape the `\n` properly:

```cmd
curl -X POST ^
  "https://waha.devlike.pro/api/sendText" ^
  -H "accept: application/json" ^
  -H "Content-Type: application/json" ^
  -d "{\"chatId\": \"11111111111@c.us\", \"text\": \"Hi there!\\nHow are you?\", \"session\": \"default\"}"
```

Notice the use of `^` as a line continuation character in `.cmd`.

---

### **3. PowerShell**

In PowerShell, use single quotes for the JSON payload to avoid escaping double quotes, and use backtick (`) to escape newlines:

```powershell
curl -Method POST `
  -Uri 'https://waha.devlike.pro/api/sendText' `
  -Headers @{
    'accept' = 'application/json'
    'Content-Type' = 'application/json'
  } `
  -Body '{
    "chatId": "11111111111@c.us",
    "text": "Hi there!\nHow are you?",
    "session": "default"
  }'
```

Alternatively, if you prefer escaping the JSON payload:

```powershell
curl -Method POST `
  -Uri 'https://waha.devlike.pro/api/sendText' `
  -Headers @{
    'accept' = 'application/json'
    'Content-Type' = 'application/json'
  } `
  -Body "{\"chatId\": \"11111111111@c.us\", \"text\": \"Hi there!\\nHow are you?\", \"session\": \"default\"}"
```

---

### **Summary of Key Points**
- **Linux (`sh`)**: Use single or double quotes, and escape JSON correctly.
- **Windows (`.cmd`)**: Escape `\n` and double quotes in JSON payload.
- **PowerShell**: Use single quotes for simpler JSON payloads or escape JSON manually.

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
