### ISSUE TITLE
Session gone after restart

### ISSUE THREAD

**Issue by ChrisRE11** [allburov/whatsapp-http-api#606]
Hello,

I have the problem that after a restart of the script or server restart the sessions in waha are gone. how can I set that they remain even after a restart?

Thank you

**Comment by devlikepro** [comment]
Hi! Have you followed the guide to install it or could you share how do you run waha?
https://waha.devlike.pro/docs/how-to/install/#install

If you're using `docker run` you can use this command line:
```
docker run --restart=always -d -v `pwd`/.sessions:/app/.sessions -p 3000:3000/tcp devlikeapro/waha-plus
```
https://waha.devlike.pro/docs/how-to/storages/

btw, sessions between restart available only in WAHA Plus version https://waha.devlike.pro/docs/how-to/waha-plus/

feel free to comment if it didn't help!

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
