### ISSUE TITLE
[FEATURE REQUEST]: Add / Edit / Remove Business Labels.

### ISSUE THREAD

**Issue by trexsiddharth** [allburov/whatsapp-http-api#607]
Is your feature request related to a problem? Please describe.

Currently, the available APIs for WhatsApp Business Labels allow adding contacts to existing labels and retrieving label information (such as which labels a contact belongs to or fetching all labels). However, there’s no API to add, edit, or remove labels directly. This creates a gap where label management requires manual intervention through the WhatsApp Business Manager interface, which disrupts workflows that could otherwise be automated.

Describe the solution you'd like

I kindly request the addition of APIs that would allow for full label management, including the ability to:

Add new labels to a WhatsApp Business account.
Edit the name or properties of existing labels.
Remove labels when they are no longer needed.
This would provide a seamless, automated way to manage labels, enabling businesses to handle customer segments more efficiently without relying on manual updates.

Describe alternatives you've considered

Without these APIs, I’ve had to manage labels manually through the WhatsApp Business Manager interface. This isn’t ideal for businesses with many contacts, as it adds extra steps and time to the process. While it’s possible to write custom scripts for manual updates, this approach is fragmented and makes it harder to maintain a consistent workflow.

Additional context

Adding these features would allow for more complete automation and better integration into CRM systems or other tools that rely on label management. It would be especially helpful for businesses that use labels dynamically and need to adjust them regularly to improve communication with customers.

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Added in 2024.11.1!

https://waha.devlike.pro/docs/how-to/labels/

----

## Endpoints

### Get labels

You can get a list of labels for the session using the endpoint:

```bash
GET /api/{session}/labels
```

Response:

```json

[
  {
    "id": "1",
    "name": "New Client",
    "color": 1,
    "colorHex": "#64c4ff"
  },
  ...
]
```

### Create label

```bash
POST /api/{session}/labels
```

Using `color`
```json
{
  "name": "New Client",
  "color": 1
}
```

Using `colorHex`
```json
{
  "name": "New Client",
  "colorHex" : "#64c4ff"
}
```

### Update label
```bash
PUT /api/{session}/labels/{labelId}
```

Using `color`
```json
{
  "name": "New Client",
  "color": 1
}
```

Using `colorHex`
```json
{
  "name": "New Client",
  "colorHex" : "#64c4ff"
}
```

### Delete label
```bash
DELETE /api/{session}/labels/{labelId}
```


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
