### ISSUE TITLE
[Feature Request] Add wppconnect

### ISSUE THREAD

**Issue by malik-telegram** [allburov/whatsapp-http-api#609]
![image](https://github.com/user-attachments/assets/d37c0028-e7da-4d4f-b3d3-e33913c06f94)

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Yeah, have this request for a long time :thinking:  we'll consider it in addition to webjs one! :+1: 
Comment "+1" to get notification when it's ready!
https://github.com/devlikeapro/waha/issues/101

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
