### ISSUE TITLE
Feature Request: WebJS Engine Button & Session Management Improvements

### ISSUE THREAD

**Issue by smihheemmaanntt** [allburov/whatsapp-http-api#611]
Hello, WAHA Team,

I have a few important suggestions that could enhance the performance and resource efficiency of WAHA:

1. **WebJS Engine Button**: Currently, there’s only a button available for the native engine. It would be great if you could add a similar button for the WebJS engine as well, so that users utilizing WebJS also have access to this feature.

2. **Docker Desktop CPU/RAM Usage Optimization**: WAHA consumes a significant amount of RAM and CPU on Docker Desktop, which impacts overall system performance and efficiency. Optimizing resource usage could help improve system performance for users.

3.**Session Stop Issue**: When stopping a session using the API it to stop “On Closing,” the WAHA Dashboard still shows the session as active. A more accurate session termination mechanism is needed to reflect the actual status of active sessions.

Implementing these features could make WAHA more reliable and provide a smoother experience for users. Thank you for considering these enhancements, and I appreciate your support!

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Response to Suggestions for WAHA WebJS Engine Button & Session Management Improvements

1. **WebJS Engine Button**: It’s unlikely that a dedicated button for the WebJS engine will be implemented. Instead, consider using **NOWEB** for enhanced functionality.

2. **Docker Desktop CPU/RAM Usage Optimization**: To reduce CPU and RAM usage, utilize **NOWEB**. The WebJS engine operates a Chrome instance, which inherently consumes resources. For persistent performance issues, reaching out to Chrome developers is advisable, as optimization on their end may be necessary.

3. **Session Stop Issue**: Could you elaborate on the problem with session stopping? Clarification will help in addressing the concern more effectively.

Thank you for your suggestions; they are appreciated and will be taken into consideration as we strive for ongoing improvements in WAHA's functionality and user experience. If you have further details or questions, please feel free to share!

----

1. Please stop using this f*ing chatgpt for everything, just use it as translator if you have doubts about the english!
2. Please create a dedicated issue for each problems you have, so it has it's own context. If it's just a question - consider openning a [Discussion](https://github.com/devlikeapro/waha/discussions) instead to find what we can do



[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
