### ISSUE TITLE
[Question]  Problems with Updating

### ISSUE THREAD

**Issue by Sabyrzhanuly** [allburov/whatsapp-http-api#612]
Hi.
I can't update to the new version. I'm following the steps indicated in the documentation. It used to work fine, but starting from version 2024.10.6, I've been having problems with updating.

Here are my steps:
`docker login -u devlikeapro -p {KEY}   I put my key here`
`docker compose pull`
`docker logout`

`docker compose up -d`

![image](https://github.com/user-attachments/assets/d6e11837-cb3d-49e4-844d-8e02c2c02068)

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Hi! Could you share your docker-compose, especially `image` tag?
What exactly do the commands say after they are completed? Are they all successful?

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Oh, the build with [2024.10.9](https://github.com/devlikeapro/waha-plus/tree/refs/tags/2024.10.9) failed :( 
We're handling it!

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by Sabyrzhanuly** [comment]
> Hi! Could you share your docker-compose, especially `image` tag? What exactly do the commands say after they are completed? Are they all successful?
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

image: devlikeapro/waha-plus:latest

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Fixed `2024.10.9`, now it should be on docker hub :crossed_fingers: 

If you still doesn't see it:
1. could you attach the output for each command please and provider `docker-compose.yaml` `image` tag :pray: 
2. Could you share your WAHA version that the dashboard show you?

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by Sabyrzhanuly** [comment]
> Fixed `2024.10.9`, now it should be on docker hub 🤞
> 
> If you still doesn't see it:
> 
> 1. could you attach the output for each command please and provider `docker-compose.yaml` `image` tag 🙏
> 2. Could you share your WAHA version that the dashboard show you?
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

Everything works. Successfully updated, thank you.

Apparently, there were build issues last time as well. I didn't write about it, just waited for the next version.

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
