### ISSUE TITLE
[Feature Request][WEBJS] Pin and Unpin Message in Group Chat

### ISSUE THREAD

**Issue by morning-bird** [allburov/whatsapp-http-api#613]
**Is your feature request related to a problem? Please describe.**
In a group, I need to pin a poll message manually the next day after created it at 9am. It will be really helpful if this flow could be automated.

**Describe the solution you'd like**
I kindly request the addition of APIs that would allow me to pin or unpin a message in a group chat.

**Describe alternatives you've considered**
I am using webjs to pin it, so it isn't ideal because now in my whatsapp there is 2 linked device, 1 to handle message flow (waha), 1 to handle pin and unpin flow (webjs). I really appreciate if this APIs could be implemented in Waha.

**Comment by devlikepro** [comment]
Added in **2024.11.5**
https://waha.devlike.pro/docs/how-to/chats/#pin-message

----

### Pin message

```
POST /api/{session}/chats/{chatId}/messages/{messageId}/pin
```

Payload:
```json
{
  "duration": 86400
}
```

- 24 hours - `duration=86400`
- 7 days - `duration=604800`
- 30 days - `duration=2592000`

Response:
```json
{
  "success": true
}
```

### Unpin message

```
POST /api/{session}/chats/{chatId}/messages/{messageId}/unpin
```

Response:
```json
{
  "success": true
}
```



[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
