### ISSUE TITLE
Sending button or interactive Message does not work on ios 

### ISSUE THREAD

**Issue by f-amine** [allburov/whatsapp-http-api#617]
Sending button message is not working on ios laterly is there a way to fix ?

**Comment by devlikepro** [comment]
Yeah, that's not super stable solution :( Always have a fallback to regular text messages so you can quickly switch it to it

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by masitings** [comment]
i wonder when this become stable. I think this button is a really cool feature tho.
