### ISSUE TITLE
[BUG][WEBJS] - Sending messages give us error 500 annot read properties of undefined

### ISSUE THREAD

**Issue by evollution** [allburov/whatsapp-http-api#622]
Error: response status is 500Response bodyDownload{   "statusCode": 500,   "timestamp": "2024-10-31T09:19:53.727Z",   "exception": {     "stack": "TypeError: Cannot read properties of undefined (reading 'includes')\n    at ensureSuffix (/app/dist/core/abc/session.abc.js:20:15)\n    at WhatsappSessionWebJSPlus.ensureSuffix (/app/dist/core/abc/session.abc.js:323:16)\n    at WhatsappSessionWebJSPlus.getChatMessages (/app/dist/core/engines/webjs/session.webjs.core.js:367:46)\n    at ChattingController.getMessages (/app/dist/api/chatting.controller.js:93:25)",     "message": "Cannot read properties of undefined (reading 'includes')",     "name": "TypeError"   },   "request": {     "path": "/api/messages?downloadMedia=false&chatId=11123123123&session=default&limit=100&offset=5000",     "method": "GET",     "body": {},     "query": {       "downloadMedia": "false",       "chatId": "11123123123",       "session": "default",       "limit": "100",       "offset": "5000"     }   },   "version": {     "version": "2024.10.13",     "engine": "WEBJS",     "tier": "PLUS",     "browser": "/usr/bin/chromium"   } }
--

**Comment by devlikepro** [comment]
Deploying the fix in `2024.10.14` :crossed_fingers: 

Thank you for the report with details!


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
