### ISSUE TITLE
[BUG][NOWEB] - send two message/message.any events

### ISSUE THREAD

**Issue by devlikepro** [allburov/whatsapp-http-api#623]
Sometimes NOWEB engine send two `message` and `message.any` events

:information_source:   **WORKAROUND**:
one event comes with `"ack": -1`,  you can just ignore it for now

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by maulanadiooo** [comment]
+1

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by stein257** [comment]
+1

**Comment by gamoridev** [comment]
+1

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Hi! Fixed in 2024.11.1 :crossed_fingers: 
You might get double message right after update, but in few hours it'll be good (when it's get ecnryption keys for all active chats)


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
@gamoridev do you use mongodb as well? Because we've fixed it only in mongodb connection, not if you're mapping `.sessions` folder (didn't notice the issue there)

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by gamoridev** [comment]
> @gamoridev do you use mongodb as well? Because we've fixed it only in mongodb connection, not if you're mapping `.sessions` folder (didn't notice the issue there)
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

Yes! I'm using mongodb as Storage.
Thanks!

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
