### ISSUE TITLE
[BUG] - Sqlite: attempt to write to read only database when after sometime (SQLITE_READONLY_DBMOVED)

### ISSUE THREAD

**Issue by devlikepro** [allburov/whatsapp-http-api#628]
[BUG] - Sqlite: attempt to write to read only database when after sometime (SQLITE_READONLY_DBMOVED)

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
https://github.com/sqlite/sqlite/blob/master/doc/wal-lock.md
https://github.com/WiseLibs/better-sqlite3/tree/master

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
![image](https://github.com/user-attachments/assets/b5309133-d045-4458-a9dd-539ed69991f0)


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
The next time, when it happens - could you check if there's
".sessions/noweb/waha.sqlite3" file?
You can check it by
"ls -la .sessions/noweb/"
command and may be send the response here.

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Could you also send "docker info" output from the server?


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
How many sessions on the server do you run?


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Could you send "df -hi" output as well please

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
another things to try is "chmod 777 .sessions/noweb/waha.sqlite"


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
in **2024.11.3` we'll add one potential fix for the issue :crossed_fingers: 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by OrionEnes** [comment]
> The next time, when it happens - could you check if there's ".sessions/noweb/waha.sqlite3" file? You can check it by "ls -la .sessions/noweb/" command and may be send the response here.
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

The file exists.

**Comment by OrionEnes** [comment]
> another things to try is "chmod 777 .sessions/noweb/waha.sqlite"
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

![777](https://github.com/user-attachments/assets/4beca8f0-e299-4128-b775-61a5da1a5044)
chmod permissions 777

**Comment by OrionEnes** [comment]
> Could you send "df -hi" output as well please
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

![dfhi](https://github.com/user-attachments/assets/4401e1d8-3443-4057-bc71-a06026e96cbf)

**Comment by OrionEnes** [comment]
> How many sessions on the server do you run?
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

A maximum of 20 sessions are running. The server is dedicated with 36 cores and 256 GB RAM – a very powerful server. I don’t think there should be any issues with this many sessions.

**Comment by devlikepro** [comment]
Fix in `2024.11.3`!

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
