### ISSUE TITLE
[BUG][NOWEB] - check-exists - 500 error

### ISSUE THREAD

**Issue by Semol2233** [allburov/whatsapp-http-api#639]
api endpoint = > api/contacts/check-exists?phone=01884228663&session=default use free version check feature but number is "regester whatsapp" api is not working

Mycountry code is +88

**Comment by devlikepro** [comment]
You need to provide it in E.164 international format, like 
+441884228663
so it'll be `441884228663` for `api/contacts/check-exists`
for your example

You can add existing phone number to WA and see what number it shows to find the right format

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
