### ISSUE TITLE
The session under FAILED status. Please try to restart it

### ISSUE THREAD

**Issue by webnetindia** [allburov/whatsapp-http-api#64]
How to solve this?

{
  "statusCode": 422,
  "message": "The session under FAILED status. Please try to restart it.",
  "error": "Unprocessable Entity"
}

**Comment by webnetindia** [comment]
Have tried closing the docker, restarting server, everything tried.

**Comment by webnetindia** [comment]
downloaded new docker, worked fine

**Comment by owen2345** [comment]
Restarted and downloded previous versions and not working:
```
docker pull devlikeapro/whatsapp-http-api:latest
docker pull devlikeapro/whatsapp-http-api:2023.7.16 
```
Result:
```
{
  "statusCode": 422,
  "message": "The session under FAILED status. Please try to restart it.",
  "error": "Unprocessable Entity"
}
```
And console:
```
[Nest] 34  - 07/29/2023, 2:33:26 PM     LOG [SessionManager] 'default' - starting session...
[Nest] 34  - 07/29/2023, 2:33:27 PM   ERROR [WhatsappSession - default] Error: Navigation failed because browser has disconnected!
```
Btw: I am using macos Monterrey + docker desktop "4.19.0 (106363)"
