### ISSUE TITLE
[Question]  Hello, is there any size limit for sending pictures or files? I didn't find relevant information in the documentation

### ISSUE THREAD

**Issue by HuangDaHui** [allburov/whatsapp-http-api#649]
And I found that webjs supports more formats when sending videos, while noweb can only send MP4 format.

**Comment by devlikepro** [comment]
Hi!
> is there any size limit for sending pictures or files?

The same limits that WA has, but if something doesn't work - feel free to open the issue! 
I remember some limits in HD videos or big files exists in the WA apps itself :thinking: 

>  noweb can only send MP4 format.

Yea, WEBJS (browser) converts it to mp4 internally, while NOWEB waits it in the right format. 

https://waha.devlike.pro/docs/how-to/send-messages/#send-video-imagesversionspluspng
```bash
ffmpeg -i input_video.mp4 -c:v libx264 output_video.mp4
```

Probably we could convert the files as well, feel free to open the feature request and let's see how many people are intersted in it!

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
