### ISSUE TITLE
[Question] Discrepancy Between Dashboard and Website Version Updates

### ISSUE THREAD

**Issue by Sabyrzhanuly** [allburov/whatsapp-http-api#651]
Hi

Are you sure the update has been released? My dashboard shows "Latest Version 2024.11.6, 1 worker ready for updates." However, your website lists version 2024.11.5, and there's no update available. I tried updating via compose.

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Hi! Oh, sorry, the last build failed :( Restart, now it should be 2024.11.6 if you fetch the latest version! :crossed_fingers: 
Thank you for the issue!

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
