### ISSUE TITLE
[BUG][WEBJS] - 

### ISSUE THREAD

**Issue by smihheemmaanntt** [allburov/whatsapp-http-api#654]
Unable to Genrate ScreenShot/QR in Version 2024.11.06 :
![image](https://github.com/user-attachments/assets/4da84cdf-3303-4f36-8c79-225c265bcc60)

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Hi! 
1. Logout/Remove session and rescan QR doesn't help, right?
2. What docker image do you use? `waha-plus` or `waha-plus:chrome`? Try using `:chrome` if using regular one
3. Could you check docker logs for any errors/warning right after you started the session, it'd be really helpful :pray: 
4. Could you try setting up a proxy for the session? https://waha.devlike.pro/docs/how-to/proxy/ I've seen blocked IP addresses that behaviour in similar way

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
related https://github.com/devlikeapro/waha/issues/653

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Another thing to try if the above doesn't help
1. Update image to `2024.11.7` version
2. Set `WAHA_WEBJS_CACHE_TYPE=none` environment variable (it'll disable cache, just in case of any issues with that)

https://waha.devlike.pro/docs/how-to/config/#webjs

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
