### ISSUE TITLE
[Question] Dashboard Shows New Version 2024.11.7 But No Changelog on Website

### ISSUE THREAD

**Issue by Sabyrzhanuly** [allburov/whatsapp-http-api#656]
Hi

The dashboard indicates that the new version is 2024.11.7. However, the website doesn't list the changes. Could you fix this? It's not very convenient to update blindly.

![image](https://github.com/user-attachments/assets/d42578dc-290b-4bd5-9120-31680ac2a483)

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
WAHA_WEBJS_CACHE_TYPE is in 11.7, not in 11.6.
Fixed and pushed the changed, TY! :+1: 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
