### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by abdoel1993** [allburov/whatsapp-http-api#658]
Waha Version : 2024.11.7
Engine : WEBJS

Not work, Not received QR-Code
![image](https://github.com/user-attachments/assets/e1f72b19-7aad-421e-b5f2-b26b355ebb13)

**Comment by devlikepro** [comment]
Try updating to `2024.11.8`

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
