### ISSUE TITLE
[BUG][WEBJS] - Not received QR-Code

### ISSUE THREAD

**Issue by abdoel1993** [allburov/whatsapp-http-api#659]
Waha Version : 2024.11.7
Engine : WEBJS

Not work, ![389360744-e1f72b19-7aad-421e-b5f2-b26b355ebb13](https://github.com/user-attachments/assets/9253c697-da4b-45c2-8ecf-804405f7aa3b)

**Comment by devlikepro** [comment]
Published `2024.11.8` with disabled cache by default (weird that it affects many people :thinking: ) try updating 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
