### ISSUE TITLE
[BUG][NOWEB] - noweb obtains incomplete chat history

### ISSUE THREAD

**Issue by HuangDaHui** [allburov/whatsapp-http-api#660]
I have 2 numbers in the same group. When I use number A to send a message, B cannot receive the webhook, and when I get the chat record through the interface, the record does not exist.
A is WEBJS
B is NOWEB  /api/messages?chatId=xxx&downloadMedia=false&limit=10&session=xxx

![image](https://github.com/user-attachments/assets/738b7c20-edb3-46ff-b02e-8d045cee64e1)

`[
  {
    "id": "false_120363347135619169@g.us_3A781864FBAED3A70DA9",
    "timestamp": 1732498327,
    "from": "120363347135619169@g.us",
    "fromMe": false,
    "body": "Okay",
    "to": "120363347135619169@g.us",
    "participant": "xxx",
    "hasMedia": false,
    "ack": null,
    "ackName": "UNKNOWN",
    "replyTo": null,
    "_data": {
      "key": {
        "remoteJid": "120363347135619169@g.us",
        "fromMe": false,
        "id": "3A781864FBAED3A70DA9",
        "participant": "xxx@s.whatsapp.net"
      },
      "messageTimestamp": 1732498327,
      "pushName": "Kingki",
      "broadcast": false,
      "message": {
        "conversation": "Okay",
        "senderKeyDistributionMessage": {
          "groupId": "120363347135619169@g.us",
          "axolotlSenderKeyDistributionMessage": {
            "type": "Buffer",
            "data": "Mwi16+wKEAMaIHZ5q6zj7Ntw3FajQU/E8WqOK49/3bjaPFaEUX9PeHTgIiEF1CbEsZwVrremihUMeYLW7s1CMoSQ/TvLwIdJNyJ4nVo="
          }
        },
        "messageContextInfo": {
          "deviceListMetadata": {
            "senderKeyHash": {
              "type": "Buffer",
              "data": "66B+Ofx197grlg=="
            },
            "senderTimestamp": 1731908727,
            "recipientKeyHash": {
              "type": "Buffer",
              "data": "u8kUD1rbSedN0w=="
            },
            "recipientTimestamp": 1732080007
          },
          "deviceListMetadataVersion": 2
        }
      }
    }
  },
  {
    "id": "false_120363347135619169@g.us_3ABF47CDE4784D942EFD",
    "timestamp": 1732497498,
    "from": "120363347135619169@g.us",
    "fromMe": false,
    "body": "可以 ，4點見😊",
    "to": "120363347135619169@g.us",
    "participant": "xxx",
    "hasMedia": false,
    "ack": null,
    "ackName": "UNKNOWN",
    "replyTo": null,
    "_data": {
      "key": {
        "remoteJid": "120363347135619169@g.us",
        "fromMe": false,
        "id": "3ABF47CDE4784D942EFD",
        "participant": "xxx@s.whatsapp.net"
      },
      "messageTimestamp": 1732497498,
      "pushName": "Kingki",
      "broadcast": false,
      "message": {
        "conversation": "可以 ，4點見😊",
        "senderKeyDistributionMessage": {
          "groupId": "120363347135619169@g.us",
          "axolotlSenderKeyDistributionMessage": {
            "type": "Buffer",
            "data": "Mwi16+wKEAIaICxrpRuFK2M7fQoSzW6zPlRCrHJVSH5RDxCI5f7woH+uIiEF1CbEsZwVrremihUMeYLW7s1CMoSQ/TvLwIdJNyJ4nVo="
          }
        },
        "messageContextInfo": {
          "deviceListMetadata": {
            "senderKeyHash": {
              "type": "Buffer",
              "data": "66B+Ofx197grlg=="
            },
            "senderTimestamp": 1731908727,
            "recipientKeyHash": {
              "type": "Buffer",
              "data": "u8kUD1rbSedN0w=="
            },
            "recipientTimestamp": 1732080007
          },
          "deviceListMetadataVersion": 2
        }
      }
    }
  },
  {
    "id": "false_120363347135619169@g.us_3A7A24510D99B88AE29D",
    "timestamp": 1732496357,
    "from": "120363347135619169@g.us",
    "fromMe": false,
    "body": "早晨26/11 3-4可以？😊",
    "to": "120363347135619169@g.us",
    "participant": "xxx",
    "hasMedia": false,
    "ack": null,
    "ackName": "UNKNOWN",
    "replyTo": {
      "id": "3EB0CB4639FE1F5C6E6410",
      "participant": "xxx",
      "body": "約 26/11 星期二 12pm 做training OK嗎？"
    },
    "_data": {
      "key": {
        "remoteJid": "120363347135619169@g.us",
        "fromMe": false,
        "id": "3A7A24510D99B88AE29D",
        "participant": "xxx@s.whatsapp.net"
      },
      "messageTimestamp": 1732496357,
      "pushName": "Kingki",
      "broadcast": false,
      "message": {
        "senderKeyDistributionMessage": {
          "groupId": "120363347135619169@g.us",
          "axolotlSenderKeyDistributionMessage": {
            "type": "Buffer",
            "data": "Mwi16+wKEAEaIMqaNLOyWVyasPcCcUFIxYp1e8M8xmUPhLuBdc60FJhEIiEF1CbEsZwVrremihUMeYLW7s1CMoSQ/TvLwIdJNyJ4nVo="
          }
        },
        "extendedTextMessage": {
          "text": "早晨26/11 3-4可以？😊",
          "contextInfo": {
            "stanzaId": "3EB0CB4639FE1F5C6E6410",
            "participant": "xxx@s.whatsapp.net",
            "quotedMessage": {
              "conversation": "約 26/11 星期二 12pm 做training OK嗎？"
            }
          }
        },
        "messageContextInfo": {
          "deviceListMetadata": {
            "senderKeyHash": {
              "type": "Buffer",
              "data": "66B+Ofx197grlg=="
            },
            "senderTimestamp": 1731908727,
            "recipientKeyHash": {
              "type": "Buffer",
              "data": "u8kUD1rbSedN0w=="
            },
            "recipientTimestamp": 1732080007
          },
          "deviceListMetadataVersion": 2
        }
      }
    }
  },
  {
    "id": "false_120363347135619169@g.us_3EB091E799A56C1FF904CD",
    "timestamp": 1732262753,
    "from": "120363347135619169@g.us",
    "fromMe": false,
    "body": "好~ ",
    "to": "120363347135619169@g.us",
    "participant": "xxx",
    "hasMedia": false,
    "ack": null,
    "ackName": "UNKNOWN",
    "replyTo": null,
    "_data": {
      "key": {
        "remoteJid": "120363347135619169@g.us",
        "fromMe": false,
        "id": "3EB091E799A56C1FF904CD",
        "participant": "xxx@s.whatsapp.net"
      },
      "messageTimestamp": 1732262753,
      "pushName": "testing",
      "broadcast": false,
      "message": {
        "senderKeyDistributionMessage": {
          "groupId": "120363347135619169@g.us",
          "axolotlSenderKeyDistributionMessage": {
            "type": "Buffer",
            "data": "MwjeutOuAxAHGiBR2p1mu3eS38XuM3NL7HZq7bMS4V7VWR00/v1BrCZpYSIhBRLveFleUa7SaBykFnA3Y1ped75JAEo6G6NKUWQgY1lE"
          }
        },
        "messageContextInfo": {},
        "conversation": "好~ "
      },
      "verifiedBizName": "testing"
    }
  },
  {
    "id": "false_120363347135619169@g.us_3A530BAC9741B55BBC3B",
    "timestamp": 1732262717,
    "from": "120363347135619169@g.us",
    "fromMe": false,
    "body": "好的，我夾一夾時間轉頭覆你😊",
    "to": "120363347135619169@g.us",
    "participant": "xxx",
    "hasMedia": false,
    "ack": null,
    "ackName": "UNKNOWN",
    "replyTo": null,
    "_data": {
      "key": {
        "remoteJid": "120363347135619169@g.us",
        "fromMe": false,
        "id": "3A530BAC9741B55BBC3B",
        "participant": "xxx@s.whatsapp.net"
      },
      "messageTimestamp": 1732262717,
      "pushName": "Kingki",
      "broadcast": false,
      "message": {
        "senderKeyDistributionMessage": {
          "groupId": "120363347135619169@g.us",
          "axolotlSenderKeyDistributionMessage": {
            "type": "Buffer",
            "data": "MwiUtL0+EA0aIOzirUDJ4qTLoi8T43qcHA/4lPAYN/g4aSMWk5IknK8ZIiEFr22HD03MTxpQkJVzmaLaytuWcdKCmshizzgvGsn3IS4="
          }
        },
        "messageContextInfo": {
          "deviceListMetadata": {
            "senderKeyHash": {
              "type": "Buffer",
              "data": "66B+Ofx197grlg=="
            },
            "senderTimestamp": 1731908727,
            "recipientKeyHash": {
              "type": "Buffer",
              "data": "u8kUD1rbSedN0w=="
            },
            "recipientTimestamp": 1732080007
          },
          "deviceListMetadataVersion": 2
        },
        "conversation": "好的，我夾一夾時間轉頭覆你😊"
      }
    }
  }
]`

**Comment by devlikepro** [comment]
related to https://github.com/devlikeapro/waha/issues/671

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Could you try to repair (logout/scan qr) the session with problem after updating to the latest update? Looks like some keys are missing

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
