### ISSUE TITLE
[BUG][WEBJS] - Getting an error at endoint messages-admin-only

### ISSUE THREAD

**Issue by ijro** [allburov/whatsapp-http-api#662]
Hello! I'm getting an error at endoint messages-admin-only

Version: Waha Plus (ARM) 2024.11.8 WEBJS

**To Reproduce**:

Call endpoint GET /api/{session}/groups/{id}/settings/security/messages-admin-only

See error:
TypeError: Cannot read properties of undefined (reading 'announce')\n    at WhatsappSessionWebJSPlus.getMessagesAdminsOnly (/app/dist/core/engines/webjs/session.webjs.core.js:505:49)

```json
{
  "statusCode": 500,
  "timestamp": "2024-11-25T15:37:27.549Z",
  "exception": {
    "stack": "TypeError: Cannot read properties of undefined (reading 'announce')\n    at WhatsappSessionWebJSPlus.getMessagesAdminsOnly (/app/dist/core/engines/webjs/session.webjs.core.js:505:49)",
    "message": "Cannot read properties of undefined (reading 'announce')",
    "name": "TypeError"
  },
  "request": {
    "path": "/api/YYYYYYYYYYY/groups/XXXXXXXXXXXX@g.us/settings/security/messages-admin-only",
    "method": "GET",
    "body": {},
    "query": {}
  },
  "version": {
    "version": "2024.11.8",
    "engine": "WEBJS",
    "tier": "PLUS",
    "browser": "/usr/bin/chromium"
  }
}
```

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Hi! Try updating to 2024.11.10 :crossed_fingers: 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
