### ISSUE TITLE
[BUG][NOWEB] - The message webhook seems to have some errors

### ISSUE THREAD

**Issue by HuangDaHui** [allburov/whatsapp-http-api#667]
{
  "request": {
    "event": "message",
    "session": "051855",
    "me": {
      "id": "xxx@c.us",
      "pushName": "TC CS"
    },
    "payload": {
      "id": "false_120363089041794203@g.us_3EB0AA25E8847C7A906E29",
      "timestamp": 1732586381,
      "from": "120363089041794203@g.us",
      "fromMe": false,
      "body": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "to": "120363089041794203@g.us",
      "participant": "xxx@c.us",
      "hasMedia": true,
      "media": {
        "url": null,
        "filename": null,
        "mimetype": "image/jpeg",
        "error": {
          "message": "Request failed with status code 403",
          "name": "AxiosError",
          "stack": "AxiosError: Request failed with status code 403\n    at settle (/app/node_modules/@adiwajshing/baileys/node_modules/axios/dist/node/axios.cjs:1983:12)\n    at RedirectableRequest.handleResponse (/app/node_modules/@adiwajshing/baileys/node_modules/axios/dist/node/axios.cjs:3033:9)\n    at RedirectableRequest.emit (node:events:520:28)\n    at RedirectableRequest._processResponse (/app/node_modules/follow-redirects/index.js:398:10)\n    at RedirectableRequest._onNativeResponse (/app/node_modules/follow-redirects/index.js:91:12)\n    at Object.onceWrapper (node:events:635:26)\n    at ClientRequest.emit (node:events:520:28)\n    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:704:27)\n    at HTTPParser.parserOnHeadersComplete (node:_http_common:118:17)\n    at TLSSocket.socketOnData (node:_http_client:546:22)\n    at TLSSocket.emit (node:events:520:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TLSWrap.onStreamRead (node:internal/stream_base_commons:191:23)\n    at TLSWrap.callbackTrampoline (node:internal/async_hooks:130:17)\n    at Axios.request (/app/node_modules/@adiwajshing/baileys/node_modules/axios/dist/node/axios.cjs:4224:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async getHttpStream (/app/node_modules/@adiwajshing/baileys/lib/Utils/messages-media.js:320:21)\n    at async downloadEncryptedContent (/app/node_modules/@adiwajshing/baileys/lib/Utils/messages-media.js:463:21)\n    at async downloadMsg (/app/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:739:24)\n    at async downloadMediaMessage (/app/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:698:20)\n    at async NOWEBEngineMediaProcessor.getMediaBuffer (/app/dist/core/engines/noweb/session.noweb.core.js:1235:17)\n    at async MediaManager.fetchMedia (/app/dist/core/media/MediaManager.js:92:24)\n    at async MediaManager.withRetry (/app/dist/core/media/MediaManager.js:116:20)\n    at async MediaManager.processMediaInternal (/app/dist/core/media/MediaManager.js:50:28)\n    at async MediaManager.processMedia (/app/dist/core/media/MediaManager.js:78:26)\n    at async WhatsappSessionNoWebPlus.processIncomingMessage (/app/dist/core/engines/noweb/session.noweb.core.js:985:27)",
          "config": {
            "transitional": {
              "silentJSONParsing": true,
              "forcedJSONParsing": true,
              "clarifyTimeoutError": false
            },
            "adapter": [
              "xhr",
              "http",
              "fetch"
            ],
            "transformRequest": [
              null
            ],
            "transformResponse": [
              null
            ],
            "timeout": 0,
            "xsrfCookieName": "XSRF-TOKEN",
            "xsrfHeaderName": "X-XSRF-TOKEN",
            "maxContentLength": null,
            "maxBodyLength": null,
            "env": {},
            "headers": {
              "Accept": "application/json, text/plain, */*",
              "Origin": "https://web.whatsapp.com",
              "User-Agent": "axios/1.7.2",
              "Accept-Encoding": "gzip, compress, deflate, br"
            },
            "responseType": "stream",
            "method": "get",
            "url": "https://mmg.whatsapp.net/o1/v/t62.7118-24/f1/m235/up-oil-image-121332b5-6c29-416d-a198-5e96adb2d5c8?ccb=9-4&oh=01_Q5AaIJKstxWo7MxQcng7LSCBG8bIwp5kJoAcbosh1_rRa6Nu&oe=6739087E&_nc_sid=e6ed6c&mms3=true"
          },
          "code": "ERR_BAD_REQUEST",
          "status": 403
        }
      },
      "mediaUrl": null,
      "ack": null,
      "ackName": "UNKNOWN",
      "replyTo": null,
      "_data": {
        "key": {
          "remoteJid": "120363089041794203@g.us",
          "fromMe": false,
          "id": "3EB0AA25E8847C7A906E29",
          "participant": "xxx@s.whatsapp.net"
        },
        "messageTimestamp": 1732586381,
        "pushName": "xxx",
        "broadcast": false,
        "message": {
          "imageMessage": {
            "url": "https://mmg.whatsapp.net/o1/v/t62.7118-24/f1/m235/up-oil-image-121332b5-6c29-416d-a198-5e96adb2d5c8?ccb=9-4&oh=01_Q5AaIJKstxWo7MxQcng7LSCBG8bIwp5kJoAcbosh1_rRa6Nu&oe=6739087E&_nc_sid=e6ed6c&mms3=true",
            "mimetype": "image/jpeg",
            "caption": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx！",
            "fileSha256": "AMw5+JNqAGpdotydxOixjdqiMPukS+Dz20VbKImuneo=",
            "fileLength": "176062",
            "height": 830,
            "width": 1199,
            "mediaKey": "3r7u4lKHk0zJOUMKCpazRTY1EXzhFQClQW2qFdaOBsw=",
            "fileEncSha256": "BWJdx3hihK1Md74K66Oab4/lsAh+PkNYh7kf9NAmNRU=",
            "directPath": "/o1/v/t62.7118-24/f1/m235/up-oil-image-e754e430-82bf-4e60-b242-c7b060893496?ccb=9-4&oh=01_Q5AaIPWZtejT_6W1znGdNo2eyuehGQrVGdUhSaYIPUpCJyUX&oe=676CB5F0&_nc_sid=e6ed6c",
            "mediaKeyTimestamp": "1729210007",
            "jpegThumbnail": "xxxx"
          },
          "messageContextInfo": {
            "deviceListMetadata": {
              "senderKeyHash": "QIDoy4MfAFg9cQ==",
              "senderTimestamp": "1731054429",
              "senderAccountType": "E2EE",
              "receiverAccountType": "E2EE",
              "recipientKeyHash": "r6TwcemvSDsDKA==",
              "recipientTimestamp": "1732178309"
            },
            "deviceListMetadataVersion": 2
          }
        },
        "media": {
          "url": null,
          "filename": null,
          "mimetype": "image/jpeg",
          "error": {
            "message": "Request failed with status code 403",
            "name": "AxiosError",
            "stack": "AxiosError: Request failed with status code 403\n    at settle (/app/node_modules/@adiwajshing/baileys/node_modules/axios/dist/node/axios.cjs:1983:12)\n    at RedirectableRequest.handleResponse (/app/node_modules/@adiwajshing/baileys/node_modules/axios/dist/node/axios.cjs:3033:9)\n    at RedirectableRequest.emit (node:events:520:28)\n    at RedirectableRequest._processResponse (/app/node_modules/follow-redirects/index.js:398:10)\n    at RedirectableRequest._onNativeResponse (/app/node_modules/follow-redirects/index.js:91:12)\n    at Object.onceWrapper (node:events:635:26)\n    at ClientRequest.emit (node:events:520:28)\n    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:704:27)\n    at HTTPParser.parserOnHeadersComplete (node:_http_common:118:17)\n    at TLSSocket.socketOnData (node:_http_client:546:22)\n    at TLSSocket.emit (node:events:520:28)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TLSWrap.onStreamRead (node:internal/stream_base_commons:191:23)\n    at TLSWrap.callbackTrampoline (node:internal/async_hooks:130:17)\n    at Axios.request (/app/node_modules/@adiwajshing/baileys/node_modules/axios/dist/node/axios.cjs:4224:41)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async getHttpStream (/app/node_modules/@adiwajshing/baileys/lib/Utils/messages-media.js:320:21)\n    at async downloadEncryptedContent (/app/node_modules/@adiwajshing/baileys/lib/Utils/messages-media.js:463:21)\n    at async downloadMsg (/app/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:739:24)\n    at async downloadMediaMessage (/app/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:698:20)\n    at async NOWEBEngineMediaProcessor.getMediaBuffer (/app/dist/core/engines/noweb/session.noweb.core.js:1235:17)\n    at async MediaManager.fetchMedia (/app/dist/core/media/MediaManager.js:92:24)\n    at async MediaManager.withRetry (/app/dist/core/media/MediaManager.js:116:20)\n    at async MediaManager.processMediaInternal (/app/dist/core/media/MediaManager.js:50:28)\n    at async MediaManager.processMedia (/app/dist/core/media/MediaManager.js:78:26)\n    at async WhatsappSessionNoWebPlus.processIncomingMessage (/app/dist/core/engines/noweb/session.noweb.core.js:985:27)",
            "config": {
              "transitional": {
                "silentJSONParsing": true,
                "forcedJSONParsing": true,
                "clarifyTimeoutError": false
              },
              "adapter": [
                "xhr",
                "http",
                "fetch"
              ],
              "transformRequest": [
                null
              ],
              "transformResponse": [
                null
              ],
              "timeout": 0,
              "xsrfCookieName": "XSRF-TOKEN",
              "xsrfHeaderName": "X-XSRF-TOKEN",
              "maxContentLength": null,
              "maxBodyLength": null,
              "env": {},
              "headers": {
                "Accept": "application/json, text/plain, */*",
                "Origin": "https://web.whatsapp.com",
                "User-Agent": "axios/1.7.2",
                "Accept-Encoding": "gzip, compress, deflate, br"
              },
              "responseType": "stream",
              "method": "get",
              "url": "https://mmg.whatsapp.net/o1/v/t62.7118-24/f1/m235/up-oil-image-121332b5-6c29-416d-a198-5e96adb2d5c8?ccb=9-4&oh=01_Q5AaIJKstxWo7MxQcng7LSCBG8bIwp5kJoAcbosh1_rRa6Nu&oe=6739087E&_nc_sid=e6ed6c&mms3=true"
            },
            "code": "ERR_BAD_REQUEST",
            "status": 403
          }
        }
      }
    },
    "engine": "NOWEB",
    "environment": {
      "version": "2024.10.8",
      "engine": "NOWEB",
      "tier": "PLUS",
      "browser": "/usr/bin/chromium"
    }
  },
  "channelId": "051855"
}

**Comment by devlikepro** [comment]
`URL signature expired` :thinking: 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
will add reupload request for that in 2024.11.11 :crossed_fingers: 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by HuangDaHui** [comment]
It still seems to exist, but the error message is different

**Comment by HuangDaHui** [comment]
`{
  "request": {
    "id": "evt_01jfh4pkct0tc8ghymj91hy66k",
    "event": "message",
    "session": "session_frwq9b",
    "metadata": {},
    "me": {
      "id": "85200000000@c.us",
      "pushName": "dumbChat.Ai"
    },
    "payload": {
      "id": "false_120363276612825991@g.us_3EB08CBE32C03B934A8E76_85254942545@c.us",
      "timestamp": 1734667022,
      "from": "120363276612825991@g.us",
      "fromMe": false,
      "body": "TVP:14875:23 JINKI COMPANY 申請表格.pdf",
      "to": "120363276612825991@g.us",
      "participant": "85200000000@c.us",
      "hasMedia": true,
      "media": {
        "url": null,
        "filename": "TVP:14875:23 JINKI COMPANY 申請表格.pdf",
        "mimetype": "application/pdf",
        "error": {
          "data": null,
          "isBoom": true,
          "isServer": false,
          "output": {
            "statusCode": 428,
            "payload": {
              "statusCode": 428,
              "error": "Precondition Required",
              "message": "Connection Closed"
            },
            "headers": {}
          },
          "details": "Error: Connection Closed\n    at sendRawMessage (/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:59:19)\n    at sendNode (/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:78:16)\n    at Object.updateMediaMessage [as reuploadRequest] (/app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:594:17)\n    at /app/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:707:41\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async downloadMediaMessage (/app/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:698:20)\n    at async NOWEBEngineMediaProcessor.getMediaBuffer (/app/dist/core/engines/noweb/session.noweb.core.js:1255:17)\n    at async MediaManager.fetchMedia (/app/dist/core/media/MediaManager.js:92:24)\n    at async MediaManager.withRetry (/app/dist/core/media/MediaManager.js:116:20)\n    at async MediaManager.processMediaInternal (/app/dist/core/media/MediaManager.js:50:28)\n    at async MediaManager.processMedia (/app/dist/core/media/MediaManager.js:78:26)\n    at async WhatsappSessionNoWebPlus.processIncomingMessage (/app/dist/core/engines/noweb/session.noweb.core.js:990:27)"
        }
      },
      "mediaUrl": null,
      "ack": null,
      "ackName": "UNKNOWN",
      "replyTo": null,
      "_data": {
        "key": {
          "remoteJid": "120363276612825991@g.us",
          "fromMe": false,
          "id": "3EB08CBE32C03B934A8E76",
          "participant": "85200000000@s.whatsapp.net"
        },
        "messageTimestamp": 1734667022,
        "pushName": "技術諮詢",
        "broadcast": false,
        "verifiedBizName": "技術諮詢",
        "message": {
          "messageContextInfo": {
            "messageSecret": "4RkiXSfjU+y6TSEid/E9NUXQSxeaH8zssQMm0IxUps8="
          },
          "documentWithCaptionMessage": {
            "message": {
              "documentMessage": {
                "url": "https://mmg.whatsapp.net/v/t62.43144-24/10000000_341820245650243_2631256799517883921_n.enc?ccb=11-4&oh=01_Q5AaICopgN6vstVJO1ZegjS5pq7c7xHVdwsVLX7ZEtD3m1yi&oe=66C69737&_nc_sid=5e03e0&mms3=true",
                "mimetype": "application/pdf",
                "title": "TVP:14875:23 JINKI COMPANY 申請表格.pdf",
                "fileSha256": "DLyAplm2LSSiMI23KRUOmrlv+5sESfSEhk7FbTc2z+k=",
                "fileLength": "179623014",
                "pageCount": 82,
                "mediaKey": "muaeC8a+0k1drQl6maTdg/2i5O//Jh9ft+r1L7yZ4v0=",
                "fileName": "TVP:14875:23 JINKI COMPANY 申請表格.pdf",
                "fileEncSha256": "r8LO7vA6ZjbPSr4q4iwP9w5hjxN7KlPtkbj1z+/cqDI=",
                "directPath": "/v/t62.43144-24/10000000_1542365699808810_7898274642380215818_n.enc?ccb=11-4&oh=01_Q5AaIFRM7bvAr1i0EK95nhiAxdTyw6TFYGWDenD75FaUddLl&oe=678C50CA&_nc_sid=5e03e0",
                "mediaKeyTimestamp": "1721707850",
                "contactVcard": false,
                "thumbnailDirectPath": "/v/t62.36145-24/31867454_1596794430946756_2354764800971259446_n.enc?ccb=11-4&oh=01_Q5AaIKUwzPvqslhhrN4ty-I8eaKUyhfSRpO1YL1gWExXbMIN&oe=678C5BB9&_nc_sid=5e03e0",
                "thumbnailSha256": "/TRmpbF38/61sQnfrV2HsIJmx46Lp2XOlX4n4MgLlCw=",
                "thumbnailEncSha256": "9fF+x2Cu+y2PjYw6R6iPVvwzX0rFKCwUNKfxJTDc4i0=",
                "jpegThumbnail": "/9j/4AAQSkZJRgABAQAASABIAAD/4QBMRXhpZgAATU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAEqADAAQAAAABAAAAGQAAAAD/wAARCAAZABIDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9sAQwACAgICAgIDAgIDBQMDAwUGBQUFBQYIBgYGBgYICggICAgICAoKCgoKCgoKDAwMDAwMDg4ODg4PDw8PDw8PDw8P/9sAQwECAgIEBAQHBAQHEAsJCxAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQ/90ABAAC/9oADAMBAAIRAxEAPwD9xBEg8QXVwLK/LLgGVp2Nqx2LwkJm29DgkRgbgec5NW53WS2WJ4naQjJjifYR75JTjtWJrfizRdE1S5k1G0n8ywiyZ1h83EcoUsExl9pKruCjG4Lu5Izi3nxI8J3btZWuqW8UgAYPPA8kBJXKkSAoh2nG7D8H5Tg9OmIHoqRqiKnzfKAOWcninYX/AGv++np+B/d/WjA/u/rRcD//0P3I1PR7HUrxJrzSbS6KyBTJMqs4jCZDrlTk78LtJXjLZ4CmnHoUOkQGPw1b2WmhiS4+zDDEkn+B07n/AArvB2pj9DWykBmBhjoaXcPQ1ZoqgP/Z",
                "contextInfo": {
                  "disappearingMode": {
                    "initiator": "CHANGED_IN_CHAT"
                  }
                },
                "thumbnailHeight": 25,
                "thumbnailWidth": 18,
                "caption": "TVP:14875:23 JINKI COMPANY 申請表格.pdf"
              },
              "messageContextInfo": {
                "messageSecret": "4RkiXSfjU+y6TSEid/E9NUXQSxeaH8zssQMm0IxUps8="
              }
            }
          }
        },
        "media": {
          "url": null,
          "filename": "TVP:14875:23 JINKI COMPANY 申請表格.pdf",
          "mimetype": "application/pdf",
          "error": {
            "data": null,
            "isBoom": true,
            "isServer": false,
            "output": {
              "statusCode": 428,
              "payload": {
                "statusCode": 428,
                "error": "Precondition Required",
                "message": "Connection Closed"
              },
              "headers": {}
            },
            "details": "Error: Connection Closed\n    at sendRawMessage (/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:59:19)\n    at sendNode (/app/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:78:16)\n    at Object.updateMediaMessage [as reuploadRequest] (/app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:594:17)\n    at /app/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:707:41\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async downloadMediaMessage (/app/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:698:20)\n    at async NOWEBEngineMediaProcessor.getMediaBuffer (/app/dist/core/engines/noweb/session.noweb.core.js:1255:17)\n    at async MediaManager.fetchMedia (/app/dist/core/media/MediaManager.js:92:24)\n    at async MediaManager.withRetry (/app/dist/core/media/MediaManager.js:116:20)\n    at async MediaManager.processMediaInternal (/app/dist/core/media/MediaManager.js:50:28)\n    at async MediaManager.processMedia (/app/dist/core/media/MediaManager.js:78:26)\n    at async WhatsappSessionNoWebPlus.processIncomingMessage (/app/dist/core/engines/noweb/session.noweb.core.js:990:27)"
          }
        }
      }
    },
    "engine": "NOWEB",
    "environment": {
      "version": "2024.11.11",
      "engine": "NOWEB",
      "tier": "PLUS",
      "browser": "/usr/bin/chromium"
    }
  },
  "channelId": "TCN104"
}
`

**Comment by devlikepro** [comment]
If you get an error - could you try to request [**Get Message By Id**](https://waha.devlike.pro/docs/how-to/receive-messages/#get-message-by-id) with `downloadMedia=True` at the webhook processing like few time until you don't get the file?
It'll reupload the file if there was any errors

`Precondition Required` sucks :( working on the fix, but no ETA yet


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by HuangDaHui** [comment]
> If you get an error - could you try to request [**Get Message By Id**](https://waha.devlike.pro/docs/how-to/receive-messages/#get-message-by-id) with `downloadMedia=True` at the webhook processing like few time until you don't get the file? It'll reupload the file if there was any errors
> 
> `Precondition Required` sucks :( working on the fix, but no ETA yet
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)


It looks like it is lost and cannot be re-downloaded.
