### ISSUE TITLE
[BUG][NOWEB] - Not able to send buttons even without image

### ISSUE THREAD

**Issue by ravikant-pal** [allburov/whatsapp-http-api#669]
### Describe the bug

Not able to send buttons even without an image in the payload 

### Version

```json
{
  "version": "2024.11.8",
  "engine": "NOWEB",
  "tier": "CORE",
  "browser": "/usr/bin/chromium"
}
```

## Steps

**To Reproduce** Steps to reproduce the behavior:

1. Go to render.com
2. Signup and Click on New → Web Service → Existing Image
3. put image name 'devlokepro/waha'
4. add environment variable WHATSAPP_DEFAULT_ENGINE =NOWEB
5. now from swagger documentation try `/api/sendButtons` with

```json
{
  "chatId": "111111111111@c.us",
  "header": "How are you?",
  "body": "Tell us how are you please 🙏",
  "footer": "If you have any questions, please send it in the chat",
  "buttons": [
    {
      "type": "reply",
      "text": "I am good!"
    },
    {
      "type": "call",
      "text": "Call us",
      "phoneNumber": "+111111111111"
    },
    {
      "type": "copy",
      "text": "Copy code",
      "copyCode": "4321"
    },
    {
      "type": "url",
      "text": "How did you do that?",
      "url": "https://waha.devlike.pro"
    }
  ],
  "session": "default"
}
```

the response is 

```json
{
  "key": {
    "remoteJid": "111111111111@s.whatsapp.net",
    "fromMe": true,
    "id": "3EB0BFED33B87EA15E31C875F65CA262C0FAD202"
  },
  "message": {
    "viewOnceMessage": {
      "message": {
        "messageContextInfo": {
          "deviceListMetadata": {},
          "deviceListMetadataVersion": 2
        },
        "interactiveMessage": {
          "header": {
            "title": "How are you?",
            "hasMediaAttachment": false
          },
          "body": {
            "text": "Tell us how are you please 🙏"
          },
          "footer": {
            "text": "If you have any questions, please send it in the chat"
          },
          "nativeFlowMessage": {
            "buttons": [
              {
                "name": "quick_reply",
                "buttonParamsJson": "{\"display_text\":\"I am good!\",\"id\":\"4311415203517172\",\"disabled\":false}"
              },
              {
                "name": "cta_call",
                "buttonParamsJson": "{\"display_text\":\"Call us\",\"id\":\"4657851719271175\",\"disabled\":false,\"phone_number\":\"+111111111111\"}"
              },
              {
                "name": "cta_copy",
                "buttonParamsJson": "{\"display_text\":\"Copy code\",\"id\":\"3073721340861375\",\"disabled\":false,\"copy_code\":\"4321\"}"
              },
              {
                "name": "cta_url",
                "buttonParamsJson": "{\"display_text\":\"How did you do that?\",\"id\":\"0164587784765506\",\"disabled\":false,\"url\":\"https://waha.devlike.pro\",\"merchant_url\":\"https://waha.devlike.pro\"}"
              }
            ],
            "messageParamsJson": "{\"from\":\"api\",\"templateId\":\"8715284566952497\"}"
          }
        }
      }
    }
  },
  "messageTimestamp": "1732674661",
  "status": "PENDING"
}
```

### Expected behavior

It should send the buttons in the chat.

### Docker Logs

`[02:31:01.550] INFO (1): request completed {"reqId":174,"req":{"id":174,"method":"POST","url":"/api/sendButtons","query":{},"params":{"0":"api/sendButtons"}},"res":{"statusCode":201},"responseTime":88}`

**Comment by KKshitiz** [comment]
Facing the same issue

[![patron:ADVANCED](https://img.shields.io/badge/patron-ADVANCED-4cd07d)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by gregoriolombardi** [comment]
Facing the same issue

**Comment by masitings** [comment]
Yeah, its wierd. It actually sent as i saw on the WhatsApp Desktop ( the recipient whatsapp ) but not showed on phone. 

<img width="333" alt="image" src="https://github.com/user-attachments/assets/c270ce1b-4698-4cfa-be18-c553d8dc4553">


[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by pravin6534** [comment]
I am also getting same issue

**Comment by devlikepro** [comment]
Hi! Buttons are fragily creatures, no gurantue it'll always work :( Looks like Meta got patched our solution recently...
Consider having a fallback logic to regular text in case of such errors.
We'll see what we can do with buttons :crossed_fingers: 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
