### ISSUE TITLE
[BUG][WEBJS] - Not displaying groups and users within the group

### ISSUE THREAD

**Issue by ghost** [allburov/whatsapp-http-api#670]
Hello
It doesn't give me the list of groups with /api/{session}/chats
And it doesn't even give me the list of users in the group with /api/{session}/groups/{id}/participants

I'm using version 2024.11.8

The page that opens for me is Json, but it's empty

**Comment by HuangDaHui** [comment]
+1

**Comment by devlikepro** [comment]
2024.11.10

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
related https://github.com/devlikeapro/waha/issues/674

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
