### ISSUE TITLE
[BUG][WEBJS] - Why do different numbers in the same version and the same interface return different JSON formats when obtaining group information?

### ISSUE THREAD

**Issue by HuangDaHui** [allburov/whatsapp-http-api#673]
WEBJS (2024.9.3)

/api/158654/groups/120363355684878098%40g.us

A:
`{
  "groupMetadata": {
    "id": {
      "server": "g.us",
      "user": "120363355684878098",
      "_serialized": "120363355684878098@g.us"
    },
    "creation": 1732526981,
    "owner": {
      "server": "c.us",
      "user": "85288888888",
      "_serialized": "85288888888@c.us"
    },
    "subject": "xxx",
    "subjectTime": 1732526981,
    "restrict": false,
    "announce": false,
    "noFrequentlyForwarded": false,
    "membershipApprovalMode": false,
    "size": 6,
    "support": false,
    "suspended": false,
    "terminated": false,
    "uniqueShortNameMap": {},
    "isLidAddressingMode": false,
    "isParentGroup": false,
    "isParentGroupClosed": false,
    "defaultSubgroup": false,
    "generalSubgroup": false,
    "hiddenSubgroup": false,
    "generalChatAutoAddDisabled": false,
    "allowNonAdminSubGroupCreation": false,
    "incognito": false,
    "hasCapi": false,
    "participants": [
      {
        "id": {
          "server": "c.us",
          "user": "85288888888",
          "_serialized": "85288888888@c.us"
        },
        "isAdmin": false,
        "isSuperAdmin": false
      }
    ],
    "pendingParticipants": [],
    "pastParticipants": [],
    "membershipApprovalRequests": [],
    "subgroupSuggestions": []
  },
  "id": {
    "server": "g.us",
    "user": "120363355684878098",
    "_serialized": "120363355684878098@g.us"
  },
  "name": "xxx",
  "isGroup": true,
  "isReadOnly": false,
  "unreadCount": 0,
  "timestamp": 1732528255,
  "pinned": false,
  "muteExpiration": 0,
  "lastMessage": {
    "_data": {
      "id": {
        "fromMe": true,
        "remote": "120363355684878098@g.us",
        "id": "3EB0594A28E378E313ED04",
        "participant": {
          "server": "c.us",
          "user": "85288888888",
          "_serialized": "85288888888@c.us"
        },
        "_serialized": "true_120363355684878098@g.us_3EB0594A28E378E313ED04_85288888888@c.us"
      },
      "viewed": false,
      "body": "你好!",
      "type": "chat",
      "subtype": "url",
      "t": 1732528255,
      "from": {
        "server": "c.us",
        "user": "85288888888",
        "_serialized": "85288888888@c.us"
      },
      "to": {
        "server": "g.us",
        "user": "120363355684878098",
        "_serialized": "120363355684878098@g.us"
      },
      "ack": 2,
      "isNewMsg": true,
      "star": false,
      "kicNotified": false,
      "isFromTemplate": false,
      "matchedText": "bud.informa@gmail.com",
      "richPreviewType": 0,
      "doNotPlayInline": true,
      "title": "gmail.com",
      "description": "bud.informa@gmail.com",
      "pollInvalidated": false,
      "isSentCagPollCreation": false,
      "latestEditMsgKey": null,
      "latestEditSenderTimestampMs": null,
      "mentionedJidList": [],
      "groupMentions": [],
      "isEventCanceled": false,
      "eventInvalidated": false,
      "isVcardOverMmsDocument": false,
      "isForwarded": false,
      "hasReaction": false,
      "productHeaderImageRejected": false,
      "lastPlaybackProgress": 0,
      "isDynamicReplyButtonsMsg": false,
      "isCarouselCard": false,
      "parentMsgId": null,
      "isMdHistoryMsg": false,
      "stickerSentTs": 0,
      "isAvatar": false,
      "lastUpdateFromServerTs": 0,
      "invokedBotWid": null,
      "bizBotType": null,
      "botResponseTargetId": null,
      "botPluginType": null,
      "botPluginReferenceIndex": null,
      "botPluginSearchProvider": null,
      "botPluginSearchUrl": null,
      "botPluginSearchQuery": null,
      "botPluginMaybeParent": false,
      "botReelPluginThumbnailCdnUrl": null,
      "botMsgBodyType": null,
      "requiresDirectConnection": false,
      "bizContentPlaceholderType": null,
      "hostedBizEncStateMismatch": false,
      "senderOrRecipientAccountTypeHosted": false,
      "placeholderCreatedWhenAccountIsHosted": false,
      "links": [
        {
          "link": "mailto:bud.informa@gmail.com",
          "isSuspicious": false
        }
      ]
    },
    "id": {
      "fromMe": true,
      "remote": "120363355684878098@g.us",
      "id": "3EB0594A28E378E313ED04",
      "participant": {
        "server": "c.us",
        "user": "85288888888",
        "_serialized": "85288888888@c.us"
      },
      "_serialized": "true_120363355684878098@g.us_3EB0594A28E378E313ED04_85288888888@c.us"
    },
    "ack": 2,
    "hasMedia": false,
    "body": "你好! ",
    "type": "chat",
    "timestamp": 1732528255,
    "from": "85288888888@c.us",
    "to": "120363355684878098@g.us",
    "deviceType": "android",
    "isForwarded": false,
    "forwardingScore": 0,
    "isStatus": false,
    "isStarred": false,
    "fromMe": true,
    "hasQuotedMsg": false,
    "hasReaction": false,
    "vCards": [],
    "mentionedIds": [],
    "groupMentions": [],
    "isGif": false,
    "title": "gmail.com",
    "description": "bud.informa@gmail.com",
    "links": [
      {
        "link": "mailto:bud.informa@gmail.com",
        "isSuspicious": false
      }
    ]
  }
}`

/api/584104/groups/120363354628495296%40g.us
B：
`{
  "id": {
    "server": "g.us",
    "user": "120363354628495296",
    "_serialized": "120363354628495296@g.us"
  },
  "name": "#2189",
  "isReadOnly": false,
  "unreadCount": 0,
  "timestamp": 1732674680,
  "archived": false,
  "pinned": false,
  "muteExpiration": 0,
  "lastMessage": {
    "_data": {
      "id": {
        "fromMe": true,
        "remote": "120363354628495296@g.us",
        "id": "3EB0B76957EEF4CDF1F0BA",
        "participant": {
          "server": "c.us",
          "user": "85288888888",
          "_serialized": "85288888888@c.us"
        },
        "_serialized": "true_120363354628495296@g.us_3EB0B76957EEF4CDF1F0BA_85288888888@c.us"
      },
      "viewed": false,
      "body": "",
      "type": "chat",
      "t": 1732674680,
      "notifyName": "",
      "from": {
        "server": "c.us",
        "user": "85288888888",
        "_serialized": "85288888888@c.us"
      },
      "to": {
        "server": "g.us",
        "user": "120363354628495296",
        "_serialized": "120363354628495296@g.us"
      },
      "author": {
        "server": "c.us",
        "user": "85288888888",
        "_serialized": "85288888888@c.us"
      },
      "ack": 3,
      "invis": false,
      "star": false,
      "kicNotified": false,
      "isFromTemplate": false,
      "pollInvalidated": false,
      "isSentCagPollCreation": false,
      "latestEditMsgKey": null,
      "latestEditSenderTimestampMs": null,
      "mentionedJidList": [],
      "groupMentions": [],
      "isEventCanceled": false,
      "eventInvalidated": false,
      "isVcardOverMmsDocument": false,
      "isForwarded": false,
      "labels": [],
      "hasReaction": false,
      "viewMode": "VISIBLE",
      "productHeaderImageRejected": false,
      "lastPlaybackProgress": 0,
      "isDynamicReplyButtonsMsg": false,
      "isCarouselCard": false,
      "parentMsgId": null,
      "isMdHistoryMsg": false,
      "stickerSentTs": 0,
      "isAvatar": false,
      "lastUpdateFromServerTs": 0,
      "invokedBotWid": null,
      "botTargetSenderJid": null,
      "bizBotType": null,
      "botResponseTargetId": null,
      "botPluginType": null,
      "botPluginReferenceIndex": null,
      "botPluginSearchProvider": null,
      "botPluginSearchUrl": null,
      "botPluginSearchQuery": null,
      "botPluginMaybeParent": false,
      "botReelPluginThumbnailCdnUrl": null,
      "botMsgBodyType": null,
      "reportingTokenInfo": null,
      "requiresDirectConnection": false,
      "bizContentPlaceholderType": null,
      "hostedBizEncStateMismatch": false,
      "senderOrRecipientAccountTypeHosted": false,
      "placeholderCreatedWhenAccountIsHosted": false,
      "links": []
    },
    "id": {
      "fromMe": true,
      "remote": "120363354628495296@g.us",
      "id": "3EB0B76957EEF4CDF1F0BA",
      "participant": {
        "server": "c.us",
        "user": "85288888888",
        "_serialized": "85288888888@c.us"
      },
      "_serialized": "true_120363354628495296@g.us_3EB0B76957EEF4CDF1F0BA_85288888888@c.us"
    },
    "ack": 3,
    "hasMedia": false,
    "body": "XXXX",
    "type": "chat",
    "timestamp": 1732674680,
    "from": "85296948882@c.us",
    "to": "120363354628495296@g.us",
    "author": "85288888888@c.us",
    "deviceType": "android",
    "isForwarded": false,
    "forwardingScore": 0,
    "isStatus": false,
    "isStarred": false,
    "fromMe": true,
    "hasQuotedMsg": false,
    "hasReaction": false,
    "vCards": [],
    "mentionedIds": [],
    "groupMentions": [],
    "isGif": false,
    "links": []
  }
}`

**Comment by devlikepro** [comment]
Hi! Could you highlight the difference please? Try updating to 2024.11.10 https://github.com/devlikeapro/waha/issues/674

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by HuangDaHui** [comment]
Has returned to normal in the new version
