### ISSUE TITLE
[BUG][WEBJS] - Unable to get group members

### ISSUE THREAD

**Issue by HuangDaHui** [allburov/whatsapp-http-api#674]
/api/{session}/groups/{id}/participants
The request was successful but no data was returned

**Comment by HuangDaHui** [comment]
It seems that only certain numbers appear

**Comment by ghost** [comment]
1+

**Comment by devlikepro** [comment]
2024.11.10

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by vailsonmarcelo** [comment]
2025-10-08 same for me
