### ISSUE TITLE
[Feature Request] Docker build for ARM64

### ISSUE THREAD

**Issue by MarianoFacundoArch** [allburov/whatsapp-http-api#675]
Can we get a docker build also available for arm64?

**Comment by ghost** [comment]
1+

**Comment by devlikepro** [comment]
Hi! try this one `devlikeapro/waha-plus:arm`
https://waha.devlike.pro/docs/how-to/engines/#docker-images

Here's docker image configurator https://portal.devlike.pro/docker-image

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
