### ISSUE TITLE
[BUG][WEBJS] - Infinit session start

### ISSUE THREAD

**Issue by Dolise** [allburov/whatsapp-http-api#677]
Version - 2024.11.4

Facing an issue while trying to create new session. Session is infinity starting. Tried to restart container. Also I have a few active sessions which are ok even if i restart them. This is only trouble with creating new sessions.

<img width="775" alt="image" src="https://github.com/user-attachments/assets/697577ce-34f2-419d-ba88-6b30048fba8a">

**Comment by devlikepro** [comment]
Hi! Try updating to 2024.11.11

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
