### ISSUE TITLE
Flexible Webhooks

### ISSUE THREAD

**Issue by allburov** [allburov/whatsapp-http-api#68]
We need to create more flexible and configurable webhooks system. 

Few notes for new system:
- [x] Ability to control webhook retries https://github.com/devlikeapro/whatsapp-http-api/issues/53 
- [x]  Multiple webhooks with different URL\events pairs - https://github.com/devlikeapro/whatsapp-http-api/issues/45
- [x]  Set multiple webhook urls at once with different events (if it's possible)
- [x]  Leave opportunity to extend configuration - like with "When to retry - on which http code or network error or other properties"
- [x]  Add `x-waha-hmac` header and ability to setup secret key
- [x]  Add custom headers configuration

When it's possible to set webhooks
- [x] At the docker start (the same way we do it right now - one webhook, multiple events)
- [x]  At session start (multiple webhooks)
- ~~Later when session is working (multiple webhooks)~~

**Comment by Kristian-Tan** [comment]
I think adding a custom http header to the webhook's request is also a good idea, so that our (custom) endpoint that receive the webhook can authenticate that it's a genuine request coming from WAHA.

It's not really vital since our (custom) endpoint that receive the webhook can infer from remote IP address tho

**Comment by allburov** [comment]
@Kristian-Tan hi! It's a good idea, we'll add it!

Also I think the good way to handle security here by adding HMAC as a header. So instead of sending the secret key WAHA'll sign the message's hash with key and send that value and receiver (your application) can verify hmac calculating and comparing header value on it's side.

**Comment by allburov** [comment]
Added almost all features except ability to configure webhooks after session is working, you have to stop and start session again to apply new webhooks or events.
Please open a new issue if it's the case for you!

**Comment by allburov** [comment]
https://waha.devlike.pro/docs/how-to/webhooks/

**Comment by allburov** [comment]
**POST /api/sessions/start**
```json
{
  "name": "default",
  "config": {
    "webhooks": [
      {
        "url": "https://httpbin.org/post",
        "events": [
          "message"
        ],
        "hmac": {
          "key": "your-secret-key"
        },
        "retries": {
          "delaySeconds": 2,
          "attempts": 15
        },
        "customHeaders": [
          {
            "name": "X-My-Custom-Header",
            "value": "Value"
          }
        ]
      }
    ]
  }
}
```
