### ISSUE TITLE
[BUG][WEBJS] - api/sessionid/groups Group list is not being fetched as expeded

### ISSUE THREAD

**Issue by wasimsohail** [allburov/whatsapp-http-api#681]
### Describe the bug
json group data is not being fetched as expected on the API
api/sessionid/groups 

### Version

Engine:
WEBJS
Version:
2024.9.5
```json
{
  "version": "YYYY.MM.DD",
  "engine": "ENGINE",
  "tier": "TIER"
}
```

Try to update to
[the latest version](https://github.com/devlikeapro/waha/releases) before
creating an issue!

## Steps

**To Reproduce** Steps to reproduce the behavior:

### Requests - Responses

Please attach all sent requests, responses that you sent.

### Docker Logs

Collect and attach related docker logs if you have any
https://waha.devlike.pro/docs/how-to/deploy/#viewing-the-logs

**Comment by devlikepro** [comment]
Try updating, it's been fixed in `2024.11.10`
https://waha.devlike.pro/docs/overview/changelog/#202411

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
