### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by smihheemmaanntt** [allburov/whatsapp-http-api#684]
![image](https://github.com/user-attachments/assets/6df580fb-5948-487e-bbe8-c5326a77fb9e)
Why DOCKER Data Increases.... with Same sessions? How to Stop and use Another Drive for Docker Data?

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Hi!
Try running `docker system prune`

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
