### ISSUE TITLE
join a group with a link

### ISSUE THREAD

**Issue by Philiger** [allburov/whatsapp-http-api#688]
Hello
idea will be to join a group with a link directly with a curl command for example because actually to join a group we have to do it with a phone
Thanks
Regards
Philippe 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Added in **2024.12.4** (both **NOWEB** and **WEBJS** engines)

https://waha.devlike.pro/docs/how-to/groups/#join-group

----

### Join group
If you have invite URL for a group (like `https://chat.whatsapp.com/invitecode`), you can 

```bash
POST /api/{session}/groups/join
```

**Body**
```json
{
  "code": "invitecode"
}
```

or using full link:
```json
{
  "code": "https://chat.whatsapp.com/invitecode"
}
```

**Response**:
```json
{
  "id": "123123123@g.us"
}
```

### Get join info for group
If you have invite URL for a group (like `https://chat.whatsapp.com/invitecode`), you can get group info:

```bash
GET /api/{session}/groups/join-info?code=invitecode
```

or using full link (remember to encode the URL)

```bash
GET /api/{session}/groups/join-info?code=https%3A%2F%2Fchat.whatsapp.com%2Finvitecode
```

Response depends on engine you're using


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
