### ISSUE TITLE
I can not install on an old docker Docker version 17.09.1-ce, build 19e2cf6

### ISSUE THREAD

**Issue by beshoo** [allburov/whatsapp-http-api#689]
Dear support ,
I have this Docker version 17.09.1-ce, build 19e2cf6
```
And I can not upgrade it since my box:
Linux server3.net 3.10.0-962.3.2.lve1.5.82.el7.x86_64 #1 SMP Tue Oct 31 10:15:24 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
`CloudLinux release 7.9  (Boris Yegorov)`

And once I want to install waha:
```
docker run -it -p 3000:3000/tcp devlikeapro/waha
Unable to find image 'devlikeapro/waha:latest' locally
docker: Error response from daemon: missing signature key.
See 'docker run --help'.
```

Please advice.

**Comment by devlikepro** [comment]
It's docker issue, not the project one. You can ask docker community but likely they'll suggest you to update docker engine 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
