### ISSUE TITLE
[BUG][WEBJS] -  An exception occurred when sending a message

### ISSUE THREAD

**Issue by HuangDaHui** [allburov/whatsapp-http-api#694]
{
	"statusCode": 500,
	"timestamp": "2024-12-12T07:58:36.338Z",
	"exception": {
		"stack": "Error: Evaluation failed: a\n    at ExecutionContext._ExecutionContext_evaluate (/app/node_modules/whatsapp-web.js/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:229:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ExecutionContext.evaluate (/app/node_modules/whatsapp-web.js/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)\n    at async WebjsClient.sendMessage (/app/node_modules/whatsapp-web.js/src/Client.js:952:25)",
		"message": "Evaluation failed: a",
		"name": "Error"
	},
	"request": {
		"path": "/api/sendtext",
		"method": "POST",
		"body": {
			"text": "xxxx",
			"session": "456584",
			"chatId": "85200000000@c.us",
			"longitude": 0,
			"latitude": 0
		},
		"query": {}
	},
	"version": {
		"version": "2024.9.3",
		"engine": "WEBJS",
		"tier": "PLUS",
		"browser": "/usr/bin/google-chrome-stable"
	}
}

It couldn't be sent at first, but then the logout was displayed.
It returned to normal after re-scanning the QRcode.

**Comment by devlikepro** [comment]
>  It returned to normal after re-scanning the QRcode.

looks like it happens due to logout (for some reason). 

> 2024.9.3

Try updating if it happens again :crossed_fingers: 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
