### ISSUE TITLE
[BUG][WEBJS] - An error occurred while replying to message

### ISSUE THREAD

**Issue by HuangDaHui** [allburov/whatsapp-http-api#698]
This happens by chance, I don’t know why.

`{
	"statusCode": 500,
	"timestamp": "2024-12-18T07:15:25.284Z",
	"exception": {
		"stack": "Error: Could not get the quoted message.\nnew Error (<anonymous>:6:31)\n    at window.WWebJS.sendMessage (evaluate at Binding.<anonymous> (/app/node_modules/whatsapp-web.js/src/Client.js:226:36), <anonymous>:50:22)\n    at #evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:388:56)\n    at async ExecutionContext.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:275:16)\n    at async IsolatedWorld.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/IsolatedWorld.js:100:16)\n    at async CdpFrame.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Frame.js:341:20)\n    at async CdpPage.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:807:20)\n    at async WebjsClient.sendMessage (/app/node_modules/whatsapp-web.js/src/Client.js:956:25)\n    at Error (:5:30)",
		"message": "Could not get the quoted message.\nnew Error (<anonymous>:6:31)",
		"name": "Error"
	},
	"request": {
		"path": "/api/sendtext",
		"method": "POST",
		"body": {
			"text": "授權條款同意書",
			"session": "212548",
			"reply_to": "true_85200000000@c.us_3EB05095152F0D474629C8",
			"chatId": "85200000000@c.us",
			"longitude": 0,
			"latitude": 0
		},
		"query": {}
	},
	"version": {
		"version": "2024.11.11",
		"engine": "WEBJS",
		"tier": "PLUS",
		"browser": "/usr/bin/google-chrome-stable"
	}
}`

**Comment by devlikepro** [comment]
duplicate https://github.com/devlikeapro/waha/issues/576

comment with +1 to get notification when it's done!

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
