### ISSUE TITLE
[BUG][NOWEB] - Poll message sent but not visible to sender

### ISSUE THREAD

**Issue by safwanadnan** [allburov/whatsapp-http-api#699]
### Polls are not visible on WhatsApp app

I use WAHA to send WhatsApp polls and they are successfully sent, visible to the recipient, I even get a notification when they vote but I can't see the poll from my end on the app. I don't know why that is happening but this is a recurring issue, happens with a lot of sessions and I keep getting the complaints. The thing is that it is constant, if someone doesn't see it then they just don't no matter what, but others do see it and its never a problem for them. Been happening since a very long time even though I am on the latest version now.

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Very long time, you're right :( 
https://github.com/devlikeapro/waha/issues/338

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by safwanadnan** [comment]
why is this not reaolved yet? any idea when it will be resolved? can I take a look at this and contribute to your project because I need this feature very urgent for the functionality of my app

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
> can I take a look at this and contribute to your project 

Sure, that would be great!

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
