### ISSUE TITLE
checkNumberStatus not working

### ISSUE THREAD

**Issue by roryspies** [allburov/whatsapp-http-api#70]
The API is throwing the same issue as reported here in the js library: https://github.com/pedroslopez/whatsapp-web.js/issues/1569

Would the same fix apply here?

**Comment by allburov** [comment]
@kinsolutions22 could you attach the response please? 
It contains all other information - the version that you use, etc.

I've tried to replicate the issue and it worked (for the latest version of the image). Please try to pull a new version and try again

**Comment by allburov** [comment]
@kinsolutions22 hi! Any updates on that?
