### ISSUE TITLE
[Feature Request] API for UI clients

### ISSUE THREAD

**Issue by devlikepro** [allburov/whatsapp-http-api#701]
In order to show "Chat UI" with "chats + profile picture + last message" it'd be good to have a dedicated endpoint that would return all info at once:
1. Chat Id
2. Contact Name (if any or phone)
3. Profile Picture (if any)
4. Last Message

We should also add **pagination** there so it doesn't return all chats by default.

May be with `expand` parameters so we can control the behaviour:
- `expand=profilePicture`
- `expand=profilePicture&lastMessage`

The main focus is `NOWEB`, but we need to check how it's solve in `WEBJS` as well

May be we even could provide a simple UI for that in Dashboard or as a separate project so it'll be easy to start implementing such UI :thinking: 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Related issues:
- Profile Picture https://github.com/devlikeapro/waha/issues/566
- Last Message https://github.com/devlikeapro/waha/issues/573

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by matteus-siqueira** [comment]
+1

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by melquisedeque-magalhaes** [comment]
+1

**Comment by lucas-cassiano** [comment]
+1

**Comment by HuangDaHui** [comment]
+1

**Comment by devlikepro** [comment]
Added in `2024.12.6` :rocket: 

https://waha.devlike.pro/docs/how-to/chats/#get-chats-overview

----

### Get chats overview
Get chats "overview" - the API that almost all  [**Chat UI**](https://waha.devlike.pro/docs/how-to/dashboard/#chat-ui) client needs!
```
GET /api/{session}/chats/overview?limit=20&offset=0
```

**Response** contains the main info you need to show in the chat list:
1. `id` - chat id
2. `name` - chat name (if any)
3. `picture` - chat picture (if any)
4. `lastMessage` - last message in the chat (if any). 
5. `_chat` - the structure depends on engine you're using

⚠️ `lastMessage` doesn't have media attachments, you need to [get message by id]({{< relref "#get-message-by-id" >}}) to get media attachments.

```json
[
  {
    "id": "12312l123@c.us",
    "name": "John Doe",
    "picture": "https://example.com/picture.jpg",
    "lastMessage": {
      "id": "true_11111111111@c.us_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "timestamp": 1667561485,
      "from": "11111111111@c.us",
      "fromMe": true,
      "to": "11111111111@c.us",
      "body": "Hi there!",
      ...
    },
    "_chat": {
      ...
    }
  }
]

```

**Pagination**:
- `limit=100` - limit the number of chats to return
- `offset=0` - skip the number of chats from the start



[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by matteus-siqueira** [comment]
> Added in `2024.12.6` 🚀
> 
> https://waha.devlike.pro/docs/how-to/chats/#get-chats-overview
> 
> ### Get chats overview
> Get chats "overview" - the API that almost all [**Chat UI**](https://waha.devlike.pro/docs/how-to/dashboard/#chat-ui) client needs!
> 
> ```
> GET /api/{session}/chats/overview?limit=20&offset=0
> ```
> 
> **Response** contains the main info you need to show in the chat list:
> 
> 1. `id` - chat id
> 2. `name` - chat name (if any)
> 3. `picture` - chat picture (if any)
> 4. `lastMessage` - last message in the chat (if any).
> 5. `_chat` - the structure depends on engine you're using
> 
> ⚠️ `lastMessage` doesn't have media attachments, you need to [get message by id]({{< relref "#get-message-by-id" >}}) to get media attachments.
> 
> ```json
> [
>   {
>     "id": "12312l123@c.us",
>     "name": "John Doe",
>     "picture": "https://example.com/picture.jpg",
>     "lastMessage": {
>       "id": "true_11111111111@c.us_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
>       "timestamp": 1667561485,
>       "from": "11111111111@c.us",
>       "fromMe": true,
>       "to": "11111111111@c.us",
>       "body": "Hi there!",
>       ...
>     },
>     "_chat": {
>       ...
>     }
>   }
> ]
> ```
> 
> **Pagination**:
> 
> * `limit=100` - limit the number of chats to return
> * `offset=0` - skip the number of chats from the start
> 
> [![patron:PRO](https://camo.githubusercontent.com/4f70c3a9ee2450c288faea5e1a1b7ebd0ffc1571450a59676b300ffb32b32537/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f706174726f6e2d50524f2d313838613432)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

Very good, thanks for the work 🚀

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
