### ISSUE TITLE
[Feature Request] Are there any plans to support Alibaba Cloud OSS?

### ISSUE THREAD

**Issue by huangzhong0406** [allburov/whatsapp-http-api#703]
I am currently using the plus version. Does WAHA have any plans to support Alibaba Cloud OSS?  Because I am mainly using Alibaba Cloud resources now ,

**Comment by devlikepro** [comment]
Hi! If it's S3 compatible storage - yes, you can use it! Configure the parameters propely and it'll work! 
https://waha.devlike.pro/docs/how-to/storages/#media---s3
https://www.alibabacloud.com/help/en/oss/developer-reference/compatibility-with-amazon-s3-1/

Remember that S3 works only to save media files, you need to either map local folder to docker container or use MongoDB
- https://waha.devlike.pro/docs/how-to/storages/#sessions---local
- https://waha.devlike.pro/docs/how-to/storages/#sessions---mongodb


[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
