### ISSUE TITLE
How can i get the ID Group ?

### ISSUE THREAD

**Issue by RedeAlphaFitness** [allburov/whatsapp-http-api#711]
👉 Kindly use
[GitHub Discussions](https://github.com/devlikeapro/waha/discussions) to ask
questions!

**Comment by devlikepro** [comment]
Try https://waha.devlike.pro/docs/how-to/groups/#get-all-groups
```
GET /api/{session}/groups
```

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by RedeAlphaFitness** [comment]
I only get this in return [] even though I'm in groups
