### ISSUE TITLE
Account Blocked

### ISSUE THREAD

**Issue by mmojadad** [allburov/whatsapp-http-api#713]
My Whatsapp account got block today after install WAHA plus , Add my Whatsapp number and just send one simple test text message in 24 hours.
Installed version : WAHA plus
Too bad, It was my business whatsapp account.
Be carefull!
![whatsapp-block](https://github.com/user-attachments/assets/745e48d0-07dc-4684-b644-715fc9d042d7)

**Comment by devlikepro** [comment]
> It was my business whatsapp account

Did you use official web client before? You should have used it before.

Was it WEBJS engine?

Unfortunately, there's no clear guide how to avoid it, try requesting unblock and try NOWEB engine

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by mmojadad** [comment]
Hi
For years i am using offical web access to whatsapp for this account ( https://web.whatsapp.com/  )
I requested for unblock and they accepted , My good chance !
I stopped WAHA plus container on docker and worry about restart it again. Can be my whatsapp account be safe if i restart the container? 
I will use another phone number in future but still i am worry about my main number that was before integrated with WAHA plus

**Comment by devlikepro** [comment]
That actually quite surprising :thinking: Especially if you've used web official one... 
Thank you for the feedback, we'll double check it! 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by mmojadad** [comment]
@devlikepro
Hello,
Could you please advise me on what I should do now?
Should I wait for a revised version from your side?
Should I keep the Docker container turned off for now?

Also, I had some questions regarding migrating to the Plus plan, which I sent to you a few days ago via the following email addresses:
admin@devlike.pro
and
waha@devlike.pro

These questions were specifically about integration with Chatwoot. However, I have not received any response from you so far.
Could you please provide guidance?
