### ISSUE TITLE
[BUG][WEBJS] - Error while sending message

### ISSUE THREAD

**Issue by gr8tushar** [allburov/whatsapp-http-api#718]
### Describe the bug

When I am trying to send a video message, most of the times I am getting a server error.

### Version
```json
{"version":"2024.12.6","engine":"WEBJS","tier":"PLUS","browser":"/usr/bin/chromium"}
```

### Requests - Responses

request errored {"reqId":190,"req":{"id":190,"method":"POST","url":"/api/sendVideo","query":{},"params":{"0":"api/sendVideo"}},"res":{"statusCode":500},"responseTime":6481}
    err: {
      "type": "Error",
      "message": "a",
      "stack":
          a: a
              at #evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:388:56)
              at async ExecutionContext.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:275:16)
              at async IsolatedWorld.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/IsolatedWorld.js:100:16)
              at async CdpFrame.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Frame.js:341:20)
              at async CdpPage.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:807:20)
              at async WebjsClient.sendMessage (/app/node_modules/whatsapp-web.js/src/Client.js:956:25)
      "name": "a"
    }

{"statusCode":500,"timestamp":"2024-12-30T09:36:31.552Z","exception":{"stack":"a: a\n    at #evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:388:56)\n    at async ExecutionContext.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ExecutionContext.js:275:16)\n    at async IsolatedWorld.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/IsolatedWorld.js:100:16)\n    at async CdpFrame.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Frame.js:341:20)\n    at async CdpPage.evaluate (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:807:20)\n    at async WebjsClient.sendMessage (/app/node_modules/whatsapp-web.js/src/Client.js:956:25)","message":"a","name":"a"},"request":{"path":"/api/sendVideo","method":"POST","body":{"session":"E6FEFC25A8C64C7FA06335BC6FEEBEB6","chatId":"xxxxxxxxxx@c.us","file":{"mimetype":"video/mp4","url":"http://publicurl.com/bc9f5f8f-84c0-4a0d-9caf-ffacc985d2e9_The Docs Extension Explaination.mp4","filename":"video.mp4"},"caption":"test"},"query":{}},"version":{"version":"2024.12.6","engine":"WEBJS","tier":"PLUS","browser":"/usr/bin/chromium"}} 

### Additional context

Removed the phone number from the logs and the public URL. The number and URL are correct. 

[![patron:PLUS](https://img.shields.io/badge/patron-PLUS-a0e6ba)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)

**Comment by devlikepro** [comment]
Hi! try using `devlikeapro/waha-plus:chrome`, chromium doesn't support sending videos

https://waha.devlike.pro/docs/how-to/send-messages/#send-video-imagesversionspluspng

Yeah, we need to add better error :D 

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
