### ISSUE TITLE
Have you tried it in a Raspberry?

### ISSUE THREAD

**Issue by martinmineo** [allburov/whatsapp-http-api#72]
Hi!
Now that you added the ARM version, this project could be deployed on a Raspberry I'm thinking of a Raspberry Pi 4 Model B with 8GB RAM)
Have you tried it? I think it would be a great option to avoid paying AWS or any of these cloud services

**Comment by allburov** [comment]
Hi! 
I haven't tried it. 
Cloud providers are not only about CPU and Memory, but also about power, internet connection, handling reboots, so sometimes it worths it :)

Please share you experience with Raspberry PI if you'll make it, it's an interesting idea! :)
