### ISSUE TITLE
feature: clear/delete/close chat

### ISSUE THREAD

**Issue by Kristian-Tan** [allburov/whatsapp-http-api#73]
![feature-in-whatsapp-web](https://user-images.githubusercontent.com/18624029/223380470-00c60489-2503-4733-bbb9-735230338bfb.png)

After using the API for a long time, chats are accumulated.

Endpoint api/contacts/all also include all those accumulated chats.

Clear/delete/close chat feature would be helpful to (hopefully) reduce memory usage and keep the conversation list clean.

**Comment by allburov** [comment]
Hi! There are few new endpoints for chat control https://waha.devlike.pro/docs/how-to/chats/

`DELETE /api/{session}/chats/{chatId}/messages` and `DELETE /api/{session}/chats/{chatId}` what you requested!
