### ISSUE TITLE
[feature] Remote storage

### ISSUE THREAD

**Issue by arthurbarros** [allburov/whatsapp-http-api#74]
Is there any plans on releasing remote storage on waha-plus ? 
I'm running my stack on Google Cloud Run, which are disk are ephemeral.

Would be nice if we could develop on our end, some common endpoints that WAHA would use to save and retrieve stored sessions

**Comment by allburov** [comment]
We're planning to add it, [hopefully in a few months](https://github.com/devlikeapro/whatsapp-http-api/issues/41). 

>common endpoints that WAHA would use to save and retrieve stored sessions

I like this idea!! It'd be easy to extend it later. Thank you, we'll diffidently add HTTP API storage with simple endpoint

@arthurbarros 
Doesn't [NFS in GCR](https://cloud.google.com/run/docs/using-network-file-systems) work properly with WAHA? I haven't tried, but it looks possible

**Comment by arthurbarros** [comment]
@allburov what is the path inside the container that should be persisted?

Thanks a lot for this NFS in GCP

**Comment by arthurbarros** [comment]
@allburov thanks for the tutorial wasn't aware of it, but I will try to spawn a VM to run the project.

Last question, which path/folder inside the cointainer should be persisted when mounted a docker volume?

**Comment by allburov** [comment]
`/app/.sessions`
https://waha.devlike.pro/docs/how-to/sessions/
