### ISSUE TITLE
Screenshot not displaying QR code

### ISSUE THREAD

**Issue by showFocus** [allburov/whatsapp-http-api#75]
I subscribed to PLUS today and installed it on a remote server.

Initially I was able to link my device and send a text. But then I started getting 500 errors so I restarted my container. Now when accessing /api/screenshot from Swagger UI I get the following image back (no QR)

![image](https://user-images.githubusercontent.com/236699/224571367-c2ffe6f1-688d-4a3e-86f2-dce959deabbb.png)

**Comment by allburov** [comment]
Hi! 
Could you try to remove `.sessions` folder if it exists and run the container again?

**Comment by allburov** [comment]
@showFocus hi! Any updates on this?
