### ISSUE TITLE
URL in texts

### ISSUE THREAD

**Issue by hksk** [allburov/whatsapp-http-api#77]
Hi guys, I recently got a plus subscription, and is a fantastic project, but I dont see how to send a link in the messages,
that feature is supported?

**Comment by allburov** [comment]
Hi! Thank you for supporting the project!

You can send a link as text. It won't make a preview from it and probably the link is not clickable, right?
We're working on adding a new engine, hopefully it'll work there!

The related issue https://github.com/devlikeapro/whatsapp-http-api/issues/30
