### ISSUE TITLE
Sending images with WAHA Plus

### ISSUE THREAD

**Issue by alijundi** [allburov/whatsapp-http-api#79]
I tried to send image using encoded64 format and could not succeed (image size was 300kb). However for smaller image such as 11kb it works fine. Can you assist

Please see attached request
[request.txt](https://github.com/devlikeapro/whatsapp-http-api/files/11061525/request.txt)

**Comment by alijundi** [comment]
This is what I am getting back from swagger

`{
"statusCode": 500,
"timestamp": "2023-03-24T11:33:59.771Z",
"exception": {
"stack": "PayloadTooLargeError: request entity too large\n at readStream (/app/node_modules/raw-body/index.js:156:17)\n at getRawBody (/app/node_modules/raw-body/index.js:109:12)\n at read (/app/node_modules/body-parser/lib/read.js:79:3)\n at jsonParser (/app/node_modules/body-parser/lib/types/json.js:135:5)\n at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)\n at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)\n at /app/node_modules/express/lib/router/index.js:286:9\n at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)\n at next (/app/node_modules/express/lib/router/index.js:280:10)\n at serveStatic (/app/node_modules/serve-static/index.js:75:16)\n at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)\n at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)\n at /app/node_modules/express/lib/router/index.js:286:9\n at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)\n at next (/app/node_modules/express/lib/router/index.js:280:10)\n at expressInit (/app/node_modules/express/lib/middleware/init.js:40:5)",
"message": "request entity too large",
"name": "PayloadTooLargeError",
"expected": 405845,
"length": 405845,
"limit": 102400,
"type": "entity.too.large"
},
"request": {
"path": "/api/sendImage",
"method": "POST",
"body": {},
"query": {}
},
"version": {
"version": "2023.3.21",
"tier": "PLUS",
"browser": "/usr/bin/chromium"
}
}`

**Comment by allburov** [comment]
Hi @alijundi, thank you for the such detailed issue!
Fixed in `2023.3.25` PlUS version - now the limit is 50mb
