### ISSUE TITLE
Need to include session information in Receive Messages WebHook

### ISSUE THREAD

**Issue by alijundi** [allburov/whatsapp-http-api#80]
Hello guys,

So I have two open sessions in PLUS. I need to know where is the message coming from. I suggest to include session name in the webhook event. This way, we know from which session we should respond.

Another solution is to make a webhook related to each open session. Meaning, we should be able to configure a uniquie webhook for each session.

Any thoughts would be nice.

**Comment by allburov** [comment]
Hi!
For now it's easy to add `session` parameter as you suggested, so the payload looks this way:
```
{
  "event": "message",
  "session": "default",
  "payload": {}
}
```
We'll add this soon, great suggestion!

We'll work on more flexible webhooks a bit later, so you'll be able to setup webhooks and events per session - https://github.com/devlikeapro/whatsapp-http-api/issues/68

**Comment by alijundi** [comment]
Thank you @allburov. For now. it is great!

**Comment by arthurbarros** [comment]
+1 to this.

As a alternative I'm saving the WhatsApp phone number on my side with the session key, that way I can look it up.

**Comment by allburov** [comment]
Added `session` field in `2023.3.28`!
