### ISSUE TITLE
Error: Failed to launch the browser process

### ISSUE THREAD

**Issue by believe75** [allburov/whatsapp-http-api#81]
I couldn't run it on my mac machine, what could be the reason? :(

![image](https://user-images.githubusercontent.com/6364121/228333998-2ff36ec3-4bdf-4981-b62d-20fbed0e5a11.png)

**Comment by believe75** [comment]
The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

**Comment by allburov** [comment]
@believe75 hi!
Use this one https://waha.devlike.pro/docs/overview/quick-start/#11-download-image-on-arm

```bash
# Download the image
docker pull devlikeapro/whatsapp-http-api:arm
# Rename it, so you can use devlikeapro/whatsapp-http-api image in other place
docker tag devlikeapro/whatsapp-http-api:arm devlikeapro/whatsapp-http-api
```

**Comment by believe75** [comment]
Thanks  @allburov , its working
