### ISSUE TITLE
group Add participants not working

### ISSUE THREAD

**Issue by garvit170** [allburov/whatsapp-http-api#82]
I created a group with /api/default/groups and am trying to add participants with
curl -X 'POST' \
  'http://localhost:3000/api/default/groups/1203XXXXXXXXXXXX25%40g.us/participants/add' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "participants": [
    {
      "id": "8XX50XXXXX@c.us"
    }
  ]
}'

but it responds with an error

{
  "statusCode": 500,
  "timestamp": "2023-04-06T11:22:09.235Z",
  "exception": {
    "stack": "Error: Evaluation failed: Error: addParticipants: incoming change missing version id\n    at Object.<anonymous> (https://web.whatsapp.com/app.777d9ff19d4bf91ee3d5.js:46:317530)\n    at Generator.next (<anonymous>)\n    at t (https://web.whatsapp.com/vendor1~app.26ad649364c0cd2a0a46.js:2:66483)\n    at s (https://web.whatsapp.com/vendor1~app.26ad649364c0cd2a0a46.js:2:66694)\n    at https://web.whatsapp.com/vendor1~app.26ad649364c0cd2a0a46.js:2:66753\n    at Y (https://web.whatsapp.com/app.777d9ff19d4bf91ee3d5.js:5:140100)\n    at new y (https://web.whatsapp.com/app.777d9ff19d4bf91ee3d5.js:5:132667)\n    at Object.<anonymous> (https://web.whatsapp.com/vendor1~app.26ad649364c0cd2a0a46.js:2:66634)\n    at t.addParticipants (https://web.whatsapp.com/app.777d9ff19d4bf91ee3d5.js:46:315044)\n    at __puppeteer_evaluation_script__:8:50\n    at ExecutionContext._evaluateInternal (/app/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ExecutionContext.evaluate (/app/node_modules/whatsapp-web.js/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)\n    at async GroupChat.addParticipants (/app/node_modules/whatsapp-web.js/src/structures/GroupChat.js:62:16)\n    at async /app/node_modules/@nestjs/core/router/router-execution-context.js:46:28\n    at async /app/node_modules/@nestjs/core/router/router-proxy.js:9:17",
    "message": "Evaluation failed: Error: addParticipants: incoming change missing version id\n    at Object.<anonymous> (https://web.whatsapp.com/app.777d9ff19d4bf91ee3d5.js:46:317530)\n    at Generator.next (<anonymous>)\n    at t (https://web.whatsapp.com/vendor1~app.26ad649364c0cd2a0a46.js:2:66483)\n    at s (https://web.whatsapp.com/vendor1~app.26ad649364c0cd2a0a46.js:2:66694)\n    at https://web.whatsapp.com/vendor1~app.26ad649364c0cd2a0a46.js:2:66753\n    at Y (https://web.whatsapp.com/app.777d9ff19d4bf91ee3d5.js:5:140100)\n    at new y (https://web.whatsapp.com/app.777d9ff19d4bf91ee3d5.js:5:132667)\n    at Object.<anonymous> (https://web.whatsapp.com/vendor1~app.26ad649364c0cd2a0a46.js:2:66634)\n    at t.addParticipants (https://web.whatsapp.com/app.777d9ff19d4bf91ee3d5.js:46:315044)\n    at __puppeteer_evaluation_script__:8:50",
    "name": "Error"
  },
  "request": {
           ...
    },
    "query": {}
  },
  "version": {
    "version": "2023.3.1",
    "tier": "CORE",
    "browser": "/usr/bin/chromium"
  }
}

**Comment by garvit170** [comment]
@allburov pls help

**Comment by arthurbarros** [comment]
Just checked and its working on the tier PLUS at the latest version, don`t know about the tier CORE 

```
{
  "version": "2023.3.21",
  "tier": "PLUS",
  "browser": "/usr/bin/chromium"
}
```

**Comment by allburov** [comment]
@garvit170 hi! Published a new CORE version - please fetch a new one - `2023.4.7`

**Comment by garvit170** [comment]
It's working now. Thanks a lot @allburov
