### ISSUE TITLE
[feature] Add Baileys as a supported engine

### ISSUE THREAD

**Issue by arthurbarros** [allburov/whatsapp-http-api#86]
Looks like Baileys would be a much more lightweight alternative to Venon, since its runs directly on top of Whatsapp Web Websockets and dont use selenium or puppetier.

https://github.com/WhiskeySockets/Baileys

**Comment by allburov** [comment]
Hi! Released the new version with Baileys today! :smile: 
https://waha.devlike.pro/docs/how-to/engines/#noweb-imagesversionscorepng 
Just call it NOWEB to highlight the difference
