### ISSUE TITLE
[NOWEB] How to use /api/sendSeen?

### ISSUE THREAD

**Issue by arthurbarros** [allburov/whatsapp-http-api#87]
Previously I could just use `chatId` and `session`, at the  `sendSeen` endpoint. But now the API asks for:

```
{
  "chatId": "11111111111@c.us",
  "messageId": "false_11111111111@c.us_AAAAAAAAAAAAAAAAAAAA",
  "participant": "11111111111@c.us",
  "session": "default"
}
```
The `messageId` is present in the payload, that is fine.

But where do i get the `participant` parameter ?

**Comment by arthurbarros** [comment]
This is the error that is showing up when trying to use the endpoint:

payload
```
{
  "chatId": "*************@c.us,
  "messageId": "false_*************@c.us_******************************",
  "participant": "*************@c.us",
  "session": "******************************************"
}
```

reponse

```
{
  "statusCode": 400,
  "message": "Unexpected token \n in JSON at position 34",
  "error": "Bad Request"
}
```


curl from swagger

```
curl -X 'POST' \
  'http://*************:3000/api/sendSeen' \
  -H 'accept: application/json' \
  -H 'X-Api-Key: *************' \
  -H 'Content-Type: application/json' \
  -d '{
  "chatId": "*************@c.us,
  "messageId": "false_*************@c.us_*************",
  "participant": "*************@c.us",
  "session": "*************"
}'
```

**Comment by allburov** [comment]
Hi! 
`participant` is only required for messages in the "group chat" - the `message` event also has it as a field.
The rule is - if there's `participant` in incoming message - add it to sendSeen, otherwise you can skip it (it means that it's a direct message from a WhatsApp account, not a group)

**Comment by allburov** [comment]
In the example payload above you haven't closed "chatId" value with `"` symbol at the end
```
# Your payload
"chatId": "*************@c.us,
# expected
"chatId": "*************@c.us",
```

it happens with all copy and paste manipulation sometimes :)

**Comment by arthurbarros** [comment]
I'm so stupid, thanks a lot. Missed it, long hours here.
