### ISSUE TITLE
[feature] endpoint to remove a session folder

### ISSUE THREAD

**Issue by arthurbarros** [allburov/whatsapp-http-api#88]
Sometimes it's impossible to respawn a session with a previously used name if you wont hard delete it inside de session folder.

Would be nice to have a endpoint that removes the session completly from the session folder.

Endpoint example:

POST `api/session/remove`
```
{ 
  'session' : 'default'
} 
```

**Comment by allburov** [comment]
Hi! 
Good idea, found it useful too, planning to add it by June 2023!

**Comment by allburov** [comment]
You can stop and logout from the session at once **POST /api/session/stop**
```json
{
  "name": "default",
  "logout": true
}
```
https://waha.devlike.pro/docs/how-to/sessions/#stop

If it doesn't work (session can be stuck) - use **POST /api/session/logout**. In the latest version it doesn't check session status at all
```json
{
  "name": "default"
}
```
https://waha.devlike.pro/docs/how-to/sessions/#logout
