### ISSUE TITLE
after restart container it need making a post request for a new session

### ISSUE THREAD

**Issue by Gemy403** [allburov/whatsapp-http-api#92]
after restart container it need make a post for new session , and scan qr code again!!!
is there a method to save session even if restarted the server or container ?!

**Comment by allburov** [comment]
Hi there!
There're two problems
1. Saving authentication information (scanning QR) - [WAHA Plus version](https://waha.devlike.pro/docs/how-to/plus-version/) supports it, Core doesn't. You can check your version by using endpoint `GET /api/version`
2. Starting sessions on restart - we're working on it right now, hopefully in June we'll add it in Plus version too

Please let me know if have any questions!
