### ISSUE TITLE
[Plus][WEBJS] Add a custom capture when sending files (/sendFile)

### ISSUE THREAD

**Issue by lightningfuzion2** [allburov/whatsapp-http-api#94]
the  caption can not be changed while attaching Files for uploading 
{
  "session": "default",
  "chatId": "11111111111@c.us",
  "file": {
    "mimetype": "image/jpeg",
    "filename": "filename.jpeg",
    "data": "........"
  },
  "caption": "string"
}

the Caption on whatsapp changes to "filename.jpeg" instead and dosen't consider the "caption": "string" key value
same is the case when using url method the caption is replaced by the File name present in the url.
this is happning in the plus Version.

**Comment by allburov** [comment]
Hi! It's a pretty new feature for WhatsApp, waiting for the engine to support it https://github.com/pedroslopez/whatsapp-web.js/issues/1849

**Comment by lightningfuzion2** [comment]
does this work in other Engines Venom and all ?

**Comment by allburov** [comment]
@lightningfuzion2 published a new plus version today - it does work in [NOWEB engine](https://waha.devlike.pro/docs/how-to/engines/#noweb)!

**Comment by allburov** [comment]
Filename issue is fixed, not filename should be overwritten by `filename` field!

**Comment by devlikepro** [comment]
Hi! 
`caption` has been fixed in **WAHA Plus** `2024.3.9`
Now both `caption` and `filename` should work with no issues in both WEBJS and NOWEB engine.

[![patron:PRO](https://img.shields.io/badge/patron-PRO-188a42)](https://waha.devlike.pro/docs/how-to/plus-version/#tiers)
