### ISSUE TITLE
Flask run REQUIREMENTS  error: windows & linux

### ISSUE THREAD

**Issue by zerosays** [allburov/whatsapp-http-api#97]
@allburov add **markupsafe==2.0.1** to the [requirements.txt](https://github.com/devlikeapro/whatsapp-http-api/blob/core/examples/python/requirements.txt)

**Comment by allburov** [comment]
Hi! Could you give the error that you got?

**Comment by zerosays** [comment]
Traceback (most recent call last):
  File "whatsapp_echo_bot.py", line 4, in <module>
    from flask import Flask
  File "site-packages\jinja2\__init__.py", line 14, in <module>
    from jinja2 import escape
  File "site-packages\jinja2\__init__.py", line 6, in <module>
    from markupsafe import escape
ModuleNotFoundError: No module named 'markupsafe' - WINDOWS

**Comment by allburov** [comment]
Weird, jinja2 must install it by default 
https://github.com/pallets/jinja/issues/1103

What commands did you use to install requirements.txt and what environment do you use, like python and pip version?

I'll freeze all lubraries in requirements.txt, but there's some problem with the environment or the installation process itself

**Comment by zerosays** [comment]
Already have it in prod. 💯 

Encountered the issue on my desktop and two servers.

Followed everything as documented: just saving someone else who might face that.

**Comment by allburov** [comment]
@zerosays btw, why exact version? It didn't work for your with the latest one? `markupsafe==2.1.2` 
Asking to make sure to fix it right
