### ISSUE TITLE
No Webhook events received.

### ISSUE THREAD

**Issue by birbull** [allburov/whatsapp-http-api#98]
Please check attached screenshot 

![Screen Shot 2023-05-17 at 11 02 54 PM](https://github.com/devlikeapro/whatsapp-http-api/assets/100991870/4b4ad4dc-fcec-42aa-9143-c4186ea111df)

**Comment by allburov** [comment]
Hi! I don't know what the issue is, please describe it properly

**Comment by allburov** [comment]
You won't receive webhooks till you start the season first if it's you question

**Comment by harie-lugster** [comment]
I already started session then I had set the webhook but no response data recieved to webhook.site

**Comment by birbull** [comment]
> You won't receive webhooks till you start the season first if it's you question


I already started session then I had set the webhook but no response data recieved to webhook.site

**Comment by allburov** [comment]
Could you try with WHATSAPP_HOOK_URL=https://httpbin.org/post and see if there's logs for that?

**Comment by birbull** [comment]
Where I can check the logs?

**Comment by allburov** [comment]
The same console or 'docker log whatsapp-http-api' command

**Comment by allburov** [comment]
Docker logs, sorry
https://docs.docker.com/engine/reference/commandline/logs/
