### ISSUE TITLE
Problem sending an image

### ISSUE THREAD

**Issue by parallels999** [allburov/whatsapp-http-api#99]
I have not problem sending texts,
but when I'm trying to send an image from PHP using `GuzzleHttp\Client`, it doesn't send anything

```php
$httpClient = new \GuzzleHttp\Client();
$imageFile = 'PATH_TO_MY_IMAGE_FILE';
$params = [
  'chatId'=> $numberNotification,
  'file'=> [
    'mimetype'=> mime_content_type($imageFile),
    'filename'=> basename($imageFile),
    'data'=> base64_encode(file_get_contents($imageFile))
  ],
  'caption'=> 'Testing Image Send',
  'session'=> 'session_testing'
];
$endpoint = 'sendImage'
$apiUri = sprintf('%s/%s', $myApiBaseUrl, $endpoint);
$httpClient->post($apiUri, [
    'form_params' => $params,
    'headers' => ['X-Api-Key' => 'MY_API_KEY'] 
]);
```
Making a debug, my request are something like this
```
chatId: MY_NUMBER_NOTIFICATION
file[mimetype]: image/jpeg
file[filename]: file_test.jpeg
file[data]: HERE_BASE64_DATA
caption: Testing Image Send
session: session_testing
```
any idea what i'm doing wrong
`file[mimetype]` fails on `BinaryFile `, or `getSchemaPath(BinaryFile)` is failing? on `MessageImageRequest` file is empty
https://github.com/devlikeapro/whatsapp-http-api/blob/e1bf8cf735287bad241a89030f1daa2d1318ff2f/src/structures/chatting.dto.ts#L120-L138
https://github.com/devlikeapro/whatsapp-http-api/blob/e1bf8cf735287bad241a89030f1daa2d1318ff2f/src/structures/chatting.dto.ts#L140-L149

**Comment by allburov** [comment]
Hi! Have you solved the issue?

**Comment by parallels999** [comment]
> Hi! Have you solved the issue?

Yes, it was my mistake, I was using `form_params` instead of `json`, thanks

**Comment by parallels999** [comment]
it would be nice a validation that warns of this mistake, like request must be `application/json` when sending `file[mimetype]` on `form/url-encoded`

**Comment by allburov** [comment]
What was the response for your request?
There's http status for that, I'm wondering if we send it or not
415 Unsupported Media Type

**Comment by parallels999** [comment]
I don't remember anymore, but now everything is working without problems
